/**
 * Canonical operation techniques — the named practices from the MTGOA chapters,
 * which are organized by the six mentor-worlds (= the deck's Operation axis).
 * Spec: .specify/specs/allyship-technique-vocabulary/spec.md § FR5
 *
 * Unlike the Tier-1 alchemy substrate (canonical.ts, tagged `alchemist`), these
 * are operation-scoped move practices available under ANY loadout
 * (superpowers: []). They fill the Grow Up + Show Up coverage gaps and land on
 * the operation column they belong to.
 *
 * Domains are intentionally left `[]` (domain-agnostic): per the deck's design,
 * the domain only changes a card's example, not the practice — so an operation
 * practice applies across all four domains of its column.
 */

import type { Technique } from './types'

const MTGOA = {
  origin: 'book',
  name: 'Mastering the Game of Allyship',
  author: 'Wendell Britt',
} as const

export const OPERATION_TECHNIQUES: Technique[] = [
  // ── Cross-cutting (operations: []) ──
  {
    id: 'tech-allyship-formula',
    slug: 'effective-allyship-formula',
    name: 'The Effective Allyship Formula',
    essence: "The book's master four-step procedure for doing allyship sustainably.",
    steps: [
      'Identify your superpower.',
      'Identify who needs that superpower.',
      'Enroll allies to help you help those people.',
      'Show up consistently.',
    ],
    source: MTGOA,
    allyshipReframe: 'The spine every operation keeps honest — self-knowledge into consistent, enrolled action.',
    moves: ['grow_up', 'show_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-one-real-situation',
    slug: 'bring-one-real-situation',
    name: 'Bring One Real Situation',
    essence: 'Anchor the work to one concrete unresolved situation, read through the token/ticket cost lens.',
    steps: [
      'Choose ONE actual situation you carry (a relationship, a room, a conflict, a care-pattern).',
      "Don't try to solve it — keep it nearby to test each move against.",
      'Ask: "What game am I actually playing, and what is it costing me?"',
      'Track each move as spending a token vs. earning a ticket (does it increase life?).',
    ],
    source: MTGOA,
    moves: ['wake_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-consent-gate',
    slug: 'consent-gate',
    name: 'The Consent Gate',
    essence: 'Get explicit consent through relationship before claiming to be someone’s ally.',
    steps: [
      'Ask: "Would you be willing to let me help with that?" or "What kind of help would you appreciate right now?"',
      'If the answer is no, treat it as information, not a failure of your goodness.',
      'If the no still activates you, recognize that activation as your own inner work.',
      'Ally with actual people, never with abstractions or categories.',
    ],
    source: MTGOA,
    allyshipReframe: 'Charity can happen without consent; allyship cannot. Consent is the gate.',
    moves: ['wake_up', 'clean_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'outer',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },

  // ── Shaman ──
  {
    id: 'tech-emotional-alchemy-map',
    slug: 'emotional-alchemy-map',
    name: 'Emotional Alchemy (the emotion-as-information map)',
    essence: 'Treat each emotion as information to stay with long enough to learn from.',
    steps: [
      'Read fear as "what matters"; anger as "where a boundary lives".',
      'Read sadness as "what I’ve lost / how far I am from what I care about".',
      'Read joy as "what is aligned"; neutrality as "I can see the room more clearly".',
      'Stay with the emotion long enough to extract its information instead of mistaking strain for virtue.',
    ],
    source: MTGOA,
    allyshipReframe: 'The foundational system the whole book references — emotions are data, not problems.',
    moves: ['wake_up', 'clean_up'],
    operations: ['shaman'],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-finding-superpower',
    slug: 'finding-your-superpower',
    name: 'Finding Your Superpower',
    essence: 'Identify the sustainable gift that gives something back to you while helping others.',
    steps: [
      'Test against three meeting-points: you can do it well; it matters to real people; using it feels right beneath praise.',
      'Recall a recent moment you were useful (not impressive): What felt easy? alive? satisfying afterward?',
      'Ask the boundary question: what help do I give that costs me too much to sustain?',
    ],
    source: MTGOA,
    moves: ['wake_up', 'grow_up'],
    operations: ['shaman'],
    domains: [],
    channels: [],
    aspect: 'inner',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-shamans-rule',
    slug: 'shamans-rule',
    name: "The Shaman's Rule",
    essence: 'Use the body as the first reader: a four-question check before judging a move.',
    steps: [
      'Does this feel energizing in a real way?',
      'Does it make the room clearer?',
      'Does it leave me more capable of the next move?',
      'Can I imagine doing this again tomorrow?',
    ],
    source: MTGOA,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-superpower-practice',
    slug: 'superpower-practice',
    name: 'Superpower Practice (the one-sentence naming)',
    essence: 'Crystallize your superpower into a single testable sentence.',
    steps: [
      'Write what it is, what it does for others, what it gives back to you, and what happens if you overdo it.',
      'Complete: "My superpower is ____, and I know because it gives me ____ when I use it."',
      'If it feels true in the body, proceed; if forced, keep looking.',
    ],
    source: MTGOA,
    moves: ['grow_up'],
    operations: ['shaman'],
    domains: [],
    channels: [],
    aspect: 'inner',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },

  // ── Challenger ──
  {
    id: 'tech-clean-no',
    slug: 'clean-no',
    name: 'The Clean No',
    essence: 'Deliver a boundary with all three load-bearing parts so it’s a line, not a hope.',
    steps: [
      'The line itself — what is not okay.',
      'The plain delivery — say it without apology.',
      'The cost — what happens if the line is ignored.',
    ],
    source: MTGOA,
    allyshipReframe: 'Without the cost, a boundary is just a hope.',
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    capabilities: ['agency'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-placement-test',
    slug: 'placement-aiming-test',
    name: 'The Placement / Aiming Test',
    essence: 'Decide whether this is your room to act in before you use your gift.',
    steps: [
      'Notice the real need.',
      'Ask whether your help is wanted.',
      'Decide whether this is your room to be useful in.',
      'If I step in, will I make the room clearer or more crowded? If unclear, slow down.',
    ],
    source: MTGOA,
    allyshipReframe: 'Allyship is not just generosity. It is placement.',
    moves: ['wake_up', 'show_up'],
    operations: ['challenger'],
    domains: [],
    channels: [],
    aspect: 'outer',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-challenger-practice',
    slug: 'challenger-practice',
    name: 'Challenger Practice (the placement worksheet)',
    essence: 'Test whether a situation you care about is actually your room.',
    steps: [
      'Write: what you think is needed; what your superpower would do here; whether you’ve been invited.',
      'Write: what would happen if you did nothing; what would happen if you stepped in.',
      'Answer: "Is this the room where my superpower should be used, or am I solving the wrong problem?"',
    ],
    source: MTGOA,
    moves: ['grow_up', 'wake_up'],
    operations: ['challenger'],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },

  // ── Regent ──
  {
    id: 'tech-cycle-of-inheritance',
    slug: 'cycle-of-inheritance',
    name: 'The Cycle of Inheritance',
    essence: 'Work consciously with what you inherited: Inherit → Honor → Steward → Reform → Entrust.',
    steps: [
      'Inherit — acknowledge what arrived: "I am carrying this. I did not create it. But it is mine now."',
      'Honor — name what still serves and what was always the wound; stop blaming, start sorting.',
      'Steward — carry, maintain, and tend it (the longest stage).',
      'Reform — change the form when the essence requires it, without dismantling what holds.',
      'Entrust — hand it on cleanly: "Have I given the next person enough to run with?"',
    ],
    source: MTGOA,
    moves: ['grow_up', 'show_up'],
    operations: ['regent'],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-polarity-honor-reform',
    slug: 'polarity-honor-reform',
    name: 'Polarity Encounter — Honor ↔ Reform',
    essence: 'Locate where you’re stuck between honoring an inheritance and reforming it, then integrate both poles.',
    steps: [
      'Name one inheritance you keep performing in one sentence.',
      'Mark where you sit on the axis: Honor what was passed ↔ Reform what no longer serves.',
      'Write one integrated sentence holding both poles.',
      'Sit 30 seconds; notice heaviness (Honor stuck), heat (Reform stuck), or ground (integrated).',
    ],
    source: MTGOA,
    moves: ['clean_up', 'grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    capabilities: ['agency'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-stewardship-ecology-test',
    slug: 'stewardship-ecology-test',
    name: 'The Stewardship Ecology Test',
    essence: 'One diagnostic question: does this keep the inheritance alive, or just preserve the shell?',
    steps: [
      'Ask: "Does this move make the inheritance more alive and receivable, or protect the shell while draining me?"',
      'Watch for spend-the-self moves: Loyalty→Compliance, Duty→Martyrdom, Tradition→Dogma, Role→Mask.',
    ],
    source: MTGOA,
    moves: ['wake_up'],
    operations: ['regent'],
    domains: [],
    channels: [],
    aspect: 'inner',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-name-inheritance',
    slug: 'name-one-inheritance-out-loud',
    name: 'Name One Inheritance Out Loud',
    essence: 'Say a claim or reform of an inheritance to the actual people who hold it.',
    steps: [
      'Pick one inheritance you carry undecided (practice / norm / role / tradition).',
      'This week, in the room, either CLAIM it ("I’m going to carry this now and tend it as I go")…',
      '…or REFORM it ("This stopped serving what it was built for; I’m naming that it needs to change").',
      'Hold both: "I love this enough to change it." Then log what you said and what it cost.',
    ],
    source: MTGOA,
    allyshipReframe: 'Interior sorting is free. Saying it out loud is where loyalty has a price.',
    moves: ['show_up'],
    operations: ['regent'],
    domains: [],
    channels: [],
    aspect: 'outer',
    superpowers: [],
    failureModes: ['The Fixer’s "one more cycle of reform before I commit"'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-8-gates-regent',
    slug: '8-gates-walk-regent',
    name: 'The 8 Gates Walk — Regent Altitude',
    essence: 'An inner walk past eight self-protective parts to reach the Vulnerable Child and reclaim the capacity to carry.',
    steps: [
      'Protector — thank it, then ask permission to pass.',
      'Controller — ask what it’s been holding; show you can hold it yourself; relieve, don’t fire it.',
      'Skeptic — ask "What would it take for you to believe in this?"',
      'Fixer — refuse the "one more reform cycle"; commit, then tend.',
      'Fear — give it a specific name; "I hear you. I’m going to keep walking anyway."',
      'Victim — let it talk; ask what it would take to risk again.',
      'Damaged Self — witness without fixing.',
      'Vulnerable Child — arrive and receive what it hands you.',
    ],
    source: MTGOA,
    moves: ['clean_up', 'grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    capabilities: ['exploration'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-regents-game',
    slug: 'regents-game-five-moves',
    name: "The Regent's Game — 5 Moves",
    essence: 'Five concrete moves for inheriting and stewarding a role, team, or tradition.',
    steps: [
      'Name the Inheritance — "Why is this here? Who built it? What was it trying to do?"',
      'Honor What Still Serves — list three things you’d fight to protect.',
      'Reform Without Erasing — keep the essence, change the form; tell people "I’m updating, not discarding."',
      'Keep the Vows — do one commitment nobody is watching you keep.',
      'Entrust Without Clinging — give enough to run with, then let go of the outcome.',
    ],
    source: MTGOA,
    moves: ['show_up', 'grow_up'],
    operations: ['regent'],
    domains: [],
    channels: [],
    aspect: 'outer',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },

  // ── Architect ──
  {
    id: 'tech-observe-model-design-deploy',
    slug: 'observe-model-design-deploy',
    name: 'Observe → Model → Design → Deploy',
    essence: 'Understand why a system produces its outcomes and redesign so the right outcome becomes natural.',
    steps: [
      'Observe — find what is actually happening (talk to people inside; read outcomes, not intentions).',
      'Model — build the simplest explanation that accounts for the behavior.',
      'Design — create the intervention that changes the system’s incentives; find the leverage point.',
      'Deploy — ship into contact with reality; treat failure as information; observe and start again.',
    ],
    source: MTGOA,
    allyshipReframe: 'Design for the actual incentive, not the stated one.',
    moves: ['grow_up', 'show_up'],
    operations: ['architect'],
    domains: [],
    channels: [],
    aspect: 'outer',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-name-assumption',
    slug: 'name-one-unstated-assumption',
    name: 'Name One Unstated Assumption',
    essence: 'Say a load-bearing invisible assumption out loud in a real room, as warm observation not indictment.',
    steps: [
      'Pick a room where everyone solves the visible problem and nobody names the underlying assumption.',
      'Name it flatly: "We’re assuming X. I don’t think that’s true anymore, and everything sits on top of it."',
      'Hold the flinch; stay warm while staying clear — don’t soften.',
      'Log which assumption, what you said, what the flinch cost.',
    ],
    source: MTGOA,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: [],
    aspect: 'outer',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-8-gates-architect',
    slug: '8-gates-walk-architect',
    name: 'The 8 Gates Walk — Architect Altitude',
    essence: 'The eight-gate inner walk applied to your design instinct, running the Wake→Clean→Grow→Show spiral at each gate.',
    steps: [
      'At each gate: Wake (notice its signal), Clean (ask what it’s showing you), Grow (find the lesson), Show (cross).',
      'Protector / Controller / Skeptic (Fear) — thank, relieve, and ask to step back.',
      'Fixer (Anger) — "I need you to wait"; ship after Gate 8.',
      'Fear — name it, let it speak, "We’re going in anyway."',
      'Victim (Sadness) / Damaged Self — listen without arguing; stay in the room.',
      'Vulnerable Child (Joy) — arrive; recognize design is a form of love.',
    ],
    source: MTGOA,
    moves: ['clean_up', 'grow_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal', 'wood'],
    aspect: 'inner',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-architects-game',
    slug: 'architects-game-five-moves',
    name: "The Architect's Game — 5 Moves",
    essence: 'Five repeatable structural-design moves that let a system run without you.',
    steps: [
      'Find the Leverage Point — where does the smallest push create the largest movement? Follow the workaround.',
      'Name the Unstated Assumption — "What are we assuming that nobody has said out loud?"',
      'Design for Handoff — "Who runs this after me? What am I assuming they know?" Write the rationale down.',
      'Ship the Minimum — ship the simplest version that tests the core hypothesis; learn, then design.',
      'Refactor Kindly — name what the previous version got right before changing it.',
    ],
    source: MTGOA,
    allyshipReframe: 'The Architect wins when the system works without them.',
    moves: ['show_up', 'grow_up'],
    operations: ['architect'],
    domains: [],
    channels: [],
    aspect: 'outer',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },

  // ── Diplomat ──
  {
    id: 'tech-diplomat-five-stages',
    slug: 'bridge-translate-hold-repair-negotiate',
    name: 'Bridge → Translate → Hold → Repair → Negotiate',
    essence: 'A relational journey from making contact to closing on honest terms so that staying means something.',
    steps: [
      'Bridge — show up with curiosity rather than judgment; make contact.',
      'Translate — render one camp’s language into terms another can hear, without betraying either.',
      'Hold — keep enough safety that difficult conversation stays possible.',
      'Repair — heal ruptures without pretending they didn’t occur.',
      'Negotiate — surface what each party protects, name the terms staying requires, and close.',
    ],
    source: MTGOA,
    allyshipReframe: 'Each stage earns the next — Bridge without Translate is noise.',
    moves: ['grow_up', 'show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: [],
    aspect: 'outer',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-stake-surfacing-close',
    slug: 'stake-surfacing-close',
    name: 'The Stake-Surfacing Close (Protect → Require → Commit)',
    essence: 'A no-skip closing structure that honors inclusion while actually producing movement.',
    steps: [
      'Protect — what is each party afraid of losing? Name the interest, not the slogan.',
      'Require — what must the agreement hold for staying to remain real?',
      'Commit — what are we agreeing to, specifically, before we leave this room?',
    ],
    source: MTGOA,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    capabilities: ['agency'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-discernment-check',
    slug: 'discernment-check',
    name: 'The Discernment Check (against false closure)',
    essence: 'A pre-close test that terms genuinely address each party’s interests rather than papering over a gap.',
    steps: [
      'Ask: "Can I paraphrase each party’s interest so its strongest advocate would recognize it?"',
      'Ask: "Do the proposed terms actually address those interests — or are we papering over a gap?"',
      'Distinguish equal hearing (precious) from equal endorsement (not automatic).',
    ],
    source: MTGOA,
    moves: ['wake_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    capabilities: ['agency'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-interpreters-discipline',
    slug: 'interpreters-discipline',
    name: "The Interpreter's Discipline",
    essence: 'Keep translation faithful by checking your interpretation against the source.',
    steps: [
      'After translating, return to the original speaker: "Did I get this right?"',
      'Offer it as genuine correction, not performance.',
    ],
    source: MTGOA,
    moves: ['show_up', 'clean_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['earth'],
    aspect: 'outer',
    capabilities: ['rest'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-precedent-of-presence',
    slug: 'precedent-of-presence',
    name: 'The Precedent of Presence',
    essence: 'A pre-committed practice of staying in the field when it becomes charged.',
    steps: [
      'Decide in advance to remain when the field gets hard; tell the field "I don’t leave when it gets hard."',
      'Name the real capacity cost of staying (unnamed depletion becomes disappearance).',
    ],
    source: MTGOA,
    moves: ['grow_up', 'show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    capabilities: ['participation'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-three-part-repair',
    slug: 'three-part-repair',
    name: 'The Three-Part Repair (Witness → Impact → Agreement)',
    essence: 'A no-skip repair structure that lets a wound heal before it’s closed.',
    steps: [
      'Witness — full accounting of what happened, without defense or justification.',
      'Impact — honest naming of what the rupture cost, for both parties.',
      'Agreement — what each person commits to doing differently (real change, not performed remorse).',
    ],
    source: MTGOA,
    moves: ['clean_up', 'show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    capabilities: ['connection'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-8-gates-diplomat',
    slug: '8-gates-walk-diplomat',
    name: 'The 8 Gates Walk — Diplomat Altitude',
    essence: 'The eight-gate inner walk applied to the fear of being "too much" — belonging without self-erasure.',
    steps: [
      'Protector — "I know why you’re here, but I am going in now."',
      'Controller — hold your shape; choose whether to accommodate rather than dissolving.',
      'Skeptic — "complexity does not invalidate my need."',
      'Fixer — "I am allowed to need something even though I have not earned it."',
      'Already Alone — "the self I recover by standing fully is worth more than the belonging I kept by disappearing."',
      'Victim — acknowledgment without verdict: "I stayed too long. That is true."',
      'Hollowed Self — notice and pause the next automatic accommodation.',
      'Vulnerable Child — allow them back in whole.',
    ],
    source: MTGOA,
    moves: ['clean_up', 'grow_up'],
    operations: ['diplomat'],
    domains: [],
    channels: [],
    aspect: 'inner',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-diplomats-game',
    slug: 'diplomats-game-five-moves',
    name: "The Diplomat's Game — 5 Moves",
    essence: 'Five relational acts (held together, not sequenced) for keeping connection possible in a charged field.',
    steps: [
      'Name the Field — say what the conversation is actually about, as an offering ("I want to check if that’s what’s in the room").',
      'Translate Across Camps — convert one camp’s meaning into the other’s framework; hold your position lightly enough to receive first.',
      'Close with Honest Terms — one sentence naming what the field must hold for your staying to be real; say it once, then leave it.',
      'Repair After Rupture — name what broke, name your part, name what you’re NOT asking for, stay present.',
      'Refuse False Equivalence — distinguish equal hearing from equal endorsement; paraphrase the opposing view, then say why you still disagree.',
    ],
    source: MTGOA,
    moves: ['show_up', 'grow_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    capabilities: ['agency'],
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },

  // ── Sage ──
  {
    id: 'tech-see-switch-serve',
    slug: 'see-switch-serve-release-return',
    name: 'See → Switch → Serve → Release → Return',
    essence: 'Identify the game a room is playing, choose a fitting move, do it, put it down, and return without condescension.',
    steps: [
      'See — name the game (power / strategy / harmony / whole-board). Seeing is orientation, not distance.',
      'Switch — choose the right game deliberately (don’t answer a power game with a strategy memo).',
      'Serve — do the work that game requires, for the actual room.',
      'Release — when the game is done, put it down.',
      'Return — come back in with the people, not above them.',
    ],
    source: MTGOA,
    allyshipReframe: 'Does the sight help the room move, or help you stand above it?',
    moves: ['wake_up', 'show_up'],
    operations: ['sage'],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: [],
    failureModes: ['Trauma Olympics', 'Captain Save-a-Kid', 'Dragging horses to water'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-sage-practice',
    slug: 'sage-practice-formula-check',
    name: 'The Sage Practice / Formula Check',
    essence: 'A self-check that runs See→Switch→Serve→Release→Return against a real situation and the Allyship Formula.',
    steps: [
      'What game is this? What does the room actually need?',
      'What move will help — and where am I tempted to use my gift as proof instead of service?',
      'Which step of the Effective Allyship Formula is active here?',
      'Serve, enroll allies, release the game, and return without making clarity a performance.',
    ],
    source: MTGOA,
    moves: ['wake_up', 'grow_up', 'show_up'],
    operations: ['sage'],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: [],
    tier: 'canonical',
    status: 'published',
  },
]
