/**
 * Canonical technique seed — the Tier-1 Emotional-Alchemy tools from
 * "Mastering the Game of Allyship" (MTGOA Part VI: The Game Engine).
 * Spec: .specify/specs/allyship-technique-vocabulary/spec.md § FR5
 *
 * These are the universal Alchemy substrate (tagged `alchemist`) — available
 * under any loadout, at any altitude (operations: []), in any domain. They are
 * the bridge from book to deck: a player learns ~11 named practices and the 120
 * cards are situations to deploy them in. Community/personal techniques live in
 * the DB (Phase 3); canonical ones stay version-controlled here.
 */

import type { Technique } from './types'

const MTGOA = {
  origin: 'book',
  name: 'Mastering the Game of Allyship',
  author: 'Wendell Britt',
} as const

export const CANONICAL_TECHNIQUES: Technique[] = [
  {
    id: 'tech-wave',
    slug: 'wave',
    name: 'W.A.V.E.',
    essence: 'A one-breath emotional-respiration move to expand your capacity to hold a charge.',
    steps: [
      'Welcome — let the feeling be here without fixing it.',
      'Acknowledge — name what it is ("this is fear / anger / grief").',
      'Validate — grant that it makes sense given what it is responding to.',
      'Exhale / Exit / Express — let the charge move on the out-breath.',
    ],
    source: MTGOA,
    allyshipReframe: 'The simplest, most reliable tool for staying present to charge instead of acting it out onto others.',
    moves: ['open_up', 'clean_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: ['alchemist'],
    optimizesFor: 'Metabolizing a live charge in real time, before it leaks.',
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-3-2-1',
    slug: '3-2-1-practice',
    name: 'The 3-2-1 Practice',
    essence: 'Metabolize a projection by moving it across three grammatical persons.',
    steps: [
      'Phase 3 — Third person: describe it ("it / they"). Observe the charge as something out there.',
      'Phase 2 — Second person: dialogue with it ("you"). What does it want? What does it fear losing?',
      'Phase 1 — First person: embody it ("I"). Speak as the emotion until its true nature shows.',
    ],
    source: MTGOA,
    allyshipReframe: 'Shadow work as emotional literacy — reclaim what you projected onto an ally or opponent.',
    moves: ['clean_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: ['alchemist'],
    optimizesFor: 'Dissolving projection so you respond to the person, not your shadow.',
    failureModes: ['Stopping at description (3) without embodying (1)', 'Intellectualizing instead of feeling'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-recursive-3-2-1',
    slug: 'recursive-3-2-1',
    name: 'Recursive 3-2-1',
    essence: 'Loop the 3-2-1 back on itself for nested projections.',
    steps: [
      'Detect the echo — notice a projection inside the projection.',
      'Switch the frame — run 3-2-1 on the nested layer.',
      'Loop as needed — repeat until the charge settles.',
    ],
    source: MTGOA,
    moves: ['clean_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: ['alchemist'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-grounding',
    slug: 'grounding',
    name: 'Grounding',
    essence: 'The core move of emotional presence — return to the body.',
    steps: [
      'Feel your contact points (feet, seat, breath).',
      'Let attention drop from the head into the body.',
      'Stay until the nervous system settles a notch.',
    ],
    source: MTGOA,
    allyshipReframe: 'You cannot steady a room you have left; presence is the precondition for every other move.',
    moves: ['open_up', 'clean_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: ['alchemist'],
    optimizesFor: 'Re-establishing presence before acting.',
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-rose',
    slug: 'rose-tool',
    name: 'The Rose Tool',
    essence: 'Boundary craft and energetic hygiene — clear what is not yours to hold.',
    steps: [
      'Picture a rose at the edge of your space.',
      'Let it gather what is not yours (others’ charge, expectations).',
      'Release it (the "Rose Explosion") and reclaim your own edge.',
    ],
    source: MTGOA,
    allyshipReframe: 'Filter before you absorb — the Alchemist’s antidote to Emotional Overload.',
    moves: ['clean_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'inner',
    superpowers: ['alchemist'],
    optimizesFor: 'Holding a boundary on what emotional energy you take on.',
    contraindications: ['Using it to wall off feedback you actually need to receive'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-contract-burning',
    slug: 'contract-burning',
    name: 'Contract Burning',
    essence: 'A ritual to dissolve an invisible energetic agreement.',
    steps: [
      'Prepare the field.',
      'Imagine the contract.',
      'Fill in its hidden terms.',
      'Move it outside your field.',
      'Destroy it with elemental energy.',
      'Reclaim the energy it was binding.',
    ],
    source: MTGOA,
    allyshipReframe: 'Surface and release the unspoken deals that quietly run your behavior.',
    moves: ['clean_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'inner',
    superpowers: ['alchemist'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-conscious-complaining',
    slug: 'conscious-complaining',
    name: 'Conscious Complaining',
    essence: 'Permission-based ventilation that gives raw voice to dissatisfaction so it can metabolize.',
    steps: [
      'Level 1 — Compost the complaint privately.',
      'Level 2 — Redirect the energy (move/express it).',
      'Level 3 — Transmute it in relationship (vulnerable, witnessed).',
    ],
    source: MTGOA,
    allyshipReframe: 'Let the charge speak so it stops leaking sideways into the work.',
    moves: ['clean_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: ['alchemist'],
    failureModes: ['Venting that recruits others into the grievance instead of metabolizing it'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-happy-apples',
    slug: 'happy-apples',
    name: 'Happy Apples',
    essence: 'Minting positive emotional tokens — generating charge you can spend, together.',
    steps: [
      'Notice a genuine good feeling.',
      'Amplify and name it ("mint" the token).',
      'Share or bank it for the work ahead.',
    ],
    source: MTGOA,
    moves: ['clean_up', 'show_up'],
    operations: [],
    domains: [],
    channels: ['wood'],
    aspect: 'both',
    superpowers: ['alchemist'],
    capabilities: ['participation'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-charge-diagnostic',
    slug: 'charge-diagnostic',
    name: 'The Charge Diagnostic Mini-Game',
    essence: 'Identify, type, and size a charge, then route it to the right alchemy.',
    steps: [
      'Identify the charge.',
      'Type the charge (which channel).',
      'Size the charge.',
      'Find its elemental resonance.',
      'Hear its developmental voice.',
      'Choose an alchemy pathway.',
      'Aim dissatisfaction toward satisfaction.',
    ],
    source: MTGOA,
    allyshipReframe: 'Diagnose before you treat — name what is live before choosing a move.',
    moves: ['wake_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'both',
    superpowers: ['alchemist'],
    optimizesFor: 'Routing a charge to the move that actually fits it.',
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-fuel-check',
    slug: 'fuel-check',
    name: 'The Fuel Check',
    essence: 'Check your emotional fuel level before you act.',
    steps: [
      'Pause before committing to the next move.',
      'Read your tank: depleted, steady, or charged?',
      'Resource or rest if you are running on empty.',
    ],
    source: MTGOA,
    allyshipReframe: 'Speed is honest — you accelerate by metabolizing blockers, not by running on fumes.',
    moves: ['wake_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'inner',
    superpowers: ['alchemist'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-roll-for-resonance',
    slug: 'roll-for-resonance',
    name: 'Roll for Resonance',
    essence: 'A ritual to discover your superpower.',
    steps: [
      'Recall a moment you were unignorably helpful.',
      'Name the feeling you had doing it.',
      'Scan the six superpowers for the closest match.',
      'Ask a friend who has seen you in action.',
    ],
    source: MTGOA,
    allyshipReframe: 'Find the method of impact that is already yours, then play it on purpose.',
    moves: ['wake_up'],
    operations: [],
    domains: [],
    channels: [],
    aspect: 'inner',
    superpowers: ['alchemist'],
    tier: 'canonical',
    status: 'published',
  },
  {
    id: 'tech-ember-breath',
    slug: 'ember-breath',
    name: 'Ember Breath',
    essence: 'A micro-break for cooling the addiction to anger.',
    steps: [
      'Feel the heat without feeding it.',
      'Lengthen the exhale.',
      'Let the ember settle from blaze to warmth.',
    ],
    source: MTGOA,
    moves: ['clean_up'],
    operations: [],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['alchemist'],
    capabilities: ['agency'],
    tier: 'canonical',
    status: 'published',
  },
]
