/**
 * Alchemy Engine — Passage Resolver (Graceful AI Fallback)
 *
 * Unified passage resolution service that detects AI availability
 * and serves the appropriate content source (AI-generated or static
 * template) transparently to consumers.
 *
 * Design principles:
 *   - Non-AI path is first-class: static content always available
 *   - Proactive detection: checks availability BEFORE attempting generation
 *   - Graceful degradation: never throws on AI failure, always returns content
 *   - Source transparency: every resolved passage reports its content source
 *   - Vertical slice: Challenger face + Wake Up WAVE move only
 *
 * Fallback chain (priority order):
 *   1. Forced static (when explicitly requested or AI disabled)
 *   2. AI generation (when available + not forced static)
 *   3. Cached AI response (when cache hit available)
 *   4. Template bank content (channel-typed, GM-authored)
 *   5. Static inline content (always available, never fails)
 *
 * Components consume `resolvePassage()` and `resolveReflectionCompletions()`
 * instead of directly calling AI or static builders. The resolver handles
 * all detection, fallback, and source attribution internally.
 *
 * @see ai-generation.ts — AI generation + static builders
 * @see template-bank-data.ts — GM-authored template bank seed data
 * @see reflection-generation.ts — reflection completion generation
 * @see template-bank-types.ts — ChannelContentSlot, resolveChannelContent
 */

import type { EmotionalChannel } from '@/lib/quest-grammar/types'
import type { ArcPhase } from './types'
import type {
  SceneContext,
  GeneratedPassage,
  GeneratePassageOptions,
  PriorPhaseContent,
} from './ai-generation'
import {
  generatePassage,
  buildStaticPassage,
  isAIGenerationAvailable,
} from './ai-generation'
import { getVerticalSliceTemplate } from './template-bank-data'
import {
  resolveChannelContent,
  isReflectionPassage,
  type PassageTemplate,
  type ReflectionPassageTemplate,
  type ChannelContentSlot,
} from './template-bank-types'
import type { ReflectionContext } from './reflection-aggregator'
import type { ReflectionCompletionSet } from './reflection-generation'
import {
  buildStaticCompletionSuggestions,
  generateReflectionCompletions,
} from './reflection-generation'
import { VERTICAL_SLICE } from './types'

// ---------------------------------------------------------------------------
// Content Source — tracks how content was resolved
// ---------------------------------------------------------------------------

/**
 * Describes the source of resolved passage content.
 *
 * - 'ai': Generated by an AI model (OpenAI)
 * - 'template_bank': Resolved from GM-authored template bank (channel-typed)
 * - 'static_inline': Built from inline static content functions
 * - 'cached_ai': Previously generated AI content served from cache
 */
export type ContentSource = 'ai' | 'template_bank' | 'static_inline' | 'cached_ai'

/**
 * Reason why the fallback was triggered.
 *
 * - 'forced_static': Explicitly requested non-AI path
 * - 'ai_unavailable': AI service detected as unavailable (no API key)
 * - 'ai_error': AI generation attempted but failed
 * - 'ai_disabled': AI feature flag is off
 * - 'preferred_static': Caller prefers static (non-AI first-class)
 * - 'none': No fallback — primary source used
 */
export type FallbackReason =
  | 'forced_static'
  | 'ai_unavailable'
  | 'ai_error'
  | 'ai_disabled'
  | 'preferred_static'
  | 'none'

// ---------------------------------------------------------------------------
// Resolved Passage — the output contract
// ---------------------------------------------------------------------------

/**
 * A fully resolved passage with source attribution and fallback metadata.
 *
 * This is what components receive: content + transparency about where it came from.
 * Components render the same UI regardless of source — the source info is for
 * debugging, analytics, and trust indicators.
 */
export interface ResolvedPassage {
  /** The scene-setting narrative. */
  situation: string
  /** The friction point — what's at stake. */
  friction: string
  /** The invitation — what the player is being asked. */
  invitation: string

  /** How the content was obtained. */
  source: ContentSource
  /** Why fallback was used (if any). */
  fallbackReason: FallbackReason
  /** AI model used (null if not AI-generated). */
  model: string | null
  /** Whether AI was available when this was resolved. */
  aiAvailable: boolean

  /** Passage metadata for logging/debugging. */
  metadata: {
    phase: ArcPhase
    channel: EmotionalChannel
    face: string
    waveMove: string
    /** Approximate token cost (null for non-AI). */
    estimatedTokens: number | null
    /** Timestamp of resolution. */
    resolvedAt: string
  }
}

/**
 * Resolved reflection completions with source attribution.
 */
export interface ResolvedReflectionCompletions {
  /** The completion set (3 channel-typed suggestions). */
  completions: ReflectionCompletionSet
  /** How the content was obtained. */
  source: ContentSource
  /** Why fallback was used (if any). */
  fallbackReason: FallbackReason
  /** Whether AI was available when this was resolved. */
  aiAvailable: boolean
}

// ---------------------------------------------------------------------------
// AI Availability Detection
// ---------------------------------------------------------------------------

/**
 * AI availability status with diagnostic details.
 */
export interface AIAvailabilityStatus {
  /** Whether AI generation is available. */
  available: boolean
  /** Human-readable reason if unavailable. */
  reason?: string
  /** Whether the API key is configured. */
  hasApiKey: boolean
  /** Whether AI is explicitly disabled via feature flag. */
  featureDisabled: boolean
  /** Timestamp of the check. */
  checkedAt: string
}

/**
 * Check AI availability with diagnostic details.
 *
 * This is a proactive check — it runs BEFORE any generation attempt.
 * It checks:
 *   1. Environment variable (OPENAI_API_KEY)
 *   2. Feature flag (ALCHEMY_AI_ENABLED, defaults to true)
 *   3. Kill switch (ALCHEMY_AI_KILL_SWITCH)
 *
 * Does NOT make an API call — just checks configuration.
 */
export function checkAIAvailability(): AIAvailabilityStatus {
  const hasApiKey = isAIGenerationAvailable()
  const featureDisabled = process.env.ALCHEMY_AI_ENABLED === 'false'
  const killSwitch = process.env.ALCHEMY_AI_KILL_SWITCH === 'true'

  const available = hasApiKey && !featureDisabled && !killSwitch

  let reason: string | undefined
  if (!hasApiKey) {
    reason = 'OPENAI_API_KEY not configured'
  } else if (featureDisabled) {
    reason = 'AI generation disabled via ALCHEMY_AI_ENABLED=false'
  } else if (killSwitch) {
    reason = 'AI generation disabled via kill switch (ALCHEMY_AI_KILL_SWITCH=true)'
  }

  return {
    available,
    reason,
    hasApiKey,
    featureDisabled: featureDisabled || killSwitch,
    checkedAt: new Date().toISOString(),
  }
}

// ---------------------------------------------------------------------------
// Passage Resolver — Template Bank Path
// ---------------------------------------------------------------------------

/**
 * Resolve passage content from the template bank (GM-authored content).
 *
 * This is the template bank fallback path. It reads the GM-authored
 * PassageTemplate for the current phase and resolves channel-typed content
 * from the ChannelContentSlot system.
 *
 * Returns null if no template is found (should never happen for vertical slice).
 */
function resolveFromTemplateBank(
  phase: ArcPhase,
  channel: EmotionalChannel,
): ResolvedPassage | null {
  try {
    const template = getVerticalSliceTemplate(phase)
    if (!template) return null

    return {
      situation: resolveChannelContent(template.situation, channel),
      friction: resolveChannelContent(template.friction, channel),
      invitation: resolveChannelContent(template.invitation, channel),
      source: 'template_bank',
      fallbackReason: 'ai_unavailable',
      model: null,
      aiAvailable: false,
      metadata: {
        phase,
        channel,
        face: template.face,
        waveMove: template.waveMove,
        estimatedTokens: null,
        resolvedAt: new Date().toISOString(),
      },
    }
  } catch {
    return null
  }
}

/**
 * Convert a GeneratedPassage (from ai-generation.ts) to a ResolvedPassage.
 */
function fromGeneratedPassage(
  passage: GeneratedPassage,
  fallbackReason: FallbackReason,
  aiAvailable: boolean,
): ResolvedPassage {
  const source: ContentSource =
    passage.source === 'ai' ? 'ai' : 'static_inline'

  return {
    situation: passage.situation,
    friction: passage.friction,
    invitation: passage.invitation,
    source,
    fallbackReason,
    model: passage.model,
    aiAvailable,
    metadata: {
      ...passage.metadata,
      resolvedAt: new Date().toISOString(),
    },
  }
}

// ---------------------------------------------------------------------------
// Resolve Options
// ---------------------------------------------------------------------------

/**
 * Options for passage resolution.
 */
export interface ResolvePassageOptions {
  /**
   * Force non-AI path. When true, skips AI entirely and serves
   * template bank or static content directly. Default: false.
   *
   * This is not a "fallback" — the non-AI path is first-class.
   * Use this when the player/system explicitly prefers static content.
   */
  preferStatic?: boolean

  /**
   * AI model to use when AI is available. Default: 'gpt-4o-mini'.
   */
  model?: string

  /**
   * Prior phase content for grounding AI generation.
   * Required for Action and Reflection phases to incorporate
   * the player's earlier naming and commitment.
   */
  priorContent?: PriorPhaseContent

  /**
   * Which Challenger move was selected (Action phase only).
   */
  challengerMoveId?: 'issue_challenge' | 'propose_move'
}

// ---------------------------------------------------------------------------
// Core Resolver — resolvePassage
// ---------------------------------------------------------------------------

/**
 * Resolve passage content for a given phase and channel.
 *
 * This is the primary entry point for components needing passage content.
 * It transparently handles AI availability detection, generation attempts,
 * and graceful fallback to static content.
 *
 * Fallback chain:
 *   1. If `preferStatic` is true → template bank content (immediate)
 *   2. If AI unavailable (proactive check) → template bank content
 *   3. If AI available → attempt AI generation
 *   4. If AI generation fails → template bank content
 *   5. If template bank fails → static inline content (never fails)
 *
 * @param phase - Current arc phase (intake, action, reflection)
 * @param channel - Player's emotional channel
 * @param options - Resolution options (preferStatic, model, priorContent)
 * @returns ResolvedPassage with content + source attribution
 *
 * @example
 * ```ts
 * // Non-AI path (first-class)
 * const passage = await resolvePassage('intake', 'Fear', { preferStatic: true })
 *
 * // AI-augmented path (with automatic fallback)
 * const passage = await resolvePassage('action', 'Anger', {
 *   priorContent: { intakeText: 'My boundary was crossed' },
 *   challengerMoveId: 'issue_challenge',
 * })
 *
 * // Always works, always returns content
 * console.log(passage.source) // 'ai' | 'template_bank' | 'static_inline'
 * console.log(passage.fallbackReason) // 'none' | 'ai_unavailable' | ...
 * ```
 */
export async function resolvePassage(
  phase: ArcPhase,
  channel: EmotionalChannel,
  options: ResolvePassageOptions = {},
): Promise<ResolvedPassage> {
  const { preferStatic = false, model, priorContent, challengerMoveId } = options

  // Build scene context for AI generation (used by both paths)
  const sceneContext: SceneContext = {
    phase,
    channel,
    face: VERTICAL_SLICE.face,
    waveMove: VERTICAL_SLICE.waveMove,
    priorContent,
    challengerMoveId,
  }

  // ── Path 1: Explicit static preference ────────────────────────────────────
  if (preferStatic) {
    // Try template bank first (channel-typed, richer content)
    const templateResult = resolveFromTemplateBank(phase, channel)
    if (templateResult) {
      return {
        ...templateResult,
        fallbackReason: 'preferred_static',
        aiAvailable: checkAIAvailability().available,
      }
    }
    // Fall through to static inline
    return fromGeneratedPassage(
      buildStaticPassage(sceneContext),
      'preferred_static',
      checkAIAvailability().available,
    )
  }

  // ── Path 2: Proactive AI availability check ───────────────────────────────
  const aiStatus = checkAIAvailability()

  if (!aiStatus.available) {
    // AI is not available — use template bank (no wasted API call)
    console.info(
      `[passage-resolver] AI unavailable (${aiStatus.reason}), serving template bank content for ${phase}/${channel}`,
    )

    const templateResult = resolveFromTemplateBank(phase, channel)
    if (templateResult) {
      const reason: FallbackReason = aiStatus.featureDisabled ? 'ai_disabled' : 'ai_unavailable'
      return { ...templateResult, fallbackReason: reason }
    }

    // Template bank miss (shouldn't happen for vertical slice) — static inline
    const reason: FallbackReason = aiStatus.featureDisabled ? 'ai_disabled' : 'ai_unavailable'
    return fromGeneratedPassage(
      buildStaticPassage(sceneContext),
      reason,
      false,
    )
  }

  // ── Path 3: AI generation attempt ─────────────────────────────────────────
  try {
    const aiOptions: GeneratePassageOptions = { model }
    const generated = await generatePassage(sceneContext, aiOptions)

    if (generated.source === 'ai') {
      // AI succeeded
      return fromGeneratedPassage(generated, 'none', true)
    }

    // generatePassage returned static (internal fallback triggered)
    // This means AI failed silently within generatePassage
    // Enhance with template bank content if available
    const templateResult = resolveFromTemplateBank(phase, channel)
    if (templateResult) {
      return { ...templateResult, fallbackReason: 'ai_error', aiAvailable: true }
    }

    return fromGeneratedPassage(generated, 'ai_error', true)
  } catch (error) {
    // Unexpected error — template bank fallback
    console.warn(
      '[passage-resolver] Unexpected error during passage resolution, falling back to template bank:',
      error instanceof Error ? error.message : String(error),
    )

    const templateResult = resolveFromTemplateBank(phase, channel)
    if (templateResult) {
      return { ...templateResult, fallbackReason: 'ai_error', aiAvailable: true }
    }

    // Ultimate fallback — static inline (always works)
    return fromGeneratedPassage(
      buildStaticPassage(sceneContext),
      'ai_error',
      true,
    )
  }
}

// ---------------------------------------------------------------------------
// Reflection Completions Resolver
// ---------------------------------------------------------------------------

/**
 * Resolve reflection completion suggestions with graceful AI fallback.
 *
 * Follows the same fallback chain as resolvePassage:
 *   1. If `preferStatic` → static completion suggestions (immediate)
 *   2. If AI unavailable → static completion suggestions
 *   3. If AI available → attempt AI generation
 *   4. If AI fails → static completion suggestions
 *
 * @param ctx - Aggregated ReflectionContext from Intake + Action phases
 * @param preferStatic - When true, uses static path (default: false)
 * @returns ResolvedReflectionCompletions with source attribution
 */
export async function resolveReflectionCompletions(
  ctx: ReflectionContext,
  preferStatic: boolean = false,
): Promise<ResolvedReflectionCompletions> {
  // ── Path 1: Explicit static preference ────────────────────────────────────
  if (preferStatic) {
    return {
      completions: buildStaticCompletionSuggestions(ctx),
      source: 'static_inline',
      fallbackReason: 'preferred_static',
      aiAvailable: checkAIAvailability().available,
    }
  }

  // ── Path 2: Proactive AI availability check ───────────────────────────────
  const aiStatus = checkAIAvailability()

  if (!aiStatus.available) {
    console.info(
      `[passage-resolver] AI unavailable (${aiStatus.reason}), serving static reflection completions`,
    )
    const reason: FallbackReason = aiStatus.featureDisabled ? 'ai_disabled' : 'ai_unavailable'
    return {
      completions: buildStaticCompletionSuggestions(ctx),
      source: 'static_inline',
      fallbackReason: reason,
      aiAvailable: false,
    }
  }

  // ── Path 3: AI generation attempt ─────────────────────────────────────────
  try {
    const completions = await generateReflectionCompletions(ctx)

    if (completions.source === 'ai') {
      return {
        completions,
        source: 'ai',
        fallbackReason: 'none',
        aiAvailable: true,
      }
    }

    // generateReflectionCompletions fell back to static internally
    return {
      completions,
      source: 'static_inline',
      fallbackReason: 'ai_error',
      aiAvailable: true,
    }
  } catch (error) {
    console.warn(
      '[passage-resolver] Unexpected error during reflection completion resolution:',
      error instanceof Error ? error.message : String(error),
    )
    return {
      completions: buildStaticCompletionSuggestions(ctx),
      source: 'static_inline',
      fallbackReason: 'ai_error',
      aiAvailable: true,
    }
  }
}

// ---------------------------------------------------------------------------
// Template Bank Passage Resolver — Direct channel-typed content
// ---------------------------------------------------------------------------

/**
 * Resolve passage content directly from the template bank.
 *
 * This is a convenience function for components that want GM-authored
 * content without any AI attempt. It resolves channel-typed content
 * from the ChannelContentSlot system.
 *
 * Use this when you need:
 *   - Preview content in admin/GM views
 *   - Guaranteed static content (no async, no network)
 *   - Channel-typed narrative text from GM-authored templates
 *
 * @param phase - Arc phase
 * @param channel - Emotional channel for content resolution
 * @returns Template bank content or null if no template exists
 */
export function resolveTemplatePassage(
  phase: ArcPhase,
  channel: EmotionalChannel,
): ResolvedPassage | null {
  return resolveFromTemplateBank(phase, channel)
}

/**
 * Get the full PassageTemplate from the template bank for a phase.
 *
 * Returns the raw template with all channel overrides, choices, and metadata.
 * Useful for rendering the full CYOA UI including choices.
 *
 * @param phase - Arc phase
 * @returns The PassageTemplate (throws if not found)
 */
export function getPhaseTemplate(phase: ArcPhase): PassageTemplate {
  return getVerticalSliceTemplate(phase)
}

/**
 * Get the ReflectionPassageTemplate with epiphany-specific fields.
 *
 * Returns the reflection template with epiphanyPrompt, epiphanySeedPhrases,
 * and allowFreeformEpiphany fields. These shape the Reflection BAR content.
 *
 * @returns ReflectionPassageTemplate or null if not a reflection template
 */
export function getReflectionTemplate(): ReflectionPassageTemplate | null {
  const template = getVerticalSliceTemplate('reflection')
  if (isReflectionPassage(template)) return template
  return null
}

/**
 * Resolve a specific ChannelContentSlot to a string for a given channel.
 *
 * Convenience wrapper around resolveChannelContent that handles null channels.
 *
 * @param slot - The content slot with default + channel overrides
 * @param channel - The player's emotional channel (null uses default)
 * @returns The resolved string content
 */
export function resolveSlot(
  slot: ChannelContentSlot,
  channel: EmotionalChannel | null,
): string {
  return resolveChannelContent(slot, channel)
}
