
export type Trigram = 'Heaven' | 'Earth' | 'Thunder' | 'Water' | 'Mountain' | 'Wind' | 'Fire' | 'Lake'

export const TRIGRAMS: Trigram[] = ['Heaven', 'Earth', 'Thunder', 'Water', 'Mountain', 'Wind', 'Fire', 'Lake']

export type HexagramIntegrityResult = {
    hexagram: number
    upperTrigram: Trigram
    lowerTrigram: Trigram
    upperArchetype: string | null
    lowerArchetype: string | null
    valid: boolean
    errors: string[]
}

interface HexagramStruct {
    upper: Trigram
    lower: Trigram
}

/**
 * The King Wen sequence, all 64, complete.
 *
 * Corrected 2026-08-27. The previous table held ten entries and sent the other
 * fifty-four through a modulo fallback, which returned a structure unrelated to
 * the figure: hexagram 44 came back as Water under Wind where it is Wind under
 * Heaven. Quest generation, the gameboard, story-clock and the wiki all read
 * this, so they were reading fabricated trigrams for 54 of the 64 figures.
 *
 * Verified two ways. Every one of the 64 (lower, upper) pairs is distinct, so
 * the table covers the 8x8 trigram grid exactly once. And the three hexagrams
 * with independently written images in the Flirtcraft situation deck — 5, 31
 * and 44 — cross-check against their prose.
 *
 * Regenerated by `04 Quests/Flirtcraft Game/scripts/build-situation-deck.mjs`,
 * which fails its build if the grid stops being covered.
 */
export const HEXAGRAM_STRUCTURE: Record<number, HexagramStruct> = {
    1: { upper: 'Heaven', lower: 'Heaven' },
    2: { upper: 'Earth', lower: 'Earth' },
    3: { upper: 'Water', lower: 'Thunder' },
    4: { upper: 'Mountain', lower: 'Water' },
    5: { upper: 'Water', lower: 'Heaven' },
    6: { upper: 'Heaven', lower: 'Water' },
    7: { upper: 'Earth', lower: 'Water' },
    8: { upper: 'Water', lower: 'Earth' },
    9: { upper: 'Wind', lower: 'Heaven' },
    10: { upper: 'Heaven', lower: 'Lake' },
    11: { upper: 'Earth', lower: 'Heaven' },
    12: { upper: 'Heaven', lower: 'Earth' },
    13: { upper: 'Heaven', lower: 'Fire' },
    14: { upper: 'Fire', lower: 'Heaven' },
    15: { upper: 'Earth', lower: 'Mountain' },
    16: { upper: 'Thunder', lower: 'Earth' },
    17: { upper: 'Lake', lower: 'Thunder' },
    18: { upper: 'Mountain', lower: 'Wind' },
    19: { upper: 'Earth', lower: 'Lake' },
    20: { upper: 'Wind', lower: 'Earth' },
    21: { upper: 'Fire', lower: 'Thunder' },
    22: { upper: 'Mountain', lower: 'Fire' },
    23: { upper: 'Mountain', lower: 'Earth' },
    24: { upper: 'Earth', lower: 'Thunder' },
    25: { upper: 'Heaven', lower: 'Thunder' },
    26: { upper: 'Mountain', lower: 'Heaven' },
    27: { upper: 'Mountain', lower: 'Thunder' },
    28: { upper: 'Lake', lower: 'Wind' },
    29: { upper: 'Water', lower: 'Water' },
    30: { upper: 'Fire', lower: 'Fire' },
    31: { upper: 'Lake', lower: 'Mountain' },
    32: { upper: 'Thunder', lower: 'Wind' },
    33: { upper: 'Heaven', lower: 'Mountain' },
    34: { upper: 'Thunder', lower: 'Heaven' },
    35: { upper: 'Fire', lower: 'Earth' },
    36: { upper: 'Earth', lower: 'Fire' },
    37: { upper: 'Wind', lower: 'Fire' },
    38: { upper: 'Fire', lower: 'Lake' },
    39: { upper: 'Water', lower: 'Mountain' },
    40: { upper: 'Thunder', lower: 'Water' },
    41: { upper: 'Mountain', lower: 'Lake' },
    42: { upper: 'Wind', lower: 'Thunder' },
    43: { upper: 'Lake', lower: 'Heaven' },
    44: { upper: 'Heaven', lower: 'Wind' },
    45: { upper: 'Lake', lower: 'Earth' },
    46: { upper: 'Earth', lower: 'Wind' },
    47: { upper: 'Lake', lower: 'Water' },
    48: { upper: 'Water', lower: 'Wind' },
    49: { upper: 'Lake', lower: 'Fire' },
    50: { upper: 'Fire', lower: 'Wind' },
    51: { upper: 'Thunder', lower: 'Thunder' },
    52: { upper: 'Mountain', lower: 'Mountain' },
    53: { upper: 'Wind', lower: 'Mountain' },
    54: { upper: 'Thunder', lower: 'Lake' },
    55: { upper: 'Thunder', lower: 'Fire' },
    56: { upper: 'Fire', lower: 'Mountain' },
    57: { upper: 'Wind', lower: 'Wind' },
    58: { upper: 'Lake', lower: 'Lake' },
    59: { upper: 'Wind', lower: 'Water' },
    60: { upper: 'Water', lower: 'Lake' },
    61: { upper: 'Wind', lower: 'Lake' },
    62: { upper: 'Thunder', lower: 'Mountain' },
    63: { upper: 'Water', lower: 'Fire' },
    64: { upper: 'Fire', lower: 'Water' },
}

/** Every hexagram is in the table above. A miss is a bug, never a fallback. */
export function getHexagramStructure(id: number): HexagramStruct {
    const struct = HEXAGRAM_STRUCTURE[id]
    if (!struct) throw new Error(`getHexagramStructure: ${id} is outside 1-64`)
    return struct
}

const SPOT_CHECKS: Partial<Record<number, {
    upperTrigram: Trigram
    lowerTrigram: Trigram
    upperArchetype: string
    lowerArchetype: string
}>> = {
    20: {
        upperTrigram: 'Wind',
        lowerTrigram: 'Earth',
        upperArchetype: 'The Subtle Influence',
        lowerArchetype: 'The Devoted Guardian',
    },
    15: {
        upperTrigram: 'Earth',
        lowerTrigram: 'Mountain',
        upperArchetype: 'The Devoted Guardian',
        lowerArchetype: 'The Still Point',
    },
}

export function verifyHexagramIntegrity(
    hexagramNumber: number,
    trigramToArchetype: Record<string, string> = {}
): HexagramIntegrityResult {
    const structure = getHexagramStructure(hexagramNumber)
    const upperTrigram = structure.upper
    const lowerTrigram = structure.lower
    const upperArchetype = trigramToArchetype[upperTrigram.toLowerCase()] || null
    const lowerArchetype = trigramToArchetype[lowerTrigram.toLowerCase()] || null
    const errors: string[] = []

    if (!upperArchetype) {
        errors.push(`Missing archetype mapping for upper trigram "${upperTrigram}"`)
    }
    if (!lowerArchetype) {
        errors.push(`Missing archetype mapping for lower trigram "${lowerTrigram}"`)
    }

    if (
        upperTrigram !== lowerTrigram &&
        upperArchetype &&
        lowerArchetype &&
        upperArchetype.toLowerCase() === lowerArchetype.toLowerCase()
    ) {
        errors.push(
            `Distinct trigrams map to same archetype ("${upperTrigram}" and "${lowerTrigram}" -> "${upperArchetype}")`
        )
    }

    const expected = SPOT_CHECKS[hexagramNumber]
    if (expected) {
        if (upperTrigram !== expected.upperTrigram || lowerTrigram !== expected.lowerTrigram) {
            errors.push(
                `Hexagram ${hexagramNumber} expected ${expected.upperTrigram} over ${expected.lowerTrigram}, got ${upperTrigram} over ${lowerTrigram}`
            )
        }
        if (upperArchetype && upperArchetype !== expected.upperArchetype) {
            errors.push(
                `Hexagram ${hexagramNumber} upper trigram archetype expected "${expected.upperArchetype}", got "${upperArchetype}"`
            )
        }
        if (lowerArchetype && lowerArchetype !== expected.lowerArchetype) {
            errors.push(
                `Hexagram ${hexagramNumber} lower trigram archetype expected "${expected.lowerArchetype}", got "${lowerArchetype}"`
            )
        }
    }

    return {
        hexagram: hexagramNumber,
        upperTrigram,
        lowerTrigram,
        upperArchetype,
        lowerArchetype,
        valid: errors.length === 0,
        errors,
    }
}

/** Trigram → its three lines, bottom to top. 1 = yang (firm), 0 = yin (yielding). */
const TRIGRAM_LINES: Record<Trigram, [number, number, number]> = {
    Heaven: [1, 1, 1],
    Lake: [1, 1, 0],
    Fire: [1, 0, 1],
    Thunder: [1, 0, 0],
    Wind: [0, 1, 1],
    Water: [0, 1, 0],
    Mountain: [0, 0, 1],
    Earth: [0, 0, 0],
}

/** The six lines of a hexagram, bottom to top. Index 0 is line one. */
export function getHexagramLines(id: number): number[] {
    const { lower, upper } = getHexagramStructure(id)
    return [...TRIGRAM_LINES[lower], ...TRIGRAM_LINES[upper]]
}

/**
 * Correctness of place (当位). Odd positions are yang places, even are yin.
 * A line is correct when a firm line sits in a yang place, or a yielding line
 * in a yin place. Hexagram 63 has all six correct; 64 has none.
 *
 * @param position 1-6, counting from the bottom.
 */
export function isLineCorrect(id: number, position: number): boolean {
    if (position < 1 || position > 6) throw new Error(`isLineCorrect: position ${position} is outside 1-6`)
    const line = getHexagramLines(id)[position - 1]
    const yangPlace = position % 2 === 1
    return yangPlace ? line === 1 : line === 0
}

/**
 * Face → its line in the figure.
 *
 * Corrected 2026-08-27. This was a face-to-trigram table that mapped six faces
 * onto six of the eight trigrams and left Water and Thunder with no face — the
 * collapse the 2026-08-23 ruling names. A face has an expression at every
 * trigram, so no trigram is nearer a face than any other, and an axis built on
 * trigram identity was scoring a relationship that does not exist. It also cost
 * coverage: 28 of the 64 figures contain Water or Thunder and scored for nobody.
 *
 * The six classical line positions divide evenly among six faces and each
 * position already carries a canonical role:
 *
 *   1  the beginning, below and hidden            → Shaman
 *   2  the officer in the field, who corresponds  → Diplomat
 *   3  the exposed transition                     → Challenger
 *   4  the minister, next to power                → Architect
 *   5  the ruler's place                          → Regent
 *   6  past the situation                         → Sage
 *
 * A figure scores when that line is correctly placed, so it supports the face's
 * seat. Every face matches exactly 32 of the 64, where the old table gave each
 * 15 and wasted 28 figures. Deleting the axis instead is a one-line change:
 * drop `breakdown.sect` from the sum in scoreHexagramAlignment.
 */
export const FACE_LINE: Record<string, number> = {
  shaman: 1,
  diplomat: 2,
  challenger: 3,
  architect: 4,
  regent: 5,
  sage: 6,
}
