BEIT = ("Speak as *I*, one paragraph, and say what you have to say about showing up as an ally.", "Speak as *I* for one paragraph, saying what you have to say about showing up as an ally.", 2)
E = [
("The Regent had built walls, and the walls held, but the Regent's walls", "The Regent had built walls that held, but the Regent's walls"),
("I was told that at nineteen, by people who meant well, and I believed them for another thirty years.", "I was nineteen when people who meant well told me that. I believed them for another thirty years."),
("The version they described does exist, and you've probably met them, and it is not what we're talking about here.", "The version they described does exist (you've probably met them), but it is not what we're talking about here."),
("Very few people can do all three without flinching, and the third is where most people stop.", "Very few people can do all three without flinching. The third is where most people stop."),
("It has two poles, and both of them are right.", "It has two poles, both of them right."),
("Both poles have a failure state, and the failure states do not mirror each other.", "Both poles have failure states that do not mirror each other."),
("was real,\n   and the line I did not draw was", "was real,\n   though the line I did not draw was"),
("in a way it had not a second earlier, and open is the condition Metal is for.", "in a way it had not a second earlier. Open is the condition Metal is for."),
("You interrupted, and now something unscripted is happening, and you are still here.", "You interrupted. Something unscripted is happening now, yet you are still here."),
("Numbness is Neutrality stuck, and it explains why", "Numbness is Neutrality stuck, which explains why"),
("Let it anchor instead of drown, and it becomes Poignance,", "Once it anchors instead of drowning, it becomes Poignance,"),
("The sequence used to skip this stage, and skipping it lets a reader", "The sequence used to skip this stage. Skipping it lets a reader"),
("a rupture that has not happened yet, and offering it converts the line into a preference.", "a rupture that has not happened yet, which converts the line into a preference."),
("It does not glare, and it does not wait for capitulation:", "It does not glare or wait for capitulation:"),
("you finish the sentence, and then you do not add another one.", "you finish the sentence, then do not add another one."),
("A version of this chapter gets braced against, and it should be named before we go further.", "A version of this chapter gets braced against. It should be named before we go further."),
("It happens, you recognize it on sight, and anyone who has been on the receiving end", "It happens; you recognize it on sight. Anyone who has been on the receiving end"),
("What 3-2-1 owns is your split, and it makes no claim about their innocence.", "What 3-2-1 owns is your split. It makes no claim about their innocence."),
("That part has an opposite, and your nervous system has already given the opposite a face.", "That part has an opposite, one your nervous system has already given a face."),
BEIT,
("*do this and you become the difficult one, and what you have with these people will not survive it.*", "*do this and you become the difficult one. What you have with these people will not survive it.*"),
("That voice is a memory, and it reports accurately.", "That voice is a memory that reports accurately."),
("out of being a memory, and you would not want to, because the memory is true.", "out of being a memory, nor would you want to, because the memory is true."),
("the honest answer names the old charge, and the auditor has just saved you", "the honest answer names the old charge, in which case the auditor has just saved you"),
("Only looking at you answers the second, and the Skeptic already knows how that audit comes out.", "Only looking at you answers the second, an audit whose outcome the Skeptic already knows."),
("Then it speaks, and it always sounds reasonable.", "Then it speaks. It always sounds reasonable."),
("You filed it instead of aiming it, and you carried it home.", "You filed it instead of aiming it, then carried it home."),
("The cost lands twice: you lose the line, and the person who needed the line ends up somewhere nobody drew one, where the crossing went unremarked, and everyone present,", "The cost lands twice: once on you, who lose the line, and once on the person who needed it, who ends up somewhere nobody drew one, where the crossing went unremarked and everyone present,"),
("that sounds like humility, and sometimes it is exactly that.", "that sounds like humility, which sometimes it is."),
("Fire your auditor and every charge becomes a line, and your no is worth nothing inside a month.", "If you fire your auditor, every charge becomes a line, so your no is worth nothing inside a month."),
("that question I want, and I will listen to the answer.", "that question I want. I will listen to the answer."),
("Yours has a house style, and that is what to work.", "Yours has a house style, which is what to work."),
("Both poles are real goods, and Section 4 named what each one costs alone.", "Both poles are real goods, though Section 4 named what each one costs alone."),
("It argues for Restraint, and Restraint is half of the truth.", "It argues for Restraint, which is half of the truth."),
("and call it discernment, and no single instance will look like a failure.", "and call it discernment, without a single instance looking like a failure."),
("Fighting comes easy by comparison, and so does certainty.", "Fighting and certainty come easy by comparison."),
("*we skipped past something, and it was about Priya, who is on this call.*", "*we skipped past something about Priya, who is on this call.*"),
("The pressure arrives feeling like urgency, and urgency is the most convincing wrong reason to say something.", "The pressure arrives feeling like urgency, the most convincing wrong reason to say something."),
("Thirty seconds, and you may think about anything except what you are going to say.", "For thirty seconds you may think about anything except what you are going to say."),
("you did the talking down, and the reading you now have", "you did the talking down, so the reading you now have"),
("**The test:** Thirty seconds passed, you said nothing, and the charge is the size it was.", "**The test:** Thirty seconds passed and you said nothing, yet the charge is the size it was."),
("You have to say something hard to someone, and you have twenty minutes before you say it.", "You have to say something hard to someone in twenty minutes."),
("Hurt delivered as anger lands as an attack, and nothing they do can satisfy it, because", "Hurt delivered as anger lands as an attack that nothing they do can satisfy, because"),
("The second sentence costs more to say, and it is the only one that can be answered.", "Only the second sentence can be answered, though it costs more to say."),
("from a calendar invite, and I think we have told her what we think she is worth", "from a calendar invite. I think we have told her what we think she is worth"),
("It tells you which fights are yours, and it tells you the four you swallowed were all the same fight.", "It tells you which fights are yours, and that the four you swallowed were all the same fight."),
("You can name the subject in one noun, and it surprises you a little.", "You can name the subject in one noun, a noun that surprises you a little."),
("does not deliver the outcome, and confusing those is how advocacy", "does not deliver the outcome. Confusing those is how advocacy"),
("You see exactly what is wrong, you name it accurately, more accurately than anyone else at the table, and nothing in the world moves.", "You see exactly what is wrong and name it accurately, more accurately than anyone else at the table, yet nothing in the world moves."),
("decide whether it stands, and the same three moves decide it in every domain.", "decide whether it stands. The same three moves decide it in every domain."),
("how big the crossing was, and the auditor's first offer is always to round it down,", "how big the crossing was, but the auditor's first offer is always to round it down,"),
("is a verdict on a character, and a verdict gives the other person something to defend", "is a verdict on a character, which gives the other person something to defend"),
("in any of the four domains, and most lines get withdrawn there,", "in any of the four domains. Most lines get withdrawn there,"),
("the limit now exists between you, out loud, and they have to decide what to do about it.", "the limit now exists between you, out loud, and that they have to decide what to do about it."),
("could not have refused, and you refused it in your own name", "could not have refused, and did so in your own name"),
("That question is real, and it belongs to the Challenger, because", "That question is real. It belongs to the Challenger, because"),
("So the discomfort goes into escrow until the verdict, and the verdict does not release it.", "So the discomfort goes into escrow until a verdict that does not release it."),
("The move gets run, and the output gets called a finding.", "The move gets run, then its output gets called a finding."),
("often the best read at the table, and nothing in the world moves.", "often the best read at the table, yet nothing in the world moves."),
("whether it was ever real, and reality gets settled at interpretation.", "whether it was ever real, which gets settled at interpretation."),
("without softening it into a question, and it will cost me being the easy vote on that panel.**", "without softening it into a question, at the cost of being the easy vote on that panel.**"),
("It is the most defensible myth in the book, and its defensibility is what makes it durable.", "It is the most defensible myth in the book, which is what makes it durable."),
("they have no relationship to, and deference is the correct posture", "they have no relationship to. Deference is the correct posture"),
("until somebody ratifies it, and ratification does not arrive inside the thirty seconds the moment lasts.", "until somebody ratifies it, which does not happen inside the thirty seconds the moment lasts."),
("name the shape the fire arrives in, and each one runs on a different EA channel,", "name the shape the fire arrives in. Each one runs on a different EA channel,"),
("the aim is the stage almost everyone skips, and the standing is the stage almost everyone collapses at,", "the aim is the stage almost everyone skips, while the standing is the stage almost everyone collapses at,"),
("turned charge into a line or spent it, and it asks not whether you were right", "turned charge into a line or spent it, asking not whether you were right"),
]
