BEIT = ("Speak as *I*, one paragraph, and say what you have to say about showing up as an ally.", "Speak as *I* for one paragraph, saying what you have to say about showing up as an ally.", 2)
E = [
("because devotion implies choice, and she has forgotten how to choose.", "because devotion implies a choice she has forgotten how to make."),
("Repair without Negotiate is generosity without closure, and generosity without closure stops being a gift;", "Repair without Negotiate is generosity without closure, which stops being a gift;"),
("better than it had since the Shaman, and the villagers said so out loud.", "better than it had since the Shaman. The villagers said so out loud."),
("was now naming a price, and a village that has been receiving", "was now naming a price. A village that has been receiving"),
("The village chose this, and it had a reason it could defend.", "The village chose this for a reason it could defend."),
("keeps everybody comfortable and moves nobody, and everyone in it stays kind and slightly stuck.", "keeps everybody comfortable and moves nobody, so everyone in it stays kind and slightly stuck."),
("The village called the pattern kindness, and the pattern emptied it one person at a time.", "The village called the pattern kindness. The pattern emptied it one person at a time."),
("tradition and inherited structure, and the Challenger operates through", "tradition and inherited structure, and where the Challenger operates through"),
("holds real (people do this), and it explains why", "holds real (people do this), which explains why"),
("is the open question here, and I am the wrong person to settle it.", "is the open question here, one I am the wrong person to settle."),
("a condition of continued affection, and it arrives while anyone still has time", "a condition of continued affection, and arrives while anyone still has time"),
("removes the other party's freedom to answer, and an honest term gives the answer back to them.", "removes the other party's freedom to answer, while an honest term gives the answer back to them."),
("because a term might land badly, and something that lands badly is harm, and harm is disqualifying.", "because a term that lands badly counts as harm, which is disqualifying."),
("It has two poles, and both of them are right.", "It has two poles, both of them right."),
("Both poles have a failure state, and the failure states do not look alike.", "Both poles have failure states that do not look alike."),
("One part of this belongs specifically to this reader, and it explains why the axis", "One part of this belongs specifically to this reader: the part that explains why the axis"),
("It happens one reasonable call at a time, and each call is defensible.", "It happens one reasonable call at a time, each call defensible."),
("possible,\n   and what I have not yet said is", "possible,\n   though what I have not yet said is"),
("treating every connection as required, and never notice what it costs until you are empty.", "treating every connection as required, without noticing what it costs until you are empty."),
("This guilt is real, and it is also a distortion.", "This guilt is real, yet also a distortion."),
("Hold is addition, and it costs, and it does not end when the silence does.", "Hold is addition, which costs and does not end when the silence does."),
("and you mean it, and then the hour runs, everyone reports status, and what actually happened last sprint never comes up.", "and you mean it. Then the hour runs and everyone reports status, while what actually happened last sprint never comes up."),
("The field is what happens between people, and everyone there makes it.", "The field is what happens between people, made by everyone there."),
("Anxiety shows up while you do this, and it reads the situation correctly,", "Anxiety shows up while you do this, reading the situation correctly,"),
("What you are watching for is growth, and you know it arrived when", "What you are watching for is growth. You know it arrived when"),
("Their sentence is between everyone now, and you could not have said it for them.", "Their sentence is between everyone now, a sentence you could not have said for them."),
("That is the Wood channel completing, and Bliss is what it feels like", "That is the Wood channel completing. Bliss is what it feels like"),
("the community meeting ends on time, and everyone leaves carrying what they walked in with.", "the community meeting ends on time. Everyone leaves carrying what they walked in with."),
("You let the hard sentence land, and you stay, and the field turns out to hold.", "When you let the hard sentence land and stay, the field turns out to hold."),
("It will move, and the Translate move gives the movement a shape.", "It will move. The Translate move gives the movement a shape."),
("People stay together, accumulate damage they never recover from, and one day something breaks", "People stay together and accumulate damage they never recover from, until one day something breaks"),
("The Challenger's line in the sand does different work, and so does the Regent's decree.", "The Challenger's line in the sand and the Regent's decree do different work."),
("by swallowing your stake, and now the calm curdles into bitterness you can't explain because", "by swallowing your stake. Now the calm curdles into bitterness you can't explain, because"),
("your chest engages, your feet plant, and nothing has exploded.", "your chest engages and your feet plant, yet nothing has exploded."),
("They say the sentence nobody else will, the temperature drops, and the matter gets settled.", "When they say the sentence nobody else will, the temperature drops and the matter gets settled."),
BEIT,
("at length, twice, and by the end I had taken up more of it than anyone.", "at length, twice. By the end I had taken up more of it than anyone."),
("absorb harm indefinitely and call it fine, and nobody there will stop you.", "absorb harm indefinitely and call it fine. Nobody there will stop you."),
("the source of your authority in the field, and that is a catastrophe you will never see happen,", "the source of your authority in the field: a catastrophe you will never see happen,"),
("Someone names an impact you had, and before they finish the sentence the ledger has opened and produced a number, and the number says this is impossible:", "Someone names an impact you had. Before they finish the sentence the ledger has opened and produced a number that says this is impossible:"),
("whether I am allowed to speak here, and it does not get a vote on whether I have caused harm.*", "whether I am allowed to speak here, nor does it get a vote on whether I have caused harm.*"),
("to the field rather than about it, and then the others take their turn.", "to the field rather than about it. Then the others take their turn."),
("One sentence, and then silence, and then whatever they do with it.", "One sentence, then silence, then whatever they do with it."),
("It does not cover the case, and that is the point.", "It does not cover the case, which is the point."),
("Then the ledger opens underneath it, and what surfaces is not a defense.", "Then the ledger opens underneath it. What surfaces is not a defense."),
("Yours has actual entries in it, and those are what to work.", "Yours has actual entries in it, which are what to work."),
("Both poles are real goods, and this chapter is unusual in the book", "Both poles are real goods. This chapter is unusual in the book"),
("sits somewhere on that axis, and where it sits is a judgment call, and judgment calls about what something costs are precisely what a ledger is for.", "sits somewhere on that axis. Where it sits is a judgment call, precisely the kind of call about cost a ledger is for."),
("It argues for Care, and Care is half the truth, and it is the half you are good at.", "It argues for Care, which is half the truth, and the half you are good at."),
("and call it discernment, and no single instance looks like an evasion.", "and call it discernment, without a single instance looking like an evasion."),
("That forms the Connector's foundation, and the word usually means something else.", "That forms the Connector's foundation, though the word usually means something else."),
("is attendance, and attendance is what everyone in a field takes for granted.", "is attendance, which everyone in a field takes for granted."),
("the returns on telling it, and some of those returns are real:", "the returns on telling it, some of them real:"),
("Dele has two children and a housing voucher, and the agent has said neither out loud.", "Dele has two children and a housing voucher, neither of which the agent has said out loud."),
("I think it may be the voucher, and I would rather we discussed that.*", "I think it may be the voucher, which I would rather we discussed.*"),
("is theirs to answer, and a correction is the move working rather than failing.", "is theirs to answer. A correction is the move working rather than failing."),
("from within their own framework, and what they're saying only makes sense from inside that framework.", "from within their own framework, so what they're saying only makes sense from inside it."),
("*\"they're questioning our authority\"*, and respond defensively", "*\"they're questioning our authority\"*, then respond defensively"),
("instead of to each other, and the conversation becomes a performance", "instead of to each other, so the conversation becomes a performance"),
("an agreement that works for both of us, and I am not running a strategy.*", "an agreement that works for both of us. I am not running a strategy.*"),
("When trust breaks, and it will, the Diplomat has a specific structure for repair, and it runs on uncomfortable sentences", "When trust breaks, as it will, the Diplomat has a specific structure for repair, one that runs on uncomfortable sentences"),
("*\"I know I've been more withdrawn the last two weeks, and I know that reads as pulling away, and I wasn't communicating why, and that must have felt like a punishment.\"*", "*\"I know I've been more withdrawn the last two weeks, which reads as pulling away. I wasn't communicating why, so it must have felt like a punishment.\"*"),
("moved Alan sideways at fifty-eight, and you were sure at the time.", "moved Alan sideways at fifty-eight, sure at the time."),
("Say so, clearly, without apology, and without pretending your refusal is neutral", "Say so, clearly and without apology, never pretending your refusal is neutral"),
("values inclusion, and inclusion can curdle into a relativistic posture", "values inclusion, which can curdle into a relativistic posture"),
("This is the basic work of the Diplomat's altitude, and it is precious.", "This is the basic, precious work of the Diplomat's altitude."),
("decide whether the terms hold, and the same three moves decide it in every domain.", "decide whether the terms hold. The same three moves decide it in every domain."),
("gets answered as a charge, and an answer spent on themselves never reaches your terms.", "gets answered as a charge. An answer spent on themselves never reaches your terms."),
("to work the number out alone, and it will work it out low.", "to work the number out alone. The field will work it out low."),
("A close is an invitation, and it gets accepted the moment somebody tells you", "A close is an invitation, accepted the moment somebody tells you"),
("run afterward with somebody else, and it cost you your standing as the one who never asks for anything. The proof is that they got to answer, and whatever they answered", "run afterward with somebody else. It cost you your standing as the one who never asks for anything. The proof is that they got to answer, and that whatever they answered"),
("the fourth conversation of its kind, and it cost you being the one everybody agreed was still listening. The proof is that the group now has terms somebody can hold it to, and the people who carried it", "the fourth conversation of its kind. It cost you being the one everybody agreed was still listening. The proof is that the group now has terms somebody can hold it to, and that the people who carried it"),
("That question is real, and it belongs to the Diplomat, because you have kept an exact record of what this costs you, and a record kept that long gives every honest sentence a second job.", "That question is real. It belongs to the Diplomat, because a record of what this costs you, kept as exactly and as long as yours, gives every honest sentence a second job."),
("Grow Up asks about other people by design, and Show Up is the relationship you build,", "Grow Up asks about other people by design. Show Up is the relationship you build,"),
("anger would have to make a request, and a request can be refused.", "anger would have to make a request, which can be refused."),
("becomes who will corroborate, and the field fills with people", "becomes who will corroborate, so the field fills with people"),
("entitles you to, and the ledger settles that account at the exact moment", "entitles you to, an account the ledger settles at the exact moment"),
("at Thursday's meeting, and it will cost me being the one who explains them to everybody else.**", "at Thursday's meeting, at the cost of being the one who explains them to everybody else.**"),
("reliably safe to be around, and it is worth saying plainly what replaces it.", "reliably safe to be around, which makes it worth saying plainly what replaces it."),
("The five stages form the chapter's spine, and you have now met all five:", "You have now met all five stages that form the chapter's spine:"),
]
