E = [
("was both embarrassing and fitting: I was writing a book about allyship, and it was making me feel like a worse ally.", "was both embarrassing and fitting: writing a book about allyship was making me feel like a worse ally."),
("that part decides, and it decides before the conscious you arrives.", "that part has decided before the conscious you arrives."),
("It plays by one rule, and the rule is keep you safe.", "It plays by one rule: keep you safe."),
("This whole book builds toward that move, and that is why so much of it runs on shadow work.", "This whole book builds toward that move, which is why so much of it runs on shadow work."),
("Somebody gets talked over, or a decision lands on the person with the least power to absorb it, and the temperature drops while everyone keeps talking.", "When somebody gets talked over, or a decision lands on the person with the least power to absorb it, the temperature drops while everyone keeps talking."),
("You can see how the systems you were born into wear people down by design, and you can see how little your moves seem to move the machine, and you keep playing anyway while the worry keeps running underneath the play.", "You can see how the systems you were born into wear people down by design and how little your moves seem to move the machine. You keep playing anyway, while the worry keeps running underneath the play."),
("Somebody built it to run on compliance, and it collects plenty, and the people it was supposed to help are still standing where they were.", "Somebody built it to run on compliance. It collects plenty, yet the people it was supposed to help are still standing where they were."),
("designed never to clear, and some part of you", "designed never to clear, so some part of you"),
("It spends theirs as well, and meaning well does not reduce the bill.", "It spends theirs as well. Meaning well does not reduce the bill."),
("The game frame is the medicine for this, and it works because", "The game frame is the medicine for this. It works because"),
("is the price of admission, and everyone pays it because", "is the price of admission. Everyone pays it because"),
("I have spent my whole adult life in those spaces, and I have needed them.", "I have needed those spaces my whole adult life."),
("That is a game of its own, and it is one I have played for myself.", "That is a game of its own, one I have played for myself."),
("what they need, and your theory of harm is invisible to them either way.", "what they need. Your theory of harm is invisible to them either way."),
("Most of the examples ahead happen at work, and several assume you have a budget or a say in how the work gets scheduled. An office leaves its machinery where you can see it, and I have spent my hours there.", "Most of the examples ahead happen at work, because an office leaves its machinery where you can see it, and because I have spent my hours there. Several assume you have a budget or a say in how the work gets scheduled."),
("in a queue, and nobody has ever asked your opinion about the rota, the move is the same.", "in a queue, and if nobody has ever asked your opinion about the rota, the move is the same."),
("showed up ready to help, and some of the spaces they walked into", "showed up ready to help, but some of the spaces they walked into"),
("Newcomers with good intentions do real damage, and the language was a way to screen for care.", "Because newcomers with good intentions do real damage, the language was a way to screen for care."),
("count as the help itself, and people who were ready", "count as the help itself, so people who were ready"),
("set out to carve himself the perfect woman, and converting them starts to feel like doing something", "set out to carve himself the perfect woman. Soon converting them feels like doing something"),
("Then one of them pushes back, and you hit the wall you cannot step around: you might have hurt someone by trying to help them, and you might never have asked whether they wanted your help in the first place.", "When one of them finally pushes back, you hit the wall you cannot step around: you might have hurt someone by trying to help them, without ever asking whether they wanted your help in the first place."),
("That shock exposes the conflict the whole game is built on, and it is not a flattering one.", "That shock exposes the unflattering conflict the whole game is built on."),
("It was true about me, and I had the framework", "It was true about me, even though I had the framework"),
("The game hands you every bit of it, and it stops paying the day you admit the game does not work.", "The game hands you every bit of it until the day you admit the game does not work."),
("I wrote a whole book about not doing this move, and I did it the entire time I was writing.", "I did this move the entire time I was writing a whole book about not doing it."),
("Here is the good news, and it happens to be", "Here is the good news, which happens to be"),
("That is the master myth, allyship means being good, and it comes in ten versions.", "That is the master myth: allyship means being good. It comes in ten versions."),
("It scores how you actually behave, and it has no score for which kind of ally you are, because", "It scores how you actually behave, not which kind of ally you are, because"),
("never saw them arrive, and you have been straining", "never saw them arrive. You have been straining"),
("the currency is tokens, and they come in two kinds.", "the currency is tokens, which come in two kinds."),
("bill you later, and the bill comes due", "bill you later. The bill comes due"),
("using yourself as the fuel, and a fire that eats", "using yourself as the fuel. A fire that eats"),
("For three years I fueled this book with guilt, and guilt is that first kind:", "For three years I fueled this book with guilt, a token of the first kind:"),
("is ore, and you have been spending it as pure loss.", "is ore you have been spending as pure loss."),
("Allyship has a prize counter too, and most people", "Allyship has a prize counter too. Most people"),
("They are external, they vanish the moment the crowd turns, and you already know what they are worth: you perform the care, you feel like somebody for an hour, and you are empty by dinner.", "They are external and vanish the moment the crowd turns. You already know what they are worth: you perform the care, feel like somebody for an hour, and are empty by dinner."),
("You walk out tired, and the satisfaction", "You walk out tired, but the satisfaction"),
("runs the other way, and the prize converts back into tokens.", "runs the other way: the prize converts back into tokens."),
("is renewable fuel, and it goes straight into the tank.", "is renewable fuel that goes straight into the tank."),
("A practice fills it, and a filled tank", "A practice fills it. A filled tank"),
("running a game of their own, and you are the one who walked onto their floor.", "running a game of their own. You are the one who walked onto their floor."),
("in front of them, and there is nothing human about it.", "in front of them. There is nothing human about it."),
("arrived offering help, and a bouncer that has met", "arrived offering help. A bouncer that has met"),
("It does not weigh you up, and it does not wonder about you.", "It does not weigh you up or wonder about you."),
("It checks you against the shape, before anybody has said much, and it checks fast.", "It checks you against the shape, fast, before anybody has said much."),
("Schoorman's, and Appendix G says", "Schoorman's. Appendix G says"),
("You can become a kinder person, and it matters, and it still does not put the finding in their head.", "Becoming a kinder person matters, but it still does not put the finding in their head."),
("how trust gets built, and a diagram like that", "how trust gets built. A diagram like that"),
("as small as it gets, and almost anybody can receive it.", "as small as it gets, so almost anybody can receive it."),
("asks for far more, and it needs a history behind it before it lands at all.", "asks for far more: a history behind you before it lands at all."),
("You will find out who those bouncers are in the next chapter, and you will meet your own first, because", "In the next chapter you will find out who those bouncers are, starting with your own, because"),
("was praise, and praise has a shape to it.", "was praise, which has a shape to it."),
("which puts one of you above the other, and you are now doing something other than allyship.", "which puts one of you above the other. At that point you are doing something other than allyship."),
("That is the test, and you can run it on anything anybody hands you.", "You can run that test on anything anybody hands you."),
("the second one gets bought, and the people who would have paid", "the second one gets bought, so the people who would have paid"),
("Those are the owners, and keeping that shelf stocked", "Those are the owners. Keeping that shelf stocked"),
("I have not worked that out, and anybody who tells you", "I have not worked that out. Anybody who tells you"),
("between you and the outcome, and it hands you clear rules", "between you and the outcome and hands you clear rules"),
("a weight good people carry), and it runs on the fuel", "a weight good people carry) that runs on the fuel"),
("burns down to nothing, and the person you showed up for is left standing there the day you finally collapse.", "burns down to nothing, leaving the person you showed up for standing there the day you finally collapse."),
("called the Infinite Arcade, and it is why the answer", "called the Infinite Arcade, and why the answer"),
("So does a line you never have to cross, and so does an exhaustion other people can see.", "So do a line you never have to cross and an exhaustion other people can see."),
("Catch yourself in the act, name your own existential kink, grin, and you are playing.", "If you catch yourself in the act, name your own existential kink and grin, you are playing."),
("at the center of the work, and you have been paying it off", "at the center of the work. You have been paying it off"),
("Those are the three reasons, and the rest of this book is built on them.", "Those are the three reasons the rest of this book is built on."),
("Trip sitting is harm reduction, and harm reduction is allyship", "Trip sitting is harm reduction, which is allyship"),
("nothing to do with that night, and it was there when I reached for it.", "nothing to do with that night, yet it was there when I reached for it."),
("running that night, and I had spent years", "running that night. I had spent years"),
("where the break could land, and refuse to read", "where the break could land and refuse to read"),
("That is the mechanic, and it is easy to walk past.", "That is the mechanic, an easy one to walk past."),
("it is the power supply, and it is why you are still holding", "it is the power supply, the reason you are still holding"),
("run the Infinite Arcade, and each one has spent a lifetime on", "run the Infinite Arcade, each with a lifetime spent on"),
("You do care too much, and it costs you.", "You do care too much. It costs you."),
("(one clean, costly line), and all you have is the Diplomat", "(one clean, costly line), but all you have is the Diplomat"),
("that keeps hurting them, and you give them the Shaman's feel for what everyone is carrying, and the rule does not move.", "that keeps hurting them, but you give them the Shaman's feel for what everyone is carrying, so the rule does not move."),
("with the Shaman in Chapter 3, and every school after uses the same form", "with the Shaman in Chapter 3. Every school after that uses the same form"),
("for who you are right now, and every chapter after this one adds another.", "for who you are right now. Every chapter after this one adds another."),
("Date every version, and across a year of play you can watch", "If you date every version, across a year of play you can watch"),
("the doctor's), and you say the words out loud to drive them past your thinking mind", "the doctor's), said out loud to drive the words past your thinking mind"),
("*I take the seat, and from here every move is chosen.*", "*I take the seat. From here, every move is chosen.*"),
("*I will fall short, and I will not call", "*I will fall short, but I will not call"),
("is halfway to something, and then everything breaks", "is halfway to something, but everything breaks"),
("how good it feels to reread it, and rereading one is a job.", "how good it feels to reread it, because rereading one is a job."),
("a place you already know, and the place hands the sentence back.", "a place you already know, a place that hands the sentence back."),
("the first in your deck, and it stays in reach", "the first in your deck. It stays in reach"),
]
