BEIT = ("Speak as *I*, one paragraph, and say what you have to say about showing up as an ally.", "Speak as *I* for one paragraph, saying what you have to say about showing up as an ally.", 2)
E = [
("That is the thesis, and it comes with a limit case attached.", "That is the thesis, with a limit case attached."),
("A conversation where somebody draws a line, and the line lands correctly, and the drawing does more", "A conversation where somebody draws a line that lands correctly, while the drawing does more"),
("doing four jobs each, and the org chart showed twelve.", "doing four jobs each, while the org chart showed twelve."),
("you have the Sage's gift, and you have lived the Sage's exile.", "you have the Sage's gift and have lived its exile."),
("The meta-awareness is real, and it gets used the way", "The meta-awareness is real, but it gets used the way"),
("the competition runs for real, and somebody loses it.", "the competition runs for real, so somebody loses it."),
("rewards unprocessed pain, and the Sage who declines to name it rewards it too.", "rewards unprocessed pain. So does the Sage who declines to name it."),
("The gap between helpful and present runs wide, and the distortion lives in it.", "The gap between helpful and present runs wide, wide enough for the distortion to live in."),
("One move is missing, and it comes first:", "One move is missing, the one that comes first:"),
("Corin would want a number, and both are asking the same question", "Corin would want a number, both asking the same question"),
("a register of where they went, and between those two documents sits", "a register of where they went. Between those two documents sits"),
("Irix would build a better ledger, and it would be a better ledger, and it would hold the same nothing more elegantly.", "Irix would build a better ledger. It would be better, yet it would hold the same nothing, more elegantly."),
("Corin would call going inward a retreat, and they would have the movement right and the destination wrong.", "Corin would call going inward a retreat, getting the movement right and the destination wrong."),
("That watcher is the Sage, and the watcher accumulates a specific kind of knowledge:", "That watcher is the Sage, who accumulates a specific kind of knowledge:"),
("without lines nothing holds structure, and without structure only chaos remains, wearing the mask of freedom.", "without lines nothing holds structure, which leaves only chaos, wearing the mask of freedom."),
("the world changes and the problems change, and the tradition that saved you can become", "the world changes and the problems change, so the tradition that saved you can become"),
("the tension remains, and the Diplomat's gift makes it bearable", "the tension remains, but the Diplomat's gift makes it bearable"),
("It means you know when you are standing there, you can choose to stay deliberately, and you can come back.", "It means you know when you are standing there, can choose to stay deliberately, and can come back."),
("once you can see the whole board, and the name for it is evolutionary purpose:", "once you can see the whole board. Its name is evolutionary purpose:"),
("your organization's mission, and it carries its own direction,", "your organization's mission, carrying its own direction,"),
("The Sage can tell the difference, and the telling takes skill rather than temperament.", "The Sage can tell the difference, which takes skill rather than temperament."),
("Watch what people actually do rather than what they say, and it answers itself.", "If you watch what people actually do rather than what they say, it answers itself."),
("is a vertical question, and its answer-set is the six roles", "is a vertical question, whose answer-set is the six roles"),
("having a bad week, and if your map can't hold that, your map is running you.", "having a bad week. If your map can't hold that, your map is running you."),
("runs the opposite way, and it has a tell you can catch:", "runs the opposite way, with a tell you can catch:"),
("and still stand outside it, and the clearer the view gets,", "and still stand outside it: the clearer the view gets,"),
("are not mine, and you should know whose they are before you use them.", "are not mine, so you should know whose they are before you use them."),
("The rule that you carry the lower altitudes instead of leaving them behind is Ken Wilber's, and it is the structural logic of the whole book.", "The rule that you carry the lower altitudes instead of leaving them behind, the structural logic of the whole book, is Ken Wilber's."),
("is Frederic Laloux's, and in his hands it describes something that happens to an organization rather than to a person, so I have borrowed it down a level and the borrowing is mine to answer for.", "is Frederic Laloux's. In his hands it describes something that happens to an organization rather than to a person, so I have borrowed it down a level, a borrowing that is mine to answer for."),
("which game a group is in, and what the stuckness costs them.", "which game a group is in and what the stuckness costs them."),
("They are playing __________, and what has actually landed with", "They are playing __________, while what has actually landed with"),
("You will feel the game from inside it, and one of these five sees from exactly there.", "You will feel the game from inside it, the exact place one of these five sees from."),
("reporting honestly on what it takes in, and what it takes in is the gap", "reporting honestly on what it takes in: the gap"),
("The anger is real, and the situation is sometimes exactly that limited.", "The anger is real. Sometimes the situation is exactly that limited."),
("*The judgment is accurate, and it is also the trap: because the moment you stand above them, you cannot be with them, and this practice is always about being with.*", "*The judgment is accurate, yet it is also the trap: this practice is always about being with, which nobody can do from above.*"),
("lives there for you, and putting it down means putting that down too.", "lives there for you, so putting it down means putting that down too."),
("This is stuck Joy, and stuck Joy is the hardest of the five to catch,", "This is stuck Joy, the hardest of the five to catch,"),
("names the feeling, and saying it feels good.", "names the feeling, a sentence that feels good to say."),
("The game was yours for a time, the time was real, and the ending is not the same as the failure.", "The game was yours for a time, a real time, but the ending is not the same as the failure."),
("It was yours, it travels, and the game is allowed to end.", "It was yours and it travels, so the game is allowed to end."),
("The sadness is the cost of the gift, and it will feel like weakness every time.", "The sadness is the cost of the gift, though it will feel like weakness every time."),
("I'm here, with you, and the seeing is still mine.*", "I'm here, with you. The seeing is still mine.*"),
("never said out loud, and it has been saving you something.", "never said out loud, one that has been saving you something."),
BEIT,
("The walk back is the hardest part, and you can drill it like anything else.", "The walk back is the hardest part, but you can drill it like anything else."),
("means something has to change, and change is expensive.", "means something has to change, which is expensive."),
("Panoramic vision is lonely, and nobody says so.", "Panoramic vision is lonely, though nobody says so."),
("The Sage insists on honesty, and honesty means speaking", "The Sage insists on honesty, which means speaking"),
("the remit widens on its own, and it widens in a direction", "the remit widens on its own, in a direction"),
("what needs fixing in you, and what needs fixing is always upstream of what needed doing.", "what needs fixing in you, which always sits upstream of what needed doing."),
("Each map is good, each one explains more than the last, and the accumulation never becomes knowledge, it stays a prosthetic", "Each map is good and explains more than the last, yet the accumulation never becomes knowledge: it stays a prosthetic"),
("Somebody offers you something, a correction, a piece of feedback, an opening, and it doesn't get received as input,", "When somebody offers you something, a correction, a piece of feedback, an opening, it doesn't get received as input,"),
("Something in me runs differently, and that reading is usually accurate, and sometimes it is the whole instrument.", "Something in me runs differently. That reading is usually accurate, sometimes the whole instrument."),
("what is allowed to grow in me, and it does not get to answer a question about capacity", "what is allowed to grow in me, nor does it get to answer a question about capacity"),
("That is the Damaged Self with the joystick, and the tell is that the second map arrives", "That is the Damaged Self with the joystick. The tell is that the second map arrives"),
("Then the Damaged Self opens underneath it, and what surfaces is not doubt;", "Then the Damaged Self opens underneath it. What surfaces is not doubt;"),
("the fourth one this quarter, and nobody has ever asked you for a map.", "the fourth one this quarter, though nobody has ever asked you for a map."),
("which is why I can see this, and what I'm going to do about it is sit here", "which is why I can see this. What I'm going to do about it is sit here"),
("Yours has a specific defect it has settled on, and that is the one to work.", "Yours has settled on a specific defect, which is the one to work."),
("than anything else in the Forest, and the mechanism repays a close look.", "than anything else in the Forest, by a mechanism that repays a close look."),
("that you're the problem, and the checking feels like exactly the discipline", "that you're the problem, a checking that feels like exactly the discipline"),
("what a person can currently hold, and it applies to you as much as to anyone.", "what a person can currently hold, a question that applies to you as much as to anyone."),
("has eaten the horizontal one, and the eating happened in the name of accuracy.", "has eaten the horizontal one, in the name of accuracy."),
("That combination is what this chapter trains, and the superpower has two halves.", "That combination, a superpower with two halves, is what this chapter trains."),
("They are recruiting, and everything they offer arrives", "They are recruiting, so everything they offer arrives"),
("Take load off without requiring the account, and the door opens.", "Once you take load off without requiring the account, the door opens."),
("whether Ellis should apply for the review board, and the argument has become logistics.", "whether Ellis should apply for the review board, an argument that has become logistics."),
("The home game feels comfortable, and it means you treat", "The home game feels comfortable, but it means you treat"),
("somebody's line got crossed, and no amount of process will touch that until", "somebody's line got crossed, which no amount of process will touch until"),
("calling itself wisdom, and it does a passable impression of the Returner.", "calling itself wisdom, doing a passable impression of the Returner."),
("rather than what you do, and putting it down means sitting with the loss", "rather than what you do, so putting it down means sitting with the loss"),
("what everyone else misses, and you can name what that bought you:", "what everyone else misses. You can name what that bought you:"),
("a table has to account for, and it is the Sage's steepest, because", "a table has to account for. It is the Sage's steepest, because"),
("You look at a live problem, the first framework explains most of it, and rather than do anything", "When you look at a live problem, the first framework explains most of it, yet rather than do anything"),
("nobody at the table has to answer a map, and from the inside it looks", "nobody at the table has to answer a map. From the inside it looks"),
("whether the table can use what you saw, and the same three moves decide it in every domain.", "whether the table can use what you saw. The same three moves decide it in every domain."),
("is accurate, and it comes from a place nobody at the table is standing in,", "is accurate, but it comes from a place nobody at the table is standing in,"),
("Same read, same size, and the words start where the work is.", "Same read, same size, but the words start where the work is."),
("tells you what would help, and what would help is usually specific and dull:", "tells you what would help, which is usually specific and dull:"),
("comes after the naming, and the Sage's exit does not use the door.", "comes after the naming. The Sage's exit does not use the door."),
("*I'll leave you to sit with that*, and it is only ever spoken on the way out.", "*I'll leave you to sit with that*, only ever spoken on the way out."),
("rather than to somebody else afterward, and you were still sitting there", "rather than to somebody else afterward, and were still sitting there"),
("That question is real, and it lands harder on the Sage", "That question is real. It lands harder on the Sage"),
("what the playing does to the player, and Show Up is legacy, and every card there names", "what the playing does to the player. Show Up is legacy: every card there names"),
("The signal registers, and alongside it registers the fact that you noticed it", "The signal registers alongside the fact that you noticed it"),
("a footnote about the noticer, and the footnote runs longer than the notice.", "a footnote about the noticer, a footnote that runs longer than the notice."),
("it gets fixed first, and the fixing has no completion condition.", "it gets fixed first, by a fixing that has no completion condition."),
("before the retreat in March, and it will cost me being the one who has to be in the meeting", "before the retreat in March, which will cost me being the one who has to be in the meeting"),
("*You saw it, and you named it and stayed, or you held it,", "*You saw it. Then you named it and stayed, or you held it,"),
("which game they're in, and you can be that person, not from above, from with.", "which game they're in. You can be that person, not from above, from with."),
("Name it, and name what it saves you from having to do.", "Name it, then name what it saves you from having to do."),
]
