BEIT = ("Speak as *I*, one paragraph, and say what you have to say about showing up as an ally.", "Speak as *I* for one paragraph, saying what you have to say about showing up as an ally.", 2)
E = [
("**The Shaman means: somebody said the unsaid charge, and it landed.**", "**The Shaman means: the unsaid charge, said out loud, landed.**"),
("They called the pattern efficiency, and the pattern starved them.", "They called the pattern efficiency. The pattern starved them."),
("the full spectrum of human feeling, and letting those feelings teach you", "the full spectrum of human feeling and letting those feelings teach you"),
("in front of witnesses, and the only instrument it could reach was mine.", "in front of witnesses, using the only instrument it could reach: mine."),
("That part is real, and it matters.", "That part is real. It matters."),
("Here is what is specific to this reader, and its shape is a squeeze rather than a lean.", "Here is what is specific to this reader: a squeeze rather than a lean."),
("available only in its group form, and the other end sounds like", "available only in its group form, while the other end sounds like"),
("I recover both ends before I am done, and I will ask you to hold them at the same time.", "I will recover both ends before I am done, then ask you to hold them at the same time."),
("Other people built some of what this chapter hands you, and their names belong with the tools.", "Other people built some of what this chapter hands you, so their names belong with the tools."),
("comes from Eugene Gendlin's *Focusing*, and the phrase names the body's knowing", "comes from Eugene Gendlin's *Focusing*, where the phrase names the body's knowing"),
("A feeling carries energy that has to finish moving, and it jams when you cut it off.", "A feeling carries energy that has to finish moving, so it jams when you cut it off."),
("The Shaman's native material is *emotion*, and what you can use runs narrower", "The Shaman's native material is *emotion*, but the part you can use runs narrower"),
("The emotion arrives, theirs and yours, and the chest reacts in a specific way:", "When the emotion arrives, theirs and yours, the chest reacts in a specific way:"),
("*Form* is the martial artist's word, and it is the exact one.", "*Form*, the martial artist's word, is the exact one."),
("The beginner runs the form and the master runs the form, and what separates them", "The beginner runs the form and the master runs the form. What separates them"),
("Name the feeling to yourself, one of the five, and find where it sits.", "Name the feeling to yourself, one of the five, then find where it sits."),
("The Shaman works by sensitivity, and an instrument kept behind glass reads nothing.", "The Shaman works by sensitivity. An instrument kept behind glass reads nothing."),
("named this the existential kink, and I will not pretend I stand outside it:", "named this the existential kink. I will not pretend I stand outside it:"),
("because what stays hidden runs the moment, and what you can feel, you can play.", "because what stays hidden runs the moment, while what you can feel, you can play."),
("where the work can reach it, and the skill that moves it is coming.", "where the work can reach it. The skill that moves it is coming."),
("Those four are **WAVE**, and the whole of it runs about as long as one breath.", "Those four are **WAVE**, which runs about as long as one breath."),
("letting it show you, and it usually takes a few seconds to a few minutes.", "letting it show you, which usually takes a few seconds to a few minutes."),
("Neutrality integrates as the larger view, and you can hold complexity", "Neutrality integrates as the larger view: you can hold complexity"),
("It differs with each feeling and each situation, and it can happen in the next ten seconds", "It differs with each feeling and each situation. It can happen in the next ten seconds"),
("classical Chinese medicine and cosmology, and it predates everything else", "classical Chinese medicine and cosmology and predates everything else"),
("the ten seconds you have to decide something, and I moved correspondences around", "the ten seconds you have to decide something, then moved correspondences around"),
("keeps other people outside them, and running a borrowed vocabulary past you unmarked is the same move", "keeps other people outside them. Running a borrowed vocabulary past you unmarked would be the same move"),
("You play a move, and the move carries the stuck charge", "You play a move that carries the stuck charge"),
("The Shaman adds the next layer: what that spending does to the living field: to the people around you, and what it leaves them carrying.", "The Shaman adds the next layer: what that spending does to the living field (the people around you) and what it leaves them carrying."),
("You draw the boundary, and you walk away tired but clear. You name the sadness, and the sadness gives you back the love underneath it. You say what needed saying, and something in you comes back online because", "You draw the boundary, then walk away tired but clear. When you name the sadness, it gives you back the love underneath it. Once you say what needed saying, something in you comes back online, because"),
("empties you as you spend it, and the renewable kind hands back", "empties you as you spend it, while the renewable kind hands back"),
("This is deep work on live material, and the material has weight.", "This is deep work on live material, which has weight."),
("the practice is doing its job, and getting help is your next move", "the practice is doing its job, so getting help is your next move"),
("You keep trying to pick the right side, and the picking exhausts you.", "You keep trying to pick the right side, until the picking exhausts you."),
("That part has a name, and you have met it before.", "That part has a name. You have met it before."),
("The practice above works on its own, and it goes on working after you close the book.", "The practice above works on its own, even after you close the book."),
("I asked the universe for a sign, and then spent forty minutes", "I asked the universe for a sign, then spent forty minutes"),
("That is integrity, and it is not automatic.", "That is integrity, which is not automatic."),
("That is a judge now, and it holds court in you.", "That is a judge now, holding court in you."),
("the person you came to help: they get the result their own way, on their own timeline, and you catch yourself docking points", "the person you came to help: when they get the result their own way, on their own timeline, you catch yourself docking points"),
("It is in bounds.* Do that, and the referee goes back to its real work:", "It is in bounds.* With that rulebook in hand, the referee goes back to its real work:"),
("It blocks with a verdict about you, and it has six of them, the same six every time:", "It blocks with a verdict about you, one of six, the same six every time:"),
("while the moment passes, and the judge already has every past ruling on file", "while the moment passes, against a judge who already has every past ruling on file"),
("argued on the judge's home ground, and you already know who wins there.", "argued on the judge's home ground, where you already know who wins."),
("You make the proportionate move while the verdict is still talking, the move returns a result the verdict did not predict, and the belief picks up", "You make the proportionate move while the verdict is still talking. When the move returns a result the verdict did not predict, the belief picks up"),
("is the hinge of the whole chapter, and the chapter's real axis: Feeling and Function.", "is the hinge of the whole chapter, the point where it turns on its real axis: Feeling and Function."),
("where nothing costs you and no one is watching, and into the places allyship actually happens", "where nothing costs you and no one is watching, into the places allyship actually happens"),
("There is a council that meets when the season turns, and it has beautiful words.", "There is a council that meets when the season turns. It has beautiful words."),
("One year the river changed course, and the lower fields, three families' fields, began to fail.", "When the river changed course one year, the lower fields, three families' fields, began to fail."),
("with real feeling, and it moved not one handful of earth.", "with real feeling, yet it moved not one handful of earth."),
("(she was going to be disliked, and she was going to say it anyway)", "(she was going to be disliked, but she was going to say it anyway)"),
("Then it sat in the circle, and no one could unsay it, and the council had to answer it, not her feeling,", "Then it sat in the circle. No one could unsay it, so the council had to answer it: not her feeling,"),
("Yours enforces a specific one, and that is what to work.", "Yours enforces a specific one, which is the one to work."),
BEIT,
("the read let all the way in, and something in you that will not let you leave the table with it unsaid.", "the read let all the way in and, at the same time, something in you that will not let you leave the table with it unsaid."),
("You cannot burn a charge you never let yourself have, and you will not spend one while the fear is still live unless", "You cannot burn a charge you never let yourself have. Nor will you spend one while the fear is still live, unless"),
("so it fires when you arrive holding a better standard, and it opens when you meet", "so it fires when you arrive holding a better standard, but opens when you meet"),
("built on top of the first, and by the time you are working with it,", "built on top of the first. By the time you are working with it,"),
("That part steers better in the dark, and the low setting is the dark.", "That part steers better in the dark. The low setting is the dark."),
("What stays hidden runs the moment, and what you can feel, you can play.", "What stays hidden runs the moment, while what you can feel, you can play."),
("to name the channel for yourself, and naming it for yourself completes the interior move.", "to name the channel for yourself, which completes the interior move."),
("to keep the channel deniable, and nobody can work a deniable channel", "to keep the channel deniable, but nobody can work a deniable channel"),
("got told it was fine, and you can name two other times", "got told it was fine, though you can name two other times"),
("Ravi raised this in March, and I would like to know why that landed differently.*", "Ravi raised this in March. I would like to know why that landed differently.*"),
("to each other and with each other, and it drives the outcome", "to each other and with each other, which drives the outcome"),
("points at a violation: something happened, everyone saw it, nobody stated it, and stating it draws a line.", "points at a violation: something happened that everyone saw and nobody stated, so stating it draws a line."),
("so that nobody can argue with you, and the case is where the read goes to die,", "so that nobody can argue with you. The case is where the read goes to die,"),
("One sentence, and nothing about who is right.", "One sentence, with nothing in it about who is right."),
("The question resolves in four minutes, and Nadia joins it.", "The question resolves in four minutes once Nadia joins it."),
("Reading under the surface is real skill, and it asks nothing of you,", "Reading under the surface is real skill, but it asks nothing of you,"),
("the ones no one can fault, and that is the awareness trap,", "the ones no one can fault. That is the awareness trap,"),
("whether it helps the person or wounds them, and the same three moves decide it in every domain.", "whether it helps the person or wounds them. The same three moves decide it in every domain."),
('"This is what I feel is happening, and I could be wrong"', '"This is what I feel is happening, but I could be wrong"'),
("sure would be granted, and you asked the person who can grant it or refuse it.", "sure would be granted, then asked the person who can grant it or refuse it."),
("The read comes first, and a read that never leaves the chair stalls the whole game.", "The read comes first, but a read that never leaves the chair stalls the whole game."),
("direct action, skillful organizing), and five times four gives twenty.", "direct action, skillful organizing): five times four gives twenty."),
("Which of the five rows is the real question, and a tempting wrong answer waits:", "Which of the five rows is the real question. A tempting wrong answer waits:"),
("It is a rule, and the rule is in force the whole way down.", "It is a rule, in force the whole way down."),
("while feeling something, and behavior is at stake the moment", "while feeling something. Behavior is at stake the moment"),
("A card that ends in a quest is a card you played, and the difference is a person.", "A card that ends in a quest is a card you played. The difference is a person."),
("Quests come from the Show Up cards, and every one of them ends in an artifact, and an artifact is something another person can encounter.", "Quests come out of the Show Up cards, because those cards end in artifacts: an artifact is something another person can encounter."),
("needs one more move, and you will meet it with the Player in Chapter 9.", "needs one more move, which you will meet with the Player in Chapter 9."),
("and not soften it, before Friday, and it will cost me her thinking I am difficult.**", "and not soften it, before Friday, at the cost of her thinking I am difficult.**"),
("before anyone else can, and the next face begins there.", "before anyone else can. The next face begins there."),
("since it arrives early, and early is the only window in which it can change what happens.", "since it arrives early, in the only window in which it can change what happens."),
("from arrival to a move, and Clean is the stage almost everyone skips,", "from arrival to a move. Clean is the stage almost everyone skips,"),
("(Face it, Talk to it, Be it), and it runs again in every chapter after this one, and the Polarity Map is here by name as well,", "(Face it, Talk to it, Be it), and runs again in every chapter after this one. The Polarity Map is here by name as well,"),
]
