E = [
("The villagers had made no mistake, and nobody had rejected them.", "The villagers had made no mistake, nor had anybody rejected them."),
("So would a protest, and so would a critique of what the villagers kept getting wrong.", "So would a protest or a critique of what the villagers kept getting wrong."),
("as a teaching instrument, and now the teaching instrument passes to you.", "as a teaching instrument. Now the instrument passes to you."),
("You return to them, and each pass through goes a little deeper.", "You return to them, each pass through going a little deeper."),
("It works as the practice surface, and every chapter has pointed at its own twenty.", "It works as the practice surface. Every chapter has pointed at its own twenty."),
("The modes loop, and each pass through goes deeper.", "The modes loop, each pass through going deeper."),
("One tell separates real building from the kind that's secretly avoidance, and it has nothing to do with how productive you feel.", "One tell, which has nothing to do with how productive you feel, separates real building from the kind that's secretly avoidance."),
("The work goes somewhere, and the somewhere has a face.", "The work goes somewhere. The somewhere has a face."),
("the same mechanic six times, and every redesign lets me dodge", "the same mechanic six times, each redesign letting me dodge"),
("Ascending belongs to somebody else's book, and so does perfecting.", "Ascending and perfecting belong to somebody else's book."),
("Then you come back, and coming back is what turns one pass into a practice.", "Then you come back, which is what turns one pass into a practice."),
("You don't arrive and then act, you act from somewhere on the path, and the acting belongs to the walking.", "You don't arrive and then act. You act from somewhere on the path, where the acting belongs to the walking."),
("ate people and produced very little, and I had quit feeding it.", "ate people and produced very little, so I had quit feeding it."),
("Now people needed something, and I had something to offer, and I wanted to get paid", "Now people needed something I had to offer. This time I wanted to get paid"),
("still gets a laugh out of me, and what arrives a second behind the laugh is shame.", "still gets a laugh out of me. What arrives a second behind the laugh is shame."),
("A game can fail to be fun, and fun on its own can fail to make a great game.", "A game can fail to be fun, just as fun on its own can fail to make a great game."),
("It came from the moment I connected back to myself after failing to make money or create the allies I'd wanted to create, and found", "It came from the moment I connected back to myself, after failing to make money or create the allies I'd wanted to create, and found"),
("instead of only understand), and I had enough of the six Faces", "instead of only understand) and enough of the six Faces"),
("with no way to tell tired from done, and I started them again anyway.", "with no way to tell tired from done, then started them again anyway."),
("That's the stage you're in, and from inside it feels like failure.", "That's the stage you're in, though from inside it feels like failure."),
("still in the confusion, and the honest answer says exactly that.", "still in the confusion, in which case the honest answer says exactly that."),
("at the Player's altitude, and it is smaller than the word *game* makes it sound: something exists that did not exist before you, and somebody who is not you has it in their hands.", "at the Player's altitude, smaller than the word *game* makes it sound: something exists that did not exist before you, in the hands of somebody who is not you."),
("It has to get made, get handed over, and come back changed.", "It has to get made, then handed over, then come back changed."),
("announces itself as the next one, and nothing you do can ever count as having failed.", "announces itself as the next one, nor can anything you do ever count as having failed."),
("the moment something lands hard, and there is nowhere to practice the difference*", "the moment something lands hard, with nowhere to practice the difference*"),
("converted into an act, and it is the only one of the five that cannot be performed alone.", "converted into an act, the only one of the five that cannot be performed alone."),
("The audience version becomes a launch, and you can spend a year preparing for a launch.", "The audience version becomes a launch, which you can spend a year preparing for."),
("I want to know where you got confused, and I will use your answer to change it.*", "I want to know where you got confused so I can use your answer to change it.*"),
("Rosa can decline, and she knows what her answer will change.", "Rosa can decline, knowing what her answer will change."),
("saying the structure is wrong, and it tends to arrive sounding like an insult,", "saying the structure is wrong. It tends to arrive sounding like an insult,"),
("Changing one variable is slower, but it is the only version that teaches you anything, because", "The only version that teaches you anything is changing one variable, slow as that is, because"),
("a system that runs without them, that is handoff, and it is a different move at a different altitude.", "a system that runs without them. That is handoff, a different move at a different altitude."),
("is already a tradition, and the Outlaw is coming for it.", "is already a tradition, one the Outlaw is coming for."),
("is a smaller one, and neither is the pen.", "is a smaller one. Neither is the pen."),
("The practice is the loop, and the list is only what the loop leaves behind.", "The practice is the loop, while the list is only what the loop leaves behind."),
("before it was good, and the ones who did not finish are the reason this exists.", "before it was good. The ones who did not finish are the reason this exists."),
("as the moment requires, and Sage is a seat you take and leave like the other five.", "as the moment requires, with Sage a seat you take and leave like the other five."),
("building toward, and it is what you cannot get from reading.", "building toward, the one you cannot get from reading."),
("In the margin is fine, and fast beats careful, since", "In the margin is fine. Fast beats careful, since"),
("The person goes still, says nothing, and the meeting moves to the next agenda item", "The person goes still and says nothing while the meeting moves to the next agenda item"),
("You have the standing to speak, and you are aware, while", "You have the standing to speak, though you are aware, while"),
("*I couldn't keep up*, and all three times you covered", "*I couldn't keep up*. All three times you covered"),
("You like them, and you can already see the shape of the next fourteen months.", "You like them, but you can already see the shape of the next fourteen months."),
("happened at her job, and about ninety seconds in you notice", "happened at her job. About ninety seconds in you notice"),
("everybody used to love, and the six people who joined most recently", "everybody used to love, but the six people who joined most recently"),
("(Chapter 4), and its entire value is that it happens", "(Chapter 4), whose entire value is that it happens"),
("The pull is toward the Regent, and it is an honorable one:", "The pull is toward the Regent, an honorable one:"),
("something useful to hand her, and what you are assembling really might be right.", "something useful to hand her, and since what you are assembling really might be right."),
("**Five is the Diplomat, and this is the one where your default face is the right call.**", "**Five is the Diplomat, the one where your default face is the right call.**"),
("There is a real field with two real positions in it, and you are the only person both sides will still talk to.", "You are the only person both sides will still talk to, in a real field with two real positions in it."),
("rather than about the argument, and it took two years to surface because", "rather than about the argument. It took two years to surface because"),
("or a different argument in the same one, and choosing between those two is the Sage's whole job.", "or a different argument in the same one. Choosing between those two is the Sage's whole job."),
("the superpower its chapter named, and what it does for people", "the superpower its chapter named, along with what it does for people"),
("are the same face, and the sheet should carry both.", "are the same face, so the sheet should carry both."),
("I wrote this book to make possible, and it is the work I most want to hand off.", "I wrote this book to make possible, the work I most want to hand off."),
]
