BEIT = ("Speak as *I*, one paragraph, and say what you have to say about showing up as an ally.", "Speak as *I* for one paragraph, saying what you have to say about showing up as an ally.", 2)
E = [
("The Regent was standing right there while it did, and that is the part of the account", "The Regent was standing right there while it did, which is the part of the account"),
("Because the Challenger was expensive and the Regent was not, and a village will take", "Because the Challenger was expensive and the Regent was not, and because a village will take"),
("The Challenger left, and the Regent had a city to build, and did not go after them.", "When the Challenger left, the Regent, with a city to build, did not go after them."),
("first the body adapts, and the adaptation is cited afterward", "first the body adapts. The adaptation is cited afterward"),
("This is the clause I would amend, and amendment is not within the office.", "This is the clause I would amend, but amendment is not within the office."),
("had separated without anyone announcing it, and everyone who pointed that out", "had separated without anyone announcing it, and where everyone who pointed that out"),
("without entering the change as damage, and my own ledgers are the reason that is hard.", "without entering the change as damage. My own ledgers are the reason that is hard."),
("It has two poles, and both of them are right.", "It has two poles, both of them right."),
("You showed up, and the tradition showed up with you, and over time it became part of what you could offer.", "When you showed up, the tradition showed up with you and, over time, became part of what you could offer."),
("a patriarch to give themselves to, and a patriarch does its own kind of damage.", "a patriarch to give themselves to. A patriarch does its own kind of damage."),
("larger than yourself, and the weight that comes with that belonging.", "larger than yourself and the weight that comes with that belonging."),
("That is the most loyal act there is, and it will read as disloyalty.", "That is the most loyal act there is, yet it will read as disloyalty."),
("The sequence used to hide this stage inside Steward, and hiding it there is how", "The sequence used to hide this stage inside Steward. Hiding it there is how"),
("Reform is a separate act with a separate cost, and the cost is what makes it separate: stewardship earns you loyalty, and reform spends it.", "Reform is a separate act, made separate by its cost: stewardship earns you loyalty, while reform spends it."),
("Whatever yours was, you inherited it, and most of adult life goes into", "Whatever yours was, you inherited it, so most of adult life goes into"),
BEIT,
("but it can *start* this week, and starting it costs something.", "but it can *start* this week. Starting it costs something."),
("I hear the shape of it and I am three steps into a solution nobody asked for, and I do it because I love them,", "The moment I hear the shape of it I am three steps into a solution nobody asked for. I do it because I love them,"),
("That is the only reason anything inherited ever improves, and it will look like meddling to somebody.", "That is the only reason anything inherited ever improves, though it will look like meddling to somebody."),
("It arrives with a condition, and the condition sounds responsible.", "It arrives with a condition that sounds responsible."),
("The trouble is the ordering, and the ordering never changes.", "The trouble is the ordering, which never changes."),
("Then comes the second move, the Healer half, and it costs you more.", "Then comes the second move, the Healer half, which costs you more."),
("From outside, those look identical, until you leave, and everyone discovers that what you were holding was you.", "From outside, those look identical until you leave, when everyone discovers that what you were holding was you."),
("having accepted the inheritance, and acceptance keeps getting deferred", "having accepted the inheritance, while acceptance keeps getting deferred"),
("The chapter's myth lives here, and it flatters more than any other in the book.", "The chapter's myth lives here, flattering more than any other in the book."),
("that is the report I want, and I will act on it.", "that is the report I want. I will act on it."),
("Name what changes in that cycle, and I will do the work.", "Once you name what changes in that cycle, I will do the work."),
("It is not enough for the other one, and it was never meant to be.", "It is not enough for the other one, nor was it ever meant to be."),
("the charter has been rewritten twice, the role still has no name, and no list anywhere names the person", "the charter has been rewritten twice and the role still has no name. No list anywhere names the person"),
("Yours has its own shape, and that is the one to work.", "Yours has its own shape, which is the one to work."),
("sits somewhere on that axis, and where it sits comes down to a judgment call, and judgment calls about damage are precisely what a Fixer is for.", "sits somewhere on that axis. Where it sits comes down to a judgment call, precisely the kind of call about damage a Fixer is for."),
("It argues for Reform, and Reform is half the truth.", "It argues for Reform, which is half the truth."),
("and call it standards, and no single instance looks like an evasion.", "and call it standards, without a single instance looking like an evasion."),
("That lays the foundation this chapter builds on, and what it trains is the Storyteller:", "That lays the foundation this chapter builds on. What it trains is the Storyteller:"),
("holding something in place on purpose, and they will not always tell you", "holding something in place on purpose, though they will not always tell you"),
("A manager set it so the week would end on a decision, and it still does that.", "A manager set it so the week would end on a decision. It still does that."),
("*this exists for a reason, and it has been costing one person for four years.*", "*this exists for a reason, but it has been costing one person for four years.*"),
("the one place the history gets told, and the person who tells it retires in three years.*", "the one place the history gets told. The person who tells it retires in three years.*"),
("every incident report yourself, and nobody has checked since.", "every incident report yourself. Nobody has checked since."),
("This month brings eleven, and nine are routine.", "This month brings eleven, nine of them routine."),
("Being noticed is a separate question, and usually the answer is no.", "Being noticed is a separate question, usually answered no."),
("a preferred name field, and Ana is nine and has answered", "a preferred name field. Ana is nine and has answered"),
("The form is trying to match children to legal records, and it still does that.", "The form is trying to match children to legal records. It still does that."),
("something you would not have chosen, and the choosing is what you handed him.", "something you would not have chosen. The choosing is what you handed him."),
("Most of those conditions are correct, and each is defensible on the day you say it.", "Most of those conditions are correct, each defensible on the day you say it."),
("because real reform spends loyalty you earned by carrying something, and you have not carried anything yet.", "because real reform spends loyalty earned by carrying something, which you have not done yet."),
("becomes yours, held in your head, and from outside that reads as devotion.", "becomes yours, held in your head. From outside that reads as devotion."),
("You carry an inheritance for years, and the same three moves decide,", "You carry an inheritance for years. The same three moves decide,"),
("will always find you one more cycle, and the damage it reports is usually real.", "will always find you one more cycle, though the damage it reports is usually real."),
("this runs because somebody does these four jobs, and the somebody is me.", "this runs because somebody does these four jobs: me."),
("with none of that attached, and it cost you the ease of letting the form speak for itself.", "with none of that attached. It cost you the ease of letting the form speak for itself."),
("you asked for the time, the budget line, or the second name on the rota that a practice needs to outlast its keeper, and you asked whoever can say yes to it, instead of covering the gap out of your own evenings another year, and it cost you", "you asked whoever can say yes for the time, the budget line, or the second name on the rota that a practice needs to outlast its keeper, instead of covering the gap out of your own evenings another year. It cost you"),
("That question is real, and it belongs to the Regent, because", "That question is real. It belongs to the Regent, because"),
("Twenty cards, and these are the Regent's.", "These twenty cards are the Regent's."),
("You have to find yours, and you already know the movements that get you there.*", "You have to find yours, using movements you already know.*"),
("between building something and inheriting it, and it makes this operation the slowest of the six.", "between building something and inheriting it, which makes this operation the slowest of the six."),
("and walk her through it once, and it will cost me being the only person who knows.**", "and walk her through it once, at the cost of being the only person who knows.**"),
("concerns becoming unnecessary, and that is the dread to trust.", "concerns becoming unnecessary, which is the dread to trust."),
("every system is also an inheritance, and every redesign is also a hand-off.", "every system is also an inheritance, and that every redesign is also a hand-off."),
]
