E = [
("It arrives before the words do, and no action item takes it out.", "It arrives before the words do. No action item takes it out."),
("Harm happens in the village, and repair has to land there, so the village is", "Because harm happens in the village and repair has to land there, the village is"),
("something the response cannot reach, and the person who responded has nothing left.", "something the response cannot reach, while the person who responded has nothing left."),
("I was trained in shamanism, and I did not want to learn it.", "I was trained in shamanism, though I did not want to learn it."),
("the practices it draws on, and it did not feel like mine to pick up.", "the practices it draws on, nor did it feel like mine to pick up."),
("They are not the same, and the work is to tell them apart.", "They are not the same. The work is to tell them apart."),
("That is a different project entirely, and it produces different results.", "That is a different project entirely, with different results."),
("that most training never reaches, and most training does not say so.", "that most training never reaches. Most training does not say so."),
("The walking went in the wrong direction, and no one had mentioned", "The walking went in the wrong direction because no one had mentioned"),
("The terms were set wrong from the beginning, and no one failed.", "The terms were set wrong from the beginning, so no one failed."),
("they override the sensation, run on fumes, and eventually the body stops cooperating.", "they override the sensation and run on fumes until the body stops cooperating."),
("the situation actually moves, and the words you practiced last year", "the situation actually moves, so the words you practiced last year"),
("eight separate voices, and neither does anybody selling you a model of one.", "eight separate voices. Neither does anybody selling you a model of one."),
("Pressure repeats, so your moves repeat, and the moves you repeat build your character,", "Pressure repeats, so your moves repeat. Repeated moves build your character,"),
("didn't know how to hold), and they delivered it to me, gift-wrapped as concern.", "didn't know how to hold), so they delivered it to me, gift-wrapped as concern."),
("I was not okay, and not for the reasons they assumed.", "I was not okay, though not for the reasons they assumed."),
("What the anger produced first was not the book, and Chapter 9 tells that part.", "What the anger produced first was not the book. Chapter 9 tells that part."),
("could do exactly this, and no one had thought to aim them at allyship yet.", "could do exactly this, but no one had thought to aim them at allyship yet."),
("The school is somewhere to stand while you practice, and that is the whole of its job.", "The school's whole job is to be somewhere to stand while you practice."),
("Recognition is where the move begins, and beginning is all it is.", "Recognition is where the move begins, but beginning is all it is."),
("the Protector does not wait for you, and it should not.", "the Protector does not wait for you, nor should it."),
("You answer armored, and the other person meets the armor", "You answer armored, so the other person meets the armor"),
("*In play:* someone you're supporting gets the result their own way, and you catch yourself", "*In play:* when someone you're supporting gets the result their own way, you catch yourself"),
("*In play:* a campaign is about to launch on a shaky assumption, and the Skeptic is what makes you", "*In play:* when a campaign is about to launch on a shaky assumption, the Skeptic is what makes you"),
("It mends what's damaged, and it keeps what's settled from moving.", "It mends what's damaged and keeps what's settled from moving."),
("it repairs the circumstance and leaves the other person's healing in their own hands, and it holds steady", "it repairs the circumstance, leaving the other person's healing in their own hands, and holds steady"),
("has stopped looking, and blanket bracing feels identical from the inside to paying attention.", "has stopped looking, yet from the inside blanket bracing feels identical to paying attention."),
("something that has not happened, and the person across from you meets the hull", "something that has not happened, so the person across from you meets the hull"),
("It trades contact for control, and the trade feels like safety.", "It trades contact for control, a trade that feels like safety."),
("spends everything you have on you, and nothing remains to carry into someone else's fight.", "spends everything you have on you, leaving nothing to carry into someone else's fight."),
("A mother does this with a child, and it is real.", "It is real: a mother does this with a child."),
("making the other person part of you, and the person you are allying with is not you.", "making the other person part of you, while the person you are allying with is not you."),
("You do not fight the Protector, and you do not shove past it.", "You do not fight the Protector or shove past it."),
("bracing my whole body.* Do that, and the Protector goes back", "bracing my whole body.* Once you do that, the Protector goes back"),
("Chapter 3 gives you both, and every chapter after it runs the same shape.", "Chapter 3 gives you both. Every chapter after it runs the same shape."),
("Fight your way back to yourself, and your hands close on the joystick in the same instant.", "The instant you fight your way back to yourself, your hands close on the joystick."),
('The Controller still sets the standard, and the standard becomes "how do I grow"', 'The Controller still sets the standard, now "how do I grow"'),
("A superpower is not a Face, and no chapter owns one.", "A superpower is not a Face, so no chapter owns one."),
("joy, neutrality), and each one is information, not noise.", "joy, neutrality), each one information, not noise."),
("Drop back into it, and watch the daemons grab the joystick", "Drop back into it, then watch the daemons grab the joystick"),
("Seven parts, each one snatching the joystick from the last, and not one of them is you.", "Seven parts, each one snatching the joystick from the last, yet not one of them is you."),
("*as within, so without*, and here it is mechanical.", "*as within, so without*. Here it is mechanical."),
("every person you will ever try to help, and they do not know you.", "every person you will ever try to help. They do not know you."),
("That trust is hers, and it comes out of the whole of her.", "That trust is hers, drawn from the whole of her."),
("something older than the offer, and what comes back is out of scale", "something older than the offer, so what comes back is out of scale"),
("She tells you the whole story again, from the beginning, and the plan waits.", "She tells you the whole story again, from the beginning, while the plan waits."),
("Seven parts, each one taking the joystick from the last, and not one of them is Imani.", "Seven parts, each one taking the joystick from the last, yet not one of them is Imani."),
("so you either meet hers or you help her move it, and both of those are allyship.", "so you either meet hers or help her move it. Both of those are allyship."),
("You see what she does, and you supply the rest, and what you supply comes out of you.", "You see what she does. Everything else you supply out of yourself."),
("That is projection, and it is the trickiest move in shadow work:", "That is projection, the trickiest move in shadow work:"),
("That distance is your **clearance**, and it is the only currency on this side of the floor.", "That distance is your **clearance**, the only currency on this side of the floor."),
("is a major error, and your character has nothing to do with it.", "is a major error, but your character has nothing to do with it."),
("It usually has an author, and the author is your Controller: it believes it knows the better standard.", "It usually has an author: your Controller, which believes it knows the better standard."),
("somewhere she was not going, and either one is more than she can metabolize today.", "somewhere she was not going, either one more than she can metabolize today."),
("those two look the same, and most people will punish both.", "those two look the same, so most people will punish both."),
("Two Protectors meet constantly, and everybody calls that a conflict.", "Two Protectors meet constantly, in what everybody calls a conflict."),
("across the table to check against, and both do their jobs perfectly", "across the table to check against. Both do their jobs perfectly"),
("Not knowing this costs you, and it costs you the same way every time.", "Not knowing this costs you the same way every time."),
("so you default, and the default is whichever daemon wants the joystick most.", "so you default to whichever daemon wants the joystick most."),
("The move is attempted above your clearance, Imani's Protector fires, and the door closes an inch.", "The move is attempted above your clearance, so Imani's Protector fires and the door closes an inch."),
("That is burnout, and every step of it is you playing hard.", "That is burnout: every step of it is you playing hard."),
("A daemon stands at Imani's door, a person stands behind it, and you have one move you can make today.", "With a daemon at Imani's door and a person behind it, you have one move you can make today."),
("take the joystick back, and saying it plainly takes the shine off", "take the joystick back. Saying it plainly takes the shine off"),
("The read becomes a move, and the part that reads comes a little further home.", "As the read becomes a move, the part that reads comes a little further home."),
("Six guides know that terrain, and one of their questions may already have landed.", "Six guides know that terrain. One of their questions may already have landed."),
("when you ran the five moves, and the job it has been doing for you.", "when you ran the five moves, along with the job it has been doing for you."),
("After it, six chapters, and each opens with a treatise", "After it come six chapters, each opening with a treatise"),
("cannot agree on the rest, and I would rather hand you the argument", "cannot agree on the rest. I would rather hand you the argument"),
]
