BEIT = ("Speak as *I*, one paragraph, and say what you have to say about showing up as an ally.", "Speak as *I* for one paragraph, saying what you have to say about showing up as an ally.", 2)
E = [
("above a conversation everybody remembers, and it is right about that more often than the villagers believe.", "above a conversation everybody remembers, a ranking that is right more often than the villagers believe."),
("something that had finally started moving, and they do it in exactly this vocabulary.", "something that had finally started moving, in exactly this vocabulary."),
("You earned the suspicion, and I am not going to argue you out of it.", "You earned the suspicion. I am not going to argue you out of it."),
("burn out the people inside them, and they do it faster than the cold ones.*", "burn out the people inside them faster than the cold ones do.*"),
("from anybody living inside it, and the drift is the mechanism rather than the error.", "from anybody living inside it. The drift is the mechanism rather than the error."),
("paid for my admiring it, and both of those sentences are true at once.", "paid for my admiring it. Both of those sentences are true at once."),
("Whoever wrote the original specification made one, and I have spent nineteen years", "Whoever wrote the original specification made one. I have spent nineteen years"),
("the report says the process worked, and it did work, on the backs of", "the report says the process worked, which it did, on the backs of"),
("The discipline goes out with it, and the discipline is what keeps a relational field", "The discipline goes out with it: the very thing that keeps a relational field"),
("the structure did exactly what it got built to do, and that was the problem.", "the structure did exactly what it got built to do, which was the problem."),
("a specific kind of expensive, and the expense has a name: the system's cut.", "a specific kind of expensive, with a name: the system's cut."),
("made a fourth time, and the system keeps the difference.", "made a fourth time, while the system keeps the difference."),
("That case is the spine of the School of the Pattern, and it holds.", "That case is the spine of the School of the Pattern. It holds."),
("on the same day, chooses otherwise, and the fact that they can", "on the same day, chooses otherwise. The fact that they can"),
("is an account of Agency, and no incentive map predicts them.", "is an account of Agency: no incentive map predicts them."),
("where it means roughly nothing, and this chapter uses it in her sense throughout.", "where it means roughly nothing, but this chapter uses it in her sense throughout."),
("a measurably better system every year, and the system will still stop working", "a measurably better system every year, yet the system will still stop working"),
("where the Architect most often walks away, and workload has nothing to do with it.", "where the Architect most often walks away, for reasons that have nothing to do with workload."),
("most valuable and most visible, and stepping out of it costs exactly that.", "most valuable and most visible, so stepping out of it costs exactly that."),
("The position takes a judgment call every time, and only a directional diagnostic works.", "The position takes a judgment call every time, so only a directional diagnostic works."),
("feeling one of the five, and a mode here runs on each of them.", "feeling one of the five. A mode here runs on each of them."),
("detects what could go wrong, and dread is that channel stuck,", "detects what could go wrong. Dread is that channel stuck,"),
("the process that used to work and doesn't anymore, and stuck Sadness keeps", "the process that used to work and doesn't anymore. Stuck Sadness keeps"),
BEIT,
("I don't think that's true anymore, and everything we're building sits on top of it.", "I don't think that's true anymore, yet everything we're building sits on top of it."),
("exactly what it was built to do, and it was built for a world we're not in anymore.*", "exactly what it was built to do, for a world we're not in anymore.*"),
("I built a spreadsheet to track my moods, and inside a week I was having", "I built a spreadsheet to track my moods. Inside a week I was having"),
("turns up everywhere for that reason, and it has kept turning up in this book", "turns up everywhere for that reason, which is why it has kept turning up in this book"),
("a different substance altogether, and the design absorbs the energy and calls it urgency.", "a different substance altogether, which the design absorbs and calls urgency."),
("The tell is a sequence, and it is easy to check.", "The tell is a sequence, an easy one to check."),
("who are feeling their way through it, and it does not fit, and they cannot say why, and the designer experiences this as resistance to change.", "who are feeling their way through it. It does not fit, for reasons they cannot name, which the designer experiences as resistance to change."),
("Here the chapter's myth lives, and it remains the most competent-looking myth in the book.", "Here the chapter's myth lives, the most competent-looking myth in the book."),
("Those are not the same event, and only one of them was about them.", "Those are not the same event. Only one of them was about them."),
("it addresses a structural failure, and it disposes of an intolerable feeling, and the second job sets the deadline.", "it addresses a structural failure and disposes of an intolerable feeling. The second job sets the deadline."),
("long enough to hear the answer, and staying in the feeling is what the conversion exists to prevent.", "long enough to hear the answer, which is what the conversion exists to prevent."),
("get dismantled in a meeting, and it still cringes at the system I built", "get dismantled in a meeting. It still cringes at the system I built"),
("Naming it changes something, and it is worth being precise about what.", "Naming it changes something. It is worth being precise about what."),
("That report I want, and I will use it.", "That report I want. I will use it."),
("Then the conversion fires, and by the time the agenda has moved one item on you have a restructure of the intake process, three slides deep, and it is good.", "Then the conversion fires. By the time the agenda has moved one item on you have a restructure of the intake process, three slides deep. It is good."),
("Yours converts in its own way, and that is the one to work.", "Yours converts in its own way, which is the one to work."),
("It argues for Structure, and Structure is half the truth.", "It argues for Structure, which is half the truth."),
("and call it sophistication, and no single instance will look like an evasion,", "and call it sophistication, without a single instance looking like an evasion,"),
("started deflecting, and the eleventh claim is as defensible as the first.", "started deflecting, though the eleventh claim is as defensible as the first."),
("Where the existing structure is already almost right, and one adjustment would make it lock into place?", "Where is the existing structure so nearly right that one adjustment would make it lock into place?"),
("in a format her screen reader can use, and three times somebody prints her", "in a format her screen reader can use. Three times somebody prints her"),
("before it will reimburse anything, and the team keeps calling", "before it will reimburse anything, while the team keeps calling"),
("from shorter form to advance payment, and people stop arguing about fields.", "from shorter form to advance payment, so people stop arguing about fields."),
("a form in two languages, and it costs the program more than you do.", "a form in two languages. It costs the program more than you do."),
("before you shipped, and wrote down what you were assuming", "before you shipped, then wrote down what you were assuming"),
("We know exactly what it should look like, and we can't bear to put it", "We know exactly what it should look like, so we can't bear to put it"),
("whether the swapping was ever the problem, and Bea stops negotiating in private.", "whether the swapping was ever the problem. Meanwhile Bea stops negotiating in private."),
("the design needs to change, and you can also hold the fact that the previous version", "the design needs to change while holding the fact that the previous version"),
("*we built this with what we knew, and it was the right call then.", "*we built this with what we knew. It was the right call then."),
("stops being able to see it, and you will need to see the next one.", "stops being able to see it. You will need to see the next one."),
("It got you here, and saying so out loud is part of the move.", "It got you here. Saying so out loud is part of the move."),
("Reading a system that way is real skill, and it asks nothing of you,", "Reading a system that way is real skill, but it asks nothing of you,"),
("before it hands you a channel, and both before you have asked anybody a question,", "before it hands you a channel, both of them before you have asked anybody a question,"),
("into a recommendation, and a recommendation is a design that has agreed", "into a recommendation, which is a design that has agreed"),
("a month you were not in, and came out altered by somebody who is not you.", "a month you were not in, then came out altered by somebody who is not you."),
("That question is real, and it belongs to the Architect, because", "That question is real. It belongs to the Architect, because"),
("The daemon is a rule, and it is in force at all five moves.", "The daemon is a rule, in force at all five moves."),
("returns the same one, at speed, and the speed gets called competence.", "returns the same one, at a speed that gets called competence."),
("has a process attached to it, and nobody will have to feel it again.", "has a process attached to it, so nobody will have to feel it again."),
("a real place in the sequence, and this one is being run early", "a real place in the sequence, but this one is being run early"),
("by the fifteenth, and it will cost me being the person they call.**", "by the fifteenth, at the cost of being the person they call.**"),
("the most reasonable-sounding myth in the set, and that is why it survives", "the most reasonable-sounding myth in the set, which is why it survives"),
("A harm occurs, you see it, you address it, the situation improves, and something in you registers", "When a harm occurs and you see it, address it, and watch the situation improve, something in you registers"),
("That is structural generosity, and it is the intent behind every one of the five moves.", "That is structural generosity, the intent behind every one of the five moves."),
("a reading before it is a finding, and it is the one part of the Architect's practice", "a reading before it is a finding, the one part of the Architect's practice"),
("do not trust each other, and design assumes a goodwill", "do not trust each other, because design assumes a goodwill"),
("That is the Diplomat's work, and it comes after the Architect's", "That is the Diplomat's work, which comes after the Architect's"),
]
