E = [
("indebted to which sources, and what those sources offer a reader", "indebted to which sources and what those sources offer a reader"),
("The science is real, and it shaped me.", "The science is real. It shaped me."),
("One more, and it is a debt with a disagreement attached.", "One more: a debt with a disagreement attached."),
("on the psychology of Alfred Adler, and Chapter 3 quotes one line from it", "on the psychology of Alfred Adler. Chapter 3 quotes one line from it"),
("you make your move, and what the other person does with it is their business", "you make your move, while what the other person does with it is their business"),
("Adler gets there by a different road than I do, and he gets there first.", "Adler gets there first, by a different road than mine."),
("Chapter 3 is where you learn to run it, and every Face after teaches its own changes on it.", "Chapter 3 is where you learn to run it. Every Face after teaches its own changes on it."),
("in this book have a shape, and the shape is **Gerard Egan's**.", "in this book have a shape: **Gerard Egan's**."),
("The term runs through the Architect chapter\nas a term of art, and it is hers.", "The term, hers, runs through the Architect chapter\nas a term of art."),
("ranking lives, and it repays rereading every few years.", "ranking lives. It repays rereading every few years."),
("Thirty years of research sits on top of it, and it earned that for the reason", "Thirty years of research sits on top of it, earned for the reason"),
("one person appraising another, and appraisal is a conscious act by a rational actor.", "one person appraising another, which is a conscious act by a rational actor."),
("puts a Protector at the door first, and a Protector appraises nothing.", "puts a Protector at the door first. A Protector appraises nothing."),
("checks you against it, and the three questions belong to the person", "checks you against it, while the three questions belong to the person"),
("leans on by name, and the distinction is his:", "leans on by name, for his distinction:"),
("anxious and compliant, and both sets produce action.", "anxious and compliant, though both sets produce action."),
("will get someone moving, and they will also burn that person down", "will get someone moving, but they will also burn that person down"),
("the struggle it creates, and the goal is disposable afterward", "the struggle it creates, a goal that is disposable afterward"),
]
