/**
 * Archetype Influence Overlay v1 — Canonical profiles
 * Spec: .specify/specs/archetype-influence-overlay/spec.md
 */

import type { ArchetypeInfluenceProfile } from './types'

export const ARCHETYPE_PROFILES: ArchetypeInfluenceProfile[] = [
  {
    archetype_id: 'bold-heart',
    archetype_name: 'The Bold Heart',
    trigram: 'Heaven',
    agency_pattern: ['initiative', 'creative leadership', 'courageous beginning'],
    action_style: ['initiate a bold action'],
    reflection_style: ['reflect on the new path created'],
    integration_style: ['reflect on the new path created'],
    prompt_modifiers: ['What courageous step could open a new path here?'],
    quest_style_modifiers: ['leadership quests', 'first-move actions', 'initiative challenges'],
  },
  {
    archetype_id: 'danger-walker',
    archetype_name: 'The Danger Walker',
    trigram: 'Water',
    agency_pattern: ['risk navigation', 'adaptation', 'depth exploration'],
    action_style: ['navigate a small controlled risk'],
    reflection_style: ['reflect on what the risk revealed'],
    integration_style: ['reflect on what the risk revealed'],
    prompt_modifiers: ['What small risk could safely reveal something new?'],
    quest_style_modifiers: ['risk navigation quests', 'fear exploration', 'uncertainty challenges'],
  },
  {
    archetype_id: 'truth-seer',
    archetype_name: 'The Truth Seer',
    trigram: 'Fire',
    agency_pattern: ['illumination', 'clarity', 'truth revelation'],
    action_style: ['reveal or speak a truth'],
    reflection_style: ['record the clarity that emerged'],
    integration_style: ['record the clarity that emerged'],
    prompt_modifiers: ['What truth is asking to be illuminated?'],
    quest_style_modifiers: ['truth speaking quests', 'insight quests', 'clarity exercises'],
  },
  {
    archetype_id: 'still-point',
    archetype_name: 'The Still Point',
    trigram: 'Mountain',
    agency_pattern: ['stillness', 'boundaries', 'stability'],
    action_style: ['pause or hold a boundary'],
    reflection_style: ['observe what became clear through stillness'],
    integration_style: ['observe what became clear through stillness'],
    prompt_modifiers: ['What happens if you pause instead of reacting?'],
    quest_style_modifiers: ['meditative quests', 'boundary practice', 'grounding challenges'],
  },
  {
    archetype_id: 'subtle-influence',
    archetype_name: 'The Subtle Influence',
    trigram: 'Wind',
    agency_pattern: ['gradual change', 'persistent shaping', 'system influence'],
    action_style: ['attempt a small influence'],
    reflection_style: ['observe what shifted'],
    integration_style: ['observe what shifted'],
    prompt_modifiers: ['What small influence could begin shifting this system?'],
    quest_style_modifiers: ['habit changes', 'gentle persuasion', 'system nudges'],
  },
  {
    archetype_id: 'devoted-guardian',
    archetype_name: 'The Devoted Guardian',
    trigram: 'Earth',
    agency_pattern: ['support', 'stewardship', 'stability creation'],
    action_style: ['provide support or build structure'],
    reflection_style: ['reflect on what stability enabled'],
    integration_style: ['reflect on what stability enabled'],
    prompt_modifiers: ['What support could help this situation grow?'],
    quest_style_modifiers: ['care quests', 'stewardship challenges', 'resource building'],
  },
  {
    archetype_id: 'decisive-storm',
    archetype_name: 'The Decisive Storm',
    trigram: 'Thunder',
    agency_pattern: ['sudden action', 'pattern disruption', 'breakthrough'],
    action_style: ['take a bold disruptive action'],
    reflection_style: ['observe the change triggered'],
    integration_style: ['observe the change triggered'],
    prompt_modifiers: ['What bold action would break this pattern?'],
    quest_style_modifiers: ['breakthrough quests', 'pattern disruption', 'shock actions'],
  },
  {
    archetype_id: 'joyful-connector',
    archetype_name: 'The Joyful Connector',
    trigram: 'Lake',
    agency_pattern: ['joy', 'connection', 'shared experience'],
    action_style: ['invite or create shared experience'],
    reflection_style: ['reflect on how connection changed the situation'],
    integration_style: ['reflect on how connection changed the situation'],
    prompt_modifiers: ['Who could share this experience with you?'],
    quest_style_modifiers: ['collaboration quests', 'social experiments', 'celebration quests'],
  },
]
