import path from 'node:path'
import { defineConfig } from 'vitest/config'

/**
 * Vitest-only suites (alchemy-engine + TSG action mocks). Sibling *.test.ts files use `tsx` + node:assert.
 */
export default defineConfig({
  test: {
    environment: 'node',
    include: [
      'src/lib/mtgoa-course/__tests__/course-foundation.test.ts',
      'src/lib/wake-up/__tests__/check-content.test.ts',
      'src/lib/mtgoa-course/__tests__/receipt-handoffs.test.ts',
      'src/lib/mtgoa-course/__tests__/round-two.test.ts',
      'src/lib/mtgoa-course/__tests__/day-eight.test.ts',
      'src/lib/mtgoa-course/__tests__/day-ten.test.ts',
      'src/lib/mtgoa-course/__tests__/day-eleven.test.ts',
      'src/components/mtgoa-check/__tests__/day-eleven-render.test.tsx',
      'src/lib/mtgoa-course/__tests__/day-twelve.test.ts',
      'src/components/mtgoa-check/__tests__/day-twelve-render.test.tsx',
      'src/lib/mtgoa-course/__tests__/day-thirteen.test.ts',
      'src/lib/mtgoa-course/__tests__/day-thirteen-store.test.ts',
      'src/components/mtgoa-check/__tests__/day-thirteen-render.test.tsx',
      'src/lib/mtgoa-course/__tests__/day-fourteen.test.ts',
      'src/components/mtgoa-check/__tests__/day-fourteen-render.test.tsx',
      'src/lib/mtgoa-course/__tests__/show-up-handoff.test.ts',
      'src/lib/mtgoa-course/__tests__/course-index.test.ts',
      'src/lib/mtgoa-course/__tests__/course-gating.test.ts',
      'src/lib/mtgoa-course/__tests__/og-cards.test.ts',
      'src/lib/show-up/__tests__/check-content.test.ts',
      'src/lib/grow-up/__tests__/check-content.test.ts',
      'src/actions/__tests__/campaign-attach.test.ts',
      'src/actions/__tests__/campaign-milestone-authoring.test.ts',
      'src/lib/alchemy-engine/__tests__/ai-generation.test.ts',
      'src/lib/alchemy-engine/__tests__/arc-flow-wiring.test.ts',
      'src/lib/alchemy-engine/__tests__/e2e-arc-dissatisfied-to-epiphany.test.ts',
      'src/lib/alchemy-engine/__tests__/passage-resolver.test.ts',
      'src/lib/alchemy-engine/__tests__/reflection-bar-persistence-wiring.test.ts',
      'src/lib/technique-library/__tests__/vocabulary-no-drift.test.ts',
      'src/lib/technique-library/__tests__/resolve.test.ts',
      'src/lib/technique-library/__tests__/validate.test.ts',
      'src/lib/technique-library/__tests__/superpower-decks.test.ts',
      'src/lib/technique-library/__tests__/quality.test.ts',
      'src/lib/technique-library/__tests__/superpower-quality.test.ts',
      'src/lib/technique-library/__tests__/go-deeper.test.ts',
      'src/lib/emotional-alchemy/__tests__/registry.test.ts',
      'src/lib/emotional-alchemy/__tests__/vector.test.ts',
      'src/lib/emotional-alchemy/__tests__/composer.test.ts',
      'src/lib/emotional-alchemy/__tests__/interim-card.test.ts',
      'src/lib/player-entitlements/__tests__/superpower-skus.test.ts',
      'src/lib/superpowers/__tests__/quiz-loadout.test.ts',
      'src/lib/launch/__tests__/superpower-offers.test.ts',
      'src/lib/ally-campaign/__tests__/economics.test.ts',
      'src/lib/ally-campaign/__tests__/content-overrides.test.ts',
      'src/lib/ally-campaign/__tests__/content-tokens.test.ts',
      'src/lib/ally-campaign/__tests__/victory-paths.test.ts',
      'src/lib/ally-campaign/__tests__/divisible-needs.test.ts',
      'src/lib/ally-campaign/__tests__/warm-selling.test.ts',
      'src/lib/ally-campaign/__tests__/digital-price-parity.test.ts',
      'src/lib/ally-campaign/__tests__/referral.test.ts',
      'src/lib/ally-campaign/__tests__/disclosure-invariant.test.ts',
      'src/lib/ally-campaign/__tests__/attribution.test.ts',
      'src/lib/open-up/__tests__/events.test.ts',
      'src/lib/open-up/__tests__/outbound.test.ts',
      'src/lib/clean-up/__tests__/check-content.test.ts',
      'src/lib/clean-up/__tests__/events.test.ts',
      // Registered by the guard below, which fails if any vitest suite is missing here.
      'src/lib/__tests__/book-toc-to-sections.test.ts',
      'src/lib/__tests__/npc-face-resolver.test.ts',
      'src/lib/cyoa-composer/__tests__/merge-overrides.test.ts',
      'src/lib/cyoa-composer/__tests__/step-registry.test.ts',
      'src/lib/__tests__/vitest-include-registration.test.ts',
    ],
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
