/**
 * Emotional Alchemy Tool Registry — canonical data, T01–T11.
 * Spec: .specify/specs/emotional-alchemy-tool-registry/spec.md
 *
 * TRANSCRIBED from docs/EMOTIONAL_ALCHEMY_TOOL_TAXONOMY.md (v1.1) and
 * docs/MTGOA_PRACTICE_ATLAS.md (v3 §4, §4.1, §5.2, §5.3, §5.4).
 * Ratings are drift-tested against the compact matrices — editing a rating
 * here is a canon change: update the taxonomy doc and the test with it.
 */

import type {
  EmotionalAlchemyTool,
  EmotionChannel,
  ElementChannel,
  HardGuard,
  HardGuardId,
  SatisfactionSpirit,
} from './types'

/** Atlas §4 — the composer enforces these as blocks, not footnotes. */
export const HARD_GUARDS: Record<HardGuardId, HardGuard> = {
  hot_charge: {
    id: 'hot_charge',
    rule: 'Intensity ≥ 7 → T07 Return to the Body is prepended before any other tool, always.',
  },
  joy_tool_block: {
    id: 'joy_tool_block',
    rule: 'Blocked at Anger or Sadness intensity ≥ 5 (toxic-positivity paint over an unmetabolized charge).',
  },
  grief_inquiry_block: {
    id: 'grief_inquiry_block',
    rule: 'Blocked on fresh Sadness; on the received-harm branch, restricted to agency-restoring turnarounds only.',
  },
  no_gamified_risk: {
    id: 'no_gamified_risk',
    rule: 'Blocked when the blocker involves physical risk — risk goes to T05 as an inventory with mitigations.',
  },
  action_on_grief_block: {
    id: 'action_on_grief_block',
    rule: 'Blocked on early Sadness — grief does not need a next action, it needs room.',
  },
  clean_line_readiness: {
    id: 'clean_line_readiness',
    rule: 'Blocked while the intent is to punish, recruit guilt, or control an outcome.',
  },
  external_gate: {
    id: 'external_gate',
    rule: 'External Show Up options require the recipient check plus intensity < 4 or an explicit asked-not-defaulted hot-action override.',
  },
}

/** Atlas §5.3 — a spirit adds exactly one fill-in-the-blank step, nothing else. */
export const SPIRIT_STEPS: Record<SatisfactionSpirit, string> = {
  peace: 'What would let this settle is ___.',
  triumph: 'The clean power I want to use here is ___.',
  poignance: 'What I care about under this is ___.',
  bliss: 'What wants to be shared or played here is ___.',
  wonder: 'The question that makes this interesting is ___.',
}

/** Bridge from taxonomy emotion channels to the deck grammar's element channels. */
export const EMOTION_TO_ELEMENT: Record<EmotionChannel, ElementChannel> = {
  anger: 'fire',
  sadness: 'water',
  fear: 'metal',
  joy: 'wood',
  neutrality: 'earth',
}

export const EMOTIONAL_ALCHEMY_TOOLS: EmotionalAlchemyTool[] = [
  {
    id: 'T01',
    slug: '321-charge-dialogue',
    genericName: 'Structured Part Dialogue',
    barsName: '321 Charge Dialogue',
    lineage:
      'Integral Life Practice 3-2-1 Shadow Process; BARS 321; general lineage: parts work and perspective-taking.',
    coreMechanic:
      'Move from observing a charged figure/part, to relating with it, to owning the clean portion of its energy.',
    waveRatings: { wake_up: 'strong', open_up: 'medium', clean_up: 'strong', grow_up: 'strong', show_up: 'medium' },
    moveRoleRatings: { metabolize: 'strong', translate: 'strong', transcend: 'medium' },
    channelRatings: { anger: 'strong', sadness: 'strong', fear: 'strong', joy: 'medium', neutrality: 'medium' },
    misuse: 'Over-identifying with a part, or making external claims from internal dialogue.',
    protocol: {
      steps: [
        'Name the charge in third person: "There is a part/figure that…"',
        'Give it a short name, image, or role.',
        'Address it directly: "You are here because…"',
        'Ask it: "What are you protecting, wanting, or refusing?"',
        'Speak as it for 3–5 sentences beginning "I am…"',
        'Write one owned sentence: "The clean energy I can reclaim is…"',
        'Choose one next expression or internal commitment.',
      ],
      miniSteps: [
        'Name and address the part in one breath each.',
        'Speak as it for two sentences.',
        'Write the owned-energy sentence.',
      ],
    },
    timebox: { minMinutes: 7, maxMinutes: 15, quickMinutes: 3 },
    outputKind: 'part-dialogue',
    outputFields: ['part_name', 'part_quote', 'owned_energy_sentence', 'next_commitment', 'quest_seed'],
    barReflection: 'I met the part called ___. It was trying to ___. The clean energy I can reclaim is ___.',
    completionCriteria: ['The player can distinguish the part’s signal from the old reaction.'],
    whenNotToUse: ['The player is too activated to keep perspective — use grounding (T07) first.'],
    preferAnotherToolWhen: [
      { condition: 'The belief is already explicit', toolId: 'T04' },
      { condition: 'The body signal is vague', toolId: 'T02' },
      { condition: 'A concrete boundary is needed now', toolId: 'T06' },
    ],
    spiritNotes: {
      peace: 'Slow the dialogue until the part can stop fighting.',
      triumph: 'Ask what power wants clean expression.',
      poignance: 'Ask what care is underneath.',
      bliss: 'Ask what aliveness wants to circulate.',
      wonder: 'Ask what new possibility this part reveals.',
    },
    showUpTemplates: {
      internal: 'Vow: "I will honor [part_name] by keeping [next_commitment] for 24 hours."',
      external: 'Send one ask written from "[owned_energy_sentence]" to [recipient] by [date].',
    },
    hardGuardIds: [],
    shapeBonusKeys: ['imagined_other', 'two_voices'],
    operationalChecks: [
      {
        criterion: 'Owned-energy sentence',
        check:
          'Must name a quality YOU want to use; must not mention the other person. Not: "The clean energy is that Marcus should listen." Yes: "The clean energy I can reclaim is my directness."',
      },
    ],
    mappings: { techniqueIds: ['tech-3-2-1', 'tech-recursive-3-2-1'], firstAidKeys: ['shadow-321'] },
  },
  {
    id: 'T02',
    slug: 'find-the-felt-thread',
    genericName: 'Felt-Sense Tracking',
    barsName: 'Find the Felt Thread',
    lineage: 'Local felt-sense praxis from Gendlin/Focusing (docs/FELT_SENSE_321_PRAXIS.md); general lineage: Focusing.',
    coreMechanic:
      'Let an unclear bodily whole form, test handles against the body, and record the phrase/image that creates a felt shift.',
    waveRatings: { wake_up: 'strong', open_up: 'strong', clean_up: 'strong', grow_up: 'medium', show_up: 'weak' },
    moveRoleRatings: { metabolize: 'strong', translate: 'medium', transcend: 'strong' },
    channelRatings: { anger: 'medium', sadness: 'strong', fear: 'strong', joy: 'medium', neutrality: 'strong' },
    misuse: 'Forcing an answer too quickly — the felt sense needs its 20–30 seconds.',
    protocol: {
      steps: [
        'Pause for 20–30 seconds before writing.',
        'Locate where the charge lives in the body.',
        'Describe its size, texture, temperature, motion, or image.',
        'Try three possible handles: word, phrase, image.',
        'Check each handle against the body: more open, tighter, neutral, or not it.',
        'Keep the best-fitting handle.',
        'Write: "What this whole thing feels like is ___."',
      ],
    },
    timebox: { minMinutes: 3, maxMinutes: 8 },
    outputKind: 'felt-thread',
    outputFields: ['body_location', 'felt_handle', 'fit_signal', 'handle_sentence'],
    barReflection: 'The felt sense was in ___. The handle that fit was ___. After checking, the shift was ___.',
    completionCriteria: ['A felt handle emerges, or the player names that no handle has formed yet (valid completion).'],
    whenNotToUse: ['The player needs immediate safety, logistics, or social repair.'],
    preferAnotherToolWhen: [
      { condition: 'The blocker is a belief', toolId: 'T04' },
      { condition: 'There are conflicting internal voices', toolId: 'T01' },
      { condition: 'The next action is already clear', toolId: 'T08' },
    ],
    spiritNotes: {
      peace: 'Look for the handle that settles.',
      triumph: 'Look for the handle that restores clean agency.',
      poignance: 'Look for the ache of care.',
      bliss: 'Look for the felt opening.',
      wonder: 'Look for the image that makes the unknown interesting.',
    },
    showUpTemplates: {
      internal: 'Save "[felt_handle]" as a BAR seed for a later quest.',
      external: 'Ask one curiosity question about "[felt_handle]" to [recipient] by [date].',
    },
    hardGuardIds: [],
    shapeBonusKeys: ['unclear_heavy_body'],
    operationalChecks: [
      {
        criterion: 'One true sentence',
        check:
          'Read it aloud; if the body loosens, keep it; if it tightens or nothing happens, try once more, then keep the best of the two. Two attempts, not a perfection loop.',
      },
    ],
    mappings: {
      techniqueIds: [],
      firstAidKeys: [],
      note: 'Focusing praxis; felt-sense scaffolding on /shadow/321 (no prior named tool id).',
    },
  },
  {
    id: 'T03',
    slug: 'bar-capture',
    genericName: 'Reflective Capture',
    barsName: 'BAR Capture',
    lineage: 'General lineage: journaling; BARS BAR seed and reflection flows.',
    coreMechanic: 'Convert internal material into a durable inspectable artifact.',
    waveRatings: { wake_up: 'strong', open_up: 'medium', clean_up: 'medium', grow_up: 'strong', show_up: 'medium' },
    moveRoleRatings: { metabolize: 'medium', translate: 'medium', transcend: 'medium' },
    channelRatings: { anger: 'medium', sadness: 'strong', fear: 'medium', joy: 'medium', neutrality: 'strong' },
    misuse: 'Writing around the move instead of producing a concrete output.',
    protocol: {
      steps: [
        'Write the current charge in one sentence.',
        'Write the desired satisfaction in one sentence.',
        'Write the blocker/story in one sentence.',
        'Complete: "The emotional move I am practicing is…"',
        'Complete: "The cleanest next artifact is…"',
        'Create the artifact: sentence, ask, boundary, map, message draft, or quest seed.',
      ],
      miniSteps: ['Write the charge in one sentence.', 'Write the cleanest next artifact in one sentence.'],
    },
    timebox: { minMinutes: 5, maxMinutes: 10, quickMinutes: 2 },
    outputKind: 'bar-seed',
    outputFields: ['charge_sentence', 'satisfaction_sentence', 'blocker_sentence', 'practice_move', 'next_artifact'],
    barReflection: 'The tool output is already BAR-shaped.',
    completionCriteria: [
      'The reflection contains current charge, desired satisfaction, blocker/story, and one next artifact.',
    ],
    whenNotToUse: ['Writing becomes rumination or self-attack (same sentence 3× = stop, switch tools).'],
    preferAnotherToolWhen: [
      { condition: 'The body is offline', toolId: 'T07' },
      { condition: 'A belief needs testing', toolId: 'T04' },
      { condition: 'External communication is needed', toolId: 'T06' },
    ],
    spiritNotes: {
      peace: 'Reduce to one true sentence.',
      triumph: 'Name earned agency.',
      poignance: 'Record care and distance.',
      bliss: 'Record aliveness and sharing.',
      wonder: 'Record a live question.',
    },
    showUpTemplates: {
      internal: 'Adopt "[next_artifact]" as a 24-hour practice; check off at [time].',
      external: 'Send or publish [next_artifact] to [recipient] by [date].',
    },
    hardGuardIds: [],
    shapeBonusKeys: [],
    operationalChecks: [],
    mappings: { techniqueIds: [], firstAidKeys: [], note: 'Journaling / BAR reflection / charge capture flows.' },
  },
  {
    id: 'T04',
    slug: 'story-turnaround',
    genericName: 'Belief Inquiry',
    barsName: 'Story Turnaround',
    lineage:
      'Local Inquiry Lite spec; general lineage: contemplative inquiry and Byron Katie-style question/turnaround practice.',
    coreMechanic:
      'Identify the story driving stuckness, test its certainty, observe its cost, and generate a truer replacement.',
    waveRatings: { wake_up: 'medium', open_up: 'weak', clean_up: 'strong', grow_up: 'strong', show_up: 'medium' },
    moveRoleRatings: { metabolize: 'strong', translate: 'medium', transcend: 'medium' },
    channelRatings: { anger: 'strong', sadness: 'medium', fear: 'strong', joy: 'weak', neutrality: 'medium' },
    misuse: 'Using inquiry to argue the player out of legitimate desire, threat, or grief.',
    protocol: {
      steps: [
        'Write the blocker story as a sentence: "I cannot ___ because ___."',
        'Ask: "Is this completely true right now?"',
        'Write what happens when you believe it: body, action, emotion.',
        'Write who you would be for 10 minutes without this thought.',
        'Write three turnarounds or cleaner versions.',
        'Choose one replacement that is testable today.',
        'Define one tiny experiment or internal commitment.',
      ],
    },
    timebox: { minMinutes: 8, maxMinutes: 15 },
    outputKind: 'belief-inquiry',
    outputFields: ['belief', 'cost_lines', 'turnarounds', 'replacement', 'experiment'],
    barReflection: 'The story was ___. When I believed it, I ___. The replacement I will test is ___.',
    completionCriteria: ['A testable replacement exists without denying the original signal.'],
    whenNotToUse: ['The problem is practical ignorance, external danger, or active overwhelm.'],
    preferAnotherToolWhen: [
      { condition: 'A part needs to speak', toolId: 'T01' },
      { condition: 'No story is visible yet', toolId: 'T02' },
      { condition: 'A direct action is available', toolId: 'T08' },
    ],
    spiritNotes: {
      peace: 'Seek a non-urgent truth.',
      triumph: 'Seek an agency-restoring truth.',
      poignance: 'Protect care from false stories.',
      bliss: 'Ask what permission the story blocks.',
      wonder: 'Turn certainty into inquiry.',
    },
    showUpTemplates: {
      internal: 'Hold "[replacement]" for 24 hours; log evidence at [time].',
      external: 'Run the ≤10-minute experiment "[experiment]" before [date].',
    },
    hardGuardIds: ['grief_inquiry_block'],
    shapeBonusKeys: ['belief_sentence'],
    operationalChecks: [],
    mappings: { techniqueIds: [], firstAidKeys: ['self-sabotage-audit'], note: 'Inquiry Lite spec.' },
  },
  {
    id: 'T05',
    slug: 'put-it-on-the-board',
    genericName: 'Field Mapping',
    barsName: 'Put It On The Board',
    lineage:
      'General lineage: systems mapping, stakeholder mapping, cognitive offloading; BARS domains and quest grammar.',
    coreMechanic: 'Externalize the situation as objects and relations so the player can see where work belongs.',
    waveRatings: { wake_up: 'strong', open_up: 'medium', clean_up: 'medium', grow_up: 'strong', show_up: 'medium' },
    moveRoleRatings: { metabolize: 'medium', translate: 'strong', transcend: 'weak' },
    channelRatings: { anger: 'strong', sadness: 'weak', fear: 'strong', joy: 'weak', neutrality: 'strong' },
    misuse: 'Mapping as avoidance.',
    protocol: {
      steps: [
        'Draw four boxes: me, blocker, desired satisfaction, field.',
        'Put every known fact in the field box.',
        'Put every interpretation/story in the blocker box.',
        'Mark each item as fact, story, need, resource, threat, or desire.',
        'Circle the one place where a move is possible now.',
        'Write the move as a sentence.',
      ],
      miniSteps: ['List facts vs stories in two columns.', 'Circle where a move is possible.', 'Write the move.'],
    },
    timebox: { minMinutes: 10, maxMinutes: 20, quickMinutes: 5 },
    outputKind: 'field-map',
    outputFields: ['field_map', 'blocker_classification', 'next_move_location', 'next_move_sentence'],
    barReflection: 'The work belongs at ___. The blocker is mostly fact/story/need/resource/threat/desire.',
    completionCriteria: ['The player can name where the next move belongs.'],
    whenNotToUse: ['The player is using analysis to avoid feeling or action.'],
    preferAnotherToolWhen: [
      { condition: 'The charge is bodily/vague', toolId: 'T02' },
      { condition: 'The next move is a message', toolId: 'T06' },
      { condition: 'Grief needs flow', toolId: 'T10' },
    ],
    spiritNotes: {
      peace: 'Map enough to reduce noise.',
      triumph: 'Map leverage.',
      poignance: 'Map care and distance.',
      bliss: 'Map aliveness and invitations.',
      wonder: 'Map unknowns as doors.',
    },
    showUpTemplates: {
      internal: 'Hold the edge: "[next_move_sentence]" is the only work on this today.',
      external: 'Make the ask named at [next_move_location] to [recipient] by [date].',
    },
    hardGuardIds: [],
    shapeBonusKeys: ['many_items'],
    operationalChecks: [
      {
        criterion: 'Board completeness',
        check:
          'Every real threat or kept item carries a mitigation or next move with an owner and a date — a board item without a dated next move is deferred avoidance.',
      },
    ],
    mappings: {
      techniqueIds: [],
      firstAidKeys: [],
      note: 'No prior named tool (the taxonomy names this as its own gap 3).',
    },
  },
  {
    id: 'T06',
    slug: 'clean-line',
    genericName: 'Clean Ask / Boundary Script',
    barsName: 'Clean Line',
    lineage:
      'Existing Boundary Shield and Rose Tool; general lineage: consent-forward communication and boundary scripting.',
    coreMechanic: 'Turn charge into a short ask, no, offer, or limit that can be spoken or held.',
    waveRatings: { wake_up: 'medium', open_up: 'weak', clean_up: 'medium', grow_up: 'strong', show_up: 'strong' },
    moveRoleRatings: { metabolize: 'weak', translate: 'medium', transcend: 'medium' },
    channelRatings: { anger: 'strong', sadness: 'weak', fear: 'strong', joy: 'weak', neutrality: 'strong' },
    misuse: 'Premature confrontation before the signal is clean.',
    protocol: {
      steps: [
        'Name the relationship or field where the line belongs.',
        'Choose script type: ask, no, offer, limit, repair.',
        'Fill the template: "I want/need ___. I can ___. I cannot ___. Would you be willing to ___?"',
        'Remove blame and over-explaining.',
        'Read it aloud once.',
        'Choose delivery: send, save, practice, or convert into internal line.',
      ],
    },
    timebox: { minMinutes: 5, maxMinutes: 12 },
    outputKind: 'clean-line',
    outputFields: ['script_type', 'line', 'delivery_choice', 'outcome'],
    barReflection: 'The clean line was ___. I sent/held/practiced it. The outcome was ___.',
    completionCriteria: ['The line is short, true, and actionable or holdable.'],
    whenNotToUse: ['The player is still trying to punish, recruit guilt, or control an outcome.'],
    preferAnotherToolWhen: [
      { condition: 'The desire is unclear', toolId: 'T02' },
      { condition: 'The belief is tangled', toolId: 'T04' },
      { condition: 'The part is exiled', toolId: 'T01' },
    ],
    spiritNotes: {
      peace: 'Soften the line without deleting it.',
      triumph: 'Make the line direct.',
      poignance: 'Include care and grief.',
      bliss: 'Make the offer generous but bounded.',
      wonder: 'Ask a question instead of closing the field.',
    },
    showUpTemplates: {
      internal: 'Keep "[line]" as a 24-hour rule.',
      external: 'Deliver "[line]" to [recipient] at [date].',
    },
    hardGuardIds: ['clean_line_readiness'],
    shapeBonusKeys: ['interpersonal_live'],
    operationalChecks: [
      {
        criterion: 'Short and true',
        check: 'Stranger test: would a stranger reading only this sentence know exactly what is being asked or declined?',
      },
    ],
    mappings: { techniqueIds: ['tech-rose'], firstAidKeys: ['boundary-shield'] },
  },
  {
    id: 'T07',
    slug: 'return-to-the-body',
    genericName: 'Regulation Reset',
    barsName: 'Return to the Body',
    lineage:
      'Existing Grounding Sequence, Grounding Cord, Breath Reset, Basic Qi Gong Reset; general lineage: breathwork, orienting, grounding, simple movement.',
    coreMechanic: 'Change state enough that the player can sense, choose, or complete a next move.',
    waveRatings: { wake_up: 'medium', open_up: 'strong', clean_up: 'medium', grow_up: 'medium', show_up: 'weak' },
    moveRoleRatings: { metabolize: 'medium', translate: 'weak', transcend: 'weak' },
    channelRatings: { anger: 'strong', sadness: 'weak', fear: 'strong', joy: 'weak', neutrality: 'strong' },
    misuse: 'Calming down to avoid truth — regulation is a gate to transformation, never a substitute for it.',
    protocol: {
      steps: [
        'Rate activation 0–10.',
        'Choose one reset: 4 rounds longer exhale, 5-4-3 orienting, feet/seat scan, 8 slow movement rounds.',
        'Do the reset without multitasking.',
        'Rate activation again.',
        'Write the first available next signal: body, emotion, thought, or action.',
      ],
    },
    timebox: { minMinutes: 1, maxMinutes: 5 },
    outputKind: 'regulation-reset',
    outputFields: ['activation_before', 'activation_after', 'reset_mode', 'next_signal'],
    barReflection: 'Before reset I was __/10. After reset I was __/10. The next signal was ___.',
    completionCriteria: [
      'Activation changes, or the player identifies that stronger support/rest is needed (valid completion).',
    ],
    whenNotToUse: ['It becomes a bypass of needed anger, grief, or action.'],
    preferAnotherToolWhen: [
      { condition: 'There is a clear belief', toolId: 'T04' },
      { condition: 'Grief needs expression', toolId: 'T10' },
      { condition: 'Action is ready', toolId: 'T08' },
    ],
    spiritNotes: {
      peace: 'Emphasize downshift.',
      triumph: 'Emphasize steady force.',
      poignance: 'Make room for softening.',
      bliss: 'Notice pleasant sensation.',
      wonder: 'Orient to new sensory details.',
    },
    showUpTemplates: {
      internal: 'Pause-before-reply rule until [time].',
      external: 'Rejoin the task and do one ≤10-minute action on [next_signal] now.',
    },
    hardGuardIds: [],
    shapeBonusKeys: [],
    operationalChecks: [],
    mappings: {
      techniqueIds: ['tech-grounding', 'tech-ember-breath', 'tech-wave'],
      firstAidKeys: ['grounding-sequence', 'wave-placeholder'],
      note: 'The W.A.V.E. breath tool folds in as a reset mode (Atlas §0 collision 2).',
    },
  },
  {
    id: 'T08',
    slug: 'one-true-next-move',
    genericName: 'Command Bridge',
    barsName: 'One True Next Move',
    lineage:
      'Existing Emotional First Aid Command Bridge; general lineage: executive-function scaffolding and next-action practice.',
    coreMechanic: 'Convert fuzzy charge into a mission sentence and one action under ten minutes.',
    waveRatings: { wake_up: 'medium', open_up: 'weak', clean_up: 'weak', grow_up: 'medium', show_up: 'strong' },
    moveRoleRatings: { metabolize: 'weak', translate: 'medium', transcend: 'medium' },
    channelRatings: { anger: 'strong', sadness: 'weak', fear: 'medium', joy: 'medium', neutrality: 'strong' },
    misuse: 'Forcing action before metabolization.',
    protocol: {
      steps: [
        'Complete: "For the next hour, my mission is ___."',
        'List three possible actions under ten minutes.',
        'Cross out any action that depends on another person responding first.',
        'Choose the smallest action that visibly advances the mission.',
        'Do it or schedule it.',
        'Log what changed.',
      ],
    },
    timebox: { minMinutes: 3, maxMinutes: 13 },
    outputKind: 'next-move',
    outputFields: ['mission_sentence', 'chosen_action', 'completion_note'],
    barReflection: 'My mission was ___. The one true next move was ___. I completed/scheduled it and learned ___.',
    completionCriteria: ['An action is done, scheduled, delegated, or explicitly declined.'],
    whenNotToUse: ['The next move would be impulsive, performative, or avoidant.'],
    preferAnotherToolWhen: [
      { condition: 'The charge is unidentified', toolId: 'T02' },
      { condition: 'The blocker is a belief', toolId: 'T04' },
      { condition: 'The action is interpersonal', toolId: 'T06' },
    ],
    spiritNotes: {
      peace: 'Choose the simplifying action.',
      triumph: 'Choose the leverage action.',
      poignance: 'Choose the care-honoring action.',
      bliss: 'Choose the energizing action.',
      wonder: 'Choose the experiment.',
    },
    showUpTemplates: {
      internal: 'Mission lock: "[mission_sentence]" — refuse other missions for one hour.',
      external: 'Do "[chosen_action]" now, or at [time].',
    },
    hardGuardIds: ['action_on_grief_block'],
    shapeBonusKeys: ['ready_to_act'],
    operationalChecks: [],
    mappings: { techniqueIds: [], firstAidKeys: ['command-bridge'] },
  },
  {
    id: 'T09',
    slug: 'happy-apples',
    genericName: 'Appreciation / Resource Scan',
    barsName: 'Happy Apples',
    lineage: 'Existing Happy Apples quest card; general lineage: gratitude, savoring, resource orientation.',
    coreMechanic:
      'Identify small real goods without forcing a silver lining, then let one become shareable or usable.',
    waveRatings: { wake_up: 'medium', open_up: 'strong', clean_up: 'weak', grow_up: 'medium', show_up: 'medium' },
    moveRoleRatings: { metabolize: 'weak', translate: 'medium', transcend: 'strong' },
    channelRatings: { anger: 'weak', sadness: 'weak', fear: 'medium', joy: 'strong', neutrality: 'strong' },
    misuse: 'Premature positivity.',
    protocol: {
      steps: [
        'Name the current charge honestly.',
        'Find three tiny things that are genuinely good right now.',
        'For each, write why it is real, not why it fixes everything.',
        'Choose one apple to receive for 30 seconds.',
        'Choose whether to share it, use it, or simply log it.',
      ],
    },
    timebox: { minMinutes: 2, maxMinutes: 5 },
    outputKind: 'happy-apples',
    outputFields: ['apples', 'received_apple', 'share_choice'],
    barReflection: 'The three apples were ___. The one I could receive was ___. It changed ___.',
    completionCriteria: ['One specific good is felt, or honestly marked as unavailable (valid completion).'],
    whenNotToUse: ['The player needs grief, anger, or boundary before appreciation can be true.'],
    preferAnotherToolWhen: [
      { condition: 'Care/distance is primary', toolId: 'T10' },
      { condition: 'Fear needs risk mapping', toolId: 'T05' },
      { condition: 'A belief is sabotaging joy', toolId: 'T04' },
    ],
    spiritNotes: {
      peace: 'Receive enoughness.',
      triumph: 'Celebrate earned progress.',
      poignance: 'Notice the tenderness inside joy.',
      bliss: 'Amplify pleasure.',
      wonder: 'Ask what else could be alive here.',
    },
    showUpTemplates: {
      internal: 'Permission slip: "[received_apple] counts."',
      external: 'Share [received_apple] with [recipient] by [date].',
    },
    hardGuardIds: ['joy_tool_block'],
    shapeBonusKeys: ['win_wont_land'],
    operationalChecks: [],
    mappings: { techniqueIds: ['tech-happy-apples'], firstAidKeys: [] },
  },
  {
    id: 'T10',
    slug: 'make-it-real',
    genericName: 'Ritual Container',
    barsName: 'Make It Real',
    lineage:
      'Existing quest/party ritual patterns; general lineage: symbolic action, release ritual, integration ritual.',
    coreMechanic:
      'Give an emotional shift a concrete symbolic action, boundary, or artifact so the body and field can register it.',
    waveRatings: { wake_up: 'weak', open_up: 'strong', clean_up: 'medium', grow_up: 'medium', show_up: 'strong' },
    moveRoleRatings: { metabolize: 'medium', translate: 'medium', transcend: 'strong' },
    channelRatings: { anger: 'medium', sadness: 'strong', fear: 'weak', joy: 'strong', neutrality: 'medium' },
    misuse: 'Performance without contact.',
    protocol: {
      steps: [
        'Name what is being released, honored, received, or begun.',
        'Choose a small physical symbol: note, stone, candle, water, song, gesture, object placement.',
        'Speak or write one sentence of meaning.',
        'Perform the symbolic action for 1–3 minutes.',
        'Record what changed in body, emotion, or intention.',
        'Choose whether this becomes a quest seed, private BAR, or no further action.',
      ],
    },
    timebox: { minMinutes: 5, maxMinutes: 15 },
    outputKind: 'ritual',
    outputFields: ['ritual_sentence', 'symbolic_action', 'integration_note', 'quest_seed'],
    barReflection: 'The ritual honored/released/began ___. I used ___. Afterward, ___.',
    completionCriteria: ['A symbolic action is completed and its effect is logged.'],
    whenNotToUse: ['Practical action, consent, or safety is required first.'],
    preferAnotherToolWhen: [
      { condition: 'A belief needs testing', toolId: 'T04' },
      { condition: 'A message needs sending', toolId: 'T06' },
      { condition: 'The charge is unclear', toolId: 'T02' },
    ],
    spiritNotes: {
      peace: 'Complete and settle.',
      triumph: 'Mark earned passage.',
      poignance: 'Honor care and distance.',
      bliss: 'Celebrate embodied aliveness.',
      wonder: 'Open a threshold.',
    },
    showUpTemplates: {
      internal: 'Perform [symbolic_action] privately at [time]; log the shift.',
      external: 'Create or share the artifact from "[ritual_sentence]" with [recipient] by [date].',
    },
    hardGuardIds: [],
    shapeBonusKeys: [],
    operationalChecks: [],
    mappings: { techniqueIds: [], firstAidKeys: [], note: 'Ritual/party quest patterns; no generic named tool before this.' },
  },
  {
    id: 'T11',
    slug: 'make-it-a-game',
    genericName: 'Game Reframe',
    barsName: 'Make It A Game',
    lineage: 'Existing MTGOA play usage; general lineage: gamification, deliberate-practice design. Canonized taxonomy v1.1.',
    coreMechanic: 'Recast a blocker or practice edge as a designed game: win condition, reps, score, playtest partner.',
    waveRatings: { wake_up: 'weak', open_up: 'medium', clean_up: 'weak', grow_up: 'strong', show_up: 'medium' },
    moveRoleRatings: { metabolize: 'weak', translate: 'medium', transcend: 'strong' },
    channelRatings: { anger: 'weak', sadness: 'not_recommended', fear: 'medium', joy: 'strong', neutrality: 'medium' },
    misuse: 'Designing the game forever instead of playing round one. Never gamify grief; never gamify real physical risk.',
    protocol: {
      steps: [
        'Name the edge or task being reframed.',
        'Define a win condition that rewards recovery, not perfection.',
        'Define one rep of 15 minutes or less.',
        'Choose a score unit (Happy Apples allowed).',
        'Schedule rep 1 — play it or put it on the calendar with a date.',
      ],
    },
    timebox: { minMinutes: 15, maxMinutes: 30 },
    outputKind: 'game-card',
    outputFields: ['game_name', 'game_rule', 'win_condition', 'score_unit', 'rep_one_date', 'rep_one_log'],
    barReflection: 'The game is ___. The win is ___. Rep 1 happened on ___; the score was ___.',
    completionCriteria: ['Rep 1 is played or scheduled with a date.'],
    whenNotToUse: [
      'Grief.',
      'Physical-risk assessment.',
      'Play would mock stakes that are real for someone else involved.',
    ],
    preferAnotherToolWhen: [
      { condition: 'The risk is real', toolId: 'T05' },
      { condition: 'The charge is unmetabolized anger/sadness at 5+', toolId: 'T01' },
    ],
    spiritNotes: {
      peace: 'Design the simplifying game.',
      triumph: 'Design the leverage rep.',
      poignance: 'Contraindicated — do not gamify grief.',
      bliss: 'Maximize play.',
      wonder: 'Design the experiment rep.',
    },
    showUpTemplates: {
      internal: 'Play round one solo tonight; log the score.',
      external: 'Recruit [recipient] for rep 1 on [rep_one_date].',
    },
    hardGuardIds: ['joy_tool_block', 'no_gamified_risk'],
    shapeBonusKeys: ['practice_edge'],
    operationalChecks: [],
    mappings: { techniqueIds: [], firstAidKeys: [], note: 'Canonized in taxonomy v1.1 (Practice Atlas gap G6).' },
  },
]
