/**
 * Transformation Move Registry v0 — Canonical 8 moves
 * Spec: .specify/specs/transformation-move-registry/spec.md
 */

import type { TransformationMove } from './types'

export const CANONICAL_MOVES: TransformationMove[] = [
  {
    move_id: 'observe',
    move_name: 'Observe',
    move_category: 'awareness',
    wcgs_stage: 'wake_up',
    description: 'Increase awareness of a pattern without judgment.',
    purpose: 'Surface implicit narrative so it can be examined.',
    prompt_templates: [
      { template_id: 'observe_basic_01', template_text: 'What story are you telling yourself about {object}?', template_type: 'reflection' },
      { template_id: 'observe_basic_02', template_text: 'When you notice {state} around {object}, what pattern do you see?', template_type: 'reflection' },
      { template_id: 'observe_basic_03', template_text: 'What would {actor} observe if {actor} stepped back from this?', template_type: 'reflection' },
    ],
    target_effect: 'pattern_visibility',
    typical_output_type: 'reflection',
    compatible_lock_types: ['identity_lock', 'emotional_lock', 'possibility_lock'],
    compatible_emotion_channels: ['fear', 'anger', 'sadness', 'neutrality', 'joy'],
    compatible_nations: [],
    compatible_archetypes: [],
    bar_integration: { creates_bar: false, optional_tracking_bar: true, bar_timing: 'pre_action', bar_prompt_template: 'Note what you\'re observing about {object}.' },
    quest_usage: { quest_stage: 'reflection', is_required_for_full_arc: false, can_stand_alone: true, suggested_follow_up_moves: ['name', 'externalize'] },
    safety_notes: ['Low intensity. Safe for all contexts.'],
  },
  {
    move_id: 'name',
    move_name: 'Name',
    move_category: 'awareness',
    wcgs_stage: 'wake_up',
    description: 'Turn vague experience into explicit language.',
    purpose: 'Clarify what is being experienced so it can be addressed.',
    prompt_templates: [
      { template_id: 'name_basic_01', template_text: 'What would you call {state} if you had to name it?', template_type: 'reflection' },
      { template_id: 'name_basic_02', template_text: 'What is the clearest way to describe what {actor} feels about {object}?', template_type: 'reflection' },
      { template_id: 'name_basic_03', template_text: 'If {state} had a label, what would it be?', template_type: 'reflection' },
    ],
    target_effect: 'narrative_clarification',
    typical_output_type: 'reflection',
    compatible_lock_types: ['emotional_lock', 'identity_lock', 'possibility_lock'],
    compatible_emotion_channels: ['fear', 'anger', 'sadness', 'neutrality', 'joy'],
    compatible_nations: [],
    compatible_archetypes: [],
    bar_integration: { creates_bar: false, optional_tracking_bar: true },
    quest_usage: { quest_stage: 'reflection', is_required_for_full_arc: false, can_stand_alone: true, suggested_follow_up_moves: ['externalize', 'feel'] },
    safety_notes: ['Low intensity.'],
  },
  {
    move_id: 'externalize',
    move_name: 'Externalize',
    move_category: 'emotional_processing',
    wcgs_stage: 'clean_up',
    description: 'Separate the pattern from identity.',
    purpose: 'Create distance between self and stuck narrative.',
    prompt_templates: [
      { template_id: 'externalize_basic_01', template_text: 'If {state} could speak, what would it say about {object}?', template_type: 'dialogue' },
      { template_id: 'externalize_basic_02', template_text: 'What if {state} were a character separate from {actor}? What would that character want?', template_type: 'dialogue' },
      { template_id: 'externalize_basic_03', template_text: 'Imagine {state} as something outside you. What does it look like?', template_type: 'reflection' },
    ],
    target_effect: 'identity_distance',
    typical_output_type: 'dialogue',
    compatible_lock_types: ['identity_lock', 'emotional_lock'],
    compatible_emotion_channels: ['fear', 'anger', 'sadness', 'neutrality', 'joy'],
    compatible_nations: [],
    compatible_archetypes: [],
    bar_integration: { creates_bar: false },
    quest_usage: { quest_stage: 'cleanup', is_required_for_full_arc: false, can_stand_alone: false, suggested_follow_up_moves: ['feel', 'reframe'] },
    safety_notes: ['May surface shadow material. Ensure player has choice to pause.'],
  },
  {
    move_id: 'feel',
    move_name: 'Feel',
    move_category: 'emotional_processing',
    wcgs_stage: 'clean_up',
    description: 'Connect insight to embodied emotional awareness.',
    purpose: 'Ground cognitive work in somatic experience.',
    prompt_templates: [
      { template_id: 'feel_basic_01', template_text: 'Where in your body do you feel {state} when you think about {object}?', template_type: 'somatic' },
      { template_id: 'feel_basic_02', template_text: 'What does {state} feel like in this moment—not the story, the sensation?', template_type: 'somatic' },
      { template_id: 'feel_channel_01', template_text: 'If {emotion_channel} had a shape or temperature, what would it be right now?', template_type: 'somatic' },
    ],
    target_effect: 'embodied_awareness',
    typical_output_type: 'somatic',
    compatible_lock_types: ['emotional_lock', 'identity_lock'],
    compatible_emotion_channels: ['fear', 'anger', 'sadness', 'neutrality', 'joy'],
    compatible_nations: [],
    compatible_archetypes: [],
    bar_integration: { creates_bar: false },
    quest_usage: { quest_stage: 'cleanup', is_required_for_full_arc: false, can_stand_alone: false, suggested_follow_up_moves: ['externalize', 'reframe'] },
    safety_notes: ['May surface intense emotion. Ensure player has choice to pause or skip.', 'Works best after Observe or Name.'],
  },
  {
    move_id: 'reframe',
    move_name: 'Reframe',
    move_category: 'reframing',
    wcgs_stage: 'grow_up',
    description: 'Change interpretation of the experience.',
    purpose: 'Shift meaning without denying the experience.',
    prompt_templates: [
      { template_id: 'reframe_basic_01', template_text: 'What might {object} be trying to teach you?', template_type: 'reflection' },
      { template_id: 'reframe_basic_02', template_text: 'What if {state} about {object} were a signal rather than a problem?', template_type: 'reflection' },
      { template_id: 'reframe_basic_03', template_text: 'What perspective might balance this situation?', template_type: 'reflection' },
    ],
    target_effect: 'meaning_shift',
    typical_output_type: 'reflection',
    compatible_lock_types: ['identity_lock', 'possibility_lock', 'emotional_lock'],
    compatible_emotion_channels: ['fear', 'anger', 'sadness', 'neutrality', 'joy'],
    compatible_nations: [],
    compatible_archetypes: [],
    bar_integration: { creates_bar: false },
    quest_usage: { quest_stage: 'growth', is_required_for_full_arc: false, can_stand_alone: false, suggested_follow_up_moves: ['invert', 'experiment'] },
    safety_notes: ['Avoid invalidating the experience. Reframe adds perspective; does not erase.'],
  },
  {
    move_id: 'invert',
    move_name: 'Invert',
    move_category: 'reframing',
    wcgs_stage: 'grow_up',
    description: 'Disrupt fixed assumptions.',
    purpose: 'Challenge rigid beliefs or identity claims.',
    prompt_templates: [
      { template_id: 'invert_basic_01', template_text: 'What if the opposite were true about {object}?', template_type: 'reflection' },
      { template_id: 'invert_basic_02', template_text: 'What would have to be true for {actor} to feel differently about {object}?', template_type: 'reflection' },
      { template_id: 'invert_basic_03', template_text: 'What assumption are you holding that, if released, would change this?', template_type: 'reflection' },
    ],
    target_effect: 'assumption_disruption',
    typical_output_type: 'reflection',
    compatible_lock_types: ['action_lock', 'possibility_lock', 'identity_lock'],
    compatible_emotion_channels: ['fear', 'anger', 'sadness', 'neutrality', 'joy'],
    compatible_nations: [],
    compatible_archetypes: [],
    bar_integration: { creates_bar: false },
    quest_usage: { quest_stage: 'growth', is_required_for_full_arc: false, can_stand_alone: false, suggested_follow_up_moves: ['reframe', 'experiment'] },
    safety_notes: ['Can feel destabilizing. Best after Observe/Name and Clean Up moves.'],
  },
  {
    move_id: 'experiment',
    move_name: 'Experiment',
    move_category: 'behavioral_experiment',
    wcgs_stage: 'show_up',
    description: 'Create a small behavioral test.',
    purpose: 'Translate insight into real-world action.',
    prompt_templates: [
      { template_id: 'experiment_basic_01', template_text: 'What is one small action where {object} is allowed?', template_type: 'action' },
      { template_id: 'experiment_basic_02', template_text: 'What could {actor} try in the next 72 hours that would test this?', template_type: 'action' },
      { template_id: 'experiment_basic_03', template_text: "What's the smallest experiment you could run with {object}?", template_type: 'action' },
    ],
    target_effect: 'behavioral_activation',
    typical_output_type: 'action',
    compatible_lock_types: ['action_lock', 'possibility_lock', 'identity_lock'],
    compatible_emotion_channels: ['fear', 'anger', 'sadness', 'neutrality', 'joy'],
    compatible_nations: [],
    compatible_archetypes: [],
    bar_integration: { creates_bar: true, bar_timing: 'post_action', bar_type: 'insight', bar_prompt_template: 'What did you learn from trying {object}?' },
    quest_usage: { quest_stage: 'action', is_required_for_full_arc: false, can_stand_alone: false, suggested_follow_up_moves: ['integrate'] },
    safety_notes: ['Action should be executable within 72 hours.', 'Must reduce avoidance, not reinforce it.'],
  },
  {
    move_id: 'integrate',
    move_name: 'Integrate',
    move_category: 'integration',
    wcgs_stage: 'show_up',
    description: 'Capture learning and convert it into retained value.',
    purpose: 'Anchor transformation in a durable artifact.',
    prompt_templates: [
      { template_id: 'integrate_basic_01', template_text: 'Capture what you learned from {object}.', template_type: 'integration' },
      { template_id: 'integrate_basic_02', template_text: 'What insight would you keep from this experience?', template_type: 'integration' },
      { template_id: 'integrate_basic_03', template_text: 'If you were to create a BAR from this, what would it say?', template_type: 'integration' },
    ],
    target_effect: 'value_capture',
    typical_output_type: 'integration',
    compatible_lock_types: ['identity_lock', 'emotional_lock', 'action_lock', 'possibility_lock'],
    compatible_emotion_channels: ['fear', 'anger', 'sadness', 'neutrality', 'joy'],
    compatible_nations: [],
    compatible_archetypes: [],
    bar_integration: { creates_bar: true, bar_timing: 'completion', bar_type: 'insight', bar_prompt_template: 'Capture what you learned from {object}.' },
    quest_usage: { quest_stage: 'completion', is_required_for_full_arc: true, can_stand_alone: false, suggested_follow_up_moves: [] },
    safety_notes: ['Integration completes the arc. Ensure preceding moves have been processed.'],
  },
]
