'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { AllyshipCard } from '@/components/deck/AllyshipCard'
import { WAKE_UP_PRACTICES } from '@/lib/mtgoa-course/course-days'
import type { MoveCard } from '@/lib/allyship-deck/types'

type Screen = 'entry' | 'q1' | 'q2' | 'q3' | 'q4' | 'q5' | 'q6' | 'draw' | 'receipt'
type Answers = { creation: string; satisfaction: string; direction: string | null; dissatisfaction: string; worldview: string; reservation: string | null }

const RESERVATIONS = ['I’m not good enough', 'I’m not ready', 'I don’t belong', 'I’m insignificant', 'I’m not worthy', 'I’m not capable']

function drawThree() {
  const cards = [...WAKE_UP_PRACTICES]
  for (let index = cards.length - 1; index > 0; index -= 1) {
    const swap = Math.floor(Math.random() * (index + 1))
    ;[cards[index], cards[swap]] = [cards[swap], cards[index]]
  }
  return cards.slice(0, 3)
}

export function WakeUpIntake({ courseRound = 1 }: { courseRound?: number }) {
  const day = (courseRound - 1) * 5 + 1
  const [screen, setScreen] = useState<Screen>('entry')
  const [answers, setAnswers] = useState<Answers>({ creation: '', satisfaction: '', direction: null, dissatisfaction: '', worldview: '', reservation: null })
  const [draw, setDraw] = useState<MoveCard[]>(drawThree)
  const [selectedCard, setSelectedCard] = useState<MoveCard | null>(null)
  const [expandedCard, setExpandedCard] = useState<MoveCard | null>(null)
  const write = (key: keyof Answers, value: string | null) => setAnswers((current) => ({ ...current, [key]: value }))
  const back = () => setScreen((current) => ({ q1: 'entry', q2: 'q1', q3: 'q2', q4: 'q3', q5: 'q4', q6: 'q5', draw: 'q6', receipt: 'draw', entry: 'entry' })[current] as Screen)
  const restart = () => { setAnswers({ creation: '', satisfaction: '', direction: null, dissatisfaction: '', worldview: '', reservation: null }); setDraw(drawThree()); setSelectedCard(null); setScreen('entry') }

  return <main className="min-h-screen bg-[#0b0910] px-4 py-7 text-[#ded7e4] sm:px-6 sm:py-10" style={{ fontFamily: 'var(--bars-font-body)' }}>
    <div className="mx-auto max-w-2xl"><header className="mb-9 flex items-center justify-between border-b border-white/10 pb-4 text-[10px] font-bold uppercase tracking-[0.2em] text-[#b7aabf]" style={{ fontFamily: 'var(--bars-font-mono)' }}><span>Mastering the Game of Allyship</span><span>Day {day} · Wake Up</span></header>
      <section className="overflow-hidden rounded-[28px] border border-[#513d58] bg-[radial-gradient(110%_95%_at_50%_-10%,#321e40,#17111d_62%,#100d14)] p-6 shadow-2xl shadow-black/40 sm:p-10">
        {screen === 'entry' ? <><Heading eyebrow="Six questions for what is actually happening" title="Wake up to your own allyship.">This is not a quiz and it does not tell you who you are. It gives you a way to see the creation you want, the life you are living now, and the reservation that may be narrowing your next move.</Heading><button type="button" onClick={() => setScreen('q1')} className="mt-8 w-full rounded-2xl bg-gradient-to-r from-[#ff73b1] to-[#e7a851] px-5 py-4 text-left font-bold text-[#1b1018]">Begin the six questions →</button></> : null}
        {screen === 'q1' ? <TextQuestion number={1} title="What experience do you want to create?" body="What kind of allyship do you want to do? Who do you want to help? Name a real experience you want to create, not a trait you think you should have." value={answers.creation} onChange={(value) => write('creation', value)} onBack={back} onNext={() => setScreen('q2')} placeholder="I want to…" /> : null}
        {screen === 'q2' ? <TextQuestion number={2} title="What will that get you?" body="If that experience existed, what satisfied emotion would it make available? Use your own word. This is about what becomes possible, not about performing the right feeling." value={answers.satisfaction} onChange={(value) => write('satisfaction', value)} onBack={back} onNext={() => setScreen('q3')} placeholder="It would let me feel…" /> : null}
        {screen === 'q3' ? <ChoiceQuestion number={3} title="Compared to that, what’s life like right now?" body="Choose the direction that is closest. This is a reading of the present, not a forecast." choices={['Flowing in the right direction', 'Stuck', 'Moving backward']} value={answers.direction} onChange={(value) => write('direction', value)} onBack={back} onNext={() => setScreen('q4')} /> : null}
        {screen === 'q4' ? <TextQuestion number={4} title="How does it feel to live here?" body="Name the dissatisfied emotional state that is actually present. You can be plain; this is for your own contact with the situation." value={answers.dissatisfaction} onChange={(value) => write('dissatisfaction', value)} onBack={back} onNext={() => setScreen('q5')} placeholder="Living here feels…" /> : null}
        {screen === 'q5' ? <TextQuestion number={5} title="What would have to be true for someone to feel this way?" body="Let the worldview beneath the feeling speak. What condition, risk, rule, or history would make this feeling make sense?" value={answers.worldview} onChange={(value) => write('worldview', value)} onBack={back} onNext={() => setScreen('q6')} placeholder="For this to make sense, it would have to be true that…" /> : null}
        {screen === 'q6' ? <ChoiceQuestion number={6} title="What reservations do you have about your creation?" body="One of these may be interrupting the move. It is a reservation to work with, not a diagnosis or a fact about you." choices={RESERVATIONS} value={answers.reservation} onChange={(value) => write('reservation', value)} onBack={back} onNext={() => setScreen('draw')} /> : null}
        {screen === 'draw' ? <><Back onClick={back} /><Heading eyebrow="A practice from the Allyship Deck" title="Draw a Wake Up card, or keep the map you made.">All 24 Wake Up cards are in the draw. A card is an invitation to notice more clearly, not a verdict about you.</Heading><div className="mt-6 grid gap-4 sm:grid-cols-3">{draw.map((card) => <div key={card.id} className={selectedCard?.id === card.id ? 'rounded-xl outline outline-2 outline-[#ff9fca] outline-offset-4' : ''}><AllyshipCard card={card} variant="grid" onClick={() => setExpandedCard(card)} /></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => { setDraw(drawThree()); setSelectedCard(null) }} className="rounded-2xl border border-white/15 px-5 py-4 font-bold text-[#f1dce8]">Draw three more</button><button type="button" onClick={() => setScreen('receipt')} className="rounded-2xl bg-[#f3e5ed] px-5 py-4 font-bold text-[#251525]">{selectedCard ? 'Continue with this card →' : 'Skip the draw →'}</button></div></> : null}
        {screen === 'receipt' ? <><Back onClick={back} /><Heading eyebrow="Your receipt" title="You made awareness.">You now have a map of what you want to create, where you are, and what may be holding the charge. Tomorrow, Open Up asks whether you can make a little room for it.</Heading><div className="mt-6 rounded-2xl border border-[#765b70] bg-black/15 p-4 text-sm leading-6 text-[#e8dce8]"><ReceiptRow label="Creation" value={answers.creation} /><ReceiptRow label="What it would get you" value={answers.satisfaction} /><ReceiptRow label="Current direction" value={answers.direction} /><ReceiptRow label="Current feeling" value={answers.dissatisfaction} /><ReceiptRow label="What would have to be true" value={answers.worldview} /><ReceiptRow label="Reservation" value={answers.reservation} />{selectedCard ? <><p className="mt-4 text-[10px] font-bold uppercase tracking-[.18em] text-[#b7aabf]" style={{ fontFamily: 'var(--bars-font-mono)' }}>Your card</p><p className="mt-2 font-bold text-white">{selectedCard.title}</p><p className="mt-1 text-[#c9bdcd]">{selectedCard.remediation}</p></> : null}</div><Link href={`/mastering-allyship/course/${courseRound}/open-up`} className="mt-6 block rounded-2xl border border-[#ff9fca] px-5 py-4 text-center font-bold text-[#ffd6e8]">Continue to Day {day + 1}: Open Up →</Link><button type="button" onClick={restart} className="mt-5 w-full text-sm text-[#bcaec0] underline underline-offset-4">Start again</button></> : null}
      </section><p className="mx-auto mt-5 max-w-xl text-center text-xs leading-5 text-[#a99daa]">Your answers stay only in this active page. Course-answer persistence is intentionally off.</p>
    </div>{expandedCard ? <CardModal card={expandedCard} onClose={() => setExpandedCard(null)} onChoose={() => { setSelectedCard(expandedCard); setExpandedCard(null) }} /> : null}
  </main>
}

function Heading({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div><p className="text-[11px] font-bold uppercase tracking-[.24em] text-[#ff9fca]" style={{ fontFamily: 'var(--bars-font-mono)' }}>{eyebrow}</p><h1 className="mt-3 text-3xl font-bold text-white sm:text-4xl" style={{ fontFamily: 'var(--bars-font-display)' }}>{title}</h1><p className="mt-3 leading-7 text-[#d0c6d5]">{children}</p></div> }
function Back({ onClick }: { onClick: () => void }) { return <button type="button" onClick={onClick} className="mb-5 text-sm text-[#c9bdcd] underline underline-offset-4">← Back</button> }
function TextQuestion({ number, title, body, value, onChange, onBack, onNext, placeholder }: { number: number; title: string; body: string; value: string; onChange: (value: string) => void; onBack: () => void; onNext: () => void; placeholder: string }) { return <><Back onClick={onBack} /><Heading eyebrow={`Six questions · ${number} of 6`} title={title}>{body}</Heading><textarea value={value} onChange={(event) => onChange(event.target.value)} rows={6} placeholder={placeholder} className="mt-6 w-full rounded-2xl border border-[#765b70] bg-black/20 p-4 text-sm leading-6 text-[#eee3f0] outline-none focus:border-[#ff9fca]" /><button type="button" onClick={onNext} className="mt-6 w-full rounded-2xl bg-[#f3e5ed] px-5 py-4 font-bold text-[#251525]">Continue →</button></> }
function ChoiceQuestion({ number, title, body, choices, value, onChange, onBack, onNext }: { number: number; title: string; body: string; choices: string[]; value: string | null; onChange: (value: string) => void; onBack: () => void; onNext: () => void }) { return <><Back onClick={onBack} /><Heading eyebrow={`Six questions · ${number} of 6`} title={title}>{body}</Heading><div className="mt-6 grid gap-2">{choices.map((choice) => <button type="button" key={choice} onClick={() => onChange(choice)} className={'rounded-2xl border p-4 text-left text-sm ' + (value === choice ? 'border-[#ff9fca] bg-[#3c2036] text-white' : 'border-white/15 bg-black/10 text-[#e6dae6]')}>{choice}</button>)}</div><button type="button" onClick={onNext} className="mt-6 w-full rounded-2xl bg-[#f3e5ed] px-5 py-4 font-bold text-[#251525]">Continue →</button></> }
function ReceiptRow({ label, value }: { label: string; value: string | null }) { return value ? <><p className="mt-4 text-[10px] font-bold uppercase tracking-[.18em] text-[#b7aabf]" style={{ fontFamily: 'var(--bars-font-mono)' }}>{label}</p><p className="mt-1 whitespace-pre-wrap">{value}</p></> : null }
function CardModal({ card, onClose, onChoose }: { card: MoveCard; onClose: () => void; onChoose: () => void }) { useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [onClose]); return <div role="dialog" aria-modal="true" aria-label={card.title} className="fixed inset-0 z-50 flex items-end bg-black/80 p-3 backdrop-blur-sm sm:items-center sm:p-8" onMouseDown={onClose}><div className="mx-auto flex max-h-[96dvh] w-full max-w-lg flex-col rounded-t-[28px] bg-[#120d17] p-4 shadow-2xl sm:rounded-[28px]" onMouseDown={(event) => event.stopPropagation()}><div className="mb-3 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.18em] text-[#c9bdcd]" style={{ fontFamily: 'var(--bars-font-mono)' }}>Drawn card</span><button type="button" onClick={onClose} className="rounded-full border border-white/15 px-3 py-1 text-sm text-[#f2e6f0]">Close</button></div><div className="min-h-0 overflow-y-auto px-1 pb-2"><AllyshipCard card={card} variant="full" /></div><button type="button" onClick={onChoose} className="mt-4 shrink-0 rounded-2xl bg-[#f3e5ed] px-5 py-4 font-bold text-[#251525]">Choose this card →</button></div></div> }
