/**
 * Allyship Deck — canonical move-library data (ADK Phase 1).
 * Authoritative grammar: .specify/specs/allyship-deck/move-library-core-rules.md
 *
 * 5 Basic Moves × 6 Operations × 4 Domains = 120 move cards.
 * The 30 submoves (move × operation) are transcribed verbatim from the core rules.
 */

import type {
  BasicMove,
  Operation,
  AllyshipDomain,
  Capability,
  Channel,
  OutputBar,
  MoveCard,
} from './types'

export interface MoveDef {
  key: BasicMove
  label: string
  abbr: string // id segment
  purpose: string
  question: string
  outputBar: OutputBar
  /** seed stem for the campaign-register question */
  campaignStem: string
}

export const MOVES: MoveDef[] = [
  { key: 'wake_up', label: 'Wake Up', abbr: 'WAKE', purpose: 'Detect charge', question: 'What is happening?', outputBar: 'awareness', campaignStem: 'What needs to be seen in this campaign' },
  { key: 'open_up', label: 'Open Up', abbr: 'OPEN', purpose: 'Receive charge', question: 'What energy is trying to get through?', outputBar: 'experience', campaignStem: 'What energy or need is trying to get through in this campaign' },
  { key: 'clean_up', label: 'Clean Up', abbr: 'CLEAN', purpose: 'Transform charge', question: 'What move is missing?', outputBar: 'insight', campaignStem: 'What move is missing for this campaign' },
  { key: 'grow_up', label: 'Grow Up', abbr: 'GROW', purpose: 'Develop capability', question: 'Who must I become?', outputBar: 'wisdom', campaignStem: 'What capacity must we build for this campaign' },
  { key: 'show_up', label: 'Show Up', abbr: 'SHOW', purpose: 'Invest capacity', question: 'What shall I create?', outputBar: 'artifact', campaignStem: 'What must we create or do for this campaign' },
]

export interface OperationDef {
  key: Operation
  label: string
  verb: string
  essence: string
}

export const OPERATIONS: OperationDef[] = [
  { key: 'shaman', label: 'Shaman', verb: 'Notice', essence: 'What is here?' },
  { key: 'challenger', label: 'Challenger', verb: 'Challenge', essence: 'What resists?' },
  { key: 'regent', label: 'Regent', verb: 'Steward', essence: 'What deserves responsibility?' },
  { key: 'architect', label: 'Architect', verb: 'Amplify', essence: 'What value wants to be increased?' },
  { key: 'diplomat', label: 'Diplomat', verb: 'Care', essence: 'What relationships or power dynamics matter?' },
  { key: 'sage', label: 'Sage', verb: 'Integrate', essence: 'What larger truth is emerging?' },
]

export interface DomainDef {
  key: AllyshipDomain
  label: string
  abbr: string
  /** the domain's contextual lens (what this domain is about) */
  lens: string
}

export const DOMAINS: DomainDef[] = [
  { key: 'GATHERING_RESOURCES', label: 'Gather Resources', abbr: 'GR', lens: 'need, asking, and marshaling resources' },
  { key: 'RAISE_AWARENESS', label: 'Raise Awareness', abbr: 'RA', lens: 'attention, truth, and what must become visible' },
  { key: 'DIRECT_ACTION', label: 'Direct Action', abbr: 'DA', lens: 'the line, intervention, and what must change' },
  { key: 'SKILLFUL_ORGANIZING', label: 'Skillful Organizing', abbr: 'SO', lens: 'structure, coordination, and who does what' },
]

export interface CapabilityDef {
  capability: Capability
  channel: Channel
  channelLabel: string
  dissatisfied: string
  satisfaction: string
  statement: string
}

export const CAPABILITIES: CapabilityDef[] = [
  { capability: 'agency', channel: 'fire', channelLabel: 'Fire', dissatisfied: 'Anger', satisfaction: 'Triumph', statement: 'I can act.' },
  { capability: 'connection', channel: 'water', channelLabel: 'Water', dissatisfied: 'Sadness', satisfaction: 'Poignance', statement: 'I can connect.' },
  { capability: 'exploration', channel: 'metal', channelLabel: 'Metal', dissatisfied: 'Fear', satisfaction: 'Wonder', statement: 'I can explore.' },
  { capability: 'rest', channel: 'earth', channelLabel: 'Earth', dissatisfied: 'Neutrality', satisfaction: 'Peace', statement: 'I can rest.' },
  { capability: 'participation', channel: 'wood', channelLabel: 'Wood', dissatisfied: 'Joy (stuck)', satisfaction: 'Bliss', statement: 'I can participate.' },
]

/** The 30 canonical submoves — verbatim from move-library-core-rules.md. */
export const SUBMOVES: Record<BasicMove, Record<Operation, { action: string; question: string }>> = {
  wake_up: {
    shaman: { action: 'Notice the signal', question: 'What is here?' },
    challenger: { action: 'Notice resistance', question: 'What resists being seen?' },
    regent: { action: 'Notice stewardship', question: 'What deserves attention?' },
    architect: { action: 'Notice potential', question: 'What value wants to increase?' },
    diplomat: { action: 'Notice relationships', question: 'What relational dynamics matter?' },
    sage: { action: 'Notice meaning', question: 'What larger pattern is emerging?' },
  },
  open_up: {
    shaman: { action: 'Allow experience', question: 'What am I actually feeling?' },
    challenger: { action: 'Allow discomfort', question: 'What am I avoiding feeling?' },
    regent: { action: 'Hold responsibility', question: 'Can I stay with this?' },
    architect: { action: 'Receive the resource', question: 'What energy is hidden here?' },
    diplomat: { action: 'Care for experience', question: 'How can I relate compassionately to this?' },
    sage: { action: 'Witness experience', question: 'What happens when I stop fighting it?' },
  },
  clean_up: {
    shaman: { action: 'Identify channel', question: 'Which channel is active — Fire, Water, Metal, Earth, or Wood?' },
    challenger: { action: 'Challenge interpretation', question: 'What story am I believing?' },
    regent: { action: 'Identify missing move', question: 'What capability is unavailable?' },
    architect: { action: 'Select transformation', question: 'Transcend, Translate, or Neutralize?' },
    diplomat: { action: 'Choose destination', question: 'Which channel would better serve this situation?' },
    sage: { action: 'Extract insight', question: 'What does this teach me?' },
  },
  grow_up: {
    shaman: { action: 'Identify emerging capacity', question: 'What wants to grow?' },
    challenger: { action: 'Identify developmental edge', question: 'What must evolve?' },
    regent: { action: 'Steward growth', question: 'What deserves practice?' },
    architect: { action: 'Amplify capacity', question: 'What capability wants strengthening?' },
    diplomat: { action: 'Relate growth', question: 'How does this affect others?' },
    sage: { action: 'Integrate growth', question: 'Who am I becoming?' },
  },
  show_up: {
    shaman: { action: 'Choose domain', question: 'Where will I invest this?' },
    challenger: { action: 'Create intervention', question: 'What must change?' },
    regent: { action: 'Create stewardship', question: 'What deserves ongoing support?' },
    architect: { action: 'Create structure', question: 'What value am I amplifying?' },
    diplomat: { action: 'Create relationship', question: 'Who must be involved? What power dynamic must be addressed?' },
    sage: { action: 'Create legacy', question: 'What artifact remains?' },
  },
}

/**
 * Authored overrides — fully written cards that replace the generated scaffold.
 * Keyed by card id. The Open Up × Gathering Resources slice (the worked template).
 */
export const AUTHORED: Record<string, Partial<MoveCard>> = {
  'OPEN-GR-SHAMAN': {
    title: 'The Empty Cup',
    primaryQuestion: 'What does the lack actually feel like in my body, before I reach for a plan?',
    campaignQuestion: 'What does their need actually feel like — and what dignity sits beneath the dollar amount?',
    optimizesFor: 'Honest contact with the felt sense of need, so resourcing starts from truth, not panic.',
    forbiddenMoves: ['Jumping straight to a budget or plan', 'Numbing the need', "Performing abundance you don't feel"],
    failureModes: ['Spiritual bypass ("I don\'t really need anything")', 'Scarcity panic', 'Talking about "the money" with no body in it'],
    remediation: 'Name the sensation of lack out loud — where it sits in the body — before you make a single ask.',
    flavor: 'The child holding the empty cup is not a problem to solve yet. First, let yourself see the cup.',
    capabilities: ['connection', 'rest'],
  },
  'OPEN-GR-CHALLENGER': {
    title: "The Ask You're Avoiding",
    primaryQuestion: 'What resource am I afraid to ask for — and what am I avoiding feeling about needing it?',
    campaignQuestion: 'What ask for them am I avoiding — and whose comfort am I protecting by not making it?',
    optimizesFor: 'Contact with the avoided discomfort of dependence; surfacing the real ask under the safe one.',
    forbiddenMoves: ['Rescuing yourself just to avoid asking', 'Self-sufficiency performance', 'Resentment in place of a request'],
    failureModes: ['Fake asking (asking for rescue, not to be changed)', 'Martyrdom', 'Saying "no" for people before they can answer'],
    remediation: 'Feel the "no" you\'re bracing against. Make the real ask anyway — for the thing you actually need.',
    flavor: 'It never worked because the asking was fake. It was asking for rescue, not asking to be changed.',
    capabilities: ['agency', 'connection'],
  },
  'OPEN-GR-REGENT': {
    title: 'Stay With the Need',
    primaryQuestion: 'Can I hold this need as mine to steward — without collapsing into helplessness or dumping it on someone else?',
    campaignQuestion: 'Can I steward their need without making it my emergency — or quietly taking it over?',
    optimizesFor: 'Staying present and responsible to the gap long enough to act from steadiness.',
    forbiddenMoves: ["Making your need someone else's emergency", 'Abdicating it entirely', 'Grabbing total control to feel safe'],
    failureModes: ['Helplessness handoff', 'Savior-summoning', 'White-knuckling it alone'],
    remediation: 'Hold the need for sixty seconds without solving it. Then choose one stewarding act you can own.',
    capabilities: ['agency', 'rest'],
  },
  'OPEN-GR-ARCHITECT': {
    title: 'The Hidden Supply',
    primaryQuestion: "What resource is already within reach that I haven't let myself receive?",
    campaignQuestion: "What resource or network for this campaign is already available that I haven't activated yet?",
    optimizesFor: 'Perceiving latent and available resources — skills, relationships, slack, standing offers.',
    forbiddenMoves: ['Hoarding', 'Discounting what\'s offered', 'The reflexive "it\'s not enough"'],
    failureModes: ['Scarcity blindness', 'Refusing help that\'s right there', 'Over-counting the future while starving the present'],
    remediation: 'List three resources already within reach. Receive one of them today.',
    capabilities: ['exploration', 'participation'],
  },
  'OPEN-GR-DIPLOMAT': {
    title: 'The Tenderness of Asking',
    primaryQuestion: "How can I relate to this need — mine and others' — with care instead of shame or scorekeeping?",
    campaignQuestion: 'Did they consent to this ask — and how do I invite givers without shaming the person or the givers?',
    optimizesFor: 'A compassionate relational stance toward resource flow; giving and receiving without debt-shame.',
    forbiddenMoves: ['Transactional scorekeeping', 'Leveraging guilt', 'Pity dressed as generosity'],
    failureModes: ['Obligation webs', 'Charity-as-power-over', 'Resentment-laden giving'],
    remediation: 'Offer or receive one resource with no strings — and say "no strings" out loud.',
    capabilities: ['connection', 'participation'],
  },
  'OPEN-GR-SAGE': {
    title: 'When You Stop Fighting the Lack',
    primaryQuestion: 'What becomes clear about this need when I stop fighting it and simply witness it?',
    campaignQuestion: 'When I stop forcing the campaign, what does it reveal it actually needs?',
    optimizesFor: 'Integrated seeing of the resource pattern — the larger truth about what the need is really about.',
    forbiddenMoves: ['Forcing the insight', 'Bypassing into "it\'s all fine"', 'Premature meaning-making'],
    failureModes: ['Spiritual gloss', 'Passivity disguised as acceptance', 'Analysis standing in for witness'],
    remediation: 'Watch the lack for three breaths without fixing it. Write the one true sentence that surfaces.',
    capabilities: ['exploration', 'connection'],
  },

  // ── WAKE UP × Gathering Resources (Detect charge → Awareness) ──
  'WAKE-GR-SHAMAN': {
    title: "What's Actually Scarce",
    primaryQuestion: 'What is actually depleted here — and what only feels depleted?',
    campaignQuestion: 'What does this effort actually lack — money, time, hands, or hope?',
    optimizesFor: 'Seeing the real resource gap before reacting to the felt one.',
    forbiddenMoves: ['Assuming scarcity without looking', 'Counting only money', 'Panic-inventory'],
    failureModes: ['Confusing "I\'m tired" with "we\'re broke"', 'Resource tunnel-vision'],
    remediation: 'Name the one resource that, if present, would change everything.',
    flavor: 'Not every empty cup is the same cup.',
    capabilities: ['exploration', 'rest'],
  },
  'WAKE-GR-CHALLENGER': {
    title: "The Number You Won't Look At",
    primaryQuestion: 'What resource truth am I refusing to look at directly?',
    campaignQuestion: 'What number are we avoiding — the real cost, the real shortfall?',
    optimizesFor: 'Surfacing the avoided figure so planning can be honest.',
    forbiddenMoves: ['Vague "we\'ll figure it out"', 'Rounding away the gap', 'Magical thinking'],
    failureModes: ['Optimism as avoidance', 'Budgets that omit the scary line'],
    remediation: 'Write the exact amount needed. Look at it for ten seconds.',
    capabilities: ['exploration', 'agency'],
  },
  'WAKE-GR-REGENT': {
    title: "What's Worth Funding",
    primaryQuestion: 'Of all that is depleted, what actually deserves resourcing first?',
    campaignQuestion: 'What in this campaign most deserves the resources we can gather?',
    optimizesFor: 'Prioritizing the resource need that matters most.',
    forbiddenMoves: ['Funding the loudest need', 'Spreading thin', 'Neglecting the core'],
    failureModes: ['Resourcing optics over substance', 'Everything is "priority"'],
    remediation: 'Rank the top three needs. Fund the first before the rest.',
    capabilities: ['rest', 'agency'],
  },
  'WAKE-GR-ARCHITECT': {
    title: 'The Untapped Vein',
    primaryQuestion: 'What resource is already here, underused, waiting to be grown?',
    campaignQuestion: 'What asset does this campaign already have that we could multiply?',
    optimizesFor: 'Spotting latent resources with upside.',
    forbiddenMoves: ['Only seeing lack', "Ignoring what's already working", 'Sunk-cost gazing'],
    failureModes: ['Scarcity blindness to existing assets', 'Under-leveraging a strength'],
    remediation: 'Name one resource you already have that could double.',
    capabilities: ['exploration', 'participation'],
  },
  'WAKE-GR-DIPLOMAT': {
    title: 'Who Holds the Purse',
    primaryQuestion: 'Whose resources, trust, or permission actually shape this?',
    campaignQuestion: 'Who are the givers, gatekeepers, and stakeholders in this ask?',
    optimizesFor: 'Seeing the relational map of resource flow and power.',
    forbiddenMoves: ['Ignoring gatekeepers', 'Treating money as apolitical', 'Bypassing consent'],
    failureModes: ['Missing who controls access', 'Stepping on a key relationship'],
    remediation: 'List who must say yes for resources to move. Start there.',
    capabilities: ['connection', 'participation'],
  },
  'WAKE-GR-SAGE': {
    title: 'The Story the Lack Tells',
    primaryQuestion: 'What pattern does this scarcity reveal about how I resource my life?',
    campaignQuestion: 'What does this shortfall reveal about the larger system around it?',
    optimizesFor: 'Reading scarcity as a signal about a bigger pattern.',
    forbiddenMoves: ['Treating each shortfall as isolated', 'Bypassing into "abundance mindset"'],
    failureModes: ['Missing the recurring pattern', 'Spiritualizing systemic lack'],
    remediation: 'Ask whether this lack has happened before. Name the pattern.',
    capabilities: ['exploration', 'connection'],
  },

  // ── CLEAN UP × Gathering Resources (Transform charge → Insight) ──
  'CLEAN-GR-SHAMAN': {
    title: 'Name the Money Feeling',
    primaryQuestion: 'Which channel is live around this resource — fear, anger, sadness, numbness, or reach?',
    campaignQuestion: "What emotional channel is driving how we're resourcing this — and is it clean?",
    optimizesFor: 'Locating the active channel so the charge can move.',
    forbiddenMoves: ['Acting on the charge before naming it', 'Assuming it\'s "just logistics"'],
    failureModes: ['Fear masquerading as strategy', 'Anger budgeting'],
    remediation: 'Name the channel out loud: "This is fear / anger / sadness about money."',
    capabilities: ['exploration'],
  },
  'CLEAN-GR-CHALLENGER': {
    title: 'The Money Story',
    primaryQuestion: 'What story about deserving, scarcity, or worth am I treating as fact?',
    campaignQuestion: 'What limiting story — "we can\'t ask for that much" — are we believing?',
    optimizesFor: 'Exposing the inherited resource script.',
    forbiddenMoves: ['Defending the story', '"But it\'s true"', 'Identifying with the lack'],
    failureModes: ['Scarcity script as identity', 'Inherited shame as realism'],
    remediation: "Write the story as a sentence. Then write the version that isn't certain.",
    flavor: 'Inherited scripts run the budget until you read them aloud.',
    capabilities: ['agency', 'exploration'],
  },
  'CLEAN-GR-REGENT': {
    title: "The Capability You're Missing",
    primaryQuestion: 'Which capability is offline — can I not act, connect, explore, rest, or participate around this?',
    campaignQuestion: 'What capability does this campaign lack — agency to ask, connection to mobilize?',
    optimizesFor: 'Naming the missing capability behind the resource block.',
    forbiddenMoves: ['Adding tactics when the block is a missing capability', 'Willpower over capacity'],
    failureModes: ["Doing more of a move you can't yet make", 'Capability-blind planning'],
    remediation: "Match the block to a capability. That's the move to grow next.",
    capabilities: ['agency', 'rest'],
  },
  'CLEAN-GR-ARCHITECT': {
    title: 'Move the Charge',
    primaryQuestion: 'Do I transcend this feeling, translate it to another channel, or neutralize it?',
    campaignQuestion: "How do we convert this campaign's charge into usable fuel — transcend, translate, neutralize?",
    optimizesFor: 'Choosing the alchemical operation that frees resourcing.',
    forbiddenMoves: ['Suppressing the charge', 'Venting it onto others', 'Forcing positivity'],
    failureModes: ['Neutralizing what should be transcended', 'Dumping anger on donors'],
    remediation: 'Pick one: transcend (let it ripen), translate (e.g. fear → agency), or neutralize. Then do it.',
    capabilities: ['agency', 'connection'],
  },
  'CLEAN-GR-DIPLOMAT': {
    title: 'Fear Into Invitation',
    primaryQuestion: 'Which channel, if I moved this charge there, would serve the ask better?',
    campaignQuestion: 'What would the ask feel like if it came from connection instead of fear?',
    optimizesFor: 'Aiming the charge toward a relationally generative channel.',
    forbiddenMoves: ['Asking from resentment', 'Guilt-tripping', 'Performing calm'],
    failureModes: ['Fear-driven asks that repel', 'Manipulation dressed as warmth'],
    remediation: 'Re-aim the ask from Connection: invite people into something good.',
    capabilities: ['connection'],
  },
  'CLEAN-GR-SAGE': {
    title: 'What the Shortfall Taught',
    primaryQuestion: 'What does this resource struggle teach me that I can keep?',
    campaignQuestion: "What's the durable lesson this campaign's resourcing is offering?",
    optimizesFor: 'Converting the struggle into reusable insight (a BAR).',
    forbiddenMoves: ['Rushing past the lesson', '"Just get the money"', 'Premature closure'],
    failureModes: ["Repeating the lesson because it wasn't extracted", 'Hollow takeaways'],
    remediation: "Write one sentence you'll carry into the next ask.",
    capabilities: ['exploration', 'connection'],
  },

  // ── GROW UP × Gathering Resources (Develop capability → Wisdom) ──
  'GROW-GR-SHAMAN': {
    title: 'The Capacity Trying to Grow',
    primaryQuestion: 'What resourcing capacity in me is trying to grow right now?',
    campaignQuestion: 'What capability is this campaign asking us to develop?',
    optimizesFor: 'Noticing the growth edge the resource work is surfacing.',
    forbiddenMoves: ['Forcing growth', 'Skipping the seedling', "Importing someone else's path"],
    failureModes: ['Naming a capacity you wish for over the one actually emerging'],
    remediation: 'Name the capacity one size bigger than today. Practice it once.',
    capabilities: ['participation', 'exploration'],
  },
  'GROW-GR-CHALLENGER': {
    title: 'The Edge of the Ask',
    primaryQuestion: 'What must evolve in me to ask or steward at the next level?',
    campaignQuestion: 'What must the team learn to resource this at the scale it needs?',
    optimizesFor: 'Locating the precise developmental edge.',
    forbiddenMoves: ["Comfortable practice that isn't the edge", 'Busywork as growth'],
    failureModes: ['Training the strength, avoiding the edge', 'Pseudo-growth'],
    remediation: "Name the thing that scares you slightly. That's the edge — step to it.",
    capabilities: ['agency'],
  },
  'GROW-GR-REGENT': {
    title: 'Worth Practicing',
    primaryQuestion: 'Which resourcing skill deserves deliberate, repeated practice?',
    campaignQuestion: 'What practice should this campaign repeat until it is reliable?',
    optimizesFor: 'Committing to repeatable practice over one-off effort.',
    forbiddenMoves: ['Hoping skill appears', 'One-and-done', 'Practicing the wrong rep'],
    failureModes: ['Inconsistency', 'Stewarding everything so nothing deepens'],
    remediation: 'Choose one rep ("make one real ask weekly"). Schedule it.',
    capabilities: ['rest', 'agency'],
  },
  'GROW-GR-ARCHITECT': {
    title: 'Strengthen the Channel',
    primaryQuestion: 'Which existing capability, if strengthened, would unlock resourcing?',
    campaignQuestion: 'What capacity, amplified, would most increase what we can gather?',
    optimizesFor: 'Investing growth where it compounds.',
    forbiddenMoves: ['Spreading practice thin', 'Strengthening the irrelevant', 'Vanity skills'],
    failureModes: ['Growth without leverage', "Polishing a capability you don't need"],
    remediation: 'Pick the capability with the highest leverage. Train it deliberately.',
    capabilities: ['participation', 'exploration'],
  },
  'GROW-GR-DIPLOMAT': {
    title: 'Growing Without Leaving People',
    primaryQuestion: 'As I grow my capacity to resource, how does it land on the people around me?',
    campaignQuestion: 'How does scaling this campaign affect the relationships that carry it?',
    optimizesFor: 'Growing in a way that strengthens, not strains, relationships.',
    forbiddenMoves: ['Growth that burns helpers', 'Leaving people behind', 'Extractive scaling'],
    failureModes: ['Capacity gains that cost trust', 'Isolating success'],
    remediation: 'Name one person your growth affects. Bring them with you.',
    capabilities: ['connection', 'participation'],
  },
  'GROW-GR-SAGE': {
    title: 'Who Resourcing Is Making Me',
    primaryQuestion: 'Who am I becoming through learning to gather and steward resources?',
    campaignQuestion: 'What is this campaign making us, as a community, become?',
    optimizesFor: 'Integrating the identity shift the work is producing.',
    forbiddenMoves: ['Skipping reflection', 'Achievement without integration', 'A new mask'],
    failureModes: ['Capacity gained, self un-integrated', "Growth that doesn't stick"],
    remediation: 'Finish the sentence: "I am becoming someone who ______."',
    capabilities: ['connection', 'participation'],
  },

  // ── SHOW UP × Gathering Resources (Invest capacity → Artifact) ──
  'SHOW-GR-SHAMAN': {
    title: 'Aim the Resources',
    primaryQuestion: "Where exactly will I invest what I've gathered?",
    campaignQuestion: "Where will this campaign's resources actually go — concretely?",
    optimizesFor: 'Committing gathered resources to a specific target.',
    forbiddenMoves: ['Hoarding "until ready"', 'Vague allocation', 'Endless gathering'],
    failureModes: ['Resources that never deploy', 'Paralysis by optimization'],
    remediation: 'Name the first concrete place the resources go this week.',
    capabilities: ['agency'],
  },
  'SHOW-GR-CHALLENGER': {
    title: 'The Ask Goes Live',
    primaryQuestion: 'What concrete resourcing act must I take now?',
    campaignQuestion: 'What intervention launches the gather — the page, the ask, the event?',
    optimizesFor: 'Shipping the actual ask or intervention.',
    forbiddenMoves: ['One more prep step', 'Private readiness', 'Soft launch to no one'],
    failureModes: ['Perpetual pre-launch', 'The ask that never posts'],
    remediation: 'Post the ask today. Make it real and specific.',
    flavor: 'A proposal names the next step when no one else will.',
    capabilities: ['agency'],
  },
  'SHOW-GR-REGENT': {
    title: 'Hold the Funds Well',
    primaryQuestion: 'What ongoing stewardship will keep these resources trustworthy?',
    campaignQuestion: 'How will we steward and account for what is given — transparently?',
    optimizesFor: 'Building accountable stewardship of gathered resources.',
    forbiddenMoves: ['Opaque handling', 'Spending without record', 'Mission drift'],
    failureModes: ['Trust eroded by sloppiness', 'Funds without follow-through'],
    remediation: 'Set one transparency practice (a public update, a ledger). Keep it.',
    capabilities: ['rest', 'connection'],
  },
  'SHOW-GR-ARCHITECT': {
    title: 'Build the Ladder',
    primaryQuestion: 'What structure makes the resourcing repeatable and growing?',
    campaignQuestion: 'What structure — milestones, tiers, matches — amplifies this campaign?',
    optimizesFor: 'Creating structure that compounds resource flow.',
    forbiddenMoves: ['One-off heroics', 'Structure for its own sake', 'Over-engineering'],
    failureModes: ["A push that can't repeat", 'Scaffolding nobody uses'],
    remediation: 'Add one structural lever: a milestone ladder ($200 / $400 / $800) or a match.',
    capabilities: ['participation', 'agency'],
  },
  'SHOW-GR-DIPLOMAT': {
    title: "Invite, Don't Extract",
    primaryQuestion: 'Who must be invited, and what power dynamic must I name to do this cleanly?',
    campaignQuestion: 'Who do we invite to give — and whose consent and power must we honor?',
    optimizesFor: 'Resourcing through invitation and honored consent, not extraction.',
    forbiddenMoves: ['Pressuring givers', "Using someone's story without consent", 'Debt-making'],
    failureModes: ['Extraction dressed as community', 'Transactional asks that sour'],
    remediation: 'Invite one person with full consent and no strings. Name the dynamic aloud.',
    capabilities: ['connection', 'participation'],
  },
  'SHOW-GR-SAGE': {
    title: 'What Remains After',
    primaryQuestion: 'What lasting artifact or story will remain from this resourcing?',
    campaignQuestion: 'What does this campaign leave behind — capacity, relationships, a story?',
    optimizesFor: 'Ensuring the effort leaves durable value beyond the dollars.',
    forbiddenMoves: ['Burning the bridge after', 'No thank-you', 'The story untold'],
    failureModes: ['Money raised, nothing built', 'Goodwill spent and not renewed'],
    remediation: 'Name the artifact that outlives the campaign. Tell its story to one giver.',
    capabilities: ['connection', 'participation'],
  },

  // ── WAKE UP × Raise Awareness ──
  'WAKE-RA-SHAMAN': {
    title: "What's Going Unseen",
    primaryQuestion: "What truth here is going unseen or unsaid?",
    campaignQuestion: "What in this situation is invisible that needs to become visible?",
    optimizesFor: "Noticing what's hidden or ignored before trying to amplify anything.",
    forbiddenMoves: ["Assuming everyone already sees it", "Amplifying noise", "Performing awareness"],
    failureModes: ["Blindness to the obvious", "Seeing only what confirms you"],
    remediation: "Name one thing present in the room that no one is naming.",
    flavor: "The unseen runs the room until someone points at it.",
    capabilities: ["exploration", "connection"],
  },
  'WAKE-RA-CHALLENGER': {
    title: "What Doesn't Want Light",
    primaryQuestion: "What truth is being actively kept from view — including by me?",
    campaignQuestion: "What is this system structured to keep invisible?",
    optimizesFor: "Surfacing the actively suppressed, not just the overlooked.",
    forbiddenMoves: ["Polite avoidance", '"Not my place" as cover', "Flinching from the hard thing"],
    failureModes: ["Collusion with the cover-up", "Comfort chosen over truth"],
    remediation: "Name the thing the room is working hard not to see.",
    capabilities: ["exploration", "agency"],
  },
  'WAKE-RA-REGENT': {
    title: "What Deserves the Spotlight",
    primaryQuestion: "Of all that could be seen, what most deserves attention right now?",
    campaignQuestion: "Whose truth or which issue most deserves visibility here?",
    optimizesFor: "Directing limited attention where it matters most.",
    forbiddenMoves: ["Chasing every injustice at once", "Attention for attention's sake", "Centering yourself"],
    failureModes: ["Scattered outrage", "Spotlight on the trivial"],
    remediation: "Choose the one truth worth the room's full attention.",
    capabilities: ["rest", "connection"],
  },
  'WAKE-RA-ARCHITECT': {
    title: "The Story That Could Land",
    primaryQuestion: "What truth, if made visible, would change the most?",
    campaignQuestion: "What framing or story has the most potential to shift understanding?",
    optimizesFor: "Spotting the high-leverage truth worth amplifying.",
    forbiddenMoves: ["Amplifying the loudest thing", "Ignoring framing", "Data with no story"],
    failureModes: ["Missing the story that would move people", "Truth that doesn't travel"],
    remediation: "Name the one fact that, if everyone saw it, would change things.",
    capabilities: ["exploration", "participation"],
  },
  'WAKE-RA-DIPLOMAT': {
    title: "Whose Voice Is Missing",
    primaryQuestion: "Whose perspective is absent from what's being seen?",
    campaignQuestion: "Whose voice must be centered — and who has been speaking over them?",
    optimizesFor: "Noticing the relational and power shape of attention.",
    forbiddenMoves: ["Speaking for others", "Tokenizing", "Ignoring who is absent"],
    failureModes: ["Amplifying yourself over those affected", "Missing the silenced"],
    remediation: "Name who isn't in the conversation. Bring their voice, or make room for it.",
    capabilities: ["connection", "participation"],
  },
  'WAKE-RA-SAGE': {
    title: "The Pattern Beneath the Incident",
    primaryQuestion: "What larger pattern does this single incident reveal?",
    campaignQuestion: "What systemic truth is this moment a symptom of?",
    optimizesFor: "Seeing the structure behind the event.",
    forbiddenMoves: ["Treating the symptom as the whole", "Isolated outrage", "Bypassing the pattern"],
    failureModes: ["Missing the system", "Framing a pattern as a one-off"],
    remediation: "Connect this incident to the pattern it belongs to.",
    capabilities: ["exploration", "connection"],
  },

  // ── OPEN UP × Raise Awareness ──
  'OPEN-RA-SHAMAN': {
    title: "What Seeing Costs",
    primaryQuestion: "What do I actually feel when I let this truth land?",
    campaignQuestion: "What does it cost us to really see what is happening here?",
    optimizesFor: "Letting the truth land in the body before reacting.",
    forbiddenMoves: ["Intellectualizing", "Numbing to the truth", "Performing feeling"],
    failureModes: ["Knowing without feeling", "Abstraction as armor"],
    remediation: "Let the truth land for one breath before you respond.",
    capabilities: ["connection"],
  },
  'OPEN-RA-CHALLENGER': {
    title: "The Truth You're Numb To",
    primaryQuestion: "What truth am I keeping at arm's length because feeling it would change me?",
    campaignQuestion: "What are we avoiding feeling about this issue?",
    optimizesFor: "Contact with the truth you've gone numb to.",
    forbiddenMoves: ['"Compassion fatigue" as excuse', '"I can\'t with this"', "Selective numbness"],
    failureModes: ["Chosen ignorance", "Outrage with no real contact"],
    remediation: "Feel the thing you've gone numb to. Then decide from there.",
    capabilities: ["connection", "agency"],
  },
  'OPEN-RA-REGENT': {
    title: "Stay Awake to It",
    primaryQuestion: "Can I stay aware of this truth without looking away?",
    campaignQuestion: "Can we keep this in view long enough to act, not just react?",
    optimizesFor: "Sustained attention without collapse or burnout.",
    forbiddenMoves: ["Doom-scrolling", "One-day outrage", "Abandoning the issue"],
    failureModes: ["Awareness that flares and fades", "Attention with no staying power"],
    remediation: "Choose one truth you'll keep in view past the news cycle.",
    capabilities: ["rest", "connection"],
  },
  'OPEN-RA-ARCHITECT': {
    title: "The Energy in the Story",
    primaryQuestion: "What energy or motivation is hidden in what I've seen?",
    campaignQuestion: "What latent will-to-act lives inside this awareness?",
    optimizesFor: "Receiving the activating charge inside a hard truth.",
    forbiddenMoves: ["Hoarding outrage", "Despair as the endpoint", "Information with no mobilizing energy"],
    failureModes: ["Awareness that deadens instead of activates"],
    remediation: "Name the energy this truth gives you. Aim it.",
    capabilities: ["participation", "exploration"],
  },
  'OPEN-RA-DIPLOMAT': {
    title: "Hold the Pain With Care",
    primaryQuestion: "How do I hold this hard truth — and others' pain in it — with care?",
    campaignQuestion: "How do we relate to those harmed without spectacle or pity?",
    optimizesFor: "A compassionate stance toward painful truth.",
    forbiddenMoves: ["Trauma as content", "Pity", "Centering your feelings over theirs"],
    failureModes: ["Extractive empathy", "Performing care"],
    remediation: "Relate to one person's reality with care, not as a case.",
    capabilities: ["connection"],
  },
  'OPEN-RA-SAGE': {
    title: "When You Let It Be True",
    primaryQuestion: "What becomes clear when I stop arguing with this truth and just witness it?",
    campaignQuestion: "What clarity comes when we stop debating and simply witness what's real?",
    optimizesFor: "Witness over debate.",
    forbiddenMoves: ["Forcing acceptance", "Debate as avoidance", "Spiritual bypass"],
    failureModes: ["Analysis instead of witness", "Arguing reality away"],
    remediation: "Witness the truth for three breaths without rebutting it.",
    capabilities: ["exploration", "connection"],
  },

  // ── CLEAN UP × Raise Awareness ──
  'CLEAN-RA-SHAMAN': {
    title: "Name the Awareness Feeling",
    primaryQuestion: "Which channel is live in this awareness — anger, grief, fear, numbness, or reach?",
    campaignQuestion: "What emotional channel is driving how we raise this — and is it clean?",
    optimizesFor: "Locating the channel under the message.",
    forbiddenMoves: ["Messaging from raw charge", 'Assuming it\'s "just the facts"'],
    failureModes: ["Rage-posting", "Grief dumped as advocacy"],
    remediation: "Name the channel before you publish a single word.",
    capabilities: ["exploration"],
  },
  'CLEAN-RA-CHALLENGER': {
    title: "The Story About the Truth",
    primaryQuestion: "What story am I telling about what I saw that may not be the whole truth?",
    campaignQuestion: "What narrative are we attached to that the facts might complicate?",
    optimizesFor: "Challenging your own framing before broadcasting it.",
    forbiddenMoves: ["Certainty", "The single story", "Defending the narrative over accuracy"],
    failureModes: ["Righteous distortion", "Truth bent to fit the story"],
    remediation: "Write the version of events that complicates your story.",
    capabilities: ["exploration", "agency"],
  },
  'CLEAN-RA-REGENT': {
    title: "What Awareness Lacks",
    primaryQuestion: "Awareness alone isn't moving me — which capability is missing?",
    campaignQuestion: "We've raised awareness but nothing shifts — what capability is the gap?",
    optimizesFor: "Naming the missing capability behind stalled awareness.",
    forbiddenMoves: ["More awareness as the answer to everything", "Willpower over capacity"],
    failureModes: ["Awareness theater", "The knowing-doing gap left unaddressed"],
    remediation: "Name the capability awareness needs next — to act, connect, or organize.",
    capabilities: ["agency", "rest"],
  },
  'CLEAN-RA-ARCHITECT': {
    title: "From Outrage to Aim",
    primaryQuestion: "Do I transcend this charge, translate it (anger to clarity), or neutralize it before I speak?",
    campaignQuestion: "How do we convert this issue's charge into communicable clarity?",
    optimizesFor: "Choosing the alchemy that makes truth land.",
    forbiddenMoves: ["Venting as advocacy", "Suppressing the charge", "Performative calm"],
    failureModes: ["Dumping charge on an audience", "Sanitized into meaninglessness"],
    remediation: "Pick transcend / translate / neutralize, then craft the message.",
    capabilities: ["agency", "connection"],
  },
  'CLEAN-RA-DIPLOMAT': {
    title: "The Tone That Reaches",
    primaryQuestion: "What emotional tone would let this truth actually reach people?",
    campaignQuestion: "From which channel would this message invite rather than alienate?",
    optimizesFor: "Aiming tone for reception, not just release.",
    forbiddenMoves: ["Shaming the audience", "Purity tone", "Despair-casting"],
    failureModes: ["Messages that repel the persuadable", "Preaching only to the choir"],
    remediation: "Re-aim the message from a channel that opens people, not closes them.",
    capabilities: ["connection"],
  },
  'CLEAN-RA-SAGE': {
    title: "What the Truth Taught",
    primaryQuestion: "What durable insight do I take from sitting with this truth?",
    campaignQuestion: "What's the lasting lesson this awareness work is offering us?",
    optimizesFor: "Converting awareness into reusable wisdom.",
    forbiddenMoves: ["Rushing to post", "The hot take over the insight", "Closing too soon"],
    failureModes: ["Lessons unlearned and repeated", "Shallow takes"],
    remediation: "Write the one insight you'll keep, beyond this moment.",
    capabilities: ["exploration", "connection"],
  },

  // ── GROW UP × Raise Awareness ──
  'GROW-RA-SHAMAN': {
    title: "The Witness Growing in You",
    primaryQuestion: "What capacity to see or speak truth is trying to grow in me?",
    campaignQuestion: "What awareness-capacity is this work asking the group to develop?",
    optimizesFor: "Noticing the emerging witness or voice.",
    forbiddenMoves: ["Forcing eloquence", "Performing growth", "Borrowing someone else's voice"],
    failureModes: ["Naming the capacity you wish for over the one emerging"],
    remediation: "Name the seeing or speaking capacity one size bigger than today.",
    capabilities: ["participation", "exploration"],
  },
  'GROW-RA-CHALLENGER': {
    title: "The Edge of Speaking",
    primaryQuestion: "What must evolve in me to name this truth out loud?",
    campaignQuestion: "What must we learn to tell this truth at the scale it needs?",
    optimizesFor: "Finding the truth-telling edge.",
    forbiddenMoves: ["Safe statements that aren't the edge", "Hiding behind nuance"],
    failureModes: ["Training comfortable speech, avoiding the edge"],
    remediation: "Name the sentence you're scared to say. That's the edge.",
    capabilities: ["agency"],
  },
  'GROW-RA-REGENT': {
    title: "Practice the Hard Conversation",
    primaryQuestion: "Which awareness skill — listening, naming, calling in — deserves deliberate practice?",
    campaignQuestion: "What communication practice should we repeat until it's reliable?",
    optimizesFor: "Committing to a repeatable practice over a single brave moment.",
    forbiddenMoves: ["Hoping skill appears", "One brave post, then silence"],
    failureModes: ["Inconsistency", "Practicing the wrong thing"],
    remediation: "Pick one rep — a weekly hard conversation. Schedule it.",
    capabilities: ["rest", "agency"],
  },
  'GROW-RA-ARCHITECT': {
    title: "Sharpen the Signal",
    primaryQuestion: "Which communication capability, if strengthened, would make my truth land better?",
    campaignQuestion: "What capacity, amplified, would most increase our reach?",
    optimizesFor: "Investing growth where reach compounds.",
    forbiddenMoves: ["Spreading practice thin", "Vanity skills", "Polishing the irrelevant"],
    failureModes: ["Growth without leverage"],
    remediation: "Pick the highest-leverage skill — clarity, story, or listening. Train it.",
    capabilities: ["participation", "exploration"],
  },
  'GROW-RA-DIPLOMAT': {
    title: "Speaking Without Burning",
    primaryQuestion: "As I get bolder with truth, how does it land on the people around me?",
    campaignQuestion: "How does our louder voice affect allies, targets, and the harmed?",
    optimizesFor: "Growing voice without scorching relationships.",
    forbiddenMoves: ["Bravery that burns bridges needlessly", "Leaving people behind"],
    failureModes: ["Truth-telling that isolates", "Collateral harm"],
    remediation: "Name one relationship your bolder voice affects. Tend it.",
    capabilities: ["connection", "participation"],
  },
  'GROW-RA-SAGE': {
    title: "Who Truth-Telling Makes You",
    primaryQuestion: "Who am I becoming as someone who sees and names what's real?",
    campaignQuestion: "What is this awareness work making us, as a community, become?",
    optimizesFor: "Integrating the identity of a truth-teller.",
    forbiddenMoves: ["Skipping reflection", "A righteous new mask"],
    failureModes: ["Capacity gained, self un-integrated"],
    remediation: 'Finish the sentence: "I am becoming someone who can see and say ______."',
    capabilities: ["connection", "participation"],
  },

  // ── SHOW UP × Raise Awareness ──
  'SHOW-RA-SHAMAN': {
    title: "Aim the Awareness",
    primaryQuestion: "Where exactly will I direct this awareness into the world?",
    campaignQuestion: "Where will this campaign's message actually go — which audience, which channel?",
    optimizesFor: "Committing awareness to a specific target.",
    forbiddenMoves: ["Broadcasting everywhere", 'Vague "spreading the word"'],
    failureModes: ["Noise with no target", "A message to no one"],
    remediation: "Name the one audience and channel this truth goes to first.",
    capabilities: ["agency"],
  },
  'SHOW-RA-CHALLENGER': {
    title: "Say the Thing",
    primaryQuestion: "What truth must I actually state — publicly or to someone's face — now?",
    campaignQuestion: "What's the intervention: the post, the testimony, the call-out or call-in?",
    optimizesFor: "Shipping the actual act of witness.",
    forbiddenMoves: ["One more draft", "Private clarity", "A soft hint instead of the thing"],
    failureModes: ["The truth that never gets said"],
    remediation: "Say the thing today — specifically, to the people who need to hear it.",
    flavor: "The naming is the first move.",
    capabilities: ["agency"],
  },
  'SHOW-RA-REGENT': {
    title: "Keep the Truth Alive",
    primaryQuestion: "What ongoing practice keeps this truth in view after the moment passes?",
    campaignQuestion: "How do we steward this awareness so it doesn't fade with the news cycle?",
    optimizesFor: "Building durable, accountable attention.",
    forbiddenMoves: ["Post-and-forget", "Performative one-offs", "Abandoning the issue"],
    failureModes: ["Awareness that spikes and dies"],
    remediation: "Set one recurring act that keeps the truth present.",
    capabilities: ["rest", "connection"],
  },
  'SHOW-RA-ARCHITECT': {
    title: "Build the Megaphone",
    primaryQuestion: "What structure makes this truth travel further and repeat?",
    campaignQuestion: "What structure — a series, toolkit, or platform — amplifies the message?",
    optimizesFor: "Structure that compounds reach.",
    forbiddenMoves: ["Chasing one-off virality", "Structure for its own sake"],
    failureModes: ["A message that can't scale or repeat"],
    remediation: "Add one structural lever: a series, a shareable artifact, or a coalition list.",
    capabilities: ["participation", "agency"],
  },
  'SHOW-RA-DIPLOMAT': {
    title: "Amplify, Don't Speak Over",
    primaryQuestion: "Whose voice should I amplify, and what power dynamic must I name to do it right?",
    campaignQuestion: "Who must lead this message, and whose consent and centering matter?",
    optimizesFor: "Raising awareness by centering the affected, not yourself.",
    forbiddenMoves: ["Speaking over", "Savior framing", "Using others' stories without consent"],
    failureModes: ["Centering yourself", "Extraction of testimony"],
    remediation: "Amplify one affected voice with consent; name your own role honestly.",
    capabilities: ["connection", "participation"],
  },
  'SHOW-RA-SAGE': {
    title: "What the Telling Leaves",
    primaryQuestion: "What lasting artifact of this truth will remain — a record, a story, a shift?",
    campaignQuestion: "What does this awareness campaign leave behind beyond the moment?",
    optimizesFor: "A durable record or shift beyond the attention spike.",
    forbiddenMoves: ["Ephemeral outrage", "Leaving no record", "The story untold"],
    failureModes: ["Attention spent, nothing retained"],
    remediation: "Name the artifact — the documented account, the changed mind — that outlives the post.",
    capabilities: ["connection", "participation"],
  },

  // ── WAKE UP × Direct Action ──
  'WAKE-DA-SHAMAN': {
    title: "Where the Harm Is",
    primaryQuestion: "Where is harm actually happening right now?",
    campaignQuestion: "What concrete harm is this action meant to confront?",
    optimizesFor: "Locating the real harm before reacting.",
    forbiddenMoves: ['Abstract "the system"', "Performative urgency", "Acting before seeing"],
    failureModes: ["Intervening where it's safe, not where harm is"],
    remediation: "Name the specific harm, in specific terms.",
    capabilities: ["exploration", "agency"],
  },
  'WAKE-DA-CHALLENGER': {
    title: "The Line You Won't Draw",
    primaryQuestion: "What boundary or confrontation am I avoiding seeing the need for?",
    campaignQuestion: "What line does this situation demand that we keep not drawing?",
    optimizesFor: "Surfacing the avoided confrontation.",
    forbiddenMoves: ["Keeping the peace at the cost of harm", "Conflict-avoidance dressed as virtue"],
    failureModes: ["Tolerating the intolerable", "Politeness as complicity"],
    remediation: "Name the line that needs drawing — the one you've been avoiding.",
    capabilities: ["agency", "exploration"],
  },
  'WAKE-DA-REGENT': {
    title: "Which Fight Is Yours",
    primaryQuestion: "Of all the harms, which is actually mine to confront?",
    campaignQuestion: "Which intervention here is ours to take responsibility for?",
    optimizesFor: "Choosing the right fight.",
    forbiddenMoves: ["Fighting everything at once", "Martyrdom", "Ignoring your actual leverage"],
    failureModes: ["Spread-thin activism", "Taking on the fight that isn't yours"],
    remediation: "Name the one harm you're actually positioned to confront.",
    capabilities: ["rest", "agency"],
  },
  'WAKE-DA-ARCHITECT': {
    title: "The Pressure Point",
    primaryQuestion: "Where would action have the most effect?",
    campaignQuestion: "What's the leverage point where intervention changes the most?",
    optimizesFor: "Spotting high-leverage intervention points.",
    forbiddenMoves: ["Symbolic gestures", "Hitting where it's visible, not where it matters", "Force without aim"],
    failureModes: ["Effort that doesn't move the harm"],
    remediation: "Name the point where pressure actually shifts the outcome.",
    capabilities: ["agency", "exploration"],
  },
  'WAKE-DA-DIPLOMAT': {
    title: "Who's at Risk",
    primaryQuestion: "Who bears the risk if I act — me, or someone more exposed?",
    campaignQuestion: "Whose safety and power are at stake in this action?",
    optimizesFor: "Seeing the risk and power map of action.",
    forbiddenMoves: ["Putting the vulnerable in front", "Ignoring who pays", "Reckless heroics"],
    failureModes: ["Action that endangers those it claims to protect"],
    remediation: "Name who bears the risk. Don't spend others' safety.",
    capabilities: ["connection", "participation"],
  },
  'WAKE-DA-SAGE': {
    title: "What the Harm Repeats",
    primaryQuestion: "What pattern of harm is this instance part of?",
    campaignQuestion: "What systemic cycle does this action interrupt?",
    optimizesFor: "Seeing action in the pattern, not just the moment.",
    forbiddenMoves: ["Whack-a-mole", "Treating each harm as isolated", "Ignoring the root"],
    failureModes: ["Addressing the instance, missing the cycle"],
    remediation: "Connect this harm to the cycle it repeats, and aim there.",
    capabilities: ["exploration", "agency"],
  },

  // ── OPEN UP × Direct Action ──
  'OPEN-DA-SHAMAN': {
    title: "The Fear Under the Fight",
    primaryQuestion: "What am I actually feeling about stepping into this — fear, fury, dread?",
    campaignQuestion: "What does the team really feel about taking this risk?",
    optimizesFor: "Feeling the charge before acting on it.",
    forbiddenMoves: ["Bravado", "Numbing the fear", "Acting to escape the feeling"],
    failureModes: ["Reckless action driven by unfelt fear"],
    remediation: "Feel the fear before you move. Then move anyway.",
    capabilities: ["connection", "agency"],
  },
  'OPEN-DA-CHALLENGER': {
    title: "What Action Asks of You",
    primaryQuestion: "What discomfort of confrontation am I avoiding by staying still?",
    campaignQuestion: "What are we avoiding feeling that keeps us from acting?",
    optimizesFor: "Contact with the avoided cost of acting.",
    forbiddenMoves: ["Comfort as caution", '"Now\'s not the time" forever', "Freeze disguised as strategy"],
    failureModes: ["Inaction rationalized", "The moment passed"],
    remediation: "Feel what acting would cost. Weigh it against the cost of not acting.",
    capabilities: ["agency"],
  },
  'OPEN-DA-REGENT': {
    title: "Can You Hold the Line",
    primaryQuestion: "Can I stay in this confrontation without collapsing or escalating?",
    campaignQuestion: "Can we sustain this action without burning out or losing control?",
    optimizesFor: "Staying steady inside conflict.",
    forbiddenMoves: ["Collapsing under pushback", "Escalating to discharge tension", "Abandoning it mid-fight"],
    failureModes: ["Folding when it gets hard", "Flaring out"],
    remediation: "Stay one beat longer in the discomfort than feels possible.",
    capabilities: ["rest", "agency"],
  },
  'OPEN-DA-ARCHITECT': {
    title: "The Power in the Anger",
    primaryQuestion: "What usable power is hidden in this anger or urgency?",
    campaignQuestion: "What force does this moment's energy give the action?",
    optimizesFor: "Receiving anger as fuel for clean action.",
    forbiddenMoves: ["Hoarding rage", "Venting", "Mistaking heat for direction"],
    failureModes: ["Anger that burns the actor, not the harm"],
    remediation: "Name the agency this anger gives you. Point it at the harm.",
    capabilities: ["agency", "participation"],
  },
  'OPEN-DA-DIPLOMAT': {
    title: "Fierce and Caring",
    primaryQuestion: "How do I confront harm while still relating to people with care?",
    campaignQuestion: "How do we act fiercely without dehumanizing even those we oppose?",
    optimizesFor: "Combining fierceness with care.",
    forbiddenMoves: ["Contempt", "Collateral cruelty", "Treating opponents as monsters"],
    failureModes: ["Action that wounds indiscriminately", "Care abandoned in the fight"],
    remediation: "Name the boundary fiercely; keep one thread of care for the human.",
    capabilities: ["connection", "agency"],
  },
  'OPEN-DA-SAGE': {
    title: "See Before You Strike",
    primaryQuestion: "What do I see clearly if I pause and witness before reacting?",
    campaignQuestion: "What clarity comes if we witness the full picture before intervening?",
    optimizesFor: "Witness that sharpens action rather than delaying it.",
    forbiddenMoves: ["Reactivity", "Striking blind", "Paralysis disguised as reflection"],
    failureModes: ["Action without sight", 'Endless "seeing" as avoidance'],
    remediation: "Witness the whole field for three breaths, then act with aim.",
    capabilities: ["exploration", "agency"],
  },

  // ── CLEAN UP × Direct Action ──
  'CLEAN-DA-SHAMAN': {
    title: "Name the Fight Feeling",
    primaryQuestion: "Which channel is driving this — clean fire, or fear or grief wearing fire's mask?",
    campaignQuestion: "What channel is fueling this action, and is it clean?",
    optimizesFor: "Locating the true channel under the urge to act.",
    forbiddenMoves: ["Acting on displaced charge", "Assuming anger is automatically righteous"],
    failureModes: ["Fear-driven aggression", "Grief acted out as attack"],
    remediation: "Name the channel honestly before you intervene.",
    capabilities: ["exploration", "agency"],
  },
  'CLEAN-DA-CHALLENGER': {
    title: "The Enemy Story",
    primaryQuestion: "What story about who's the enemy am I treating as fact?",
    campaignQuestion: "What us-versus-them narrative might be distorting our read?",
    optimizesFor: "Challenging the framing that justifies the action.",
    forbiddenMoves: ["Certainty about villains", "Single-cause stories", "Righteousness as proof"],
    failureModes: ["Action built on a distorted enemy", "Collateral injustice"],
    remediation: 'Write the version where the "enemy" is more complicated. Then aim true.',
    capabilities: ["exploration", "agency"],
  },
  'CLEAN-DA-REGENT': {
    title: "What the Fight Needs",
    primaryQuestion: "I'm stuck on this confrontation — which capability is missing?",
    campaignQuestion: "What capability does this action lack — agency, connection, structure?",
    optimizesFor: "Naming the missing capability behind stalled action.",
    forbiddenMoves: ["More force as the answer", "Willpower over capacity"],
    failureModes: ["Pushing harder on a missing capability", "Burnout"],
    remediation: "Name the capability the action needs next, and grow it.",
    capabilities: ["agency", "rest"],
  },
  'CLEAN-DA-ARCHITECT': {
    title: "Forge the Anger",
    primaryQuestion: "Do I transcend this charge, translate it (fear to agency), or neutralize it before acting?",
    campaignQuestion: "How do we forge this charge into clean, aimed force?",
    optimizesFor: "Alchemizing charge into clean action.",
    forbiddenMoves: ["Venting onto targets", "Suppression", "Performative restraint"],
    failureModes: ["Discharging on the wrong target", "Force that scatters"],
    remediation: "Pick transcend / translate / neutralize, then act from the forged state.",
    flavor: "Forge anger into a boundary said, a limit set.",
    capabilities: ["agency"],
  },
  'CLEAN-DA-DIPLOMAT': {
    title: "From Rage to Resolve",
    primaryQuestion: "Which channel, if I moved this charge there, would make the action cleaner?",
    campaignQuestion: "What would this action look like from resolve instead of rage?",
    optimizesFor: "Aiming the charge toward effective action.",
    forbiddenMoves: ["Acting from raw rage", "Cold detachment", "Performative calm"],
    failureModes: ["Rage that sabotages the cause", "Numbness that under-acts"],
    remediation: "Re-aim from resolve — an earned boundary, not blind heat.",
    capabilities: ["agency", "connection"],
  },
  'CLEAN-DA-SAGE': {
    title: "What the Confrontation Taught",
    primaryQuestion: "What do I learn from this fight that I'll carry forward?",
    campaignQuestion: "What's the durable lesson this action is teaching us?",
    optimizesFor: "Converting confrontation into wisdom.",
    forbiddenMoves: ["Rushing to the next fight", "No debrief", "The lesson skipped"],
    failureModes: ["The same fight again, unlearned"],
    remediation: "Write the one lesson this confrontation taught you.",
    capabilities: ["exploration", "agency"],
  },

  // ── GROW UP × Direct Action ──
  'GROW-DA-SHAMAN': {
    title: "The Courage Trying to Grow",
    primaryQuestion: "What capacity for action or boundary is trying to grow in me?",
    campaignQuestion: "What action-capacity is this work asking us to develop?",
    optimizesFor: "Noticing the emerging courage.",
    forbiddenMoves: ["Forcing bravado", "Performing fearlessness", "Borrowed nerve"],
    failureModes: ["Naming the courage you wish for over the one emerging"],
    remediation: "Name the boundary or action one size bigger than today. Take it once.",
    capabilities: ["agency", "participation"],
  },
  'GROW-DA-CHALLENGER': {
    title: "The Edge of the Line",
    primaryQuestion: "What must evolve in me to draw the line this calls for?",
    campaignQuestion: "What must we learn to confront at the scale this needs?",
    optimizesFor: "Finding the action edge.",
    forbiddenMoves: ["Safe action that isn't the edge", "Busywork as bravery"],
    failureModes: ["Training comfort, avoiding the real confrontation"],
    remediation: "Name the confrontation that scares you slightly. Step to it.",
    capabilities: ["agency"],
  },
  'GROW-DA-REGENT': {
    title: "Practice Holding the Line",
    primaryQuestion: "Which action skill — saying no, staying steady, de-escalating — deserves practice?",
    campaignQuestion: "What action practice should we drill until it's reliable?",
    optimizesFor: "Repeatable practice of action skills.",
    forbiddenMoves: ["Hoping courage appears", "One brave act, then retreat"],
    failureModes: ["Inconsistency", "Drilling the wrong skill"],
    remediation: 'Pick one rep — a small "no" daily. Practice it.',
    capabilities: ["rest", "agency"],
  },
  'GROW-DA-ARCHITECT': {
    title: "Strengthen Your Stance",
    primaryQuestion: "Which existing capability, if strengthened, would make my action more effective?",
    campaignQuestion: "What capacity, amplified, would most increase our impact?",
    optimizesFor: "Investing growth where impact compounds.",
    forbiddenMoves: ["Spreading thin", "Vanity toughness", "The irrelevant skill"],
    failureModes: ["Growth without leverage"],
    remediation: "Pick the highest-leverage action capability. Train it.",
    capabilities: ["agency", "participation"],
  },
  'GROW-DA-DIPLOMAT': {
    title: "Acting Without Abandoning",
    primaryQuestion: "As I get bolder in action, how does it land on those beside me?",
    campaignQuestion: "How does escalating this action affect allies and the people we protect?",
    optimizesFor: "Growing action without endangering or alienating allies.",
    forbiddenMoves: ["Heroics that strand the team", "Risk imposed on others"],
    failureModes: ["Bold action that isolates or endangers"],
    remediation: "Name who your bolder action affects. Move with them, not past them.",
    capabilities: ["connection", "participation"],
  },
  'GROW-DA-SAGE': {
    title: "Who the Fight Makes You",
    primaryQuestion: "Who am I becoming as someone willing to act and confront?",
    campaignQuestion: "What is this struggle making us, as a community, become?",
    optimizesFor: "Integrating the identity of one who acts.",
    forbiddenMoves: ["Skipping reflection", "A hardened new mask", "War without self"],
    failureModes: ["Capacity gained, self un-integrated", "Becoming what you fought"],
    remediation: 'Finish the sentence: "I am becoming someone who can act and still ______."',
    capabilities: ["connection", "agency"],
  },

  // ── SHOW UP × Direct Action ──
  'SHOW-DA-SHAMAN': {
    title: "Aim the Action",
    primaryQuestion: "Where exactly will I direct this action?",
    campaignQuestion: "Where will this action land — which target, which moment?",
    optimizesFor: "Committing action to a specific target.",
    forbiddenMoves: ["Diffuse protest", 'Vague "doing something"', "Endless prep"],
    failureModes: ["Action with no target", "Energy scattered"],
    remediation: "Name the one place this action lands first.",
    capabilities: ["agency"],
  },
  'SHOW-DA-CHALLENGER': {
    title: "Make the Move",
    primaryQuestion: "What concrete confrontation or intervention must I make now?",
    campaignQuestion: "What's the action that actually goes — the stand, the disruption, the demand?",
    optimizesFor: "Shipping the actual intervention.",
    forbiddenMoves: ["One more meeting", "Private resolve", "A hint instead of the act"],
    failureModes: ["The action that never happens"],
    remediation: "Take the action today — specific, real, visible.",
    flavor: "A challenge opens a new front.",
    capabilities: ["agency"],
  },
  'SHOW-DA-REGENT': {
    title: "Sustain the Pressure",
    primaryQuestion: "What ongoing commitment keeps this action from being a one-off?",
    campaignQuestion: "How do we sustain and steward this action over time?",
    optimizesFor: "Durable, accountable pressure.",
    forbiddenMoves: ["One-day actions", "Burnout sprints", "Abandoning it after the headline"],
    failureModes: ["Pressure that vanishes", "Unsustained campaigns"],
    remediation: "Set one sustainable recurring commitment to keep the pressure on.",
    capabilities: ["rest", "agency"],
  },
  'SHOW-DA-ARCHITECT': {
    title: "Build the Leverage",
    primaryQuestion: "What structure makes this action repeatable and harder to ignore?",
    campaignQuestion: "What structure — escalation ladder, tactics, roles — amplifies the action?",
    optimizesFor: "Structure that compounds pressure.",
    forbiddenMoves: ["One-off heroics", "Structure for show", "Over-planning into paralysis"],
    failureModes: ["Action that can't escalate or repeat"],
    remediation: "Add one structural lever — an escalation step or a clear next demand.",
    capabilities: ["agency", "participation"],
  },
  'SHOW-DA-DIPLOMAT': {
    title: "Act With, Not For",
    primaryQuestion: "Who must be involved, and what power dynamic must I name to act cleanly?",
    campaignQuestion: "Who leads this action, whose consent matters, and who must be protected?",
    optimizesFor: "Action rooted in consent and shared power, not saviorism.",
    forbiddenMoves: ["Acting for people without them", "Exposing the vulnerable", "Lone-wolf heroics"],
    failureModes: ['"Help" that disempowers', "Action that speaks over"],
    remediation: "Act with the affected, by their lead; name and protect who's at risk.",
    capabilities: ["connection", "participation"],
  },
  'SHOW-DA-SAGE': {
    title: "What the Action Leaves",
    primaryQuestion: "What lasting change or precedent will this action leave?",
    campaignQuestion: "What does this action leave behind — a precedent, a protection, a shift?",
    optimizesFor: "Durable change beyond the moment of confrontation.",
    forbiddenMoves: ["Catharsis with no change", "No follow-through", "Precedent left unset"],
    failureModes: ["A fight won, nothing changed", "The harm returns"],
    remediation: "Name the change that must outlast the action; secure it.",
    capabilities: ["agency", "participation"],
  },

  // ── WAKE UP × Skillful Organizing ──
  'WAKE-SO-SHAMAN': {
    title: "What's Holding It Together",
    primaryQuestion: "What structure — or lack of it — is actually shaping this?",
    campaignQuestion: "What's the real organizational state: who's doing what, and what's missing?",
    optimizesFor: "Seeing the actual structure before redesigning anything.",
    forbiddenMoves: ["Assuming the org chart is reality", "Reorganizing before observing"],
    failureModes: ["Fixing imagined structure", "Missing the informal one that runs things"],
    remediation: "Name how the work actually flows right now, not how it's supposed to.",
    capabilities: ["exploration", "rest"],
  },
  'WAKE-SO-CHALLENGER': {
    title: "The Dysfunction No One Names",
    primaryQuestion: "What structural problem is everyone working around but not naming?",
    campaignQuestion: "What broken process are we all quietly compensating for?",
    optimizesFor: "Surfacing the unspoken dysfunction.",
    forbiddenMoves: ["Politeness about process", "Blaming people for structural failures"],
    failureModes: ["Heroics covering broken structure", "The workaround becoming permanent"],
    remediation: "Name the structural problem people keep absorbing personally.",
    capabilities: ["exploration", "agency"],
  },
  'WAKE-SO-REGENT': {
    title: "What Needs Tending",
    primaryQuestion: "Which part of the structure most needs stewarding right now?",
    campaignQuestion: "What in this organization most needs tending before it breaks?",
    optimizesFor: "Directing organizing attention well.",
    forbiddenMoves: ["Tending the visible over the load-bearing", "Neglecting maintenance"],
    failureModes: ["Polishing the front while the foundation cracks"],
    remediation: "Name the load-bearing part that needs care first.",
    capabilities: ["rest", "participation"],
  },
  'WAKE-SO-ARCHITECT': {
    title: "The Structure That Wants to Exist",
    primaryQuestion: "What structure is trying to emerge that would make this work better?",
    campaignQuestion: "What system, if built, would multiply the group's capacity?",
    optimizesFor: "Spotting the high-leverage structure to build.",
    forbiddenMoves: ["Structure for its own sake", "Copying a template that doesn't fit", "Premature scaling"],
    failureModes: ["Building the wrong system", "Missing the one that would help"],
    remediation: "Name the structure that would remove the most friction.",
    capabilities: ["participation", "exploration"],
  },
  'WAKE-SO-DIPLOMAT': {
    title: "Who Actually Decides",
    primaryQuestion: "Who holds real power and trust in how this gets organized?",
    campaignQuestion: "What's the real map of roles, power, and relationship here?",
    optimizesFor: "Seeing the relational and power structure, not just the formal one.",
    forbiddenMoves: ["Ignoring informal power", "Org-chart blindness", "Bypassing trust"],
    failureModes: ["A plan that ignores who really decides", "Stepping on relationships"],
    remediation: "Name who actually holds decision power and trust.",
    capabilities: ["connection", "participation"],
  },
  'WAKE-SO-SAGE': {
    title: "The Pattern in the Chaos",
    primaryQuestion: "What recurring organizational pattern keeps producing this?",
    campaignQuestion: "What systemic dynamic does this coordination problem reveal?",
    optimizesFor: "Seeing the pattern behind the mess.",
    forbiddenMoves: ["Blaming individuals for systemic patterns", "One-off fixes"],
    failureModes: ["Fixing the instance while the pattern recurs"],
    remediation: "Connect this breakdown to the pattern it repeats.",
    capabilities: ["exploration", "connection"],
  },

  // ── OPEN UP × Skillful Organizing ──
  'OPEN-SO-SHAMAN': {
    title: "What the Mess Feels Like",
    primaryQuestion: "What do I actually feel inside this disorganization — overwhelm, resentment, dread?",
    campaignQuestion: "What's the felt experience of being in this structure, or its absence?",
    optimizesFor: "Feeling the human cost of the structure before fixing it.",
    forbiddenMoves: ["Jumping to a system", "Treating people as resources", "Numbing to the strain"],
    failureModes: ["Process fixes that ignore how it feels to live in them"],
    remediation: "Name what the current structure feels like to be inside.",
    capabilities: ["connection", "rest"],
  },
  'OPEN-SO-CHALLENGER': {
    title: "The Role You're Avoiding",
    primaryQuestion: "What organizing responsibility am I avoiding because it's uncomfortable?",
    campaignQuestion: "What structural decision are we avoiding because it'll upset someone?",
    optimizesFor: "Contact with the avoided organizing work.",
    forbiddenMoves: ["Avoiding the hard role or delegation talk", "Conflict-dodging dressed as harmony"],
    failureModes: ["Structure left vague to avoid discomfort", "Everyone quietly overworked"],
    remediation: "Name the role or decision you're avoiding.",
    capabilities: ["agency", "connection"],
  },
  'OPEN-SO-REGENT': {
    title: "Can You Hold the Whole",
    primaryQuestion: "Can I hold responsibility for this structure without controlling everything or dropping it?",
    campaignQuestion: "Can we steward this organization steadily, sharing the load?",
    optimizesFor: "Holding the whole without over-controlling or abdicating.",
    forbiddenMoves: ["Micromanagement", "Abdication", "Hero-coordinator burnout"],
    failureModes: ["The structure depending on one exhausted person"],
    remediation: "Hold the whole for a beat; then hand one piece to someone you trust.",
    capabilities: ["rest", "participation"],
  },
  'OPEN-SO-ARCHITECT': {
    title: "The Capacity in the Room",
    primaryQuestion: "What organizing capacity or willingness is here, unused?",
    campaignQuestion: "What latent capacity in this group hasn't been activated?",
    optimizesFor: "Receiving the group's untapped capacity.",
    forbiddenMoves: ["Doing it all yourself", "Discounting others' skills", "Ignoring volunteers"],
    failureModes: ["Scarcity of help while help stands unused"],
    remediation: "Name three people's capacities you haven't drawn on. Invite one.",
    capabilities: ["participation", "exploration"],
  },
  'OPEN-SO-DIPLOMAT': {
    title: "Structure That Cares",
    primaryQuestion: "How do I build structure that holds people with care, not just efficiency?",
    campaignQuestion: "How do we organize in a way that tends relationships, not just tasks?",
    optimizesFor: "Humane structure.",
    forbiddenMoves: ["Efficiency over people", "Treating people as interchangeable", "Cold process"],
    failureModes: ["A system that works and burns people", "Extraction by spreadsheet"],
    remediation: "Design one part of the structure around how it cares for people.",
    capabilities: ["connection", "participation"],
  },
  'OPEN-SO-SAGE': {
    title: "When You Stop Forcing Order",
    primaryQuestion: "What becomes clear when I stop forcing order and witness how the work wants to flow?",
    campaignQuestion: "What structure reveals itself when we stop imposing and start watching?",
    optimizesFor: "Witnessing the natural flow before imposing structure.",
    forbiddenMoves: ["Forcing a system", "Control as the only tool", "Ignoring emergence"],
    failureModes: ["Rigid structure fighting the actual work"],
    remediation: "Watch how the work actually wants to move for three breaths. Organize with that.",
    capabilities: ["exploration", "rest"],
  },

  // ── CLEAN UP × Skillful Organizing ──
  'CLEAN-SO-SHAMAN': {
    title: "Name the Organizing Feeling",
    primaryQuestion: "Which channel is live in this coordination strain — fear, anger, overwhelm, numbness?",
    campaignQuestion: "What emotional channel is driving our organizing, and is it clean?",
    optimizesFor: "Locating the channel under the process strain.",
    forbiddenMoves: ["Building systems from anxiety", 'Assuming it\'s "just logistics"'],
    failureModes: ["Control-from-fear", "Resentment baked into the structure"],
    remediation: "Name the channel before you redesign anything.",
    capabilities: ["exploration"],
  },
  'CLEAN-SO-CHALLENGER': {
    title: "The 'Only I Can' Story",
    primaryQuestion: "What story about who can do this am I treating as fact?",
    campaignQuestion: 'What belief — "only we can," "they\'ll mess it up" — is blocking delegation?',
    optimizesFor: "Challenging the story that prevents sharing the work.",
    forbiddenMoves: ["Indispensability stories", "Perfectionism as control", "Distrust treated as fact"],
    failureModes: ["The bottleneck enshrined", "Everything routed through one person"],
    remediation: "Write the story that keeps you the bottleneck. Then test it: hand one thing off.",
    capabilities: ["agency", "participation"],
  },
  'CLEAN-SO-REGENT': {
    title: "What the System Lacks",
    primaryQuestion: "This keeps breaking — which capability is the structure missing?",
    campaignQuestion: "What capability does this organization lack — clarity, trust, follow-through?",
    optimizesFor: "Naming the missing capability behind the breakdown.",
    forbiddenMoves: ["Adding process to a capability gap", "Rules over capacity"],
    failureModes: ["More procedure, same dysfunction"],
    remediation: "Name the capability the structure needs — not another rule.",
    capabilities: ["participation", "rest"],
  },
  'CLEAN-SO-ARCHITECT': {
    title: "Redirect the Strain",
    primaryQuestion: "Do I transcend this strain, translate it, or neutralize it before I (re)build?",
    campaignQuestion: "How do we convert organizing strain into clean structure?",
    optimizesFor: "Clearing the charge before designing.",
    forbiddenMoves: ["Building while activated", "Venting via reorg", "Suppression"],
    failureModes: ["Structure that encodes the strain", "Reorg as discharge"],
    remediation: "Clear the charge first; then design from steadiness.",
    capabilities: ["rest", "participation"],
  },
  'CLEAN-SO-DIPLOMAT': {
    title: "From Control to Trust",
    primaryQuestion: "Which channel would let me organize from trust instead of control?",
    campaignQuestion: "What would this structure look like built from trust, not fear?",
    optimizesFor: "Aiming organizing energy toward trust.",
    forbiddenMoves: ["Control masquerading as rigor", "Surveillance", "Performative empowerment"],
    failureModes: ["Structures that signal distrust", "Disengagement"],
    remediation: "Re-aim one structure from trust — give real ownership, not just tasks.",
    capabilities: ["connection", "participation"],
  },
  'CLEAN-SO-SAGE': {
    title: "What the Breakdown Taught",
    primaryQuestion: "What does this organizing breakdown teach me to build differently?",
    campaignQuestion: "What's the durable lesson this coordination struggle offers?",
    optimizesFor: "Converting breakdown into design wisdom.",
    forbiddenMoves: ["Rushing the next reorg", "No retrospective", "The lesson skipped"],
    failureModes: ["Rebuilding the same flawed system"],
    remediation: "Write the one design principle this breakdown taught you.",
    capabilities: ["exploration", "participation"],
  },

  // ── GROW UP × Skillful Organizing ──
  'GROW-SO-SHAMAN': {
    title: "The Organizer Growing in You",
    primaryQuestion: "What organizing or coordinating capacity is trying to grow in me?",
    campaignQuestion: "What organizing capacity is this work asking the group to develop?",
    optimizesFor: "Noticing the emerging organizer.",
    forbiddenMoves: ["Forcing leadership", "Performing competence", "Borrowed authority"],
    failureModes: ["Naming the capacity you wish for over the one emerging"],
    remediation: "Name the organizing capacity one size bigger than today. Practice it once.",
    capabilities: ["participation", "exploration"],
  },
  'GROW-SO-CHALLENGER': {
    title: "The Edge of Letting Go",
    primaryQuestion: "What must evolve in me to organize at the next level — often, to let go?",
    campaignQuestion: "What must the group learn to coordinate at the scale it needs?",
    optimizesFor: "Finding the organizing edge — often delegation and trust.",
    forbiddenMoves: ["Comfortable control that isn't the edge", "Busywork"],
    failureModes: ["Training the wrong muscle", "Clinging to doing it yourself"],
    remediation: "Name the thing you must stop doing yourself. Hand it off.",
    capabilities: ["agency", "participation"],
  },
  'GROW-SO-REGENT': {
    title: "Practice Delegating",
    primaryQuestion: "Which organizing skill — delegating, facilitating, documenting — deserves practice?",
    campaignQuestion: "What organizing practice should we repeat until it's reliable?",
    optimizesFor: "Repeatable practice of organizing skills.",
    forbiddenMoves: ["Hoping coordination improves on its own", "One good system, then drift"],
    failureModes: ["Inconsistency", "Practicing the wrong skill"],
    remediation: "Pick one rep — delegate one real thing weekly. Practice it.",
    capabilities: ["rest", "participation"],
  },
  'GROW-SO-ARCHITECT': {
    title: "Strengthen the System",
    primaryQuestion: "Which capability, if strengthened, would make the whole structure more effective?",
    campaignQuestion: "What capacity, amplified, would most increase the group's throughput?",
    optimizesFor: "Investing where structural leverage compounds.",
    forbiddenMoves: ["Spreading thin", "Vanity process", "Optimizing the irrelevant"],
    failureModes: ["Growth without leverage"],
    remediation: "Pick the highest-leverage capability — clarity, trust, or follow-through. Build it.",
    capabilities: ["participation", "agency"],
  },
  'GROW-SO-DIPLOMAT': {
    title: "Growing the Team, Not Just You",
    primaryQuestion: "As I grow as an organizer, am I growing others' capacity too?",
    campaignQuestion: "How does scaling our structure develop people, not just exploit them?",
    optimizesFor: "Growing capacity in a way that develops others.",
    forbiddenMoves: ["Hoarding skill or authority", "Growth that deskills the team", "Extraction"],
    failureModes: ["One strong organizer, a dependent group"],
    remediation: "Name one person whose capacity your growth could grow. Invest in them.",
    capabilities: ["connection", "participation"],
  },
  'GROW-SO-SAGE': {
    title: "Who Organizing Makes You",
    primaryQuestion: "Who am I becoming as someone who builds and holds structure?",
    campaignQuestion: "What is this organizing work making us, as a community, become?",
    optimizesFor: "Integrating the identity of a builder and steward.",
    forbiddenMoves: ["Skipping reflection", "A controlling new mask"],
    failureModes: ["Capacity gained, self un-integrated", "Becoming the bottleneck you feared"],
    remediation: 'Finish the sentence: "I am becoming someone who can build and still ______."',
    capabilities: ["connection", "participation"],
  },

  // ── SHOW UP × Skillful Organizing ──
  'SHOW-SO-SHAMAN': {
    title: "Aim the Structure",
    primaryQuestion: "Where exactly will I invest this organizing energy?",
    campaignQuestion: "Where will this structure actually apply — which process, which team?",
    optimizesFor: "Committing organizing to a specific target.",
    forbiddenMoves: ["Reorganizing everything", 'Vague "getting organized"', "Endless planning"],
    failureModes: ["Systems built for nothing in particular"],
    remediation: "Name the one process this structure serves first.",
    capabilities: ["agency", "participation"],
  },
  'SHOW-SO-CHALLENGER': {
    title: "Ship the System",
    primaryQuestion: "What concrete structural change must I make now?",
    campaignQuestion: "What's the intervention — the role defined, the process launched, the meeting fixed?",
    optimizesFor: "Shipping the actual structural change.",
    forbiddenMoves: ["One more planning doc", "Private clarity", "A suggestion instead of a change"],
    failureModes: ["The reorg that never happens"],
    remediation: "Make the structural change today — define one role, fix one process.",
    capabilities: ["agency", "participation"],
  },
  'SHOW-SO-REGENT': {
    title: "Tend the Structure",
    primaryQuestion: "What ongoing stewardship keeps this structure healthy over time?",
    campaignQuestion: "How do we maintain and steward this system so it doesn't rot?",
    optimizesFor: "Durable, accountable maintenance.",
    forbiddenMoves: ["Set-and-forget systems", "No owner", "Maintenance neglected"],
    failureModes: ["Structure that decays", "Nobody tending it"],
    remediation: "Assign one owner and one review rhythm to the structure.",
    capabilities: ["rest", "participation"],
  },
  'SHOW-SO-ARCHITECT': {
    title: "Build to Last",
    primaryQuestion: "What structure makes this repeatable, scalable, and resilient?",
    campaignQuestion: "What system — roles, process, handoffs — amplifies the group's work?",
    optimizesFor: "Structure that compounds capacity.",
    forbiddenMoves: ["Heroic one-offs", "Bureaucracy for show", "Over-engineering"],
    failureModes: ["A structure that can't scale or survive a departure"],
    remediation: "Add one durable lever — a documented process, a clear role, a handoff.",
    flavor: "Design is making complexity navigable without making it simple.",
    capabilities: ["participation", "agency"],
  },
  'SHOW-SO-DIPLOMAT': {
    title: "Share the Power",
    primaryQuestion: "Who must hold real ownership, and what power dynamic must I name to build this fairly?",
    campaignQuestion: "How do we distribute roles and power so the structure is just, not concentrated?",
    optimizesFor: "Structure that shares power and consent, rather than centralizing it.",
    forbiddenMoves: ["Concentrating power", "Assigning roles without consent", "Performative inclusion"],
    failureModes: ["A structure that entrenches the few", "Tokens without power"],
    remediation: "Distribute one piece of real ownership; name the power dynamic openly.",
    capabilities: ["connection", "participation"],
  },
  'SHOW-SO-SAGE': {
    title: "What the Structure Leaves",
    primaryQuestion: "What lasting capacity or institution will this organizing leave behind?",
    campaignQuestion: "What does this organizing leave behind — a durable structure, trained people?",
    optimizesFor: "Durable institutional capacity beyond the effort.",
    forbiddenMoves: ["Structure that dies with you", "No documentation", "Capacity left uncaptured"],
    failureModes: ["The work collapses when you leave"],
    remediation: "Name the structure or trained people that outlast you; secure them.",
    capabilities: ["participation", "connection"],
  },
}
