import Link from 'next/link'
import { db } from '@/lib/db'
const cell = (value: string | null | undefined) => `"${(value ?? '').replace(/"/g, '""')}"`
export const metadata = { title: 'Book Tour help - Admin' }
export default async function AdminBookTourHelpPage() {
  const rows = await db.bookTourHelpInterest.findMany({ orderBy: { createdAt: 'desc' }, take: 500 })
  const csv = [['created_at', 'name', 'email', 'location', 'help_types', 'note', 'consent', 'source'].map(cell).join(','), ...rows.map((row) => [row.createdAt.toISOString(), row.name, row.email, row.location, row.helpTypes.join(' | '), row.note, String(row.consent), row.source].map(cell).join(','))].join('\n')
  return <main className="min-h-screen bg-black px-4 py-10 text-zinc-200 sm:px-8"><div className="mx-auto max-w-5xl space-y-8"><header><Link href="/admin" className="text-xs text-zinc-500 hover:text-zinc-300">← Admin</Link><p className="mt-5 text-[11px] font-bold uppercase tracking-[0.22em] text-emerald-400">Mastering Allyship Book Tour</p><h1 className="mt-2 text-2xl font-bold text-white">Help offers</h1><p className="mt-2 text-sm text-zinc-500">{rows.length} captured offers. Copy the CSV for personal follow-up or export.</p></header><section><h2 className="text-sm font-bold text-white">CSV export</h2><textarea readOnly value={csv} className="mt-3 min-h-48 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-4 font-mono text-xs leading-5 text-zinc-300" /></section><section className="space-y-3"><h2 className="text-sm font-bold text-white">Recent offers</h2>{rows.length === 0 ? <p className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-5 text-sm text-zinc-500">No one has offered help yet.</p> : rows.map((row) => <article key={row.id} className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-5"><p className="font-semibold text-white">{row.name || row.email}</p><p className="mt-1 text-sm text-zinc-400">{row.email}{row.location ? ` · ${row.location}` : ''}</p><p className="mt-3 text-sm text-emerald-300">{row.helpTypes.join(' · ')}</p>{row.note ? <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-zinc-300">{row.note}</p> : null}</article>)}</section></div></main>
}
