/**
 * I Ching Prompt Templates — Face-Anchored Questions
 * 
 * Every hexagram carries:
 *   - A BASE QUESTION (its wisdom theme as a prompt)
 *   - 6 FACE-ANGLED QUESTIONS — the base question filtered through each Game Master Face
 * 
 * HOW TO USE:
 *   import { getIChingPromptTemplate, HEXAGRAM_PROMPT_TEMPLATES } from '@/shared/iching-prompt-templates'
 *   
 *   // Get all 6 face questions for a hexagram
 *   const entry = HEXAGRAM_PROMPT_TEMPLATES[17]
 *   entry.shaman  // → "What in your body knows the answer to this before your mind does? What opportunity is..."
 * 
 *   // Or via the helper (returns structured object)
 *   const { base, faceQuestion, faceLabel } = getIChingPromptTemplate(17, 'challenger')
 * 
 * FACE ORDER (consistent with LINE_TO_FACE mapping in cast-iching.ts):
 *   shaman      → line 1 (bottom)  — body, roots, felt sense
 *   challenger  → line 2           — opposition, truth, edge
 *   regent      → line 3           — judgment, long arc, order
 *   architect   → line 4           — structure, strategy, blueprint
 *   diplomat    → line 5           — bridge, relationship, care
 *   sage        → line 6 (top)    — integration, wisdom, precedent
 * 
 * UX FLOW:
 *   1. Player draws hexagram
 *   2. Sees 6 face cards (not questions yet) — "Which face do you need to hear from?"
 *   3. Player picks a face — that choice IS the reading (they stake on which lens they need)
 *   4. Player sees that face's question for this hexagram
 *   5. Player writes their response → player_response BAR created with face + hexagram + response
 */

export type GameMasterFace = 'shaman' | 'challenger' | 'regent' | 'architect' | 'diplomat' | 'sage'

export const FACE_LABELS: Record<GameMasterFace, string> = {
  shaman:     'Shaman',
  challenger: 'Challenger',
  regent:     'Regent',
  architect:  'Architect',
  diplomat:   'Diplomat',
  sage:       'Sage',
}

export interface IChingPromptTemplateEntry {
  name: string
  tone: string
  base: string
  shaman: string
  challenger: string
  regent: string
  architect: string
  diplomat: string
  sage: string
}

/**
 * Full 64-entry template database.
 * Use HEXAGRAM_PROMPT_TEMPLATES[id] to get all 6 face-angled questions for a hexagram.
 */
export const HEXAGRAM_PROMPT_TEMPLATES: Record<number, IChingPromptTemplateEntry> = {
  1: {
    name: 'Creative Power',
    tone: 'Rising Energy',
    base: 'What is being called into existence through you right now?',
    shaman: 'What in your body knows the answer to this before your mind does? What is being called into existence through you right now?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is being called into existence through you right now?',
    regent: 'What serves the long arc here, even if it costs the short game? What is being called into existence through you right now?',
    architect: 'What is the precise structure or strategy this requires? What is being called into existence through you right now?',
    diplomat: 'What bridge can you build between your need and theirs? What is being called into existence through you right now?',
    sage: 'What has someone wiser than you already learned about this? What is being called into existence through you right now?',
  },
  2: {
    name: 'Supportive Power',
    tone: 'Receptivity',
    base: 'What is asking to be received rather than forced?',
    shaman: 'What in your body knows the answer to this before your mind does? What is asking to be received rather than forced?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is asking to be received rather than forced?',
    regent: 'What serves the long arc here, even if it costs the short game? What is asking to be received rather than forced?',
    architect: 'What is the precise structure or strategy this requires? What is asking to be received rather than forced?',
    diplomat: 'What bridge can you build between your need and theirs? What is asking to be received rather than forced?',
    sage: 'What has someone wiser than you already learned about this? What is asking to be received rather than forced?',
  },
  3: {
    name: 'Initial Challenge',
    tone: 'Overcoming obstacles',
    base: 'What difficulty is actually the necessary first step of something important?',
    shaman: 'What in your body knows the answer to this before your mind does? What difficulty is actually the necessary first step of something important?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What difficulty is actually the necessary first step of something important?',
    regent: 'What serves the long arc here, even if it costs the short game? What difficulty is actually the necessary first step of something important?',
    architect: 'What is the precise structure or strategy this requires? What difficulty is actually the necessary first step of something important?',
    diplomat: 'What bridge can you build between your need and theirs? What difficulty is actually the necessary first step of something important?',
    sage: 'What has someone wiser than you already learned about this? What difficulty is actually the necessary first step of something important?',
  },
  4: {
    name: 'Naiveté',
    tone: 'Seek Wisdom',
    base: 'Where is your ignorance actually a gift that lets you see what experts miss?',
    shaman: 'What in your body knows the answer to this before your mind does? Where is your ignorance actually a gift that lets you see what experts miss?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? Where is your ignorance actually a gift that lets you see what experts miss?',
    regent: 'What serves the long arc here, even if it costs the short game? Where is your ignorance actually a gift that lets you see what experts miss?',
    architect: 'What is the precise structure or strategy this requires? Where is your ignorance actually a gift that lets you see what experts miss?',
    diplomat: 'What bridge can you build between your need and theirs? Where is your ignorance actually a gift that lets you see what experts miss?',
    sage: 'What has someone wiser than you already learned about this? Where is your ignorance actually a gift that lets you see what experts miss?',
  },
  5: {
    name: 'Patience',
    tone: 'Cultivate Patience',
    base: 'What is being asked of you that requires you to wait without losing your center?',
    shaman: 'What in your body knows the answer to this before your mind does? What is being asked of you that requires you to wait without losing your center?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is being asked of you that requires you to wait without losing your center?',
    regent: 'What serves the long arc here, even if it costs the short game? What is being asked of you that requires you to wait without losing your center?',
    architect: 'What is the precise structure or strategy this requires? What is being asked of you that requires you to wait without losing your center?',
    diplomat: 'What bridge can you build between your need and theirs? What is being asked of you that requires you to wait without losing your center?',
    sage: 'What has someone wiser than you already learned about this? What is being asked of you that requires you to wait without losing your center?',
  },
  6: {
    name: 'The Trial',
    tone: 'Conflict Management',
    base: 'What conflict is asking you to hold steady rather than resolve?',
    shaman: 'What in your body knows the answer to this before your mind does? What conflict is asking you to hold steady rather than resolve?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What conflict is asking you to hold steady rather than resolve?',
    regent: 'What serves the long arc here, even if it costs the short game? What conflict is asking you to hold steady rather than resolve?',
    architect: 'What is the precise structure or strategy this requires? What conflict is asking you to hold steady rather than resolve?',
    diplomat: 'What bridge can you build between your need and theirs? What conflict is asking you to hold steady rather than resolve?',
    sage: 'What has someone wiser than you already learned about this? What conflict is asking you to hold steady rather than resolve?',
  },
  7: {
    name: 'The Army',
    tone: 'Unify Ambitions',
    base: 'What requires you to organize your will and the wills of others toward a single end?',
    shaman: 'What in your body knows the answer to this before your mind does? What requires you to organize your will and the wills of others toward a single end?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What requires you to organize your will and the wills of others toward a single end?',
    regent: 'What serves the long arc here, even if it costs the short game? What requires you to organize your will and the wills of others toward a single end?',
    architect: 'What is the precise structure or strategy this requires? What requires you to organize your will and the wills of others toward a single end?',
    diplomat: 'What bridge can you build between your need and theirs? What requires you to organize your will and the wills of others toward a single end?',
    sage: 'What has someone wiser than you already learned about this? What requires you to organize your will and the wills of others toward a single end?',
  },
  8: {
    name: 'Alliance',
    tone: 'Unity and Leadership',
    base: 'What becomes possible when you stop working alone and join with others?',
    shaman: 'What in your body knows the answer to this before your mind does? What becomes possible when you stop working alone and join with others?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What becomes possible when you stop working alone and join with others?',
    regent: 'What serves the long arc here, even if it costs the short game? What becomes possible when you stop working alone and join with others?',
    architect: 'What is the precise structure or strategy this requires? What becomes possible when you stop working alone and join with others?',
    diplomat: 'What bridge can you build between your need and theirs? What becomes possible when you stop working alone and join with others?',
    sage: 'What has someone wiser than you already learned about this? What becomes possible when you stop working alone and join with others?',
  },
  9: {
    name: 'Cultivate Gently',
    tone: 'Gentle Refinement',
    base: 'What needs gentle tending rather than forceful intervention to become what it should?',
    shaman: 'What in your body knows the answer to this before your mind does? What needs gentle tending rather than forceful intervention to become what it should?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What needs gentle tending rather than forceful intervention to become what it should?',
    regent: 'What serves the long arc here, even if it costs the short game? What needs gentle tending rather than forceful intervention to become what it should?',
    architect: 'What is the precise structure or strategy this requires? What needs gentle tending rather than forceful intervention to become what it should?',
    diplomat: 'What bridge can you build between your need and theirs? What needs gentle tending rather than forceful intervention to become what it should?',
    sage: 'What has someone wiser than you already learned about this? What needs gentle tending rather than forceful intervention to become what it should?',
  },
  10: {
    name: 'Treading',
    tone: 'High Stakes',
    base: 'What requires careful, precise behavior in a situation where the margin for error is small?',
    shaman: 'What in your body knows the answer to this before your mind does? What requires careful, precise behavior in a situation where the margin for error is small?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What requires careful, precise behavior in a situation where the margin for error is small?',
    regent: 'What serves the long arc here, even if it costs the short game? What requires careful, precise behavior in a situation where the margin for error is small?',
    architect: 'What is the precise structure or strategy this requires? What requires careful, precise behavior in a situation where the margin for error is small?',
    diplomat: 'What bridge can you build between your need and theirs? What requires careful, precise behavior in a situation where the margin for error is small?',
    sage: 'What has someone wiser than you already learned about this? What requires careful, precise behavior in a situation where the margin for error is small?',
  },
  11: {
    name: 'Harmony',
    tone: 'Balance & Prosperity',
    base: 'What is in balance right now, and what would disrupt that balance if changed?',
    shaman: 'What in your body knows the answer to this before your mind does? What is in balance right now, and what would disrupt that balance if changed?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is in balance right now, and what would disrupt that balance if changed?',
    regent: 'What serves the long arc here, even if it costs the short game? What is in balance right now, and what would disrupt that balance if changed?',
    architect: 'What is the precise structure or strategy this requires? What is in balance right now, and what would disrupt that balance if changed?',
    diplomat: 'What bridge can you build between your need and theirs? What is in balance right now, and what would disrupt that balance if changed?',
    sage: 'What has someone wiser than you already learned about this? What is in balance right now, and what would disrupt that balance if changed?',
  },
  12: {
    name: 'Stalemate',
    tone: 'Blocked Flow',
    base: 'What has stopped flowing, and what would need to change for things to move again?',
    shaman: 'What in your body knows the answer to this before your mind does? What has stopped flowing, and what would need to change for things to move again?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What has stopped flowing, and what would need to change for things to move again?',
    regent: 'What serves the long arc here, even if it costs the short game? What has stopped flowing, and what would need to change for things to move again?',
    architect: 'What is the precise structure or strategy this requires? What has stopped flowing, and what would need to change for things to move again?',
    diplomat: 'What bridge can you build between your need and theirs? What has stopped flowing, and what would need to change for things to move again?',
    sage: 'What has someone wiser than you already learned about this? What has stopped flowing, and what would need to change for things to move again?',
  },
  13: {
    name: 'Fellowship',
    tone: 'Community, Generosity',
    base: 'What opens when you step out of isolation and into genuine community with others?',
    shaman: 'What in your body knows the answer to this before your mind does? What opens when you step out of isolation and into genuine community with others?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What opens when you step out of isolation and into genuine community with others?',
    regent: 'What serves the long arc here, even if it costs the short game? What opens when you step out of isolation and into genuine community with others?',
    architect: 'What is the precise structure or strategy this requires? What opens when you step out of isolation and into genuine community with others?',
    diplomat: 'What bridge can you build between your need and theirs? What opens when you step out of isolation and into genuine community with others?',
    sage: 'What has someone wiser than you already learned about this? What opens when you step out of isolation and into genuine community with others?',
  },
  14: {
    name: 'Accolades',
    tone: 'Great Blessings',
    base: 'What great possession or blessing has come into your life, and what does it ask of you to steward it well?',
    shaman: 'What in your body knows the answer to this before your mind does? What great possession or blessing has come into your life, and what does it ask of you to steward it well?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What great possession or blessing has come into your life, and what does it ask of you to steward it well?',
    regent: 'What serves the long arc here, even if it costs the short game? What great possession or blessing has come into your life, and what does it ask of you to steward it well?',
    architect: 'What is the precise structure or strategy this requires? What great possession or blessing has come into your life, and what does it ask of you to steward it well?',
    diplomat: 'What bridge can you build between your need and theirs? What great possession or blessing has come into your life, and what does it ask of you to steward it well?',
    sage: 'What has someone wiser than you already learned about this? What great possession or blessing has come into your life, and what does it ask of you to steward it well?',
  },
  15: {
    name: 'Modesty',
    tone: 'Humility, Temperance',
    base: 'What would become possible if you stopped trying to be more than you are?',
    shaman: 'What in your body knows the answer to this before your mind does? What would become possible if you stopped trying to be more than you are?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What would become possible if you stopped trying to be more than you are?',
    regent: 'What serves the long arc here, even if it costs the short game? What would become possible if you stopped trying to be more than you are?',
    architect: 'What is the precise structure or strategy this requires? What would become possible if you stopped trying to be more than you are?',
    diplomat: 'What bridge can you build between your need and theirs? What would become possible if you stopped trying to be more than you are?',
    sage: 'What has someone wiser than you already learned about this? What would become possible if you stopped trying to be more than you are?',
  },
  16: {
    name: 'Enthusiasm',
    tone: 'Motivated Action',
    base: 'What is asking for your wholehearted energy and commitment right now?',
    shaman: 'What in your body knows the answer to this before your mind does? What is asking for your wholehearted energy and commitment right now?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is asking for your wholehearted energy and commitment right now?',
    regent: 'What serves the long arc here, even if it costs the short game? What is asking for your wholehearted energy and commitment right now?',
    architect: 'What is the precise structure or strategy this requires? What is asking for your wholehearted energy and commitment right now?',
    diplomat: 'What bridge can you build between your need and theirs? What is asking for your wholehearted energy and commitment right now?',
    sage: 'What has someone wiser than you already learned about this? What is asking for your wholehearted energy and commitment right now?',
  },
  17: {
    name: 'Inspiring Followers',
    tone: 'Leadership through Service',
    base: "What opportunity is actually available to you right now, if you're willing to follow where it leads?",
    shaman: "What in your body knows the answer to this before your mind does? What opportunity is actually available to you right now, if you're willing to follow where it leads?",
    challenger: "What are you avoiding about this? What would the opposition say if you faced it? What opportunity is actually available to you right now, if you're willing to follow where it leads?",
    regent: "What serves the long arc here, even if it costs the short game? What opportunity is actually available to you right now, if you're willing to follow where it leads?",
    architect: "What is the precise structure or strategy this requires? What opportunity is actually available to you right now, if you're willing to follow where it leads?",
    diplomat: "What bridge can you build between your need and theirs? What opportunity is actually available to you right now, if you're willing to follow where it leads?",
    sage: "What has someone wiser than you already learned about this? What opportunity is actually available to you right now, if you're willing to follow where it leads?",
  },
  18: {
    name: 'Decay',
    tone: 'Renewal, Action',
    base: 'What needs to be corrected or renewed before it can become what it should?',
    shaman: 'What in your body knows the answer to this before your mind does? What needs to be corrected or renewed before it can become what it should?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What needs to be corrected or renewed before it can become what it should?',
    regent: 'What serves the long arc here, even if it costs the short game? What needs to be corrected or renewed before it can become what it should?',
    architect: 'What is the precise structure or strategy this requires? What needs to be corrected or renewed before it can become what it should?',
    diplomat: 'What bridge can you build between your need and theirs? What needs to be corrected or renewed before it can become what it should?',
    sage: 'What has someone wiser than you already learned about this? What needs to be corrected or renewed before it can become what it should?',
  },
  19: {
    name: 'Spring is Coming',
    tone: 'Renewal',
    base: 'What approach is arriving at the right moment — and what should you do to meet it?',
    shaman: 'What in your body knows the answer to this before your mind does? What approach is arriving at the right moment — and what should you do to meet it?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What approach is arriving at the right moment — and what should you do to meet it?',
    regent: 'What serves the long arc here, even if it costs the short game? What approach is arriving at the right moment — and what should you do to meet it?',
    architect: 'What is the precise structure or strategy this requires? What approach is arriving at the right moment — and what should you do to meet it?',
    diplomat: 'What bridge can you build between your need and theirs? What approach is arriving at the right moment — and what should you do to meet it?',
    sage: 'What has someone wiser than you already learned about this? What approach is arriving at the right moment — and what should you do to meet it?',
  },
  20: {
    name: 'Observation',
    tone: 'Careful Consideration',
    base: 'What needs your sustained and careful attention before you act?',
    shaman: 'What in your body knows the answer to this before your mind does? What needs your sustained and careful attention before you act?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What needs your sustained and careful attention before you act?',
    regent: 'What serves the long arc here, even if it costs the short game? What needs your sustained and careful attention before you act?',
    architect: 'What is the precise structure or strategy this requires? What needs your sustained and careful attention before you act?',
    diplomat: 'What bridge can you build between your need and theirs? What needs your sustained and careful attention before you act?',
    sage: 'What has someone wiser than you already learned about this? What needs your sustained and careful attention before you act?',
  },
  21: {
    name: 'Bite Through',
    tone: 'Overcoming Obstacles',
    base: 'What must you break through or bite through to get to what you actually need?',
    shaman: 'What in your body knows the answer to this before your mind does? What must you break through or bite through to get to what you actually need?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What must you break through or bite through to get to what you actually need?',
    regent: 'What serves the long arc here, even if it costs the short game? What must you break through or bite through to get to what you actually need?',
    architect: 'What is the precise structure or strategy this requires? What must you break through or bite through to get to what you actually need?',
    diplomat: 'What bridge can you build between your need and theirs? What must you break through or bite through to get to what you actually need?',
    sage: 'What has someone wiser than you already learned about this? What must you break through or bite through to get to what you actually need?',
  },
  22: {
    name: 'Luminosity',
    tone: 'Character Building',
    base: 'What is worth refining or adorning about yourself or your situation right now?',
    shaman: 'What in your body knows the answer to this before your mind does? What is worth refining or adorning about yourself or your situation right now?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is worth refining or adorning about yourself or your situation right now?',
    regent: 'What serves the long arc here, even if it costs the short game? What is worth refining or adorning about yourself or your situation right now?',
    architect: 'What is the precise structure or strategy this requires? What is worth refining or adorning about yourself or your situation right now?',
    diplomat: 'What bridge can you build between your need and theirs? What is worth refining or adorning about yourself or your situation right now?',
    sage: 'What has someone wiser than you already learned about this? What is worth refining or adorning about yourself or your situation right now?',
  },
  23: {
    name: 'Partition',
    tone: 'Caution, Patience',
    base: 'What is crumbling or separating, and should you let it go rather than hold it together?',
    shaman: 'What in your body knows the answer to this before your mind does? What is crumbling or separating, and should you let it go rather than hold it together?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is crumbling or separating, and should you let it go rather than hold it together?',
    regent: 'What serves the long arc here, even if it costs the short game? What is crumbling or separating, and should you let it go rather than hold it together?',
    architect: 'What is the precise structure or strategy this requires? What is crumbling or separating, and should you let it go rather than hold it together?',
    diplomat: 'What bridge can you build between your need and theirs? What is crumbling or separating, and should you let it go rather than hold it together?',
    sage: 'What has someone wiser than you already learned about this? What is crumbling or separating, and should you let it go rather than hold it together?',
  },
  24: {
    name: 'Repose',
    tone: 'Conserve Strength',
    base: 'What needs to return to its source or root before it can move forward again?',
    shaman: 'What in your body knows the answer to this before your mind does? What needs to return to its source or root before it can move forward again?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What needs to return to its source or root before it can move forward again?',
    regent: 'What serves the long arc here, even if it costs the short game? What needs to return to its source or root before it can move forward again?',
    architect: 'What is the precise structure or strategy this requires? What needs to return to its source or root before it can move forward again?',
    diplomat: 'What bridge can you build between your need and theirs? What needs to return to its source or root before it can move forward again?',
    sage: 'What has someone wiser than you already learned about this? What needs to return to its source or root before it can move forward again?',
  },
  25: {
    name: 'Without Folly',
    tone: 'Common Sense',
    base: 'What would happen if you acted with complete sincerity and without self-deception right now?',
    shaman: 'What in your body knows the answer to this before your mind does? What would happen if you acted with complete sincerity and without self-deception right now?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What would happen if you acted with complete sincerity and without self-deception right now?',
    regent: 'What serves the long arc here, even if it costs the short game? What would happen if you acted with complete sincerity and without self-deception right now?',
    architect: 'What is the precise structure or strategy this requires? What would happen if you acted with complete sincerity and without self-deception right now?',
    diplomat: 'What bridge can you build between your need and theirs? What would happen if you acted with complete sincerity and without self-deception right now?',
    sage: 'What has someone wiser than you already learned about this? What would happen if you acted with complete sincerity and without self-deception right now?',
  },
  26: {
    name: 'Cultivate the Supreme',
    tone: 'Restraint and Power',
    base: 'What great force are you containing, and what would releasing it require of you?',
    shaman: 'What in your body knows the answer to this before your mind does? What great force are you containing, and what would releasing it require of you?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What great force are you containing, and what would releasing it require of you?',
    regent: 'What serves the long arc here, even if it costs the short game? What great force are you containing, and what would releasing it require of you?',
    architect: 'What is the precise structure or strategy this requires? What great force are you containing, and what would releasing it require of you?',
    diplomat: 'What bridge can you build between your need and theirs? What great force are you containing, and what would releasing it require of you?',
    sage: 'What has someone wiser than you already learned about this? What great force are you containing, and what would releasing it require of you?',
  },
  27: {
    name: 'Receive Nourishment',
    tone: 'Nurturing Advice',
    base: "What are you nourishing, and is what you're feeding yourself actually what you need?",
    shaman: "What in your body knows the answer to this before your mind does? What are you nourishing, and is what you're feeding yourself actually what you need?",
    challenger: "What are you avoiding about this? What would the opposition say if you faced it? What are you nourishing, and is what you're feeding yourself actually what you need?",
    regent: "What serves the long arc here, even if it costs the short game? What are you nourishing, and is what you're feeding yourself actually what you need?",
    architect: "What is the precise structure or strategy this requires? What are you nourishing, and is what you're feeding yourself actually what you need?",
    diplomat: "What bridge can you build between your need and theirs? What are you nourishing, and is what you're feeding yourself actually what you need?",
    sage: "What has someone wiser than you already learned about this? What are you nourishing, and is what you're feeding yourself actually what you need?",
  },
  28: {
    name: 'Undertake the Great',
    tone: 'Critical Juncture',
    base: 'What watershed moment is approaching, and what does it ask of you to meet it well?',
    shaman: 'What in your body knows the answer to this before your mind does? What watershed moment is approaching, and what does it ask of you to meet it well?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What watershed moment is approaching, and what does it ask of you to meet it well?',
    regent: 'What serves the long arc here, even if it costs the short game? What watershed moment is approaching, and what does it ask of you to meet it well?',
    architect: 'What is the precise structure or strategy this requires? What watershed moment is approaching, and what does it ask of you to meet it well?',
    diplomat: 'What bridge can you build between your need and theirs? What watershed moment is approaching, and what does it ask of you to meet it well?',
    sage: 'What has someone wiser than you already learned about this? What watershed moment is approaching, and what does it ask of you to meet it well?',
  },
  29: {
    name: 'The Abyss',
    tone: 'Uncertainty',
    base: 'What danger are you being asked to move through rather than avoid?',
    shaman: 'What in your body knows the answer to this before your mind does? What danger are you being asked to move through rather than avoid?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What danger are you being asked to move through rather than avoid?',
    regent: 'What serves the long arc here, even if it costs the short game? What danger are you being asked to move through rather than avoid?',
    architect: 'What is the precise structure or strategy this requires? What danger are you being asked to move through rather than avoid?',
    diplomat: 'What bridge can you build between your need and theirs? What danger are you being asked to move through rather than avoid?',
    sage: 'What has someone wiser than you already learned about this? What danger are you being asked to move through rather than avoid?',
  },
  30: {
    name: 'The Spark',
    tone: 'Enlightenment',
    base: 'What is illuminating or clarifying in your life right now — and what does it ask you to see?',
    shaman: 'What in your body knows the answer to this before your mind does? What is illuminating or clarifying in your life right now — and what does it ask you to see?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is illuminating or clarifying in your life right now — and what does it ask you to see?',
    regent: 'What serves the long arc here, even if it costs the short game? What is illuminating or clarifying in your life right now — and what does it ask you to see?',
    architect: 'What is the precise structure or strategy this requires? What is illuminating or clarifying in your life right now — and what does it ask you to see?',
    diplomat: 'What bridge can you build between your need and theirs? What is illuminating or clarifying in your life right now — and what does it ask you to see?',
    sage: 'What has someone wiser than you already learned about this? What is illuminating or clarifying in your life right now — and what does it ask you to see?',
  },
  31: {
    name: 'Mutual Accord',
    tone: 'Attraction, Influence',
    base: 'What mutual attraction or influence is at work, and how should you respond to it?',
    shaman: 'What in your body knows the answer to this before your mind does? What mutual attraction or influence is at work, and how should you respond to it?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What mutual attraction or influence is at work, and how should you respond to it?',
    regent: 'What serves the long arc here, even if it costs the short game? What mutual attraction or influence is at work, and how should you respond to it?',
    architect: 'What is the precise structure or strategy this requires? What mutual attraction or influence is at work, and how should you respond to it?',
    diplomat: 'What bridge can you build between your need and theirs? What mutual attraction or influence is at work, and how should you respond to it?',
    sage: 'What has someone wiser than you already learned about this? What mutual attraction or influence is at work, and how should you respond to it?',
  },
  32: {
    name: 'The Eternal',
    tone: 'Enduring Change',
    base: 'What enduring pattern in your life needs to be recognized and worked with, not fought?',
    shaman: 'What in your body knows the answer to this before your mind does? What enduring pattern in your life needs to be recognized and worked with, not fought?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What enduring pattern in your life needs to be recognized and worked with, not fought?',
    regent: 'What serves the long arc here, even if it costs the short game? What enduring pattern in your life needs to be recognized and worked with, not fought?',
    architect: 'What is the precise structure or strategy this requires? What enduring pattern in your life needs to be recognized and worked with, not fought?',
    diplomat: 'What bridge can you build between your need and theirs? What enduring pattern in your life needs to be recognized and worked with, not fought?',
    sage: 'What has someone wiser than you already learned about this? What enduring pattern in your life needs to be recognized and worked with, not fought?',
  },
  33: {
    name: 'Withdraw',
    tone: 'Strategic Retreat',
    base: 'What requires strategic withdrawal rather than continued engagement?',
    shaman: 'What in your body knows the answer to this before your mind does? What requires strategic withdrawal rather than continued engagement?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What requires strategic withdrawal rather than continued engagement?',
    regent: 'What serves the long arc here, even if it costs the short game? What requires strategic withdrawal rather than continued engagement?',
    architect: 'What is the precise structure or strategy this requires? What requires strategic withdrawal rather than continued engagement?',
    diplomat: 'What bridge can you build between your need and theirs? What requires strategic withdrawal rather than continued engagement?',
    sage: 'What has someone wiser than you already learned about this? What requires strategic withdrawal rather than continued engagement?',
  },
  34: {
    name: 'Great Power',
    tone: 'Strength and Caution',
    base: 'Where is your great strength being tested, and what does proper deployment of power look like here?',
    shaman: 'What in your body knows the answer to this before your mind does? Where is your great strength being tested, and what does proper deployment of power look like here?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? Where is your great strength being tested, and what does proper deployment of power look like here?',
    regent: 'What serves the long arc here, even if it costs the short game? Where is your great strength being tested, and what does proper deployment of power look like here?',
    architect: 'What is the precise structure or strategy this requires? Where is your great strength being tested, and what does proper deployment of power look like here?',
    diplomat: 'What bridge can you build between your need and theirs? Where is your great strength being tested, and what does proper deployment of power look like here?',
    sage: 'What has someone wiser than you already learned about this? Where is your great strength being tested, and what does proper deployment of power look like here?',
  },
  35: {
    name: 'Advancement',
    tone: 'Progression',
    base: 'What is available to advance toward, and what is the wise pace of progression?',
    shaman: 'What in your body knows the answer to this before your mind does? What is available to advance toward, and what is the wise pace of progression?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is available to advance toward, and what is the wise pace of progression?',
    regent: 'What serves the long arc here, even if it costs the short game? What is available to advance toward, and what is the wise pace of progression?',
    architect: 'What is the precise structure or strategy this requires? What is available to advance toward, and what is the wise pace of progression?',
    diplomat: 'What bridge can you build between your need and theirs? What is available to advance toward, and what is the wise pace of progression?',
    sage: 'What has someone wiser than you already learned about this? What is available to advance toward, and what is the wise pace of progression?',
  },
  36: {
    name: 'Darkening of the Light',
    tone: 'Cautious Patience',
    base: 'What light is being hidden or obscured, and how do you act rightly under difficulty?',
    shaman: 'What in your body knows the answer to this before your mind does? What light is being hidden or obscured, and how do you act rightly under difficulty?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What light is being hidden or obscured, and how do you act rightly under difficulty?',
    regent: 'What serves the long arc here, even if it costs the short game? What light is being hidden or obscured, and how do you act rightly under difficulty?',
    architect: 'What is the precise structure or strategy this requires? What light is being hidden or obscured, and how do you act rightly under difficulty?',
    diplomat: 'What bridge can you build between your need and theirs? What light is being hidden or obscured, and how do you act rightly under difficulty?',
    sage: 'What has someone wiser than you already learned about this? What light is being hidden or obscured, and how do you act rightly under difficulty?',
  },
  37: {
    name: 'The Family',
    tone: 'Interdependence, Loyalty',
    base: 'What relationship or family structure is asking to be built or healed?',
    shaman: 'What in your body knows the answer to this before your mind does? What relationship or family structure is asking to be built or healed?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What relationship or family structure is asking to be built or healed?',
    regent: 'What serves the long arc here, even if it costs the short game? What relationship or family structure is asking to be built or healed?',
    architect: 'What is the precise structure or strategy this requires? What relationship or family structure is asking to be built or healed?',
    diplomat: 'What bridge can you build between your need and theirs? What relationship or family structure is asking to be built or healed?',
    sage: 'What has someone wiser than you already learned about this? What relationship or family structure is asking to be built or healed?',
  },
  38: {
    name: 'Opposition',
    tone: 'Conflicting Paths',
    base: 'What opposition or conflict is clarifying what you actually stand for?',
    shaman: 'What in your body knows the answer to this before your mind does? What opposition or conflict is clarifying what you actually stand for?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What opposition or conflict is clarifying what you actually stand for?',
    regent: 'What serves the long arc here, even if it costs the short game? What opposition or conflict is clarifying what you actually stand for?',
    architect: 'What is the precise structure or strategy this requires? What opposition or conflict is clarifying what you actually stand for?',
    diplomat: 'What bridge can you build between your need and theirs? What opposition or conflict is clarifying what you actually stand for?',
    sage: 'What has someone wiser than you already learned about this? What opposition or conflict is clarifying what you actually stand for?',
  },
  39: {
    name: 'An Impasse',
    tone: 'Blocked Progress',
    base: 'What blockage or impasse is redirecting you toward a different path?',
    shaman: 'What in your body knows the answer to this before your mind does? What blockage or impasse is redirecting you toward a different path?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What blockage or impasse is redirecting you toward a different path?',
    regent: 'What serves the long arc here, even if it costs the short game? What blockage or impasse is redirecting you toward a different path?',
    architect: 'What is the precise structure or strategy this requires? What blockage or impasse is redirecting you toward a different path?',
    diplomat: 'What bridge can you build between your need and theirs? What blockage or impasse is redirecting you toward a different path?',
    sage: 'What has someone wiser than you already learned about this? What blockage or impasse is redirecting you toward a different path?',
  },
  40: {
    name: 'Release of Tension',
    tone: 'Completion, Stability',
    base: 'What tension has built to the point where release and resolution are now possible?',
    shaman: 'What in your body knows the answer to this before your mind does? What tension has built to the point where release and resolution are now possible?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What tension has built to the point where release and resolution are now possible?',
    regent: 'What serves the long arc here, even if it costs the short game? What tension has built to the point where release and resolution are now possible?',
    architect: 'What is the precise structure or strategy this requires? What tension has built to the point where release and resolution are now possible?',
    diplomat: 'What bridge can you build between your need and theirs? What tension has built to the point where release and resolution are now possible?',
    sage: 'What has someone wiser than you already learned about this? What tension has built to the point where release and resolution are now possible?',
  },
  41: {
    name: 'Debilitation',
    tone: 'Endings and Change',
    base: 'What decrease or loss is actually creating space for something more essential?',
    shaman: 'What in your body knows the answer to this before your mind does? What decrease or loss is actually creating space for something more essential?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What decrease or loss is actually creating space for something more essential?',
    regent: 'What serves the long arc here, even if it costs the short game? What decrease or loss is actually creating space for something more essential?',
    architect: 'What is the precise structure or strategy this requires? What decrease or loss is actually creating space for something more essential?',
    diplomat: 'What bridge can you build between your need and theirs? What decrease or loss is actually creating space for something more essential?',
    sage: 'What has someone wiser than you already learned about this? What decrease or loss is actually creating space for something more essential?',
  },
  42: {
    name: 'Burgeoning',
    tone: 'Growth, Opportunity',
    base: 'What growth or increase is asking to be cultivated and acted upon right now?',
    shaman: 'What in your body knows the answer to this before your mind does? What growth or increase is asking to be cultivated and acted upon right now?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What growth or increase is asking to be cultivated and acted upon right now?',
    regent: 'What serves the long arc here, even if it costs the short game? What growth or increase is asking to be cultivated and acted upon right now?',
    architect: 'What is the precise structure or strategy this requires? What growth or increase is asking to be cultivated and acted upon right now?',
    diplomat: 'What bridge can you build between your need and theirs? What growth or increase is asking to be cultivated and acted upon right now?',
    sage: 'What has someone wiser than you already learned about this? What growth or increase is asking to be cultivated and acted upon right now?',
  },
  43: {
    name: 'Decisive Action',
    tone: 'Breakthrough',
    base: 'What breakthrough or decisive action is being called for that cannot be delayed?',
    shaman: 'What in your body knows the answer to this before your mind does? What breakthrough or decisive action is being called for that cannot be delayed?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What breakthrough or decisive action is being called for that cannot be delayed?',
    regent: 'What serves the long arc here, even if it costs the short game? What breakthrough or decisive action is being called for that cannot be delayed?',
    architect: 'What is the precise structure or strategy this requires? What breakthrough or decisive action is being called for that cannot be delayed?',
    diplomat: 'What bridge can you build between your need and theirs? What breakthrough or decisive action is being called for that cannot be delayed?',
    sage: 'What has someone wiser than you already learned about this? What breakthrough or decisive action is being called for that cannot be delayed?',
  },
  44: {
    name: 'Improper Meeting',
    tone: 'Caution, Independence',
    base: 'What unexpected encounter or meeting requires you to be clear about your boundaries?',
    shaman: 'What in your body knows the answer to this before your mind does? What unexpected encounter or meeting requires you to be clear about your boundaries?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What unexpected encounter or meeting requires you to be clear about your boundaries?',
    regent: 'What serves the long arc here, even if it costs the short game? What unexpected encounter or meeting requires you to be clear about your boundaries?',
    architect: 'What is the precise structure or strategy this requires? What unexpected encounter or meeting requires you to be clear about your boundaries?',
    diplomat: 'What bridge can you build between your need and theirs? What unexpected encounter or meeting requires you to be clear about your boundaries?',
    sage: 'What has someone wiser than you already learned about this? What unexpected encounter or meeting requires you to be clear about your boundaries?',
  },
  45: {
    name: 'Assembly',
    tone: 'Leadership & Preparation',
    base: 'What gathering or assembly is forming, and what is your role in bringing people together?',
    shaman: 'What in your body knows the answer to this before your mind does? What gathering or assembly is forming, and what is your role in bringing people together?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What gathering or assembly is forming, and what is your role in bringing people together?',
    regent: 'What serves the long arc here, even if it costs the short game? What gathering or assembly is forming, and what is your role in bringing people together?',
    architect: 'What is the precise structure or strategy this requires? What gathering or assembly is forming, and what is your role in bringing people together?',
    diplomat: 'What bridge can you build between your need and theirs? What gathering or assembly is forming, and what is your role in bringing people together?',
    sage: 'What has someone wiser than you already learned about this? What gathering or assembly is forming, and what is your role in bringing people together?',
  },
  46: {
    name: 'Hoist',
    tone: 'Growth and Success',
    base: 'What is rising — your standing, your situation, your influence — and how do you ascend with grace?',
    shaman: 'What in your body knows the answer to this before your mind does? What is rising — your standing, your situation, your influence — and how do you ascend with grace?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is rising — your standing, your situation, your influence — and how do you ascend with grace?',
    regent: 'What serves the long arc here, even if it costs the short game? What is rising — your standing, your situation, your influence — and how do you ascend with grace?',
    architect: 'What is the precise structure or strategy this requires? What is rising — your standing, your situation, your influence — and how do you ascend with grace?',
    diplomat: 'What bridge can you build between your need and theirs? What is rising — your standing, your situation, your influence — and how do you ascend with grace?',
    sage: 'What has someone wiser than you already learned about this? What is rising — your standing, your situation, your influence — and how do you ascend with grace?',
  },
  47: {
    name: 'Blockade',
    tone: 'Overcoming obstacles',
    base: 'What oppression or blockade are you being asked to endure without losing your inner resource?',
    shaman: 'What in your body knows the answer to this before your mind does? What oppression or blockade are you being asked to endure without losing your inner resource?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What oppression or blockade are you being asked to endure without losing your inner resource?',
    regent: 'What serves the long arc here, even if it costs the short game? What oppression or blockade are you being asked to endure without losing your inner resource?',
    architect: 'What is the precise structure or strategy this requires? What oppression or blockade are you being asked to endure without losing your inner resource?',
    diplomat: 'What bridge can you build between your need and theirs? What oppression or blockade are you being asked to endure without losing your inner resource?',
    sage: 'What has someone wiser than you already learned about this? What oppression or blockade are you being asked to endure without losing your inner resource?',
  },
  48: {
    name: 'The Fountainhead',
    tone: 'Nourishment',
    base: 'What is the wellspring or source you are drawing from, and is it sufficient for what you need?',
    shaman: 'What in your body knows the answer to this before your mind does? What is the wellspring or source you are drawing from, and is it sufficient for what you need?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is the wellspring or source you are drawing from, and is it sufficient for what you need?',
    regent: 'What serves the long arc here, even if it costs the short game? What is the wellspring or source you are drawing from, and is it sufficient for what you need?',
    architect: 'What is the precise structure or strategy this requires? What is the wellspring or source you are drawing from, and is it sufficient for what you need?',
    diplomat: 'What bridge can you build between your need and theirs? What is the wellspring or source you are drawing from, and is it sufficient for what you need?',
    sage: 'What has someone wiser than you already learned about this? What is the wellspring or source you are drawing from, and is it sufficient for what you need?',
  },
  49: {
    name: 'Revolution',
    tone: 'Change, Momentum',
    base: 'What transformation or revolution is underway, and what old form needs to be shed?',
    shaman: 'What in your body knows the answer to this before your mind does? What transformation or revolution is underway, and what old form needs to be shed?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What transformation or revolution is underway, and what old form needs to be shed?',
    regent: 'What serves the long arc here, even if it costs the short game? What transformation or revolution is underway, and what old form needs to be shed?',
    architect: 'What is the precise structure or strategy this requires? What transformation or revolution is underway, and what old form needs to be shed?',
    diplomat: 'What bridge can you build between your need and theirs? What transformation or revolution is underway, and what old form needs to be shed?',
    sage: 'What has someone wiser than you already learned about this? What transformation or revolution is underway, and what old form needs to be shed?',
  },
  50: {
    name: 'The Cauldron',
    tone: 'Nourishment & Purification',
    base: 'What is being refined, purified, or transformed in the crucible of this moment?',
    shaman: 'What in your body knows the answer to this before your mind does? What is being refined, purified, or transformed in the crucible of this moment?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is being refined, purified, or transformed in the crucible of this moment?',
    regent: 'What serves the long arc here, even if it costs the short game? What is being refined, purified, or transformed in the crucible of this moment?',
    architect: 'What is the precise structure or strategy this requires? What is being refined, purified, or transformed in the crucible of this moment?',
    diplomat: 'What bridge can you build between your need and theirs? What is being refined, purified, or transformed in the crucible of this moment?',
    sage: 'What has someone wiser than you already learned about this? What is being refined, purified, or transformed in the crucible of this moment?',
  },
  51: {
    name: 'Jolt',
    tone: 'Sudden Change',
    base: 'What sudden shock or awakening is cracking something open that needed to be broken?',
    shaman: 'What in your body knows the answer to this before your mind does? What sudden shock or awakening is cracking something open that needed to be broken?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What sudden shock or awakening is cracking something open that needed to be broken?',
    regent: 'What serves the long arc here, even if it costs the short game? What sudden shock or awakening is cracking something open that needed to be broken?',
    architect: 'What is the precise structure or strategy this requires? What sudden shock or awakening is cracking something open that needed to be broken?',
    diplomat: 'What bridge can you build between your need and theirs? What sudden shock or awakening is cracking something open that needed to be broken?',
    sage: 'What has someone wiser than you already learned about this? What sudden shock or awakening is cracking something open that needed to be broken?',
  },
  52: {
    name: 'Listen to the Wind',
    tone: 'Calm and Silent',
    base: 'What requires you to become still, quiet, and focused before anything else?',
    shaman: 'What in your body knows the answer to this before your mind does? What requires you to become still, quiet, and focused before anything else?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What requires you to become still, quiet, and focused before anything else?',
    regent: 'What serves the long arc here, even if it costs the short game? What requires you to become still, quiet, and focused before anything else?',
    architect: 'What is the precise structure or strategy this requires? What requires you to become still, quiet, and focused before anything else?',
    diplomat: 'What bridge can you build between your need and theirs? What requires you to become still, quiet, and focused before anything else?',
    sage: 'What has someone wiser than you already learned about this? What requires you to become still, quiet, and focused before anything else?',
  },
  53: {
    name: 'Steadfast',
    tone: 'Patience, Growth',
    base: 'What gradual and steady development is underway that rewards patient persistence?',
    shaman: 'What in your body knows the answer to this before your mind does? What gradual and steady development is underway that rewards patient persistence?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What gradual and steady development is underway that rewards patient persistence?',
    regent: 'What serves the long arc here, even if it costs the short game? What gradual and steady development is underway that rewards patient persistence?',
    architect: 'What is the precise structure or strategy this requires? What gradual and steady development is underway that rewards patient persistence?',
    diplomat: 'What bridge can you build between your need and theirs? What gradual and steady development is underway that rewards patient persistence?',
    sage: 'What has someone wiser than you already learned about this? What gradual and steady development is underway that rewards patient persistence?',
  },
  54: {
    name: 'Marrying Maiden',
    tone: 'Caution, Patience',
    base: 'What dynamic or energetic exchange is occurring, and what do proper boundaries look like in this?',
    shaman: 'What in your body knows the answer to this before your mind does? What dynamic or energetic exchange is occurring, and what do proper boundaries look like in this?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What dynamic or energetic exchange is occurring, and what do proper boundaries look like in this?',
    regent: 'What serves the long arc here, even if it costs the short game? What dynamic or energetic exchange is occurring, and what do proper boundaries look like in this?',
    architect: 'What is the precise structure or strategy this requires? What dynamic or energetic exchange is occurring, and what do proper boundaries look like in this?',
    diplomat: 'What bridge can you build between your need and theirs? What dynamic or energetic exchange is occurring, and what do proper boundaries look like in this?',
    sage: 'What has someone wiser than you already learned about this? What dynamic or energetic exchange is occurring, and what do proper boundaries look like in this?',
  },
  55: {
    name: 'Opulence',
    tone: 'Abundance and Change',
    base: 'What fullness or abundance has arrived, and what does stewardship of it require?',
    shaman: 'What in your body knows the answer to this before your mind does? What fullness or abundance has arrived, and what does stewardship of it require?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What fullness or abundance has arrived, and what does stewardship of it require?',
    regent: 'What serves the long arc here, even if it costs the short game? What fullness or abundance has arrived, and what does stewardship of it require?',
    architect: 'What is the precise structure or strategy this requires? What fullness or abundance has arrived, and what does stewardship of it require?',
    diplomat: 'What bridge can you build between your need and theirs? What fullness or abundance has arrived, and what does stewardship of it require?',
    sage: 'What has someone wiser than you already learned about this? What fullness or abundance has arrived, and what does stewardship of it require?',
  },
  56: {
    name: 'The Wanderer',
    tone: 'Cautious Integration',
    base: 'What is the quality of your wandering — are you moving with purpose or just moving?',
    shaman: 'What in your body knows the answer to this before your mind does? What is the quality of your wandering — are you moving with purpose or just moving?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is the quality of your wandering — are you moving with purpose or just moving?',
    regent: 'What serves the long arc here, even if it costs the short game? What is the quality of your wandering — are you moving with purpose or just moving?',
    architect: 'What is the precise structure or strategy this requires? What is the quality of your wandering — are you moving with purpose or just moving?',
    diplomat: 'What bridge can you build between your need and theirs? What is the quality of your wandering — are you moving with purpose or just moving?',
    sage: 'What has someone wiser than you already learned about this? What is the quality of your wandering — are you moving with purpose or just moving?',
  },
  57: {
    name: 'Use Gentle Force',
    tone: 'Subtle Influence',
    base: 'What requires persistent, gentle pressure over time rather than immediate force?',
    shaman: 'What in your body knows the answer to this before your mind does? What requires persistent, gentle pressure over time rather than immediate force?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What requires persistent, gentle pressure over time rather than immediate force?',
    regent: 'What serves the long arc here, even if it costs the short game? What requires persistent, gentle pressure over time rather than immediate force?',
    architect: 'What is the precise structure or strategy this requires? What requires persistent, gentle pressure over time rather than immediate force?',
    diplomat: 'What bridge can you build between your need and theirs? What requires persistent, gentle pressure over time rather than immediate force?',
    sage: 'What has someone wiser than you already learned about this? What requires persistent, gentle pressure over time rather than immediate force?',
  },
  58: {
    name: 'Joyous Exchange',
    tone: 'Exchange, Joy',
    base: 'What exchange or dialogue is generating joy, and how do you receive what it offers?',
    shaman: 'What in your body knows the answer to this before your mind does? What exchange or dialogue is generating joy, and how do you receive what it offers?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What exchange or dialogue is generating joy, and how do you receive what it offers?',
    regent: 'What serves the long arc here, even if it costs the short game? What exchange or dialogue is generating joy, and how do you receive what it offers?',
    architect: 'What is the precise structure or strategy this requires? What exchange or dialogue is generating joy, and how do you receive what it offers?',
    diplomat: 'What bridge can you build between your need and theirs? What exchange or dialogue is generating joy, and how do you receive what it offers?',
    sage: 'What has someone wiser than you already learned about this? What exchange or dialogue is generating joy, and how do you receive what it offers?',
  },
  59: {
    name: 'Making Waves',
    tone: 'Reform, Change',
    base: 'What disruption or wave is asking you to reform rather than resist?',
    shaman: 'What in your body knows the answer to this before your mind does? What disruption or wave is asking you to reform rather than resist?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What disruption or wave is asking you to reform rather than resist?',
    regent: 'What serves the long arc here, even if it costs the short game? What disruption or wave is asking you to reform rather than resist?',
    architect: 'What is the precise structure or strategy this requires? What disruption or wave is asking you to reform rather than resist?',
    diplomat: 'What bridge can you build between your need and theirs? What disruption or wave is asking you to reform rather than resist?',
    sage: 'What has someone wiser than you already learned about this? What disruption or wave is asking you to reform rather than resist?',
  },
  60: {
    name: 'Boundaries',
    tone: 'Discipline, Purpose',
    base: 'What limits or boundaries are actually serving you by defining what is possible?',
    shaman: 'What in your body knows the answer to this before your mind does? What limits or boundaries are actually serving you by defining what is possible?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What limits or boundaries are actually serving you by defining what is possible?',
    regent: 'What serves the long arc here, even if it costs the short game? What limits or boundaries are actually serving you by defining what is possible?',
    architect: 'What is the precise structure or strategy this requires? What limits or boundaries are actually serving you by defining what is possible?',
    diplomat: 'What bridge can you build between your need and theirs? What limits or boundaries are actually serving you by defining what is possible?',
    sage: 'What has someone wiser than you already learned about this? What limits or boundaries are actually serving you by defining what is possible?',
  },
  61: {
    name: 'Faith Within',
    tone: 'Inner Truth',
    base: 'Where is your inner truth pointing, even if no one else can see or confirm it?',
    shaman: 'What in your body knows the answer to this before your mind does? Where is your inner truth pointing, even if no one else can see or confirm it?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? Where is your inner truth pointing, even if no one else can see or confirm it?',
    regent: 'What serves the long arc here, even if it costs the short game? Where is your inner truth pointing, even if no one else can see or confirm it?',
    architect: 'What is the precise structure or strategy this requires? Where is your inner truth pointing, even if no one else can see or confirm it?',
    diplomat: 'What bridge can you build between your need and theirs? Where is your inner truth pointing, even if no one else can see or confirm it?',
    sage: 'What has someone wiser than you already learned about this? Where is your inner truth pointing, even if no one else can see or confirm it?',
  },
  62: {
    name: 'Pay Attention to Details',
    tone: 'Attention to Detail',
    base: 'What small detail or precise attention is the gateway to everything else?',
    shaman: 'What in your body knows the answer to this before your mind does? What small detail or precise attention is the gateway to everything else?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What small detail or precise attention is the gateway to everything else?',
    regent: 'What serves the long arc here, even if it costs the short game? What small detail or precise attention is the gateway to everything else?',
    architect: 'What is the precise structure or strategy this requires? What small detail or precise attention is the gateway to everything else?',
    diplomat: 'What bridge can you build between your need and theirs? What small detail or precise attention is the gateway to everything else?',
    sage: 'What has someone wiser than you already learned about this? What small detail or precise attention is the gateway to everything else?',
  },
  63: {
    name: 'After the Ending',
    tone: 'Cautious Progress',
    base: 'What has reached near-completion, and what does careful consolidation after success require?',
    shaman: 'What in your body knows the answer to this before your mind does? What has reached near-completion, and what does careful consolidation after success require?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What has reached near-completion, and what does careful consolidation after success require?',
    regent: 'What serves the long arc here, even if it costs the short game? What has reached near-completion, and what does careful consolidation after success require?',
    architect: 'What is the precise structure or strategy this requires? What has reached near-completion, and what does careful consolidation after success require?',
    diplomat: 'What bridge can you build between your need and theirs? What has reached near-completion, and what does careful consolidation after success require?',
    sage: 'What has someone wiser than you already learned about this? What has reached near-completion, and what does careful consolidation after success require?',
  },
  64: {
    name: 'Toward an End',
    tone: 'Approaching Completion',
    base: 'What is nearly finished but not quite — and what is the final stretch asking of you?',
    shaman: 'What in your body knows the answer to this before your mind does? What is nearly finished but not quite — and what is the final stretch asking of you?',
    challenger: 'What are you avoiding about this? What would the opposition say if you faced it? What is nearly finished but not quite — and what is the final stretch asking of you?',
    regent: 'What serves the long arc here, even if it costs the short game? What is nearly finished but not quite — and what is the final stretch asking of you?',
    architect: 'What is the precise structure or strategy this requires? What is nearly finished but not quite — and what is the final stretch asking of you?',
    diplomat: 'What bridge can you build between your need and theirs? What is nearly finished but not quite — and what is the final stretch asking of you?',
    sage: 'What has someone wiser than you already learned about this? What is nearly finished but not quite — and what is the final stretch asking of you?',
  },

}

/**
 * Get the face-angled question for a specific hexagram + face combination.
 * Returns the full entry if face is omitted.
 */
export function getIChingPromptTemplate(
  hexagramId: number,
  face?: GameMasterFace
): IChingPromptTemplateEntry | string {
  const entry = HEXAGRAM_PROMPT_TEMPLATES[hexagramId]
  if (!entry) {
    return `What does hexagram ${hexagramId} ask of you?`
  }
  if (!face) return entry
  return entry[face] ?? entry.base
}

/**
 * Get all face questions for a hexagram as an array (for face-picker UI).
 */
export function getFaceQuestionsForHexagram(hexagramId: number): Array<{ face: GameMasterFace; question: string }> {
  const entry = HEXAGRAM_PROMPT_TEMPLATES[hexagramId]
  if (!entry) return []
  return [
    { face: 'shaman',     question: entry.shaman },
    { face: 'challenger', question: entry.challenger },
    { face: 'regent',     question: entry.regent },
    { face: 'architect',  question: entry.architect },
    { face: 'diplomat',   question: entry.diplomat },
    { face: 'sage',       question: entry.sage },
  ]
}
