'use client'

import { useMemo, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { askBudgetLineQuestion, saveVolunteerCfoAgreement, submitFamilyFundingDecision } from '@/actions/family-support'
import { usd, type FamilyFinancialSnapshot } from '@/lib/family-support/financial-snapshot'
import { Reflection321 } from './Reflection321'
import { ScenarioExplorer } from './ScenarioExplorer'
import { BudgetQuestionThread } from './BudgetQuestionThread'
import { WeeklyReview } from './WeeklyReview'
import { AltitudeCommitment } from './AltitudeCommitment'

type RoomState = Awaited<ReturnType<typeof import('@/actions/family-support').getFamilyRoomView>>
type View = 'story' | 'decision' | 'walk' | 'budget' | 'scenario' | 'reflection' | 'cfo' | 'review'
const label: Record<string, string> = { essential: 'Essential', experiment: 'Planned experiment', covered: 'Covered', income: 'Proposed income' }

export function FamilySupportRoom({ snapshot, state }: { snapshot: FamilyFinancialSnapshot; state: RoomState }) {
  const router = useRouter()
  const [view, setView] = useState<View>('story')
  const [expanded, setExpanded] = useState<string | null>(null)
  const [customAmount, setCustomAmount] = useState('')
  const [terms, setTerms] = useState('')
  const [notice, setNotice] = useState<string | null>(null)
  const [pending, startTransition] = useTransition()
  const openQuestions = useMemo(() => state.questions.filter((q) => q.status === 'open').length, [state.questions])
  const decide = (option: 'week' | 'month' | 'ninety' | 'custom' | 'no') => startTransition(async () => {
    const amountCents = option === 'custom' ? Math.round(Number(customAmount || 0) * 100) : 0
    const result = await submitFamilyFundingDecision({ option, amountCents, terms })
    setNotice(result.ok ? 'Your decision was saved for the room.' : result.error ?? 'Unable to save your decision.')
    if (result.ok) router.refresh()
  })
  const ask = (lineItemKey: string, body: string) => startTransition(async () => {
    const result = await askBudgetLineQuestion({ lineItemKey, body })
    setNotice(result.ok ? 'Your question is now visible in the shared room.' : result.error ?? 'Unable to share your question.')
    if (result.ok) router.refresh()
  })
  return <main className="min-h-screen bg-[radial-gradient(125%_85%_at_50%_-10%,#241932_0%,#100e14_62%)] px-4 py-7 text-[#f7f2e8]">
    <div className="mx-auto max-w-4xl">
      <header className="mb-6 flex flex-col justify-between gap-4 border-b border-white/10 pb-5 sm:flex-row sm:items-end">
        <div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#d4a017]">Family contribution · repayable plan</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">A path to a clear decision</h1></div>
        <p className="max-w-xs text-sm leading-5 text-[#c6c0ca]">You can skip the story, pause anywhere, ask for a revision, or say no. Nothing here requires a yes.</p>
      </header>
      <nav aria-label="Room sections" className="mb-6 flex flex-wrap gap-2">{([['story', 'The story'], ['decision', 'Decision now'], ['budget', `Architect map${openQuestions ? ` · ${openQuestions} open` : ''}`], ['scenario', 'What if?'], ['reflection', 'Private 3·2·1'], ['cfo', 'Volunteer CFO'], ['review', 'Weekly review']] as [View, string][]).map(([key, title]) => <button key={key} onClick={() => setView(key)} className={`rounded-full px-4 py-2 text-sm font-medium ${view === key ? 'bg-[#7452b8] text-white' : 'border border-white/15 text-[#d7d0da]'}`}>{title}</button>)}</nav>
      {notice && <p role="status" className="mb-5 rounded-xl border border-[#d4a017]/30 bg-[#d4a017]/10 px-4 py-3 text-sm text-[#f7e0a0]">{notice}</p>}
      {view === 'story' && <StoryJourney onDecision={() => setView('decision')} onBudget={() => setView('budget')} onReflection={() => setView('reflection')} onCfo={() => setView('cfo')} />}
      {view === 'decision' && <Decision snapshot={snapshot} customAmount={customAmount} setCustomAmount={setCustomAmount} terms={terms} setTerms={setTerms} pending={pending} onDecide={decide} onBudget={() => setView('budget')} />}
      {view === 'walk' && <Walk onDecision={() => setView('decision')} onBudget={() => setView('budget')} />}
      {view === 'budget' && <Budget snapshot={snapshot} expanded={expanded} setExpanded={setExpanded} questions={state.questions} pending={pending} onAsk={ask} />}
      {view === 'scenario' && <ScenarioExplorer snapshot={snapshot} scenarios={state.scenarios} />}
      {view === 'reflection' && <Reflection321 initial={state.myReflection} shared={state.sharedSyntheses} />}
      {view === 'cfo' && <Cfo pending={pending} onAccept={() => startTransition(async () => { await saveVolunteerCfoAgreement(); setNotice('Volunteer CFO agreement saved.'); router.refresh() })} agreements={state.agreements.length} commitments={state.altitudeCommitments} participantId={state.participantId} />}
      {view === 'review' && <WeeklyReview reviews={state.reviews} />}
    </div>
  </main>
}

const storyBeats = [
  { face: 'Shaman', title: 'The year that brought us here', body: 'You already know much of this: finishing the book, losing the tea-store job after three days, leaving Portland, and trying to hold a future together while the ground kept moving.', choice: 'I understand the context', aside: 'I need to slow down and name what this brings up' },
  { face: 'Sage', title: 'What we are all reaching for', body: 'The external desire is a stable, successful career that brings in the money Wendell knows he can earn through his skill and the work he has built. Internally, the desire is release from daily fear, shame, and the isolation of trying to solve it all alone.', choice: 'That shared future makes sense', aside: 'Show me the concrete opportunities' },
  { face: 'Challenger', title: 'The wall is real', body: 'The tea-store job looked like the bridge and disappeared immediately. The job search has not landed yet. Meanwhile the book, coaching, events, and Flirtcraft have real potential—but need time, focus, and a small runway to become dependable income.', choice: 'I see the constraint', aside: 'I want to test the assumptions' },
  { face: 'Diplomat', title: 'The epiphany: partnership, not rescue', body: 'Past asks have often landed as “please come save me.” This asks for something different: enough context, agency, and room to negotiate so support can become a partnership rather than a silent burden for anyone.', choice: 'I can meet this as a partner', aside: 'I need to name a concern first' },
  { face: 'Architect', title: 'The plan has more than one finish line', body: 'There are two paths toward stability: a new job at $20/hour or more, and building coaching into a full-time business. The book, events, Flirtcraft, and Patreon are supporting income experiments—not promises. The budget and scenario map make every assumption inspectable.', choice: 'Show me the map', aside: 'I want to explore a different scenario' },
  { face: 'Regent', title: 'Make it a 90-day game with real governance', body: 'The invitation is to become Volunteer CFOs: a weekly check-in on job applications, marketing, revenue, spending, and next commitments. New spending above $100 and scaling ads require approval. Every dollar earned goes toward paying down the family contribution.', choice: 'I understand the accountability offer', aside: 'I want to negotiate the role' },
  { face: 'Sage', title: 'Choose the next true step', body: 'There is no hidden gate. You can fund a week, a month, or 90 days; propose another shape; ask for a pause; or say no. The point is to leave with shared context and an honest next move.', choice: 'Go to the decision', aside: 'Return to the map before deciding' },
] as const

function StoryJourney({ onDecision, onBudget, onReflection, onCfo }: { onDecision: () => void; onBudget: () => void; onReflection: () => void; onCfo: () => void }) {
  const [beat, setBeat] = useState(0)
  const current = storyBeats[beat]
  const last = beat === storyBeats.length - 1
  const advance = () => last ? onDecision() : setBeat((value) => value + 1)
  const aside = () => {
    if (current.face === 'Shaman') onReflection()
    else if (current.face === 'Regent') onCfo()
    else onBudget()
  }
  return <div className="mx-auto max-w-2xl"><div className="mb-5 flex items-center justify-between text-xs font-semibold uppercase tracking-[0.18em] text-[#aaa3af]"><span>{current.face} gate</span><span>{beat + 1} / {storyBeats.length}</span></div><div className="mb-5 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#d4a017] transition-all" style={{ width: `${((beat + 1) / storyBeats.length) * 100}%` }} /></div><Card><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#d4a017]">{current.face}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">{current.title}</h2><p className="mt-5 text-lg leading-8 text-[#e4dde8]">{current.body}</p><div className="mt-8 grid gap-3"><button onClick={advance} className="rounded-xl bg-[#7452b8] px-5 py-4 text-left text-sm font-semibold">{current.choice} <span aria-hidden="true">→</span></button><button onClick={aside} className="rounded-xl border border-white/20 px-5 py-4 text-left text-sm font-medium text-[#d7d0da]">{current.aside}</button></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm"><button onClick={onDecision} className="font-semibold text-[#e5bf4e]">Jump to the decision</button><button onClick={onBudget} className="font-semibold text-[#e5bf4e]">Open the Architect map</button>{beat > 0 && <button onClick={() => setBeat((value) => value - 1)} className="text-[#aaa3af]">Back</button>}</div></Card><p className="mt-5 text-center text-xs leading-5 text-[#aaa3af]">These are invitations to understanding, not commitments. Each gate can be skipped, revisited, or negotiated.</p></div>
}

function Card({ children }: { children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-[#19151f]/90 p-5 shadow-xl">{children}</section> }
function Decision({ snapshot, customAmount, setCustomAmount, terms, setTerms, pending, onDecide, onBudget }: { snapshot: FamilyFinancialSnapshot; customAmount: string; setCustomAmount: (v: string) => void; terms: string; setTerms: (v: string) => void; pending: boolean; onDecide: (o: 'week' | 'month' | 'ninety' | 'custom' | 'no') => void; onBudget: () => void }) {
  const options: ['week' | 'month' | 'ninety', string, number, string][] = [['week', 'Stabilize this week', snapshot.weeklyStabilizationCents, 'U-Haul, phone, food bridge, and debt payment.'], ['month', 'Fund one month', snapshot.monthRequestCents, 'Current approved runway, including the planned experiments.'], ['ninety', 'Fund 90 days', snapshot.ninetyDayCeilingCents, 'Current ceiling before proposed income.']]
  return <div className="grid gap-5"><Card><p className="text-sm leading-6 text-[#c6c0ca]">The ask is a family contribution intended to be paid back. Each month, revenue is recorded against it; the goal is three consecutive months at break-even without outside contribution.</p><div className="mt-4 flex flex-wrap gap-4"><button onClick={onBudget} className="text-sm font-semibold text-[#e5bf4e]">Inspect every line item →</button><a href="/ally/mom/budget" className="text-sm font-semibold text-[#e5bf4e]">Download full budget workbook →</a></div></Card><div className="grid gap-4 md:grid-cols-3">{options.map(([key, title, amount, detail]) => <Card key={key}><p className="text-xs uppercase tracking-wider text-[#d4a017]">{title}</p><p className="mt-2 text-3xl font-semibold">{usd(amount)}</p><p className="mt-3 min-h-12 text-sm leading-5 text-[#c6c0ca]">{detail}</p><button disabled={pending} onClick={() => onDecide(key)} className="mt-5 w-full rounded-xl bg-[#7452b8] px-4 py-3 text-sm font-semibold disabled:opacity-60">Choose this</button></Card>)}</div><Card><h2 className="text-lg font-semibold">Negotiate a different shape</h2><div className="mt-4 grid gap-3 sm:grid-cols-[180px_1fr]"><label className="grid gap-1 text-sm">Amount<input inputMode="decimal" value={customAmount} onChange={(e) => setCustomAmount(e.target.value)} placeholder="$0" className="rounded-xl border border-white/15 bg-black/20 px-3 py-2" /></label><label className="grid gap-1 text-sm">Terms or questions<textarea value={terms} onChange={(e) => setTerms(e.target.value)} className="min-h-20 rounded-xl border border-white/15 bg-black/20 px-3 py-2" placeholder="What would make this workable?" /></label></div><div className="mt-4 flex flex-wrap gap-3"><button disabled={pending} onClick={() => onDecide('custom')} className="rounded-xl bg-[#7452b8] px-4 py-3 text-sm font-semibold">Save custom proposal</button><button disabled={pending} onClick={() => onDecide('no')} className="rounded-xl border border-white/20 px-4 py-3 text-sm font-semibold">No financial contribution now</button></div></Card></div>
}
function Walk({ onDecision, onBudget }: { onDecision: () => void; onBudget: () => void }) { return <div className="grid gap-4"><Card><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#d4a017]">Shaman → Challenger → Regent → Architect</p><h2 className="mt-2 text-2xl font-semibold">A path for understanding, not a trap.</h2><p className="mt-3 leading-7 text-[#c6c0ca]">You are welcome to name what this request brings up, question its assumptions, set boundaries, and decide what is workable. The Private 3·2·1 tab is an optional practice; it never unlocks the plan or pressures a yes.</p><div className="mt-5 flex flex-wrap gap-3"><button onClick={onBudget} className="rounded-xl border border-white/20 px-4 py-3 text-sm font-semibold">Start with questions</button><button onClick={onDecision} className="rounded-xl bg-[#7452b8] px-4 py-3 text-sm font-semibold">Go to Architect</button></div></Card></div> }
function Budget({ snapshot, expanded, setExpanded, questions, pending, onAsk }: { snapshot: FamilyFinancialSnapshot; expanded: string | null; setExpanded: (v: string | null) => void; questions: RoomState['questions']; pending: boolean; onAsk: (key: string, body: string) => void }) { const [draft, setDraft] = useState(''); return <div className="grid gap-4"><Card><h2 className="text-2xl font-semibold">Budget explorer</h2><p className="mt-2 text-sm leading-6 text-[#c6c0ca]">Snapshot {snapshot.version} · {snapshot.asOf}. Open a line to understand it or post a question. Questions are shared; they are not an approval or a commitment.</p></Card>{snapshot.lines.map((line) => { const isOpen = expanded === line.key; const lineQuestions = questions.filter((q) => q.lineItemKey === line.key); return <Card key={line.key}><button onClick={() => { setExpanded(isOpen ? null : line.key); setDraft('') }} className="flex w-full items-start justify-between gap-4 text-left"><span><span className="text-xs font-semibold uppercase tracking-wider text-[#d4a017]">{label[line.category]}</span><span className="mt-1 block text-lg font-semibold">{line.name}</span><span className="mt-1 block text-sm text-[#c6c0ca]">{usd(line.amountCents)} · {line.cadence}</span></span><span className="text-[#d4a017]">{isOpen ? '−' : '+'}</span></button>{isOpen && <div className="mt-5 grid gap-4 border-t border-white/10 pt-4"><dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-[#aaa3af]">Included in</dt><dd className="mt-1">{line.includedIn}</dd></div><div><dt className="text-[#aaa3af]">Why it exists</dt><dd className="mt-1 leading-5">{line.why}</dd></div><div><dt className="text-[#aaa3af]">Assumption</dt><dd className="mt-1 leading-5">{line.assumption}</dd></div></dl><div className="rounded-xl bg-black/20 p-4"><p className="text-sm font-semibold">Ask about this line</p><textarea value={draft} onChange={(e) => setDraft(e.target.value)} className="mt-2 min-h-20 w-full rounded-lg border border-white/15 bg-[#100e14] px-3 py-2 text-sm" placeholder="What would you like clarified or challenged?" /><button disabled={pending || draft.trim().length < 2} onClick={() => { onAsk(line.key, draft); setDraft('') }} className="mt-2 rounded-lg bg-[#7452b8] px-3 py-2 text-sm font-semibold disabled:opacity-60">Post question</button></div><BudgetQuestionThread questions={lineQuestions} /></div>}</Card> })}</div> }
function Cfo({ pending, onAccept, agreements, commitments, participantId }: { pending: boolean; onAccept: () => void; agreements: number; commitments: RoomState['altitudeCommitments']; participantId: string }) { return <Card><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#d4a017]">Regent + Architect</p><h2 className="mt-2 text-2xl font-semibold">Volunteer Chief Financial Officer</h2><p className="mt-3 leading-7 text-[#c6c0ca]">This is an accountability role, not an unlimited obligation. It is recommended for one-month or 90-day support and is fully negotiable.</p><ul className="mt-5 grid gap-2 text-sm leading-6 text-[#e4dde8]"><li>Weekly review of spending, job search, revenue, and marketing.</li><li>Approval before new spending above $100.</li><li>Approval before an ad test scales.</li><li>Right to request a pause or revised plan.</li><li>Right to negotiate the funding structure.</li></ul><button disabled={pending} onClick={onAccept} className="mt-6 rounded-xl bg-[#7452b8] px-4 py-3 text-sm font-semibold disabled:opacity-60">{agreements ? 'Add my agreement' : 'Accept this role as drafted'}</button><AltitudeCommitment commitments={commitments} participantId={participantId} /></Card> }
