/**
 * ARDS Register 5 (Frame/Chrome) — four move icons, 24×24 monochrome PNGs.
 * Generated by scripts/generate-move-icons.ts; colorized via CSS filter / parent text color where needed.
 */

export const MOVE_ICON_PATHS = {
  'wake-up': '/icons/moves/wake-up.png',
  'clean-up': '/icons/moves/clean-up.png',
  'grow-up': '/icons/moves/grow-up.png',
  'show-up': '/icons/moves/show-up.png',
} as const

export type MoveIconSlug = keyof typeof MOVE_ICON_PATHS

/** Vault / config keys → icon slug */
export const VAULT_MOVE_KEY_TO_ICON: Record<'wakeUp' | 'cleanUp' | 'growUp' | 'showUp', MoveIconSlug> = {
  wakeUp: 'wake-up',
  cleanUp: 'clean-up',
  growUp: 'grow-up',
  showUp: 'show-up',
}

/** Display labels from deriveSuggestion / UI → icon slug */
export function moveLabelToIconSlug(label: string): MoveIconSlug | null {
  const m: Record<string, MoveIconSlug> = {
    'Wake Up': 'wake-up',
    'Clean Up': 'clean-up',
    'Grow Up': 'grow-up',
    'Show Up': 'show-up',
  }
  return m[label] ?? null
}
