/**
 * Baseline Narrative OS map — config-first; no DB in v0.
 * Deep links follow .specify/specs/narrative-os-map-v0/plan.md inventory.
 */

import type { NarrativeMapLink, NarrativeSpaceSection } from './types'

export const DEFAULT_CAMPAIGN_REF = 'bruised-banana'

const forestCampaign = (path: string) =>
  `${path}${path.includes('?') ? '&' : '?'}ref=${encodeURIComponent(DEFAULT_CAMPAIGN_REF)}`

export const NARRATIVE_SPACE_SECTIONS: NarrativeSpaceSection[] = [
  {
    id: 'library',
    title: 'Library',
    subtitle: 'Knowledge & discovery',
    narrativeDescription: 'Lore, rules, maps, and discoverable quests — where content becomes insight.',
    mechanicalDescription: 'Browse, read, fork paths into other spaces.',
    accentBar: 'from-emerald-500/40 to-transparent',
    items: [
      {
        id: 'lib-quests',
        label: 'Quest library',
        description: 'Browse quests, unpack moves, request new ones.',
        href: '/library',
        accent: 'border-indigo-700/50 hover:border-indigo-500/60',
        tag: 'text-indigo-400',
        moveTag: 'Grow Up',
      },
      {
        id: 'lib-wiki',
        label: 'World wiki',
        description: 'Emotional alchemy, moves, domains, player guides.',
        href: '/wiki',
        accent: 'border-zinc-600/50 hover:border-zinc-500/60',
        tag: 'text-zinc-400',
        moveTag: 'Grow Up',
      },
      {
        id: 'lib-reliquary',
        label: 'Reliquary',
        description: 'Blessed objects and collectibles you’ve earned.',
        href: '/reliquary',
        accent: 'border-yellow-700/50 hover:border-yellow-500/60',
        tag: 'text-yellow-500',
        moveTag: 'Show Up',
      },
      {
        id: 'lib-nations',
        label: 'Nations',
        description: 'Five elemental nations and their archetypes.',
        href: '/nation',
        accent: 'border-zinc-600/50 hover:border-zinc-500/60',
        tag: 'text-zinc-400',
        moveTag: 'Grow Up',
      },
    ],
  },
  {
    id: 'dojo',
    title: 'Dojo',
    subtitle: 'Practice & refinement',
    narrativeDescription: 'Safe repetition — moves, templates, and skill paths without full stakes.',
    mechanicalDescription: 'Practice moves, character paths, and unpack scaffolding.',
    accentBar: 'from-amber-500/35 to-transparent',
    items: [
      {
        id: 'dojo-moves',
        label: 'Moves in your hand',
        description: 'Transformation moves you are carrying and refining.',
        href: '/hand/moves',
        accent: 'border-amber-700/50 hover:border-amber-500/60',
        tag: 'text-amber-400',
        moveTag: 'Grow Up',
      },
      {
        id: 'dojo-character',
        label: 'Character creator',
        description: 'Archetype, nation, playbook — your expressive kit.',
        href: '/character-creator',
        accent: 'border-amber-800/50 hover:border-amber-600/60',
        tag: 'text-amber-500',
        moveTag: 'Grow Up',
      },
      {
        id: 'dojo-create',
        label: 'New character',
        description: 'Start or revisit the guided character flow.',
        href: '/character/create',
        accent: 'border-zinc-600/50 hover:border-zinc-500/60',
        tag: 'text-zinc-400',
        moveTag: 'Wake Up',
      },
    ],
  },
  {
    id: 'forest',
    title: 'Forest',
    subtitle: 'Encounters & exploration',
    narrativeDescription: 'Quests, campaigns, live play — capability meets consequence.',
    mechanicalDescription: 'Adventures, campaign field, spatial world, I Ching portals.',
    accentBar: 'from-teal-500/35 to-transparent',
    items: [
      {
        id: 'for-adventures',
        label: 'Adventures',
        description: 'Published and active journeys.',
        href: '/adventures',
        accent: 'border-teal-700/50 hover:border-teal-500/60',
        tag: 'text-teal-400',
        moveTag: 'Show Up',
      },
      {
        id: 'for-play',
        label: 'Play hub',
        description: 'Teaser loop and orientation entry.',
        href: '/play',
        accent: 'border-teal-800/50 hover:border-teal-600/60',
        tag: 'text-teal-300',
        moveTag: 'Show Up',
      },
      {
        id: 'for-hub',
        label: 'Campaign hub',
        description: 'Eight portals into the residency CYOA for this Kotter stage.',
        href: forestCampaign('/campaign/hub'),
        accent: 'border-amber-700/50 hover:border-amber-500/60',
        tag: 'text-amber-400',
        moveTag: 'Show Up',
      },
      {
        id: 'for-board',
        label: 'Campaign field',
        description: 'Eight live draws for the residency period (instance deck).',
        href: forestCampaign('/campaign/board'),
        accent: 'border-purple-700/50 hover:border-purple-600/60',
        tag: 'text-purple-400',
        moveTag: 'Show Up',
      },
      {
        id: 'for-market',
        label: 'Campaign stalls',
        description: 'List BARs and quests — mall stalls for this campaign.',
        href: forestCampaign('/campaign/marketplace'),
        accent: 'border-teal-700/50 hover:border-teal-500/60',
        tag: 'text-teal-400',
        moveTag: 'Show Up',
      },
      {
        id: 'for-lobby',
        label: 'Lobby',
        description: 'Walk the shared space; join or host a campaign room.',
        href: '/lobby',
        accent: 'border-teal-700/50 hover:border-teal-500/60',
        tag: 'text-teal-400',
        moveTag: 'Show Up',
      },
      {
        id: 'for-world',
        label: 'World room',
        description: 'Your instance spatial map.',
        href: '/world',
        accent: 'border-teal-600/50 hover:border-teal-400/60',
        tag: 'text-teal-300',
        moveTag: 'Show Up',
      },
      {
        id: 'for-iching',
        label: 'I Ching',
        description: 'Cast and read the period’s hexagram thread.',
        href: '/iching',
        accent: 'border-violet-700/50 hover:border-violet-500/60',
        tag: 'text-violet-400',
        moveTag: 'Wake Up',
      },
    ],
  },
  {
    id: 'forge',
    title: 'Forge',
    subtitle: 'Charge & integration',
    narrativeDescription: 'Metabolize friction — capture, shadow work, vault, daemons.',
    mechanicalDescription: 'Charge → BAR / quest / artifact; links into Vault for possession.',
    accentBar: 'from-sky-500/40 to-transparent',
    items: [
      {
        id: 'forge-now',
        label: 'Now (dashboard)',
        description: 'Daily check-in, compass, journeys — home surface.',
        href: '/',
        accent: 'border-emerald-800/50 hover:border-emerald-500/60',
        tag: 'text-emerald-400',
        moveTag: 'Wake Up',
      },
      {
        id: 'forge-capture',
        label: 'Capture a charge',
        description: 'Name the voltage before it dissipates.',
        href: '/capture',
        accent: 'border-emerald-900/50 hover:border-emerald-600/60',
        tag: 'text-emerald-500',
        moveTag: 'Wake Up',
      },
      {
        id: 'forge-321',
        label: '321 Shadow process',
        description: 'Face it, talk to it, be it — then turn it into a quest.',
        href: '/shadow/321',
        accent: 'border-sky-800/50 hover:border-sky-500/60',
        tag: 'text-sky-400',
        moveTag: 'Clean Up',
      },
      {
        id: 'forge-efa',
        label: 'Emotional first aid',
        description: 'Short protocols when you’re stuck or overwhelmed.',
        href: '/emotional-first-aid',
        accent: 'border-rose-800/50 hover:border-rose-500/60',
        tag: 'text-rose-400',
        moveTag: 'Clean Up',
      },
      {
        id: 'forge-vault',
        label: 'Vault',
        description: 'Your private studio — charges, quests, drafts (top nav).',
        href: '/hand',
        accent: 'border-amber-800/50 hover:border-amber-600/60',
        tag: 'text-amber-400',
        moveTag: 'Clean Up',
      },
      {
        id: 'forge-daemons',
        label: 'Daemons',
        description: 'Named patterns you’re working with.',
        href: '/daemons',
        accent: 'border-purple-800/50 hover:border-purple-500/60',
        tag: 'text-purple-400',
        moveTag: 'Grow Up',
      },
    ],
  },
]

/** Lower-traffic meta links (not a fifth space). */
export const NARRATIVE_META_LINKS: NarrativeMapLink[] = [
  {
    id: 'meta-fork',
    label: 'Fork this game',
    description: 'Deploy your own BARs Engine instance.',
    href: '/fork-game',
    accent: 'border-teal-800/40 hover:border-teal-600/50',
    tag: 'text-teal-500/80',
  },
]
