-- Migration: Add ContributionRecord and CampaignMilestoneMarker
-- CCV Phase 2 — seed_0ad7b87a2df5
-- Depends on: 20260428000000_add_campaign_contribution_visibility

-- ContributionRecord: one row per player per annotated action per campaign.
-- status='retired' means the source action was soft-archived but the record still counts.
CREATE TABLE "contribution_records" (
    "id"          TEXT NOT NULL,
    "campaignRef" TEXT NOT NULL,
    "playerId"    TEXT NOT NULL,
    "sourceType"  TEXT NOT NULL,
    "sourceId"    TEXT NOT NULL,
    "gmLabel"     TEXT NOT NULL DEFAULT '',
    "status"      TEXT NOT NULL DEFAULT 'active',
    "earnedAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "contribution_records_pkey" PRIMARY KEY ("id")
);

-- One record per (campaign, player, sourceType, sourceId) — no double-counting
CREATE UNIQUE INDEX "contribution_records_campaignRef_playerId_sourceType_sourceId_key"
    ON "contribution_records"("campaignRef", "playerId", "sourceType", "sourceId");

CREATE INDEX "contribution_records_campaignRef_playerId_idx"
    ON "contribution_records"("campaignRef", "playerId");

CREATE INDEX "contribution_records_campaignRef_status_idx"
    ON "contribution_records"("campaignRef", "status");

-- FK → players
ALTER TABLE "contribution_records"
    ADD CONSTRAINT "contribution_records_playerId_fkey"
    FOREIGN KEY ("playerId") REFERENCES "players"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

-- CampaignMilestoneMarker: GM-curated milestone with narrative text.
-- Triggers at triggerCount contributions. Generated by wizard, fully editable.
CREATE TABLE "campaign_milestone_markers" (
    "id"            TEXT NOT NULL,
    "campaignRef"   TEXT NOT NULL,
    "name"          TEXT NOT NULL,
    "triggerCount"  INTEGER NOT NULL,
    "narrativeText" TEXT NOT NULL,
    "status"        TEXT NOT NULL DEFAULT 'active',
    "sortOrder"     INTEGER NOT NULL DEFAULT 0,
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "campaign_milestone_markers_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "campaign_milestone_markers_campaignRef_status_idx"
    ON "campaign_milestone_markers"("campaignRef", "status");
