#!/usr/bin/env npx tsx
/**
 * Avatar lock-step verification — generates phase→layer matrix artifact.
 * Run: npx tsx scripts/verify-avatar-lockstep.ts
 *
 * Output: .specify/specs/avatar-character-lockstep/PHASE_LAYER_MATRIX.md
 */

import * as fs from 'fs'
import * as path from 'path'
import {
  getUnlockedLayersForProgress,
  getUnlockedLayersForNode,
  type CharacterCreatorPhase,
  type PartLayer,
} from '../src/lib/avatar-parts'

const PHASES: CharacterCreatorPhase[] = [
  'landing',
  'discovery',
  'archetype_reveal',
  'archetype_alternatives',
  'archetype_moves',
  'nation_discovery',
  'nation_moves',
  'story_community',
  'story_dreams',
  'story_fears',
  'complete',
]

const LAYERS: PartLayer[] = ['base', 'nation_body', 'archetype_outfit', 'nation_accent', 'archetype_accent']

function main() {
  const rows: string[] = []
  rows.push('# Avatar Lock-Step: Phase → Layer Matrix')
  rows.push('')
  rows.push('**Generated by**: `npx tsx scripts/verify-avatar-lockstep.ts`')
  rows.push('')
  rows.push('Verification that Character Creator phases unlock avatar layers in lock-step.')
  rows.push('')
  rows.push('## Character Creator')
  rows.push('')
  rows.push('| Phase | base | nation_body | archetype_outfit | nation_accent | archetype_accent |')
  rows.push('|-------|------|-------------|------------------|---------------|-----------------|')

  for (const phase of PHASES) {
    const layers = getUnlockedLayersForProgress('character-creator', {
      phase,
      resolvedArchetypeName: 'The Bold Heart',
      resolvedNationName: 'Argyra',
    })
    const cells = LAYERS.map((l) => (layers.includes(l) ? '✓' : ''))
    rows.push(`| ${phase} | ${cells.join(' | ')} |`)
  }

  rows.push('')
  rows.push('## BB Campaign (sample nodes)')
  rows.push('')
  rows.push('| Node | base | nation_body | archetype_outfit | nation_accent | archetype_accent |')
  rows.push('|------|------|-------------|------------------|---------------|-----------------|')

  const bbSamples: Array<{ node: string; state: Record<string, unknown> }> = [
    { node: 'BB_Start', state: {} },
    { node: 'BB_ChooseNation', state: { nationId: 'n1' } },
    { node: 'BB_SetPlaybook_1', state: { archetypeId: 'p1' } },
    { node: 'BB_ChooseDomain', state: { nationId: 'n1', archetypeId: 'p1', campaignDomainPreference: ['GATHERING'] } },
    { node: 'BB_Moves_1', state: { nationId: 'n1', archetypeId: 'p1' } },
  ]

  for (const { node, state } of bbSamples) {
    const layers = getUnlockedLayersForNode(node, state)
    const cells = LAYERS.map((l) => (layers.includes(l) ? '✓' : ''))
    rows.push(`| ${node} | ${cells.join(' | ')} |`)
  }

  rows.push('')
  rows.push('## Run tests')
  rows.push('')
  rows.push('```bash')
  rows.push('npx tsx src/lib/__tests__/avatar-parts.test.ts')
  rows.push('```')

  const output = rows.join('\n')
  const outPath = path.join(process.cwd(), '.specify/specs/avatar-character-lockstep/PHASE_LAYER_MATRIX.md')
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, output, 'utf8')
  console.log(`Wrote ${outPath}`)
}

main()
