import Link from 'next/link'
import { KOTTER_STAGES } from '@/lib/kotter'

export default function GlossaryPage() {
  return (
    <div className="space-y-6">
      <header className="space-y-2">
        <div className="text-xs text-zinc-500">
          <Link href="/wiki" className="hover:text-zinc-400">Wiki</Link>
          {' / '}
          <span className="text-zinc-500">Glossary</span>
        </div>
        <h1 className="text-3xl font-bold text-white">Glossary</h1>
        <p className="text-zinc-400 text-sm">
          Core terms: Yellow Brick Road, Vibeulons, BAR, Kotter stages.
        </p>
      </header>

      <section id="vibeulon" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Vibeulon</h2>
        <p className="text-zinc-300 text-sm">
          The currency/token of the game. Vibeulons are earned by completing quests, Emotional First Aid,
          and other actions. They represent emotional energy and contribution to the collective.
        </p>
      </section>

      <section id="bar" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">BAR</h2>
        <p className="text-zinc-300 text-sm">
          A kernel — a compressed unit of potential. A BAR can become a quest, a rule, a piece of lore,
          a design decision, or a community norm. BARs are seeds with provenance, not notes.
        </p>
      </section>

      <section id="yellow-brick-road" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Yellow Brick Road</h2>
        <p className="text-zinc-300 text-sm">
          For any Point A (where you are) and Point B (who you want to become), there is a road made of yellow bricks.
          The Bars-Engine is the vehicle: it carries individuals and groups along the road, and it converts blockers
          into the bricks that pave it.
        </p>
        <p className="text-zinc-300 text-sm">
          <span className="text-zinc-100 font-medium">Yellow Brick BARs</span> are the kernels that become road.
          Emotional Alchemy is the kiln — transmuting blockers (dissatisfied state) into bricks (satisfied state).
          Vibeulons are the fuel generated by the alchemy.
        </p>
        <p className="text-zinc-300 text-sm">
          The vehicle moves at the speed of metabolizing blockers. No shortcut past them — they are the raw material.
          Even when the road forks, you can never go the wrong way: wherever it leads is where you want to go.
        </p>
      </section>

      <section id="kotter" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-3">
        <h2 className="text-lg font-bold text-white">Kotter Stages</h2>
        <p className="text-zinc-300 text-sm">
          The 8-step change model for social adoption. Each stage maps to an archetype move.
        </p>
        <div className="grid gap-2 text-sm">
          {Object.entries(KOTTER_STAGES).map(([stage, data]) => (
            <div key={stage} className="flex items-center gap-3 text-zinc-300">
              <span className="text-zinc-500 w-6">{stage}.</span>
              <span className="font-medium">{data.name}</span>
              <span className="text-zinc-500">({data.move})</span>
            </div>
          ))}
        </div>
      </section>

      <div className="text-xs text-zinc-500">
        <Link href="/wiki" className="hover:text-zinc-300">← Back to index</Link>
      </div>
    </div>
  )
}
