import Link from 'next/link'
import { KOTTER_STAGES } from '@/lib/kotter'

export default function GlossaryPage() {
  return (
    <div className="space-y-6">
      <header className="space-y-2">
        <div className="text-xs text-zinc-500">
          <Link href="/wiki" className="hover:text-zinc-400">Wiki</Link>
          {' / '}
          <span className="text-zinc-500">Glossary</span>
        </div>
        <h1 className="text-3xl font-bold text-white">Glossary</h1>
        <p className="text-zinc-400 text-sm">
          Core terms: Yellow Brick Road, Vibeulons, BAR, Kotter stages.
        </p>
      </header>

      <section id="vibeulon" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Vibeulon</h2>
        <p className="text-zinc-300 text-sm">
          A unit of crystallized value minted from completing quests. Vibeulons can attach to BARs (locking them); attached vibeulons are destroyed if the BAR is composted and not transformed before expiry. Earned by completing quests, Emotional First Aid, and other actions.
        </p>
        <Link href="/wiki/rules" className="text-xs text-amber-400 hover:text-amber-300">→ Game Rules</Link>
      </section>

      <section id="bar" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">BAR</h2>
        <p className="text-zinc-300 text-sm">
          Basic Artifact Resource — a compact, shareable unit of signal; a &quot;seed packet&quot; for eventual action. BARs can be private (notebook) or public (spellbook). A BAR can become a quest, a rule, a piece of lore, or a community norm. BARs are seeds with provenance, not notes.
        </p>
        <Link href="/wiki/rules" className="text-xs text-amber-400 hover:text-amber-300">→ Game Rules</Link>
      </section>

      <section id="yellow-brick-road" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Yellow Brick Road</h2>
        <p className="text-zinc-300 text-sm">
          For any Point A (where you are) and Point B (who you want to become), there is a road made of yellow bricks.
          The Bars-Engine is the vehicle: it carries individuals and groups along the road, and it converts blockers
          into the bricks that pave it.
        </p>
        <p className="text-zinc-300 text-sm">
          <span className="text-zinc-100 font-medium">Yellow Brick BARs</span> are the kernels that become road.
          Emotional Alchemy is the kiln — transmuting blockers (dissatisfied state) into bricks (satisfied state).
          Vibeulons are the fuel generated by the alchemy.
        </p>
        <p className="text-zinc-300 text-sm">
          The vehicle moves at the speed of metabolizing blockers. No shortcut past them — they are the raw material.
          Even when the road forks, you can never go the wrong way: wherever it leads is where you want to go.
        </p>
      </section>

      <section id="kotter" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-3">
        <h2 className="text-lg font-bold text-white">Kotter Stages</h2>
        <p className="text-zinc-300 text-sm">
          The 8-step change model for social adoption. Each stage maps to an archetype move.
        </p>
        <div className="grid gap-2 text-sm">
          {Object.entries(KOTTER_STAGES).map(([stage, data]) => (
            <div key={stage} className="flex items-center gap-3 text-zinc-300">
              <span className="text-zinc-500 w-6">{stage}.</span>
              <span className="font-medium">{data.name}</span>
              <span className="text-zinc-500">({data.move})</span>
            </div>
          ))}
        </div>
      </section>

      <section id="stewardship" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Stewardship</h2>
        <p className="text-zinc-300 text-sm">
          Responsibility for carrying a BAR. Anyone can adopt stewardship; it does not claim authorship. Persists until released or composted. Practice: carrying, refining, upgrading, converting to quest, composting.
        </p>
        <Link href="/wiki/rules/stewardship" className="text-xs text-amber-400 hover:text-amber-300">→ Stewardship</Link>
      </section>

      <section id="quest" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Quest</h2>
        <p className="text-zinc-300 text-sm">
          An actionable commitment in the field. Quests have limited BAR slots; BARs played onto quests mint vibeulons on completion.
        </p>
        <Link href="/wiki/rules/quests-slots" className="text-xs text-amber-400 hover:text-amber-300">→ Quests + Slots</Link>
      </section>

      <section id="compost" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Compost</h2>
        <p className="text-zinc-300 text-sm">
          A zone for BARs removed from active play. Temporary; untransformed composted BARs are destroyed after a time window (with any attached vibeulons). Ecological tone—&quot;returned to the fire.&quot;
        </p>
        <Link href="/wiki/rules/compost" className="text-xs text-amber-400 hover:text-amber-300">→ Compost Heap</Link>
      </section>

      <section id="equipped" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Equipped / In Play</h2>
        <p className="text-zinc-300 text-sm">
          <strong>Equipped</strong> = BARs in your hand; curated for current play; capacity limits apply; do nothing passively. <strong>In Play</strong> = BAR attached to a quest slot.
        </p>
        <Link href="/wiki/rules/decks" className="text-xs text-amber-400 hover:text-amber-300">→ Decks</Link>
      </section>

      <section id="quadrant" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Quadrant</h2>
        <p className="text-zinc-300 text-sm">
          Tag for BAR content: About me, About something happening, About us, About the system. Human language; no AQAL jargon.
        </p>
        <Link href="/wiki/rules/bar-format" className="text-xs text-amber-400 hover:text-amber-300">→ BAR Format</Link>
      </section>

      <section id="values-vs-polarities" className="bg-zinc-900/40 border border-zinc-800 rounded-xl p-4 space-y-2">
        <h2 className="text-lg font-bold text-white">Values vs polarities</h2>
        <p className="text-zinc-300 text-sm">
          <strong className="text-zinc-200">Value systems</strong> (developmental / worldview — akin to Spiral Dynamics
          vMemes) are not the same as <strong className="text-zinc-200">tension pairs</strong> on Scene Atlas or
          in polarity-thinking maps. <strong className="text-zinc-200">Move polarity</strong> in the database is a third
          channel: nation move tags.
        </p>
        <Link href="/wiki/values-and-polarities#footnote" className="text-xs text-amber-400 hover:text-amber-300">
          → Values & polarities (wiki footnote)
        </Link>
      </section>

      <div className="text-xs text-zinc-500 flex gap-4 flex-wrap">
        <Link href="/wiki" className="hover:text-zinc-300">← Back to index</Link>
        <Link href="/wiki/rules/glossary" className="hover:text-zinc-300">Rules Glossary</Link>
      </div>
    </div>
  )
}
