/**
 * Hand-authored hero cells — Alchemist (inner + outer). Authored to L4.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 *
 * CAMPAIGN-AGNOSTIC. Alchemist = emotional transmutation: turning heavy, messy
 * emotion into fuel. The universal substrate — every player takes a level in it.
 * Inner = metabolizing your own charge; outer = helping a field hold what it can't
 * yet. Shadows woven through: the Sponge (absorbing what isn't yours) and the
 * Detached Observer (intellectualizing, refusing to feel). Six coords × both
 * aspects = 12 cells; published.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const ALCHEMIST_OVERRIDES: Record<string, Technique> = {
  // ── wake_up × shaman — notice the charge ──
  'sp-alchemist-WAKE-SHAMAN-INNER': {
    id: 'sp-alchemist-WAKE-SHAMAN-INNER',
    slug: 'alchemist-wake_up-shaman-inner',
    name: 'Notice the Charge in Your Body',
    essence: 'Catch the emotional charge as a sensation, before it becomes a story.',
    steps: [
      'Pause when something moves in you.',
      'Feel exactly where it sits — the throat, the chest, the gut — and what it weighs.',
      'Name the raw sensation before naming a reason for it.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['alchemist'],
    capabilities: ['connection'],
    primaryQuestion: 'What is moving in my body right now, before I explain it?',
    campaignQuestion: 'What charge am I carrying that I have not let myself feel?',
    optimizesFor: 'Meeting the charge as raw material instead of as a verdict.',
    forbiddenMoves: ['Jumping straight to the story', 'Pressuring yourself to feel nothing', 'Analyzing the feeling instead of feeling it'],
    failureModes: ['The Detached Observer — naming, never feeling', 'Charge that runs you unseen'],
    remediation: 'Put a hand where it sits; describe the sensation in three plain words.',
    tell: { working: 'You feel the charge as sensation.', performed: 'You narrate the feeling to avoid it.' },
    contraindications: ['When you are flooded and need grounding before sensing more'],
    example: 'Before deciding you are "fine," you notice the tightness sitting under your ribs.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-alchemist-WAKE-SHAMAN-OUTER': {
    id: 'sp-alchemist-WAKE-SHAMAN-OUTER',
    slug: 'alchemist-wake_up-shaman-outer',
    name: 'Sense the Emotion Running the Room',
    essence: 'Notice the emotional weather moving the room beneath its words.',
    steps: [
      'Drop beneath what is being said to what is being felt.',
      'Feel the room’s charge in your own body without claiming it as yours.',
      'Name the emotional weather to yourself before responding to the content.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['alchemist'],
    capabilities: ['connection'],
    primaryQuestion: 'What is this room feeling underneath what it is saying?',
    campaignQuestion: 'What emotion is actually driving this group right now?',
    optimizesFor: 'Reading the field’s real charge before working with the content.',
    forbiddenMoves: ['Taking the room’s feeling as your own', 'Pressuring people to admit what they feel', 'Treating the mood as the truth of one person'],
    failureModes: ['The Sponge — absorbing the room', 'Reacting to content, missing the charge'],
    remediation: 'Ask silently "whose feeling is this?" and locate the field, not just yourself.',
    tell: { working: 'You sense the field without merging with it.', performed: 'You drown in the room’s mood.' },
    contraindications: ['When you are already overwhelmed and need to step out, not tune in'],
    example: 'The meeting is "about logistics" but you feel the grief no one has named.',
    tier: 'canonical',
    status: 'published',
  },

  // ── open_up × diplomat — hold what others can't ──
  'sp-alchemist-OPEN-DIPLOMAT-INNER': {
    id: 'sp-alchemist-OPEN-DIPLOMAT-INNER',
    slug: 'alchemist-open_up-diplomat-inner',
    name: 'Welcome the Feeling Without Drowning',
    essence: 'Let the heavy feeling fully in while keeping your feet on the ground.',
    steps: [
      'Open to the feeling instead of bracing against it.',
      'Feel it move through your body while you keep breathing slow and low.',
      'Stay at the edge where you can feel it and still stand.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['alchemist'],
    capabilities: ['connection'],
    primaryQuestion: 'Can I feel this fully and still keep my feet under me?',
    campaignQuestion: 'What feeling am I bracing against that I could let move through?',
    optimizesFor: 'Full contact with the feeling without being swept away by it.',
    forbiddenMoves: ['Bracing the feeling shut', 'Pressuring yourself to "be over it"', 'Letting it flood until you disappear'],
    failureModes: ['The Detached Observer — armored', 'The Sponge — flooded'],
    remediation: 'Feel it for one slow breath with both feet on the floor; then continue.',
    tell: { working: 'You feel it and stay grounded.', performed: 'You either numb it or drown in it.' },
    contraindications: ['When acute trauma needs support, not solo immersion'],
    example: 'Grief rises; you let it move through you while keeping your breath steady.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-alchemist-OPEN-DIPLOMAT-OUTER': {
    id: 'sp-alchemist-OPEN-DIPLOMAT-OUTER',
    slug: 'alchemist-open_up-diplomat-outer',
    name: 'Hold What Others Cannot Yet',
    essence: 'Be a steady container for a feeling another person can’t hold alone — without taking it on.',
    steps: [
      'Stay present to their feeling without rushing to fix it.',
      'Feel your own ground so theirs can rest against it.',
      'Let them borrow your steadiness; do not carry the feeling home.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['alchemist'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I holding space for their feeling or absorbing it as mine?',
    campaignQuestion: 'What feeling does this person need held that they cannot hold alone?',
    optimizesFor: 'Being a container others can lean on without becoming the Sponge.',
    forbiddenMoves: ['Taking their pain home as yours', 'Pressuring them to feel better for your sake', 'Fixing to end your own discomfort'],
    failureModes: ['The Sponge — their feeling becomes yours', 'Caretaking that creates dependence'],
    remediation: 'After, name what was theirs and consciously set it down.',
    tell: { working: 'They feel held; you stay whole.', performed: 'You take their weight home and sag.' },
    contraindications: ['When you have nothing left to hold with and need to say so'],
    example: 'A friend falls apart; you stay steady beside them and don’t absorb the despair.',
    tier: 'canonical',
    status: 'published',
  },

  // ── clean_up × sage — transmute the stuck charge ──
  'sp-alchemist-CLEAN-SAGE-INNER': {
    id: 'sp-alchemist-CLEAN-SAGE-INNER',
    slug: 'alchemist-clean_up-sage-inner',
    name: 'Transmute Your Own Stuck Charge',
    essence: 'Turn the heavy, stuck emotion in you into usable fuel.',
    steps: [
      'Find the feeling that has gone stagnant and heavy.',
      'Feel it all the way down instead of around it.',
      'Ask what it is for, and let it become fuel for one real thing.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['sage'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['alchemist'],
    capabilities: ['connection'],
    primaryQuestion: 'What is this stuck feeling for, and what could it fuel?',
    campaignQuestion: 'What heavy emotion in me is ready to become fuel?',
    optimizesFor: 'Turning your own stuck charge into motion instead of weight.',
    forbiddenMoves: ['Bypassing the feeling with positivity', 'Pressuring a transformation before you have felt it', 'Discharging it onto someone'],
    failureModes: ['Spiritual bypass', 'The same charge, stuck again'],
    remediation: 'Feel it fully once; then name the single thing it can power.',
    tell: { working: 'The heaviness becomes movement.', performed: 'You slap a bright reframe on it.' },
    contraindications: ['When the feeling needs witnessing more than it needs a use'],
    example: 'Old resentment becomes the fuel to finally have the conversation you avoided.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-alchemist-CLEAN-SAGE-OUTER': {
    id: 'sp-alchemist-CLEAN-SAGE-OUTER',
    slug: 'alchemist-clean_up-sage-outer',
    name: 'Transmute the Field’s Stuck Emotion',
    essence: 'Help a group’s stuck emotion move and become shared energy.',
    steps: [
      'Name the stuck feeling in the room without blaming anyone for it.',
      'Feel for the shift from frozen to flowing as it gets witnessed.',
      'Offer the gesture — a word, a ritual, a pause — that lets it become shared fuel.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['sage'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['alchemist'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I helping the field’s feeling move, or managing it away?',
    campaignQuestion: 'What stuck emotion in this group is ready to become shared energy?',
    optimizesFor: 'A field that metabolizes its emotion together instead of freezing.',
    forbiddenMoves: ['Managing the feeling out of sight', 'Pressuring the group to "move on"', 'Performing catharsis for effect'],
    failureModes: ['Suppressed charge leaking later', 'The Sponge — you carry the field’s weight'],
    remediation: 'Witness the feeling aloud, then offer one small shared gesture.',
    tell: { working: 'The room unfreezes and moves together.', performed: 'You stage a feeling no one actually has.' },
    contraindications: ['When the group needs a boundary or a decision, not catharsis'],
    example: 'You name the unspoken grief in the team and the meeting finally moves.',
    tier: 'canonical',
    status: 'published',
  },

  // ── grow_up × regent — strengthen filtration ──
  'sp-alchemist-GROW-REGENT-INNER': {
    id: 'sp-alchemist-GROW-REGENT-INNER',
    slug: 'alchemist-grow_up-regent-inner',
    name: 'Strengthen Your Filtration',
    essence: 'Build the discernment to ask "is this mine?" before you carry a feeling.',
    steps: [
      'When a feeling arrives, pause before owning it.',
      'Feel for whether it rises from you or arrived from the room.',
      'Practice the sorting until "is this mine?" becomes reflex.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['alchemist'],
    capabilities: ['exploration'],
    primaryQuestion: 'Is this feeling mine, or am I carrying it for someone else?',
    campaignQuestion: 'What am I absorbing that was never mine to hold?',
    optimizesFor: 'A clear membrane between your charge and everyone else’s.',
    forbiddenMoves: ['Owning every feeling that lands', 'Pressuring yourself to be unaffected', 'Walling off all feeling to feel safe'],
    failureModes: ['The Sponge — no boundary', 'The Detached Observer — wall instead of filter'],
    remediation: 'Sort one current feeling: mine, theirs, or both — and act accordingly.',
    tell: { working: 'You can tell your charge from the room’s.', performed: 'You carry everything or block it all.' },
    contraindications: ['When constant sorting becomes a way to avoid intimacy'],
    example: 'You realize the dread you "caught" all day belonged to a stressed colleague.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-alchemist-GROW-REGENT-OUTER': {
    id: 'sp-alchemist-GROW-REGENT-OUTER',
    slug: 'alchemist-grow_up-regent-outer',
    name: 'Grow the Group’s Capacity to Feel',
    essence: 'Build, over time, a group that can feel hard things together without shattering.',
    steps: [
      'Make small space for real feeling a normal part of how the group works.',
      'Feel for the group’s growing edge — a little more than last time, not a flood.',
      'Let each held feeling widen what the group can hold next.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['alchemist'],
    capabilities: ['participation'],
    primaryQuestion: 'Is this group becoming more able to feel hard things together?',
    campaignQuestion: 'How do I grow the group’s capacity to hold emotion without overwhelming it?',
    optimizesFor: 'A group that metabolizes feeling together, a little stronger each time.',
    forbiddenMoves: ['Forcing vulnerability on the group', 'Pressuring people to share before it is safe', 'Mistaking exposure for capacity'],
    failureModes: ['Forced vulnerability that backfires', 'Emotional flooding, then withdrawal'],
    remediation: 'Right-size the next emotional ask to what the group just held well.',
    tell: { working: 'The group holds harder things over time.', performed: 'The group recoils from feeling around you.' },
    contraindications: ['When the work genuinely needs focus, not feeling, right now'],
    example: 'You build a brief check-in ritual, and over months the team can name hard things.',
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × challenger — channel the fuel into act ──
  'sp-alchemist-SHOW-CHALLENGER-INNER': {
    id: 'sp-alchemist-SHOW-CHALLENGER-INNER',
    slug: 'alchemist-show_up-challenger-inner',
    name: 'Channel the Fuel into One Act',
    essence: 'Spend the transmuted charge on a single concrete act, now.',
    steps: [
      'Take the fuel you made from the feeling and aim it.',
      'Feel the difference between charged action and reactive venting.',
      'Do the one real thing the energy is for, today.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['alchemist'],
    capabilities: ['agency'],
    primaryQuestion: 'What one act is this fuel actually for?',
    campaignQuestion: 'Where do I spend this charged energy before it dissipates?',
    optimizesFor: 'Converting metabolized emotion into a single real action.',
    forbiddenMoves: ['Venting the charge as reaction', 'Pressuring a big gesture to feel powerful', 'Letting the fuel evaporate in talk'],
    failureModes: ['Charge discharged as drama', 'Fuel wasted on nothing'],
    remediation: 'Name the smallest concrete act the energy is for and do it now.',
    tell: { working: 'The feeling becomes one real act.', performed: 'The feeling becomes a scene.' },
    contraindications: ['When acting on the charge now would just be reactivity'],
    example: 'The grief you metabolized becomes the email that starts the memorial fund.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-alchemist-SHOW-CHALLENGER-OUTER': {
    id: 'sp-alchemist-SHOW-CHALLENGER-OUTER',
    slug: 'alchemist-show_up-challenger-outer',
    name: 'Turn Shared Charge into a Move',
    essence: 'Help a group spend its transmuted emotion on one decisive, shared act.',
    steps: [
      'Gather the group’s energy toward a single concrete move.',
      'Feel for the moment the charge is ready to become action.',
      'Name the move and take the first step together.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['alchemist'],
    capabilities: ['agency'],
    primaryQuestion: 'Is the group’s charge becoming a move or just more heat?',
    campaignQuestion: 'What shared act can this group’s energy power right now?',
    optimizesFor: 'A group that turns its collective feeling into one decisive act.',
    forbiddenMoves: ['Whipping up feeling with no outlet', 'Pressuring the group into your action', 'Mistaking a charged room for a committed one'],
    failureModes: ['Heat that fizzles', 'A fired-up room that does nothing'],
    remediation: 'Offer one concrete shared step while the energy is live.',
    tell: { working: 'The group moves together on the charge.', performed: 'The room burns hot and goes home.' },
    contraindications: ['When the group needs to grieve before it is asked to act'],
    example: 'You channel the room’s outrage into a single, signed, collective letter that night.',
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × sage — integrate into shared momentum ──
  'sp-alchemist-SHOW-SAGE-INNER': {
    id: 'sp-alchemist-SHOW-SAGE-INNER',
    slug: 'alchemist-show_up-sage-inner',
    name: 'Become Someone Who Transmutes',
    essence: 'Integrate the practice until turning feeling into fuel is simply who you are.',
    steps: [
      'Notice the times you metabolized instead of spilled or numbed.',
      'Feel that this is becoming a capacity, not a fluke.',
      'Claim it: you are someone who can feel the heavy thing and make it fuel.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['alchemist'],
    capabilities: ['agency'],
    primaryQuestion: 'Who am I becoming as I learn to transmute instead of spill or numb?',
    campaignQuestion: 'What durable capacity is forming in me through this practice?',
    optimizesFor: 'Transmutation as integrated identity, not a one-off trick.',
    forbiddenMoves: ['Performing the wise alchemist', 'Pressuring an identity you have not lived', 'Skipping the feeling to claim the title'],
    failureModes: ['A spiritual persona over old habits', 'Bypass dressed as mastery'],
    remediation: 'Name one recent time you genuinely transmuted; let it count.',
    tell: { working: 'The capacity feels like yours now.', performed: 'You perform serenity you do not have.' },
    contraindications: ['When naming it freezes a change still in motion'],
    example: 'You realize you now meet hard feelings as fuel by default, and own it quietly.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-alchemist-SHOW-SAGE-OUTER': {
    id: 'sp-alchemist-SHOW-SAGE-OUTER',
    slug: 'alchemist-show_up-sage-outer',
    name: 'Channel the Charge into Shared Momentum',
    essence: 'Weave the group’s metabolized emotion into lasting, shared momentum.',
    steps: [
      'Connect today’s charged act to the larger arc the group is living.',
      'Feel for what wants to continue, not just discharge.',
      'Name the thread so the energy becomes momentum, not a one-night fire.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['alchemist'],
    capabilities: ['participation'],
    primaryQuestion: 'Is this charge becoming lasting momentum or a single flare?',
    campaignQuestion: 'How does this group’s energy become a current that carries us forward?',
    optimizesFor: 'Collective feeling woven into durable shared momentum.',
    forbiddenMoves: ['Chasing the next emotional high', 'Pressuring the group to sustain a peak', 'Letting the energy strand after one act'],
    failureModes: ['Burnout after the peak', 'Momentum that dies with the mood'],
    remediation: 'Name the next small shared step that carries the energy past tonight.',
    tell: { working: 'The energy becomes an ongoing current.', performed: 'The group peaks and crashes.' },
    contraindications: ['When the honest thing is to let a moment simply complete and end'],
    example: 'After the charged action, you name the next gathering so the momentum keeps a home.',
    tier: 'canonical',
    status: 'published',
  },
}
