/**
 * Hand-authored hero cells — Coach (inner + outer). Authored to L4.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 * Coach canon: .specify/specs/superpower-system-reconciliation/reconciliation.md
 *
 * CAMPAIGN-AGNOSTIC. Coach = "calling people up": reminding people of the power
 * they've forgotten and helping them leave a level they've outgrown. Inner =
 * self-coaching; outer = coaching another. Shadows woven through: the Taskmaster
 * (drags instead of calls up, creates dependence) and the Empty Cheerleader
 * (only affirms, never nudges). Six coords × both aspects = 12 cells; published.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const COACH_OVERRIDES: Record<string, Technique> = {
  // ── wake_up × shaman — see the level / the forgotten power ──
  'sp-coach-WAKE-SHAMAN-INNER': {
    id: 'sp-coach-WAKE-SHAMAN-INNER',
    slug: 'coach-wake_up-shaman-inner',
    name: "See the Level You've Outgrown",
    essence: "Notice the level you keep playing on that you've actually outgrown.",
    steps: [
      'Notice where the game feels too small or stale.',
      "Feel the boredom or itch in your body — it's data.",
      "Name the level you've outgrown out loud.",
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['coach'],
    capabilities: ['agency'],
    primaryQuestion: "What level am I still playing on that I've already outgrown?",
    campaignQuestion: 'Where am I staying small out of habit?',
    optimizesFor: 'Catching your own outgrown level before it quietly caps you.',
    forbiddenMoves: ['Mistaking comfort for fit', 'Pressuring yourself to level up before you see it', 'Calling restlessness failure'],
    failureModes: ['Staying on a dead level', 'Numbing the itch'],
    remediation: "Name one level you've outgrown; sit with the discomfort for a breath.",
    tell: { working: 'You feel the itch and name it.', performed: 'You declare a new level to look impressive.' },
    contraindications: ['When you actually need to consolidate, not level up'],
    example: "The work bores you; instead of grinding, you name the level you've outgrown.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-coach-WAKE-SHAMAN-OUTER': {
    id: 'sp-coach-WAKE-SHAMAN-OUTER',
    slug: 'coach-wake_up-shaman-outer',
    name: "See the Power They've Forgotten",
    essence: 'Notice the power the person in front of you has forgotten they have.',
    steps: [
      "Look past what they're doing to what they're capable of.",
      "Feel where they've gone small.",
      'Name the strength you see, specifically.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['coach'],
    capabilities: ['agency'],
    primaryQuestion: 'Am I seeing their capacity or just their current performance?',
    campaignQuestion: 'What power has this person forgotten they have?',
    optimizesFor: 'Seeing people at their capacity, not their slump.',
    forbiddenMoves: ['Fixing them', 'Flattery (the Empty Cheerleader)', 'Pressuring them to perform'],
    failureModes: ['Seeing only the deficit', 'Empty cheerleading'],
    remediation: 'Name one specific strength you genuinely see in them.',
    tell: { working: 'They stand a little taller.', performed: 'You compliment to be liked.' },
    contraindications: ['When they need practical help, not a pep read'],
    example: "You tell a discouraged friend the specific strength you've watched them use.",
    tier: 'canonical',
    status: 'published',
  },

  // ── open_up × diplomat — meet the resistance ──
  'sp-coach-OPEN-DIPLOMAT-INNER': {
    id: 'sp-coach-OPEN-DIPLOMAT-INNER',
    slug: 'coach-open_up-diplomat-inner',
    name: 'Meet Your Own Resistance',
    essence: 'Let yourself feel your resistance to being called up, without obeying it.',
    steps: [
      "Notice the part that wants to stay where it's safe.",
      'Feel the resistance in your body.',
      'Thank it, and choose to move anyway.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['coach'],
    capabilities: ['agency'],
    primaryQuestion: 'What am I protecting by refusing to level up?',
    campaignQuestion: 'What resistance in me is keeping me small?',
    optimizesFor: 'Moving up without bulldozing your own fear.',
    forbiddenMoves: ['Forcing past the fear', 'Pressuring yourself into shame', 'Calling caution cowardice'],
    failureModes: ['Self-flagellation as motivation', 'Freeze'],
    remediation: 'Name the resistance; take one small step with it, not against it.',
    tell: { working: 'You move with the fear, not over it.', performed: 'You shame yourself into a sprint.' },
    contraindications: ['When the resistance is wisdom, not fear'],
    example: 'You feel the urge to hide; you name it and send the thing anyway.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-coach-OPEN-DIPLOMAT-OUTER': {
    id: 'sp-coach-OPEN-DIPLOMAT-OUTER',
    slug: 'coach-open_up-diplomat-outer',
    name: 'Receive Their Resistance',
    essence: 'Hear the person’s resistance to being called up without overriding it.',
    steps: [
      'Ask what makes the next level feel risky for them.',
      'Feel their fear as legitimate, not an obstacle.',
      'Reflect it back before you invite the step.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['coach'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I honoring their fear or steamrolling it?',
    campaignQuestion: 'What makes leveling up feel unsafe for them?',
    optimizesFor: 'Calling people up at a pace they can actually take.',
    forbiddenMoves: ['Dragging them past their no', 'Guilt-tripping them upward', 'Dismissing the fear'],
    failureModes: ['Creating dependence', 'Pushback and shutdown'],
    remediation: 'Name their fear in their words; ask what would make one step feel safe.',
    tell: { working: 'They feel met, then willing.', performed: 'You push and they comply resentfully.' },
    contraindications: ["When they've clearly said not now"],
    example: 'You ask what feels scary about the bigger role before nudging them toward it.',
    tier: 'canonical',
    status: 'published',
  },

  // ── clean_up × challenger — drop the story that keeps you/them small ──
  'sp-coach-CLEAN-CHALLENGER-INNER': {
    id: 'sp-coach-CLEAN-CHALLENGER-INNER',
    slug: 'coach-clean_up-challenger-inner',
    name: "Drop the Story Keeping You Small",
    essence: "Clear the story that keeps you on a level you've outgrown.",
    steps: [
      "Write the story you tell about why you can't move up.",
      "Feel where it's fear wearing fact's clothes.",
      "Rewrite it as the version that isn't certain.",
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['coach'],
    capabilities: ['agency'],
    primaryQuestion: 'What story is keeping me on a dead level?',
    campaignQuestion: 'What belief about myself is capping me here?',
    optimizesFor: 'Freeing yourself from the script that caps you.',
    forbiddenMoves: ['Defending the story', 'Toxic positivity over it', 'Pressuring a breakthrough'],
    failureModes: ['Identifying with the limit', 'Affirmations with no contact'],
    remediation: "Say the story aloud, then the part you actually don't know is true.",
    tell: { working: 'The story loosens.', performed: 'You slap an affirmation over it.' },
    contraindications: ['When the limit is real and worth respecting'],
    example: "You name 'I'm not a leader' as a story, then test it once.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-coach-CLEAN-CHALLENGER-OUTER': {
    id: 'sp-coach-CLEAN-CHALLENGER-OUTER',
    slug: 'coach-clean_up-challenger-outer',
    name: 'Name the Story That Keeps Them Small',
    essence: "Surface the story keeping the other person on a level they've outgrown.",
    steps: [
      "Reflect the limiting story you hear them tell ('I'm just the…').",
      "Feel for whether they're ready to question it.",
      "Offer the question, not the answer: 'is that still true?'",
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['coach'],
    capabilities: ['agency'],
    primaryQuestion: 'Am I imposing my read or surfacing theirs?',
    campaignQuestion: 'What story is keeping this person from their next level?',
    optimizesFor: 'Loosening the script without doing their work for them.',
    forbiddenMoves: ['Telling them who to be', 'Pressuring the reframe', "Ripping the story away before they're ready"],
    failureModes: ['Creating dependence on your insight', 'Defensiveness'],
    remediation: "Ask 'is that story still serving you?' and let them answer.",
    tell: { working: 'They question the story themselves.', performed: 'You hand them your conclusion.' },
    contraindications: ["When trust isn't there yet"],
    example: "You gently ask a teammate if 'I'm bad at this' is still true.",
    tier: 'canonical',
    status: 'published',
  },

  // ── grow_up × regent — grow without creating dependence ──
  'sp-coach-GROW-REGENT-INNER': {
    id: 'sp-coach-GROW-REGENT-INNER',
    slug: 'coach-grow_up-regent-inner',
    name: 'Coach Yourself Without Dragging',
    essence: 'Build the capacity to call yourself up steadily, without self-tyranny.',
    steps: [
      "Set one stretch that's just past comfortable.",
      'Feel the difference between challenge and self-punishment.',
      'Practice the rep; rest is part of it.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['earth'],
    aspect: 'inner',
    superpowers: ['coach'],
    capabilities: ['rest'],
    primaryQuestion: 'Am I calling myself up or just driving myself?',
    campaignQuestion: 'What sustainable practice grows me without burning me?',
    optimizesFor: 'Self-development that lasts, not a crash diet of willpower.',
    forbiddenMoves: ['Becoming your own Taskmaster', 'No-rest grinding', 'Pressuring yourself past sense'],
    failureModes: ['Burnout dressed as discipline', 'All-or-nothing'],
    remediation: 'Pick one stretch and one rest; do both.',
    tell: { working: 'You stretch and recover.', performed: 'You flog yourself and call it growth.' },
    contraindications: ['When you need recovery more than a stretch'],
    example: 'You set a stretch goal and schedule the rest that makes it sustainable.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-coach-GROW-REGENT-OUTER': {
    id: 'sp-coach-GROW-REGENT-OUTER',
    slug: 'coach-grow_up-regent-outer',
    name: 'Grow Them at Their Pace',
    essence: "Steward another's growth over time without creating dependence.",
    steps: [
      "Find the next stretch that's theirs, not yours.",
      "Feel where you're tempted to do it for them.",
      'Hand back the rep; let them carry it.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['coach'],
    capabilities: ['participation'],
    primaryQuestion: 'Am I building their capacity or my indispensability?',
    campaignQuestion: "What's their next right stretch, at their pace?",
    optimizesFor: 'People who can do it without you.',
    forbiddenMoves: ['Rescuing', 'Pressuring their pace', 'Making them depend on you'],
    failureModes: ['The Taskmaster — dependence', 'Doing their reps for them'],
    remediation: "Name one thing you'll stop doing for them this week.",
    tell: { working: 'They need you less over time.', performed: 'They need you more.' },
    contraindications: ['When they genuinely need you to step in now'],
    example: 'You let a mentee struggle through the task you could finish in a minute.',
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × challenger — call up ──
  'sp-coach-SHOW-CHALLENGER-INNER': {
    id: 'sp-coach-SHOW-CHALLENGER-INNER',
    slug: 'coach-show_up-challenger-inner',
    name: 'Call Yourself Up',
    essence: 'Name the level you’re stepping to, and step — out loud, on the record.',
    steps: [
      'Name the next level specifically.',
      'Feel the fear and commit anyway.',
      'Take the first concrete action toward it today.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['coach'],
    capabilities: ['agency'],
    primaryQuestion: "What level am I committing to, and what's the first move?",
    campaignQuestion: "What's the step up I keep deferring?",
    optimizesFor: 'Crossing into the next level instead of admiring it.',
    forbiddenMoves: ['Declaring without doing', 'Waiting to feel ready', 'Pressuring a leap with no footing'],
    failureModes: ['All talk, no step', 'Leap with no landing'],
    remediation: 'Take the smallest real action toward the level today.',
    tell: { working: 'You take a concrete step.', performed: 'You announce the level and stall.' },
    contraindications: ['When you need a plan before a leap'],
    example: 'You commit to the harder role and send one email that starts it.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-coach-SHOW-CHALLENGER-OUTER': {
    id: 'sp-coach-SHOW-CHALLENGER-OUTER',
    slug: 'coach-show_up-challenger-outer',
    name: 'Call Them Up',
    essence: 'Name the level you see them ready for, and the why — then invite the step.',
    steps: [
      'Name the level you see them ready for, specifically.',
      'Say why you believe it — name the evidence you’ve felt, not flattery.',
      'Invite one concrete step — and let them choose.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['coach'],
    capabilities: ['agency'],
    primaryQuestion: 'Am I calling them up or pushing them where I want them?',
    campaignQuestion: 'What level is this person ready for that no one has named?',
    optimizesFor: "The moment someone steps up because you named what they couldn't see.",
    forbiddenMoves: ['Flattery without a step', 'Pressuring the yes', 'Naming a level for your benefit'],
    failureModes: ['Empty cheerleading', "The Taskmaster's demand"],
    remediation: 'Pair the belief with one concrete, optional next step.',
    tell: { working: 'They step up of their own will.', performed: 'They comply to please you.' },
    contraindications: ["When they haven't asked and trust is thin"],
    example: "'You're ready to lead this — here's why. Want to take the first piece?'",
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × sage — integrate / leave them capable ──
  'sp-coach-SHOW-SAGE-INNER': {
    id: 'sp-coach-SHOW-SAGE-INNER',
    slug: 'coach-show_up-sage-inner',
    name: 'Become Someone Who Calls Up',
    essence: 'Integrate the shift: become a person who levels up and brings themselves whole.',
    steps: [
      "Name who you're becoming by taking this level.",
      'Feel whether it’s integration or just ambition.',
      "Carry the part of you that was scared; don't leave it behind.",
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['coach'],
    capabilities: ['agency'],
    primaryQuestion: 'Who am I becoming by calling myself up?',
    campaignQuestion: "What's the durable identity shift here, not just the win?",
    optimizesFor: 'Growth that integrates, not a new mask.',
    forbiddenMoves: ['Leaving your scared parts behind', 'Performing the upgraded self', 'Pressuring an identity'],
    failureModes: ['A shinier mask', 'Self left behind'],
    remediation: "Finish: 'I'm becoming someone who can ____ and still ____.'",
    tell: { working: 'The new level feels like you.', performed: 'You cosplay the upgrade.' },
    contraindications: ["When you're mid-change and naming it freezes it"],
    example: "You name the leader you're becoming and keep the tender part along.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-coach-SHOW-SAGE-OUTER': {
    id: 'sp-coach-SHOW-SAGE-OUTER',
    slug: 'coach-show_up-sage-outer',
    name: 'Leave Them More Capable',
    essence: "Coach so that, when you're gone, they're stronger and freer — not dependent.",
    steps: [
      'Aim for them to outgrow needing you.',
      "Feel where you're holding on for your own sake.",
      'Hand over what they can now carry; celebrate it.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['coach'],
    capabilities: ['participation'],
    primaryQuestion: 'Will they be more capable after me, or more dependent?',
    campaignQuestion: 'What capacity do I want to leave behind in them?',
    optimizesFor: "People who carry it without you — the Coach's win.",
    forbiddenMoves: ['Making yourself indispensable', 'Hoarding the credit', 'Guilt-binding them to you'],
    failureModes: ['The Taskmaster — dependence', 'Coaching as control'],
    remediation: 'Name one responsibility to fully hand over now.',
    tell: { working: 'They thrive without you.', performed: "They can't function without you." },
    contraindications: ['When they still genuinely need scaffolding'],
    example: "You hand a mentee the thing you've always done, and step back.",
    tier: 'canonical',
    status: 'published',
  },
}
