/**
 * Hand-authored hero cells — Connector (inner + outer). Authored to L4.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 *
 * CAMPAIGN-AGNOSTIC: the durable fields work for ANY campaign (fundraising,
 * organizing, advocacy, personal goals). `example` is one concrete illustration,
 * not a constraint. These replace the generated draft at their coordinate; keyed
 * by id; applied in decks.ts. Published — they pass the no-published-below-L3 gate.
 *
 * Outer = how the Connector helps others (the warm/direct ask, mapping reach).
 * Inner = how the Connector defends themselves: tending their OWN ties and
 * receiving connection instead of only hosting it — metabolizing the Overextended
 * Hub shadow (everything routing through you). Six coords × both aspects = 12 cells.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const CONNECTOR_OVERRIDES: Record<string, Technique> = {
  'sp-connector-OPEN-DIPLOMAT-OUTER': {
    id: 'sp-connector-OPEN-DIPLOMAT-OUTER',
    slug: 'connector-open_up-diplomat-outer',
    name: 'The Warm Ask',
    essence: "Open a real ask to someone who'd want to help — without turning the relationship into a ledger.",
    steps: [
      "List the people who'd be glad to be asked.",
      "For each, name the specific thing you'd ask for and a true reason you feel in your body.",
      'Ask one today, in your own voice, with an explicit no-strings out.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['connection'],
    primaryQuestion: 'Whose help am I afraid to receive, and what story makes the ask feel like a debt?',
    campaignQuestion: 'Who would genuinely want a chance to help with this — and how do I invite them cleanly?',
    optimizesFor: 'Support that flows through warmth, not pressure.',
    forbiddenMoves: ['Mass-blast the same message', 'Imply obligation', 'Pre-decide their no for them'],
    failureModes: ['Transactional scorekeeping', 'Shame-leveraging', 'Only asking the people who least mind'],
    remediation: "If it curdles, say 'no strings — really,' and mean it.",
    tell: { working: 'You feel cleaner after asking, win or lose.', performed: 'You start tracking who now owes you.' },
    contraindications: ["When there's no real warmth in the relationship yet"],
    example: "Message one person who'd want in: name the specific thing and a clear amount or task, with a genuine 'no worries if not.'",
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-CHALLENGER-OUTER': {
    id: 'sp-connector-SHOW-CHALLENGER-OUTER',
    slug: 'connector-show_up-challenger-outer',
    name: 'The Direct Ask',
    essence: 'Make the one concrete ask that moves the work today — specific person, specific request, by when.',
    steps: [
      'Pick the person and the specific request.',
      "Make the ask plainly, with a deadline.",
      'Make it easy to say yes — and easy to say no.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['agency'],
    primaryQuestion: 'What am I feeling in my gut right before I make the ask — and am I about to soften it?',
    campaignQuestion: "What's the single ask that moves things today: to whom, for what, by when?",
    optimizesFor: 'A real, specific request on the table, not a softened hint.',
    forbiddenMoves: ['Hinting instead of asking', 'Burying the request', 'Pressure a yes'],
    failureModes: ['The ask that never quite gets made', "Vague 'anything helps' with no target"],
    remediation: 'If you softened it, follow up with one line naming the real request.',
    tell: { working: "There's a specific request on the table.", performed: "You 'raised awareness' but asked no one." },
    contraindications: ["When you haven't built any relationship with the person yet"],
    example: "Ask directly: 'Could you do [specific thing] by Friday? Totally fine to say no.'",
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-CLEAN-SHAMAN-OUTER': {
    id: 'sp-connector-CLEAN-SHAMAN-OUTER',
    slug: 'connector-clean_up-shaman-outer',
    name: 'Clear the Static',
    essence: 'Clear the relational static with someone before you ask, so the ask lands clean.',
    steps: [
      'Notice the unspoken charge with this person (old debts, awkwardness).',
      'Name it lightly to yourself, then feel where it sits in your body.',
      'Ask only once the static has dropped a notch.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['connection'],
    primaryQuestion: 'What old relational charge am I about to route into this ask?',
    campaignQuestion: "What's unspoken between us that would make the ask land wrong if I ignore it?",
    optimizesFor: 'An ask received as warmth, not as the next move in an old pattern.',
    forbiddenMoves: ['Asking through resentment', 'Using guilt as leverage', "Pretending the awkwardness isn't there"],
    failureModes: ['The ask reopens an old wound', 'They feel handled, not asked'],
    remediation: "If static spikes mid-ask, pause and name it: 'I know it's been a while — no pressure here.'",
    tell: { working: 'The exchange feels lighter afterward.', performed: 'You rehearse the ask to manage their reaction.' },
    contraindications: ['When the relationship needs repair before any ask'],
    example: "Before reaching out to someone you've drifted from, feel the old charge, then lead with reconnection, not the ask.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-WAKE-ARCHITECT-OUTER': {
    id: 'sp-connector-WAKE-ARCHITECT-OUTER',
    slug: 'connector-wake_up-architect-outer',
    name: 'Map the Network',
    essence: 'See the whole web of people who could help — who can act, who can connect you onward, who can amplify.',
    steps: [
      'List everyone in reach who cares, in three tiers: help directly, connect you onward, amplify.',
      'Spot the one connector who could open ten more doors — and notice who you flinch to ask.',
      'Name the highest-leverage ask first.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['exploration'],
    primaryQuestion: 'Whose support am I overlooking because asking them feels too exposing?',
    campaignQuestion: "Who can help directly, who can connect, who can amplify — and where's the leverage?",
    optimizesFor: 'Seeing latent reach before grinding out one-by-one asks.',
    forbiddenMoves: ['Only counting the obvious few', "Ignoring people who'd want to help", "Pressure people who can't help"],
    failureModes: ['Tunnel vision on the obvious few', "Missing the person who'd rally others"],
    remediation: "If stuck, ask one person 'who else do you know who'd want in on this?'",
    tell: { working: 'The map feels bigger and more alive.', performed: 'You make a list but ask no one on it.' },
    contraindications: ["When you're using mapping to avoid the actual ask"],
    example: 'Realize an old teammate runs a group chat of 40 — one warm intro could matter more than ten DMs.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-ARCHITECT-OUTER': {
    id: 'sp-connector-SHOW-ARCHITECT-OUTER',
    slug: 'connector-show_up-architect-outer',
    name: 'Build the Milestone Ladder',
    essence: 'Give the goal a structure people can join — milestones, a match, a visible climb.',
    steps: [
      'Break the goal into rungs (25% / 50% / 75% / 100%) with a why for each.',
      'Line up one person to match or double a rung.',
      'Post the ladder so people see the climb and where they fit.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['participation'],
    primaryQuestion: 'Am I avoiding building structure because it makes the need feel real?',
    campaignQuestion: 'What structure — milestones, a match, a tracker — turns scattered effort into a climb people join?',
    optimizesFor: 'Momentum that compounds instead of one-off pushes.',
    forbiddenMoves: ['Over-engineering the tracker', 'Hiding the goal', 'Pressure a matcher'],
    failureModes: ['A ladder no one sees', 'Structure that stalls the actual work'],
    remediation: 'Ship the simplest version today: three rungs and a visible tracker.',
    tell: { working: 'People start asking how to help.', performed: 'You tinker with the design to delay asking.' },
    contraindications: ['When structure is procrastination in disguise'],
    example: "Post the first milestone and a matcher: 'Hit the first 25% and a friend matches the next chunk.'",
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-DIPLOMAT-OUTER': {
    id: 'sp-connector-SHOW-DIPLOMAT-OUTER',
    slug: 'connector-show_up-diplomat-outer',
    name: "Invite, Don't Extract",
    essence: 'Ask in a way that gives people the gift of helping, with full consent and no strings.',
    steps: [
      'Frame the ask as an invitation into something good.',
      'State the no-strings out loud and feel whether your body agrees.',
      'Thank helpers in a way that completes the loop, not opens a debt.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['connection', 'participation'],
    primaryQuestion: 'Am I about to extract from someone instead of inviting them?',
    campaignQuestion: 'How do I invite people to help so they feel chosen, not used?',
    optimizesFor: 'Helping that strengthens the relationship instead of taxing it.',
    forbiddenMoves: ['Guilt-tripping', "Using someone's story without consent", 'Implying obligation'],
    failureModes: ['The helper feels cornered', 'A yes that quietly costs the friendship'],
    remediation: "If you sense pressure, say 'genuinely no strings — I'll love you either way.'",
    tell: { working: 'Helpers thank YOU for the chance.', performed: 'You feel a flicker of leverage.' },
    contraindications: ["When you need it so badly you can't hear a no"],
    example: "'I'm inviting a few people who've had my back to be part of this — zero pressure.'",
    tier: 'canonical',
    status: 'published',
  },

  // ── inner aspect — tend your own ties; stop being the Overextended Hub ──
  'sp-connector-OPEN-DIPLOMAT-INNER': {
    id: 'sp-connector-OPEN-DIPLOMAT-INNER',
    slug: 'connector-open_up-diplomat-inner',
    name: 'Let Yourself Be Held',
    essence: "Receive the room's care without immediately flipping into hosting or repaying it.",
    steps: [
      'Notice the reflex that turns receiving into hosting.',
      'Feel the discomfort of being held instead of holding — let it stay one breath longer.',
      'Accept one moment of belonging without doing anything to earn it.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['connector'],
    capabilities: ['connection'],
    primaryQuestion: 'Can I let myself be held without turning it into something I have to manage?',
    campaignQuestion: 'Where am I hosting connection I could be receiving?',
    optimizesFor: 'Being inside the web you tend, not only running it.',
    forbiddenMoves: ['Turning every moment of care into hosting', 'Pressuring yourself to repay the care', 'Deflecting belonging by managing it'],
    failureModes: ['The Overextended Hub — never a guest', 'Connection that only flows outward'],
    remediation: 'Let one person take care of you this week without reciprocating.',
    tell: { working: 'You feel held and let it land.', performed: 'You receive, then immediately start organizing.' },
    contraindications: ['When the group truly needs you to hold space right now'],
    example: 'A friend checks on you; instead of flipping to their needs, you let yourself be cared for.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-CHALLENGER-INNER': {
    id: 'sp-connector-SHOW-CHALLENGER-INNER',
    slug: 'connector-show_up-challenger-inner',
    name: 'Reach Out for Your Own Sake',
    essence: 'Make the one concrete reach-out that is purely for your own connection, not the work.',
    steps: [
      'Pick a person you miss, not one you need something from.',
      'Feel the small fear of reaching out with no agenda.',
      'Send the message today — connection as the whole point.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['connector'],
    capabilities: ['agency'],
    primaryQuestion: 'When did I last reach out to someone purely because I wanted them, not their help?',
    campaignQuestion: "What connection am I starving while I tend everyone else's?",
    optimizesFor: 'Tending your own ties, not only the network’s.',
    forbiddenMoves: ['Only reaching out when you need something', 'Pressuring the contact into a favor', 'Routing your own need through the work'],
    failureModes: ['The hub with no friends of its own', 'Agenda-only contact'],
    remediation: 'Send one no-agenda message right now.',
    tell: { working: 'You reach out with nothing to gain.', performed: 'You slip an ask into the catch-up.' },
    contraindications: ['When you are using a social reach-out to avoid a real task'],
    example: 'You text an old friend just to say you miss them, with nothing attached.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-CLEAN-SHAMAN-INNER': {
    id: 'sp-connector-CLEAN-SHAMAN-INNER',
    slug: 'connector-clean_up-shaman-inner',
    name: 'Drop the Need to Be the Hub',
    essence: 'Clear your compulsion to route every connection through yourself.',
    steps: [
      'Notice where you have made yourself the single point everyone passes through.',
      'Feel the grip of needing to be needed in your body.',
      'Let one connection happen without you in the middle.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['connector'],
    capabilities: ['connection'],
    primaryQuestion: 'What do I get from being the hub that I am afraid to live without?',
    campaignQuestion: 'Where am I the bottleneck because being needed feels like belonging?',
    optimizesFor: 'Relationships that survive without you in the center.',
    forbiddenMoves: ['Inserting yourself into every connection', 'Pressuring people to come through you', 'Confusing being needed with being loved'],
    failureModes: ['The Overextended Hub — everything routes through you', 'Indispensability as identity'],
    remediation: 'Introduce two people and step out of the thread.',
    tell: { working: 'You let go and the tie holds.', performed: 'You quietly reinsert yourself.' },
    contraindications: ['When you are genuinely the only safe bridge right now'],
    example: 'You connect two friends and resist staying in the chat to mediate.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-WAKE-ARCHITECT-INNER': {
    id: 'sp-connector-WAKE-ARCHITECT-INNER',
    slug: 'connector-wake_up-architect-inner',
    name: "See Where You're the Single Point of Failure",
    essence: 'Map where your web depends entirely on you — and where that is bleeding you dry.',
    steps: [
      'List the ties that only exist because you maintain them.',
      'Feel which ones drain you versus feed you.',
      'Name the one place you are overextended before it collapses.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['connector'],
    capabilities: ['exploration'],
    primaryQuestion: 'Where in my web am I the single point of failure?',
    campaignQuestion: 'Which connections am I holding up alone, and at what cost to me?',
    optimizesFor: 'Seeing your own overextension before it becomes burnout.',
    forbiddenMoves: ['Counting only what you give, never what it costs', 'Pressuring yourself to hold more ties', 'Ignoring the drain to feel indispensable'],
    failureModes: ['The Overextended Hub — invisible until collapse', 'Burnout mistaken for devotion'],
    remediation: 'Name one tie you will let rest or hand off.',
    tell: { working: 'You see the overload honestly.', performed: 'You add one more thread to prove you can.' },
    contraindications: ['When mapping becomes an excuse to drop people you fear'],
    example: 'You realize four group chats run only because you keep them alive, and it is draining you.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-ARCHITECT-INNER': {
    id: 'sp-connector-SHOW-ARCHITECT-INNER',
    slug: 'connector-show_up-architect-inner',
    name: "Build Ties That Don't Route Through You",
    essence: 'Structure your relationships so they sustain themselves without you as the hub.',
    steps: [
      'Pick a connection that depends on you and design a way it runs without you.',
      'Feel the fear that you will not be needed.',
      'Build the structure — an intro, a shared ritual — and let it stand on its own.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: ['wood'],
    aspect: 'inner',
    superpowers: ['connector'],
    capabilities: ['participation'],
    primaryQuestion: 'Am I building connections that free me, or ones that need me forever?',
    campaignQuestion: 'What structure lets my ties thrive without me carrying them?',
    optimizesFor: 'A web that holds itself, so you can rest in it.',
    forbiddenMoves: ['Designing dependence on you', 'Pressuring people into a structure they did not choose', 'Hoarding the connective tissue'],
    failureModes: ['The Overextended Hub, formalized', 'Structure that still routes through you'],
    remediation: 'Hand one connecting role to someone else this week.',
    tell: { working: 'The tie thrives without you tending it.', performed: 'You build it so it still needs you.' },
    contraindications: ['When a relationship genuinely needs your active tending now'],
    example: 'You start a recurring dinner and pass the hosting around so it is not yours to carry.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-DIPLOMAT-INNER': {
    id: 'sp-connector-SHOW-DIPLOMAT-INNER',
    slug: 'connector-show_up-diplomat-inner',
    name: 'Let Yourself Belong',
    essence: 'Invite yourself into belonging instead of only hosting it for others.',
    steps: [
      'Name a circle you tend but never let yourself fully join.',
      'Feel the vulnerability of being a member, not the host.',
      'Step in as a participant, with no role to play.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['connector'],
    capabilities: ['connection'],
    primaryQuestion: 'Where do I host belonging for others but never claim it for myself?',
    campaignQuestion: 'What circle could I let myself simply belong to?',
    optimizesFor: 'Belonging you receive, not only belonging you manufacture.',
    forbiddenMoves: ['Only ever being the host', 'Pressuring yourself to earn your place', 'Turning your own belonging into another job'],
    failureModes: ['The host who never gets to be a guest', 'Belonging always deferred'],
    remediation: 'Join one thing this month where you have no role but to be there.',
    tell: { working: 'You let yourself be a member.', performed: 'You volunteer to run it instead.' },
    contraindications: ['When stepping back from hosting would actually abandon people who need it'],
    example: 'You attend the gathering as a guest and resist the urge to start organizing it.',
    tier: 'canonical',
    status: 'published',
  },
}
