/**
 * Hand-authored hero cells — Connector (outer), for the $8,500 car campaign.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 *
 * These replace the generated draft at their coordinate and are authored to L4
 * (full anatomy + trust tests + voice). Published — they pass the no-published-
 * below-L3 gate. Keyed by card id; applied in decks.ts.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const CONNECTOR_OVERRIDES: Record<string, Technique> = {
  'sp-connector-OPEN-DIPLOMAT-OUTER': {
    id: 'sp-connector-OPEN-DIPLOMAT-OUTER',
    slug: 'connector-open_up-diplomat-outer',
    name: 'The Warm Ask',
    essence: "Open a real ask to someone who'd want to help — without turning the relationship into a ledger.",
    steps: [
      "List ten people who'd be glad to be asked.",
      'For each, name a specific amount and a true reason you feel in your body.',
      'Ask one today, in your own voice, with an explicit no-strings out.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['connection'],
    primaryQuestion: 'Whose help am I afraid to receive for the car, and what story makes the ask feel like a debt?',
    campaignQuestion: 'Who would genuinely want to chip in $50–$500 toward the car, and how do I invite them cleanly?',
    optimizesFor: 'Resource flow through warmth, not pressure.',
    forbiddenMoves: ['Mass-blast the same message', 'Imply obligation', 'Pre-decide their no for them'],
    failureModes: ['Transactional scorekeeping', 'Shame-leveraging', 'Only asking the people who least mind'],
    remediation: "If it curdles, say 'no strings — really,' and mean it.",
    tell: { working: 'You feel cleaner after asking, win or lose.', performed: 'You start tracking who now owes you.' },
    contraindications: ["When there's no real warmth in the relationship yet"],
    example: "Text Aunt Dana: 'Saving for a car so I can stop borrowing rides. Would you put $200 toward it? Totally fine if not.'",
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-CHALLENGER-OUTER': {
    id: 'sp-connector-SHOW-CHALLENGER-OUTER',
    slug: 'connector-show_up-challenger-outer',
    name: 'The Direct Ask',
    essence: 'Make the one concrete ask that moves the car fund today — specific person, specific number, by when.',
    steps: [
      'Pick the person and the number.',
      "Make the ask plainly, with a deadline ('trying to close the gap by month's end').",
      'Send the link so yes is easy; make no easy too.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['agency'],
    primaryQuestion: 'What am I feeling in my gut right before I send the ask — and am I about to soften it?',
    campaignQuestion: "What's the single ask that moves the fund today: to whom, how much, by when?",
    optimizesFor: 'An actual dollar amount on the table, not a softened hint.',
    forbiddenMoves: ['Hinting instead of asking', 'Burying the number', 'Pressure a yes'],
    failureModes: ['The ask that never quite gets sent', "Vague 'anything helps' with no target"],
    remediation: 'If you softened it, send a one-line follow-up with the real number.',
    tell: { working: "There's a specific number on the table.", performed: "You 'raised awareness' but asked no one." },
    contraindications: ["When you haven't built any relationship with the person yet"],
    example: "DM a friend: 'Closing in on the car — could you do $100 by Friday? Link here. No worries if not.'",
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-CLEAN-SHAMAN-OUTER': {
    id: 'sp-connector-CLEAN-SHAMAN-OUTER',
    slug: 'connector-clean_up-shaman-outer',
    name: 'Clear the Static',
    essence: 'Clear the relational static with a giver before you ask, so the ask lands clean.',
    steps: [
      'Notice the unspoken charge with this person (old debts, awkwardness).',
      'Name it lightly to yourself, then feel where it sits in your body.',
      'Ask only once the static has dropped a notch.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['connection'],
    primaryQuestion: 'What old relational charge am I about to route into this ask?',
    campaignQuestion: "What's unspoken between us that would make the ask land wrong if I ignore it?",
    optimizesFor: 'An ask received as warmth, not as the next move in an old pattern.',
    forbiddenMoves: ['Asking through resentment', 'Using guilt as leverage', "Pretending the awkwardness isn't there"],
    failureModes: ['The ask reopens an old wound', 'They feel handled, not asked'],
    remediation: "If static spikes mid-ask, pause and name it: 'I know it's been a while — no pressure here.'",
    tell: { working: 'The exchange feels lighter afterward.', performed: 'You rehearse the ask to manage their reaction.' },
    contraindications: ['When the relationship needs repair before any ask'],
    example: 'Before texting an estranged cousin, feel the old charge, then lead with reconnection, not the ask.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-WAKE-ARCHITECT-OUTER': {
    id: 'sp-connector-WAKE-ARCHITECT-OUTER',
    slug: 'connector-wake_up-architect-outer',
    name: 'Map the Givers',
    essence: 'See the whole giving network — who could give, who could match, who could spread the ask.',
    steps: [
      'List everyone in reach who cares about you, in three tiers: give, match, amplify.',
      'Spot the one connector who could open ten more doors — and notice who you flinch to ask.',
      'Name the highest-leverage ask first.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['exploration'],
    primaryQuestion: 'Whose generosity am I overlooking because asking them feels too exposing?',
    campaignQuestion: "Who in the network gives, who matches, and who amplifies — and where's the leverage?",
    optimizesFor: 'Seeing latent reach before grinding out one-by-one asks.',
    forbiddenMoves: ['Only counting the obvious few', "Ignoring people who'd want to help", "Pressure people who can't give"],
    failureModes: ['Tunnel vision on three donors', "Missing the person who'd rally others"],
    remediation: "If stuck, ask one person 'who else do you know who'd want in on this?'",
    tell: { working: 'The map feels bigger and more alive.', performed: 'You make a list but ask no one on it.' },
    contraindications: ["When you're using mapping to avoid the actual ask"],
    example: 'Realize your old teammate runs a group chat of 40 — one warm intro could matter more than ten DMs.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-ARCHITECT-OUTER': {
    id: 'sp-connector-SHOW-ARCHITECT-OUTER',
    slug: 'connector-show_up-architect-outer',
    name: 'Build the Milestone Ladder',
    essence: 'Give the $8,500 a structure people can join — milestones, a match, a visible climb.',
    steps: [
      'Break the goal into rungs ($2k / $4k / $6k / $8.5k) with a why for each.',
      'Line up one matcher to double a rung.',
      'Post the ladder so people see the climb and where they fit.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['participation'],
    primaryQuestion: 'Am I avoiding building structure because it makes the need feel real?',
    campaignQuestion: 'What structure — milestones, a match, a tracker — turns scattered asks into a climb people join?',
    optimizesFor: 'Momentum that compounds instead of one-off asks.',
    forbiddenMoves: ['Over-engineering the spreadsheet', 'Hiding the number', 'Pressure a matcher'],
    failureModes: ['A ladder no one sees', 'Structure that stalls the actual asking'],
    remediation: 'Ship the simplest version today: three rungs and a thermometer.',
    tell: { working: 'People start asking how to help.', performed: 'You tinker with the design to delay asking.' },
    contraindications: ['When structure is procrastination in disguise'],
    example: "Post: 'Car fund: $2k unlocks the down payment. A friend matches the next $1k!'",
    tier: 'canonical',
    status: 'published',
  },
  'sp-connector-SHOW-DIPLOMAT-OUTER': {
    id: 'sp-connector-SHOW-DIPLOMAT-OUTER',
    slug: 'connector-show_up-diplomat-outer',
    name: "Invite, Don't Extract",
    essence: 'Ask in a way that gives people the gift of helping, with full consent and no strings.',
    steps: [
      'Frame the ask as an invitation into something good.',
      'State the no-strings out loud and feel whether your body agrees.',
      'Thank givers in a way that completes the loop, not opens a debt.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['connector'],
    capabilities: ['connection', 'participation'],
    primaryQuestion: 'Am I about to extract from someone instead of inviting them?',
    campaignQuestion: 'How do I invite givers to the car fund so they feel chosen, not used?',
    optimizesFor: 'Giving that strengthens the relationship instead of taxing it.',
    forbiddenMoves: ['Guilt-tripping', "Using someone's story without consent", 'Implying obligation'],
    failureModes: ['The giver feels cornered', 'A yes that quietly costs the friendship'],
    remediation: "If you sense pressure, say 'genuinely no strings — I'll love you either way.'",
    tell: { working: 'Givers thank YOU for the chance.', performed: 'You feel a flicker of leverage.' },
    contraindications: ["When you need money so badly you can't hear a no"],
    example: "'I'm inviting a few people who've had my back to help me get mobile again — zero pressure.'",
    tier: 'canonical',
    status: 'published',
  },
}
