/**
 * Hand-authored hero cells — Disruptor (inner + outer). Authored to L4.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 *
 * CAMPAIGN-AGNOSTIC. Disruptor = clean interruption: breaking stagnation and
 * protecting integrity over false harmony — rupture aimed at repair. Inner =
 * metabolizing your own heat; outer = breaking the pattern others tiptoe around.
 * Shadows woven through: the Demolisher (rupture with no repair) and the Caged
 * Rebel (bitter, waiting for permission, inert). Six coords × both aspects = 12
 * cells; published.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const DISRUPTOR_OVERRIDES: Record<string, Technique> = {
  // ── wake_up × shaman — notice the stagnation / the urge ──
  'sp-disruptor-WAKE-SHAMAN-INNER': {
    id: 'sp-disruptor-WAKE-SHAMAN-INNER',
    slug: 'disruptor-wake_up-shaman-inner',
    name: 'Notice Your Urge to Break',
    essence: 'Catch the urge to break something before it drives the wheel.',
    steps: [
      'Notice the itch to blow up the situation.',
      'Feel where it lives in your body — the clenched jaw, the heat rising.',
      'Name whether it is integrity asking to act or just frustration looking for a target.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['disruptor'],
    capabilities: ['agency'],
    primaryQuestion: 'Is this the urge of integrity or just my frustration looking for a target?',
    campaignQuestion: 'What am I about to break, and is it the right thing?',
    optimizesFor: 'Knowing your own heat before it picks the target for you.',
    forbiddenMoves: ['Acting on the first spark', 'Pressuring yourself to "stay calm" and swallow it', 'Mistaking every frustration for a cause'],
    failureModes: ['The Demolisher — breaking the nearest thing', 'Heat with no aim'],
    remediation: 'Name what the urge wants to protect before you let it move.',
    tell: { working: 'You feel the heat and name its source.', performed: 'You let the heat pick a victim.' },
    contraindications: ['When the moment truly demands an immediate, decisive break'],
    example: 'You feel like quitting on the spot; you pause and name what integrity is actually defending.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-disruptor-WAKE-SHAMAN-OUTER': {
    id: 'sp-disruptor-WAKE-SHAMAN-OUTER',
    slug: 'disruptor-wake_up-shaman-outer',
    name: 'See the Stagnation No One Names',
    essence: 'Notice the stuck pattern everyone has agreed not to mention.',
    steps: [
      'Notice where the room keeps a polite peace over something rotten.',
      'Feel the heaviness of the thing no one will say.',
      'Name the stagnation plainly, before proposing to break it.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['disruptor'],
    capabilities: ['agency'],
    primaryQuestion: 'Am I seeing the real stagnation or just the thing that annoys me?',
    campaignQuestion: 'What stuck pattern is everyone agreeing not to name?',
    optimizesFor: 'Naming the stagnation honestly so the rupture lands on the real thing.',
    forbiddenMoves: ['Naming it to start a fight', 'Pressuring the room to agree it is broken', 'Calling difference dysfunction'],
    failureModes: ['Breaking healthy peace', 'Mistaking discomfort for rot'],
    remediation: 'Describe the stuck pattern in plain, specific terms before judging it.',
    tell: { working: 'The room recognizes the stuck thing.', performed: 'You stir conflict and call it honesty.' },
    contraindications: ['When the "stagnation" is rest the group actually needs'],
    example: 'You name the unspoken process everyone works around but no one will fix.',
    tier: 'canonical',
    status: 'published',
  },

  // ── open_up × challenger — anger as information ──
  'sp-disruptor-OPEN-CHALLENGER-INNER': {
    id: 'sp-disruptor-OPEN-CHALLENGER-INNER',
    slug: 'disruptor-open_up-challenger-inner',
    name: 'Feel the Anger as Information',
    essence: 'Let your anger speak as data without letting it drive.',
    steps: [
      'Let the anger be there without acting on it.',
      'Feel it fully in your body — the pressure, the wish to push.',
      'Ask what boundary it is reporting, and write that down.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['disruptor'],
    capabilities: ['agency'],
    primaryQuestion: 'What boundary or value is my anger actually reporting?',
    campaignQuestion: 'What is my anger trying to protect here?',
    optimizesFor: 'Reading the information in your anger before it becomes a weapon.',
    forbiddenMoves: ['Discharging it onto someone', 'Pressuring yourself to suppress it as "bad"', 'Acting it out to feel powerful'],
    failureModes: ['Anger weaponized', 'Anger buried, then leaking'],
    remediation: 'Finish the sentence "I am angry because the line crossed was ____."',
    tell: { working: 'You hear the message in the anger.', performed: 'You aim the anger and fire.' },
    contraindications: ['When you are using "feeling it" to avoid ever acting'],
    example: 'A decision enrages you; you sit with it and find the value it violated.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-disruptor-OPEN-CHALLENGER-OUTER': {
    id: 'sp-disruptor-OPEN-CHALLENGER-OUTER',
    slug: 'disruptor-open_up-challenger-outer',
    name: 'Take In the Hidden Cost',
    essence: 'Receive the cost the stuck pattern is quietly extracting from people.',
    steps: [
      'Ask who is paying for the pattern that keeps the peace.',
      'Feel the weight of that cost instead of abstracting it.',
      'Let the cost — not your irritation — become the reason to act.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['disruptor'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I breaking this for the people who pay for it, or for me?',
    campaignQuestion: 'Who is quietly paying the cost of leaving this pattern intact?',
    optimizesFor: 'Rupture motivated by the real harm, not your discomfort.',
    forbiddenMoves: ['Acting for your own catharsis', 'Pressuring the harmed into your fight', 'Using their cost as ammunition'],
    failureModes: ['Disruption that serves the disruptor', 'Speaking over the people who pay'],
    remediation: 'Name the specific person and cost your action is meant to relieve.',
    tell: { working: 'The harmed feel seen by your move.', performed: 'You use their pain to win your point.' },
    contraindications: ['When the people paying have asked you not to act yet'],
    example: 'You ground your challenge in the junior staff burning out, not your own annoyance.',
    tier: 'canonical',
    status: 'published',
  },

  // ── clean_up × challenger — forge heat into clean aim ──
  'sp-disruptor-CLEAN-CHALLENGER-INNER': {
    id: 'sp-disruptor-CLEAN-CHALLENGER-INNER',
    slug: 'disruptor-clean_up-challenger-inner',
    name: 'Forge the Heat into Aim',
    essence: 'Transmute raw anger into a clean, specific intention.',
    steps: [
      'Take the hot, vague anger and write what it wants.',
      'Feel the difference between "burn it down" and "change this one thing."',
      'Forge it into a single clean aim you could say out loud.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['disruptor'],
    capabilities: ['agency'],
    primaryQuestion: 'What is the one clean change my heat is actually aiming at?',
    campaignQuestion: 'How do I turn this fire into a precise target?',
    optimizesFor: 'A focused aim instead of a blast radius.',
    forbiddenMoves: ['Letting the heat stay a blast', 'Pressuring a target into existence', 'Confusing intensity with clarity'],
    failureModes: ['The Demolisher — wide damage', 'Diffuse rage, no result'],
    remediation: 'Reduce the anger to one sentence: "I want this specific thing to change."',
    tell: { working: 'The heat narrows to one clear aim.', performed: 'You stay hot and hit everything.' },
    contraindications: ['When forcing precision suppresses a grief that needs room first'],
    example: 'Furious at the whole org, you forge it into one concrete policy you will challenge.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-disruptor-CLEAN-CHALLENGER-OUTER': {
    id: 'sp-disruptor-CLEAN-CHALLENGER-OUTER',
    slug: 'disruptor-clean_up-challenger-outer',
    name: 'Point Rupture Toward Repair',
    essence: 'Aim the break so it opens a path to repair, not just a hole.',
    steps: [
      'Before you break the pattern, name what should grow in its place.',
      'Feel whether you are leaving people a way forward or just wreckage.',
      'Make the break and the repair part of the same move.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['disruptor'],
    capabilities: ['agency'],
    primaryQuestion: 'What grows where I am about to break something?',
    campaignQuestion: 'Does this rupture leave a path forward, or just a hole?',
    optimizesFor: 'Breaks that open repair instead of leaving rubble.',
    forbiddenMoves: ['Breaking with no plan for after', 'Pressuring people to applaud the wreckage', 'Calling demolition courage'],
    failureModes: ['The Demolisher — rupture with no repair', 'Burned bridges, no crossing'],
    remediation: 'Name the next constructive step before you make the break.',
    tell: { working: 'People can see the way forward through the break.', performed: 'You break it and walk away.' },
    contraindications: ['When a thing must simply end and no replacement is owed'],
    example: 'You kill the broken ritual and, in the same breath, propose what replaces it.',
    tier: 'canonical',
    status: 'published',
  },

  // ── grow_up × regent — temper timing and aim ──
  'sp-disruptor-GROW-REGENT-INNER': {
    id: 'sp-disruptor-GROW-REGENT-INNER',
    slug: 'disruptor-grow_up-regent-inner',
    name: 'Temper Your Timing',
    essence: 'Build the patience to strike when it lands, not the instant you feel it.',
    steps: [
      'Notice the pull to act the second the anger spikes.',
      'Feel the restlessness of waiting without going inert.',
      'Practice holding the charge until the moment it will actually work.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['earth'],
    aspect: 'inner',
    superpowers: ['disruptor'],
    capabilities: ['rest'],
    primaryQuestion: 'Can I hold this heat until the moment it will actually land?',
    campaignQuestion: 'Am I striking on my timing or just on my impulse?',
    optimizesFor: 'Timing that makes the same force land far harder.',
    forbiddenMoves: ['Striking on impulse', 'Pressuring the moment to arrive now', 'Letting "waiting" curdle into the Caged Rebel'],
    failureModes: ['Premature rupture', 'The Caged Rebel — bitter, inert waiting'],
    remediation: 'Name the condition that means "now"; act when it is true, not before.',
    tell: { working: 'You strike when it lands.', performed: 'You wait forever and grow bitter.' },
    contraindications: ['When waiting is just fear wearing the mask of strategy'],
    example: 'You hold the hard feedback until the review, where it can actually change the call.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-disruptor-GROW-REGENT-OUTER': {
    id: 'sp-disruptor-GROW-REGENT-OUTER',
    slug: 'disruptor-grow_up-regent-outer',
    name: 'Grow the Group’s Tolerance',
    essence: 'Build the group’s capacity to take change without shattering.',
    steps: [
      'Introduce disruption in doses the group can metabolize.',
      'Feel for the edge between productive heat and panic.',
      'Let each survived change make the next one easier to take.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['disruptor'],
    capabilities: ['participation'],
    primaryQuestion: 'Can this group take the change I am about to bring?',
    campaignQuestion: 'How do I build their tolerance for change instead of overwhelming it?',
    optimizesFor: 'A group that grows able to change instead of bracing against it.',
    forbiddenMoves: ['Overwhelming the group at once', 'Pressuring them past their capacity', 'Mistaking shock for growth'],
    failureModes: ['Change fatigue and shutdown', 'Whiplash, then resistance'],
    remediation: 'Right-size the next disruption to what they just survived.',
    tell: { working: 'The group takes change more easily over time.', performed: 'The group flinches at the sight of you.' },
    contraindications: ['When the harm is acute and gradualism is complicity'],
    example: 'You sequence the reorg so each step is survivable, and trust grows with each one.',
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × challenger — break the pattern ──
  'sp-disruptor-SHOW-CHALLENGER-INNER': {
    id: 'sp-disruptor-SHOW-CHALLENGER-INNER',
    slug: 'disruptor-show_up-challenger-inner',
    name: 'Break Your Own Complicity',
    essence: 'Make the move that stops your own quiet participation in the stuck pattern.',
    steps: [
      'Name the way you have been going along with it.',
      'Feel the fear of being the one who stops.',
      'Take the concrete action that ends your complicity today.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['disruptor'],
    capabilities: ['agency'],
    primaryQuestion: 'How am I helping the stuck pattern survive, and what stops that today?',
    campaignQuestion: 'What is my part in this, and how do I break it first?',
    optimizesFor: 'Disrupting your own complicity before demanding others change.',
    forbiddenMoves: ['Demanding change you will not start', 'Pressuring others while you comply', 'Waiting for permission to stop'],
    failureModes: ['The Caged Rebel — outrage without action', 'Hypocrisy that kills credibility'],
    remediation: 'Name one thing you will stop doing that feeds the pattern, and stop it.',
    tell: { working: 'You change your own behavior first.', performed: 'You demand of others what you will not do.' },
    contraindications: ['When self-focus becomes a way to avoid naming a real external wrong'],
    example: 'You stop attending the meeting that launders the bad decision, and say why.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-disruptor-SHOW-CHALLENGER-OUTER': {
    id: 'sp-disruptor-SHOW-CHALLENGER-OUTER',
    slug: 'disruptor-show_up-challenger-outer',
    name: 'Break the Pattern',
    essence: 'Make the clean, public interruption that stops the stuck pattern from continuing.',
    steps: [
      'Name the pattern out loud, specifically, to the people who can change it.',
      'Feel the fear of being the one who says it, and say it anyway.',
      'Make the concrete move that makes continuing impossible.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['disruptor'],
    capabilities: ['agency'],
    primaryQuestion: 'Am I interrupting cleanly, or just causing a scene?',
    campaignQuestion: 'What concrete move makes this stuck pattern impossible to continue?',
    optimizesFor: 'The clean interruption that actually stops the harm.',
    forbiddenMoves: ['Making a scene for its own sake', 'Pressuring people through humiliation', 'Breaking without naming why'],
    failureModes: ['The Demolisher — drama, no change', 'Rupture that rallies the defenders'],
    remediation: 'Tie the interruption to the specific harm and the specific next step.',
    tell: { working: 'The pattern actually stops.', performed: 'You make noise and it resumes tomorrow.' },
    contraindications: ['When a private word would stop it without the cost of a public break'],
    example: 'You halt the meeting to name the decision that keeps getting made in the hallway.',
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × sage — repair / integrate after rupture ──
  'sp-disruptor-SHOW-SAGE-INNER': {
    id: 'sp-disruptor-SHOW-SAGE-INNER',
    slug: 'disruptor-show_up-sage-inner',
    name: 'Carry the Cost of Breaking',
    essence: 'Integrate the aftermath: stay present to what your rupture cost, including in you.',
    steps: [
      'After the break, stay instead of fleeing the wreckage.',
      'Feel the grief or guilt without numbing or justifying it.',
      'Name what you would protect and what you would do differently next time.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['disruptor'],
    capabilities: ['connection'],
    primaryQuestion: 'Can I stay present to what my rupture cost, including in me?',
    campaignQuestion: 'What do I owe the aftermath of the break I made?',
    optimizesFor: 'A disruptor who integrates the cost instead of fleeing it.',
    forbiddenMoves: ['Fleeing the wreckage', 'Pressuring yourself to feel only righteous', 'Numbing the guilt with the next fight'],
    failureModes: ['Serial rupture, never repair', 'Righteousness as armor'],
    remediation: 'Sit with the cost for one honest minute before moving to the next thing.',
    tell: { working: 'You stay and feel what it cost.', performed: 'You sprint to the next thing to break.' },
    contraindications: ['When self-blame becomes its own indulgence'],
    example: 'After the hard call, you let yourself feel the loss instead of declaring victory.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-disruptor-SHOW-SAGE-OUTER': {
    id: 'sp-disruptor-SHOW-SAGE-OUTER',
    slug: 'disruptor-show_up-sage-outer',
    name: 'Repair What You Break',
    essence: 'Complete the rupture by tending the repair that lets something better grow.',
    steps: [
      'After the break, turn toward the people left in it.',
      'Feel what they need to trust a way forward.',
      'Do the concrete repair — the conversation, the rebuild — that the rupture was for.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['disruptor'],
    capabilities: ['participation'],
    primaryQuestion: 'Have I tended the repair, or only enjoyed the break?',
    campaignQuestion: 'What repair lets something better grow where I broke the old thing?',
    optimizesFor: "The disruptor's whole arc: rupture completed by repair.",
    forbiddenMoves: ['Leaving others to clean up', 'Pressuring a fast reconciliation to look good', 'Calling the break finished at the break'],
    failureModes: ['The Demolisher — no repair', 'Trust that never returns'],
    remediation: 'Name one concrete act of repair and do it within the week.',
    tell: { working: 'Something better grows where you broke the old thing.', performed: 'You leave and call the rubble progress.' },
    contraindications: ['When forcing repair denies people the space to be angry first'],
    example: 'After ending the broken process, you help build and staff the one that replaces it.',
    tier: 'canonical',
    status: 'published',
  },
}
