/**
 * Hand-authored hero cells — Escape Artist (inner), for the $8,500 car campaign.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 *
 * Matched to the Connector outer hero coordinates so a player running
 * inner=escape_artist / outer=connector gets both slots at L4 on the same
 * move × face — lighting up campaign-ready base cells. Authored to L4, published.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const ESCAPE_ARTIST_OVERRIDES: Record<string, Technique> = {
  'sp-escape_artist-OPEN-DIPLOMAT-INNER': {
    id: 'sp-escape_artist-OPEN-DIPLOMAT-INNER',
    slug: 'escape_artist-open_up-diplomat-inner',
    name: 'Receive Without Bracing',
    essence: 'Let help land for the car without bracing for the catch.',
    steps: [
      'Notice the brace in your body when someone offers.',
      'Breathe; let the offer in one inch further than feels safe.',
      "Say a clean 'thank you' without deflecting.",
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['connection'],
    primaryQuestion: 'What am I protecting by refusing help — and is it still worth the cost?',
    campaignQuestion: 'Whose offered help for the car am I deflecting out of habit?',
    optimizesFor: 'Actually receiving the resources people offer, so the fund grows.',
    forbiddenMoves: ['Deflecting the offer', "Over-explaining why you don't really need it", 'Attaching strings to received help'],
    failureModes: ["'I'm fine' when you're not", 'Turning help into a debt you must repay'],
    remediation: "If you deflect, circle back: 'Actually — yes, that would help.'",
    tell: { working: 'You feel the brace soften.', performed: 'You accept but immediately plan to pay it back double.' },
    contraindications: ["When the 'help' has real strings you're right to refuse"],
    example: "A friend offers $300; instead of 'oh you don't have to,' say 'thank you — that genuinely helps.'",
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-CHALLENGER-INNER': {
    id: 'sp-escape_artist-SHOW-CHALLENGER-INNER',
    slug: 'escape_artist-show_up-challenger-inner',
    name: 'Stay for the Ask',
    essence: "Don't vanish in the sixty seconds before you send the ask.",
    steps: [
      'Feel the urge to flee right before sending.',
      'Set a 10-minute timer; name the fear out loud.',
      'Send one ask before it rings.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['agency'],
    primaryQuestion: 'Is my urge to bolt protecting me from real danger, or just from being seen needing help?',
    campaignQuestion: 'Which ask am I one click away from sending but keep escaping?',
    optimizesFor: 'Sending the ask — the move that could actually increase life — instead of fleeing it.',
    forbiddenMoves: ["Calling avoidance 'timing'", 'Suddenly reorganizing your whole plan to avoid sending', 'Pressuring yourself into freeze'],
    failureModes: ["Perpetual 'not the right moment'", 'Researching instead of asking'],
    remediation: 'Shrink it: send the ask to one safe person first.',
    tell: { working: 'You name the fear and send anyway.', performed: 'You produce three more reasons to wait.' },
    contraindications: ['When pausing is genuinely wiser — but be honest'],
    example: 'Timer set: text one person the fundraiser link before 10 minutes pass.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-CLEAN-SHAMAN-INNER': {
    id: 'sp-escape_artist-CLEAN-SHAMAN-INNER',
    slug: 'escape_artist-clean_up-shaman-inner',
    name: 'Wise Retreat or Just Scared?',
    essence: 'Sort a genuine reason not to ask from plain exposure-fear.',
    steps: [
      'Feel the flinch and locate it in the body.',
      "Ask the Escape Artist's question: what is this fear protecting?",
      'Sort: a real reason (name it) vs. just being seen needing help (proceed anyway).',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['exploration'],
    primaryQuestion: "Is this 'no' wisdom, or is it just fear wearing wisdom's coat?",
    campaignQuestion: "Where am I calling avoidance 'discernment' in the campaign?",
    optimizesFor: 'Not abandoning a good ask because needing help feels exposing.',
    forbiddenMoves: ['Dressing avoidance as discernment', 'Ghosting the campaign to dodge the feeling', "Carrying others' guilt about your need"],
    failureModes: ["Perpetual 'not the right time'", 'Researching instead of asking'],
    remediation: 'Set a 10-minute timer; send one ask before it rings.',
    tell: { working: 'You name the fear and move.', performed: 'You generate three more reasons to wait.' },
    contraindications: ['When the retreat really is the wise move — then rest without guilt'],
    example: 'You feel dread posting the fundraiser; you sort it: not danger, just exposure — you post.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-WAKE-ARCHITECT-INNER': {
    id: 'sp-escape_artist-WAKE-ARCHITECT-INNER',
    slug: 'escape_artist-wake_up-architect-inner',
    name: 'Spot Your Dodge',
    essence: "Notice the plan you're avoiding because building it makes the need real.",
    steps: [
      'Scan for the task you keep sliding past (the budget, the page, the list).',
      'Feel the avoidance in your body.',
      'Name the dodge out loud and take the smallest next step.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['exploration'],
    primaryQuestion: 'What am I not letting myself see about the fund because seeing it commits me?',
    campaignQuestion: 'What structural step for the car am I quietly dodging?',
    optimizesFor: 'Seeing the avoided move before it silently sinks the campaign.',
    forbiddenMoves: ["Calling the dodge 'being busy'", 'Guilt-spiraling instead of acting', 'Vanishing into research'],
    failureModes: ['The budget you never open', 'Motion without the key move'],
    remediation: 'Open the avoided thing for 5 minutes only.',
    tell: { working: 'You name the dodge and touch it.', performed: 'You make a new to-do list to avoid the old one.' },
    contraindications: ['When you genuinely need rest, not another push'],
    example: "You keep 'forgetting' to total the costs; you open the doc for five minutes.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-ARCHITECT-INNER': {
    id: 'sp-escape_artist-SHOW-ARCHITECT-INNER',
    slug: 'escape_artist-show_up-architect-inner',
    name: 'Pre-Commit the Rest',
    essence: "Decide in advance when you'll rest, so you don't bolt from the campaign mid-push.",
    steps: [
      "Name the point where you'll pause (after the asks go out, not before).",
      'Schedule the rest like an appointment.',
      'When the urge to vanish hits early, feel it, point to the scheduled rest, and keep going.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: ['earth'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['rest'],
    primaryQuestion: "Am I about to call quitting 'self-care' to escape the exposure?",
    campaignQuestion: 'What sustainable rhythm lets me keep asking without burning out or bolting?',
    optimizesFor: 'Staying in the campaign by resourcing rest, so the effort can increase life rather than drain you.',
    forbiddenMoves: ['Disguising flight as self-care', 'Pushing with no rest until you crash', 'Ghosting without a return plan'],
    failureModes: ['Bolting right before the finish', 'Burnout framed as boundaries'],
    remediation: 'If you bolted, name the real fear and set the next small ask.',
    tell: { working: 'You rest on schedule and return.', performed: "You 'rest' the moment it gets exposing." },
    contraindications: ['When you truly need to stop — then stop, cleanly'],
    example: 'Plan: send five asks, then take the weekend off, then resume Monday.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-DIPLOMAT-INNER': {
    id: 'sp-escape_artist-SHOW-DIPLOMAT-INNER',
    slug: 'escape_artist-show_up-diplomat-inner',
    name: 'Name the Cost of Staying',
    essence: 'Name what staying in the ask actually costs you, so the cost is chosen, not leaked.',
    steps: [
      'Feel where the campaign drains you.',
      'Name the real cost out loud (time, pride, exposure).',
      "Decide if it's worth it — and if yes, stay on purpose.",
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['earth'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['rest'],
    primaryQuestion: "What is staying in this fundraiser costing me that I haven't named?",
    campaignQuestion: 'What do I need to acknowledge about the cost so I can keep showing up honestly?',
    optimizesFor: 'Chosen, sustainable presence instead of silent depletion.',
    forbiddenMoves: ['Pretending it costs nothing', 'Becoming a martyr', "Turning your cost into others' obligation"],
    failureModes: ['Unnamed depletion becomes disappearance', 'Resentment poisons the gratitude'],
    remediation: 'Name the cost to one trusted person; let it be witnessed.',
    tell: { working: 'You stay clear-eyed about the price and stay anyway.', performed: 'You keep score of what staying costs.' },
    contraindications: ["When the cost is too high — then it's okay to step back"],
    example: 'Admit asking for money bruises your pride; name it, and choose to keep asking.',
    tier: 'canonical',
    status: 'published',
  },
}
