/**
 * Hand-authored hero cells — Escape Artist (inner + outer). Authored to L4.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 *
 * CAMPAIGN-AGNOSTIC: durable fields work for any campaign; `example` is one
 * concrete illustration, not a constraint. Matched to the Connector hero
 * coordinates so the inner=escape_artist / outer=connector loadout gets both
 * slots at L4 on the same move × face. Published.
 *
 * Inner = honoring your OWN wisdom of fear (staying for the ask, sorting wise
 * retreat from flight). Outer = helping others find a dignified exit — seeing the
 * trap, opening a door, offering a graceful way out — metabolizing the Perpetual
 * Vanisher shadow (leaving, or making others leave, before it's time). Six coords
 * × both aspects = 12 cells.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const ESCAPE_ARTIST_OVERRIDES: Record<string, Technique> = {
  'sp-escape_artist-OPEN-DIPLOMAT-INNER': {
    id: 'sp-escape_artist-OPEN-DIPLOMAT-INNER',
    slug: 'escape_artist-open_up-diplomat-inner',
    name: 'Receive Without Bracing',
    essence: 'Let help land without bracing for the catch.',
    steps: [
      'Notice the brace in your body when someone offers.',
      'Breathe; let the offer in one inch further than feels safe.',
      "Say a clean 'thank you' without deflecting.",
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['connection'],
    primaryQuestion: 'What am I protecting by refusing help — and is it still worth the cost?',
    campaignQuestion: 'Whose offered help am I deflecting out of habit?',
    optimizesFor: 'Actually receiving the support people offer.',
    forbiddenMoves: ['Deflecting the offer', "Over-explaining why you don't really need it", 'Attaching strings to received help'],
    failureModes: ["'I'm fine' when you're not", 'Turning help into a debt you must repay'],
    remediation: "If you deflect, circle back: 'Actually — yes, that would help.'",
    tell: { working: 'You feel the brace soften.', performed: 'You accept but immediately plan to pay it back double.' },
    contraindications: ["When the 'help' has real strings you're right to refuse"],
    example: "Someone offers to pitch in; instead of 'oh you don't have to,' say 'thank you — that genuinely helps.'",
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-CHALLENGER-INNER': {
    id: 'sp-escape_artist-SHOW-CHALLENGER-INNER',
    slug: 'escape_artist-show_up-challenger-inner',
    name: 'Stay for the Ask',
    essence: 'Don’t vanish in the sixty seconds before you make the ask.',
    steps: [
      'Feel the urge to flee right before you act.',
      'Set a 10-minute timer; name the fear out loud.',
      'Make one ask before it rings.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['agency'],
    primaryQuestion: 'Is my urge to bolt protecting me from real danger, or just from being seen needing help?',
    campaignQuestion: 'Which ask am I one click away from making but keep escaping?',
    optimizesFor: 'Making the ask — the move that could actually increase life — instead of fleeing it.',
    forbiddenMoves: ["Calling avoidance 'timing'", 'Suddenly reorganizing your whole plan to avoid acting', 'Pressuring yourself into freeze'],
    failureModes: ["Perpetual 'not the right moment'", 'Researching instead of asking'],
    remediation: 'Shrink it: make the ask to one safe person first.',
    tell: { working: 'You name the fear and act anyway.', performed: 'You produce three more reasons to wait.' },
    contraindications: ['When pausing is genuinely wiser — but be honest'],
    example: 'Timer set: make one ask before 10 minutes pass.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-CLEAN-SHAMAN-INNER': {
    id: 'sp-escape_artist-CLEAN-SHAMAN-INNER',
    slug: 'escape_artist-clean_up-shaman-inner',
    name: 'Wise Retreat or Just Scared?',
    essence: 'Sort a genuine reason not to act from plain exposure-fear.',
    steps: [
      'Feel the flinch and locate it in the body.',
      "Ask the Escape Artist's question: what is this fear protecting?",
      'Sort: a real reason (name it) vs. just being seen needing help (proceed anyway).',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['exploration'],
    primaryQuestion: "Is this 'no' wisdom, or is it just fear wearing wisdom's coat?",
    campaignQuestion: "Where am I calling avoidance 'discernment'?",
    optimizesFor: 'Not abandoning a good move because being seen needing help feels exposing.',
    forbiddenMoves: ['Dressing avoidance as discernment', 'Going quiet to dodge the feeling', "Carrying others' guilt about your need"],
    failureModes: ["Perpetual 'not the right time'", 'Researching instead of acting'],
    remediation: 'Set a 10-minute timer; take one real step before it rings.',
    tell: { working: 'You name the fear and move.', performed: 'You generate three more reasons to wait.' },
    contraindications: ['When the retreat really is the wise move — then rest without guilt'],
    example: 'You feel dread about posting the ask; you sort it: not danger, just exposure — you post.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-WAKE-ARCHITECT-INNER': {
    id: 'sp-escape_artist-WAKE-ARCHITECT-INNER',
    slug: 'escape_artist-wake_up-architect-inner',
    name: 'Spot Your Dodge',
    essence: "Notice the step you're avoiding because doing it makes the need real.",
    steps: [
      'Scan for the task you keep sliding past.',
      'Feel the avoidance in your body.',
      'Name the dodge out loud and take the smallest next step.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['exploration'],
    primaryQuestion: 'What am I not letting myself see because seeing it commits me?',
    campaignQuestion: 'What key step am I quietly dodging?',
    optimizesFor: 'Seeing the avoided move before it silently sinks the effort.',
    forbiddenMoves: ["Calling the dodge 'being busy'", 'Guilt-spiraling instead of acting', 'Vanishing into research'],
    failureModes: ['The task you never open', 'Motion without the key move'],
    remediation: 'Open the avoided thing for 5 minutes only.',
    tell: { working: 'You name the dodge and touch it.', performed: 'You make a new to-do list to avoid the old one.' },
    contraindications: ['When you genuinely need rest, not another push'],
    example: "You keep 'forgetting' the key task; you open it for five minutes.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-ARCHITECT-INNER': {
    id: 'sp-escape_artist-SHOW-ARCHITECT-INNER',
    slug: 'escape_artist-show_up-architect-inner',
    name: 'Pre-Commit the Rest',
    essence: "Decide in advance when you'll rest, so you don't bolt mid-push.",
    steps: [
      "Name the point where you'll pause (after the work goes out, not before).",
      'Schedule the rest like an appointment.',
      'When the urge to vanish hits early, feel it, point to the scheduled rest, and keep going.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: ['earth'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['rest'],
    primaryQuestion: "Am I about to call quitting 'self-care' to escape the exposure?",
    campaignQuestion: 'What sustainable rhythm lets me keep showing up without burning out or bolting?',
    optimizesFor: 'Staying in the work by resourcing rest, so the effort can increase life rather than drain you.',
    forbiddenMoves: ['Disguising flight as self-care', 'Pushing with no rest until you crash', 'Ghosting without a return plan'],
    failureModes: ['Bolting right before the finish', 'Burnout framed as boundaries'],
    remediation: 'If you bolted, name the real fear and set the next small step.',
    tell: { working: 'You rest on schedule and return.', performed: "You 'rest' the moment it gets exposing." },
    contraindications: ['When you truly need to stop — then stop, cleanly'],
    example: 'Plan: do the next batch of work, then take the weekend off, then resume Monday.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-DIPLOMAT-INNER': {
    id: 'sp-escape_artist-SHOW-DIPLOMAT-INNER',
    slug: 'escape_artist-show_up-diplomat-inner',
    name: 'Name the Cost of Staying',
    essence: 'Name what staying in the work actually costs you, so the cost is chosen, not leaked.',
    steps: [
      'Feel where the work drains you.',
      'Name the real cost out loud (time, pride, exposure).',
      "Decide if it's worth it — and if yes, stay on purpose.",
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['earth'],
    aspect: 'inner',
    superpowers: ['escape_artist'],
    capabilities: ['rest'],
    primaryQuestion: "What is staying in this costing me that I haven't named?",
    campaignQuestion: 'What do I need to acknowledge about the cost so I can keep showing up honestly?',
    optimizesFor: 'Chosen, sustainable presence instead of silent depletion.',
    forbiddenMoves: ['Pretending it costs nothing', 'Becoming a martyr', "Turning your cost into others' obligation"],
    failureModes: ['Unnamed depletion becomes disappearance', 'Resentment poisons the gratitude'],
    remediation: 'Name the cost to one trusted person; let it be witnessed.',
    tell: { working: 'You stay clear-eyed about the price and stay anyway.', performed: 'You keep score of what staying costs.' },
    contraindications: ["When the cost is too high — then it's okay to step back"],
    example: 'Admit the work bruises your pride; name it, and choose to keep going.',
    tier: 'canonical',
    status: 'published',
  },

  // ── outer aspect — give others a dignified exit; honor their wisdom of fear ──
  'sp-escape_artist-OPEN-DIPLOMAT-OUTER': {
    id: 'sp-escape_artist-OPEN-DIPLOMAT-OUTER',
    slug: 'escape_artist-open_up-diplomat-outer',
    name: 'Hear Their Need to Get Out',
    essence: "Receive someone's quiet wish to leave without shaming them for it.",
    steps: [
      'Listen for the person hinting they want out but afraid to say it.',
      'Feel your own urge to talk them into staying, and set it down.',
      "Reflect their need back: 'it sounds like you might need an exit.'",
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['escape_artist'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I hearing their need to leave, or only my wish for them to stay?',
    campaignQuestion: 'Who is quietly asking for a way out that no one will acknowledge?',
    optimizesFor: "Honoring another's wisdom of fear instead of overriding it.",
    forbiddenMoves: ['Talking them out of their no', 'Pressuring them to stay for your sake', 'Shaming the wish to leave'],
    failureModes: ['The exit they never felt allowed to name', 'Loyalty extracted by guilt'],
    remediation: "Ask 'do you need a way out of this?' and let the answer stand.",
    tell: { working: 'They feel permission to name the exit.', performed: 'You argue them back into the trap.' },
    contraindications: ['When someone is fleeing what they would be better staying with — but ask, do not assume'],
    example: 'A teammate keeps hinting at burnout; you name that it is okay to step back.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-CHALLENGER-OUTER': {
    id: 'sp-escape_artist-SHOW-CHALLENGER-OUTER',
    slug: 'escape_artist-show_up-challenger-outer',
    name: 'Open a Door for Them',
    essence: 'Make the concrete move that gives someone a real way out, today.',
    steps: [
      'Find the specific exit the person cannot make for themselves.',
      'Feel the risk of acting on their behalf, and check it is wanted.',
      'Open the door — the introduction, the cover, the off-ramp — concretely.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['fire'],
    aspect: 'outer',
    superpowers: ['escape_artist'],
    capabilities: ['agency'],
    primaryQuestion: 'What concrete door can I open that they cannot open alone?',
    campaignQuestion: 'Whose exit am I one action away from making real?',
    optimizesFor: 'A real, usable way out placed in someone’s hand.',
    forbiddenMoves: ['Pushing them through a door they did not choose', 'Pressuring the exit on your timeline', 'Opening it for your own relief'],
    failureModes: ['An exit no one asked for', 'Rescue that strips their agency'],
    remediation: 'Confirm they want it, then take the one action that opens the way.',
    tell: { working: 'They walk through a door they choose.', performed: 'You shove them out for your own peace.' },
    contraindications: ['When the person needs to find their own exit to own it'],
    example: 'You quietly arrange the introduction that lets a stuck friend leave a bad situation.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-CLEAN-SHAMAN-OUTER': {
    id: 'sp-escape_artist-CLEAN-SHAMAN-OUTER',
    slug: 'escape_artist-clean_up-shaman-outer',
    name: 'Sort Their Exit from Their Flight',
    essence: 'Help someone tell a wise retreat from plain panic before they bolt.',
    steps: [
      'Slow the moment before they run.',
      'Feel with them whether the fear is signal or just exposure.',
      'Name the difference: a real reason to leave, or fear wearing wisdom’s coat.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['escape_artist'],
    capabilities: ['exploration'],
    primaryQuestion: 'Am I helping them discern, or just endorsing the bolt?',
    campaignQuestion: "Is this person's exit wisdom, or fear in wisdom's coat?",
    optimizesFor: 'A clear-eyed choice to stay or go, not a reflex.',
    forbiddenMoves: ['Rubber-stamping the flight', 'Pressuring them to stay through guilt', 'Deciding for them'],
    failureModes: ['Endorsing avoidance as discernment', 'A bolt they later regret'],
    remediation: "Ask 'what is the fear protecting?' and sort it together.",
    tell: { working: 'They choose with clear eyes.', performed: 'You hand them a reason to run.' },
    contraindications: ['When delay itself is the danger — then help them go'],
    example: 'A friend wants to quit on the spot; you help them sort real reasons from raw fear first.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-WAKE-ARCHITECT-OUTER': {
    id: 'sp-escape_artist-WAKE-ARCHITECT-OUTER',
    slug: 'escape_artist-wake_up-architect-outer',
    name: 'See the Trap Closing on Them',
    essence: 'Notice the trap closing on someone before they feel it themselves.',
    steps: [
      'Scan for the person being slowly boxed in.',
      'Feel the closing in your own gut as an early warning.',
      'Name the trap to them plainly, while there is still room to move.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['escape_artist'],
    capabilities: ['exploration'],
    primaryQuestion: 'What trap is closing on someone that they cannot yet see?',
    campaignQuestion: 'Who is being boxed in while everyone looks away?',
    optimizesFor: 'Early warning that leaves someone time to choose.',
    forbiddenMoves: ['Naming the trap to frighten them', 'Pressuring them to flee on your read', 'Watching the trap close in silence'],
    failureModes: ['The warning that comes too late', 'Crying trap at every shadow'],
    remediation: 'Describe the specific closing door you see and ask if they see it too.',
    tell: { working: 'They see the trap with time to act.', performed: 'You alarm them and offer no room.' },
    contraindications: ['When your "trap" is your own fear projected onto them'],
    example: 'You notice a colleague being set up to take the fall and name it before it lands.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-ARCHITECT-OUTER': {
    id: 'sp-escape_artist-SHOW-ARCHITECT-OUTER',
    slug: 'escape_artist-show_up-architect-outer',
    name: 'Build More Than One Way Out',
    essence: 'Structure options so the person is not cornered into a single path.',
    steps: [
      'Map the choices the person actually has, beyond the obvious one.',
      'Feel where they believe there is only one door.',
      'Build at least one more real option and lay it beside the first.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: ['earth'],
    aspect: 'outer',
    superpowers: ['escape_artist'],
    capabilities: ['rest'],
    primaryQuestion: 'Does this person have more than one way out, or only the door I see?',
    campaignQuestion: 'What second option would keep someone from being cornered?',
    optimizesFor: 'Choice instead of a forced move.',
    forbiddenMoves: ['Offering one exit and calling it freedom', 'Pressuring them down the path you prefer', 'Designing options that all lead where you want'],
    failureModes: ['A false choice', 'One door dressed as many'],
    remediation: 'Add one genuinely different option they had not considered.',
    tell: { working: 'They have real, different choices.', performed: 'You build doors that all open the same way.' },
    contraindications: ['When too many options would paralyze someone who needs to move'],
    example: 'Before someone quits with nothing lined up, you help build two viable alternatives.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-escape_artist-SHOW-DIPLOMAT-OUTER': {
    id: 'sp-escape_artist-SHOW-DIPLOMAT-OUTER',
    slug: 'escape_artist-show_up-diplomat-outer',
    name: 'Offer a Graceful Exit',
    essence: 'Give someone a way out that keeps their dignity, with full consent and no shame.',
    steps: [
      'Frame the exit as honorable, not a failure.',
      'Feel whether your offer carries any judgment, and clear it.',
      'Make leaving easy and face-saving, then let them choose freely.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['escape_artist'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I offering an exit that protects their dignity, or one that costs them face?',
    campaignQuestion: 'How do I let someone leave without shame or strings?',
    optimizesFor: 'Exits that preserve dignity and relationship.',
    forbiddenMoves: ['Making the exit humiliating', 'Pressuring them to take it', 'Holding their leaving over them later'],
    failureModes: ['A way out that costs too much face to use', 'Help that becomes a debt'],
    remediation: "Say 'there's no shame in stepping back — genuinely.'",
    tell: { working: 'They leave with their dignity intact.', performed: 'You let the exit cost them face.' },
    contraindications: ['When someone needs to stay and face something, not be handed an out'],
    example: 'You give a volunteer a graceful, no-shame way to step down from a role they can no longer carry.',
    tier: 'canonical',
    status: 'published',
  },
}
