/**
 * Hand-authored hero cells — Storyteller (inner + outer). Authored to L4.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 *
 * CAMPAIGN-AGNOSTIC: durable fields work for any campaign; `example` is one
 * illustration. Authored at 6 Storyteller-strong coordinates in BOTH aspects, so
 * a storyteller/storyteller loadout gets both slots at L4 on the same move × face.
 * The Storyteller's shadow ("the Performer — spectacle over truth") threads the
 * forbidden/failure/tell lines. Published.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const STORYTELLER_OVERRIDES: Record<string, Technique> = {
  // ── wake_up × shaman — sense the story/meaning present ──
  'sp-storyteller-WAKE-SHAMAN-INNER': {
    id: 'sp-storyteller-WAKE-SHAMAN-INNER',
    slug: 'storyteller-wake_up-shaman-inner',
    name: "Catch the Story You're Telling",
    essence: "Notice the story you're already telling yourself before it runs the show.",
    steps: [
      'Catch the narration running under the moment.',
      'Feel where it grips in your body.',
      "Name it as a story, not a fact — 'I'm telling myself that…'.",
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['storyteller'],
    capabilities: ['exploration'],
    primaryQuestion: 'What story am I already inside, and is it true?',
    campaignQuestion: 'What story is quietly shaping how I see this?',
    optimizesFor: 'Catching the narrative before it drives the move.',
    forbiddenMoves: ['Mistaking the story for the facts', 'Performing a tidier story than the real one', 'Pressuring the feeling into a neat arc'],
    failureModes: ['Living inside an old script', 'Spectacle over truth'],
    remediation: 'Say the story out loud, then ask what part you actually know.',
    tell: { working: 'You can feel the story loosen its grip.', performed: 'You polish the story instead of questioning it.' },
    contraindications: ['When you need to act now, not narrate'],
    example: "You notice you're telling yourself 'no one will care' — you name it as a story, not truth.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-storyteller-WAKE-SHAMAN-OUTER': {
    id: 'sp-storyteller-WAKE-SHAMAN-OUTER',
    slug: 'storyteller-wake_up-shaman-outer',
    name: 'Sense the Meaning Surfacing',
    essence: 'Sense the meaning trying to surface in the room before you shape it.',
    steps: [
      'Listen for what the moment is reaching toward.',
      'Feel the charge in the room in your body.',
      'Name the meaning lightly, as a question, not a verdict.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['storyteller'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I imposing my meaning, or sensing theirs?',
    campaignQuestion: 'What meaning is the group reaching for that no one has named?',
    optimizesFor: 'Surfacing shared meaning instead of imposing a script.',
    forbiddenMoves: ["Hijacking the room's story", 'Performing insight', 'Pressuring people into your frame'],
    failureModes: ['The narrator who centers themselves', 'Spectacle over truth'],
    remediation: "Offer the meaning as 'I wonder if this is about…' and let them correct you.",
    tell: { working: "People say 'yes, that's it.'", performed: 'You narrate over them.' },
    contraindications: ['When the room needs action, not interpretation'],
    example: "In a tense meeting you name 'I wonder if this is really about feeling unseen' — and the room exhales.",
    tier: 'canonical',
    status: 'published',
  },

  // ── open_up × diplomat — feel what it means ──
  'sp-storyteller-OPEN-DIPLOMAT-INNER': {
    id: 'sp-storyteller-OPEN-DIPLOMAT-INNER',
    slug: 'storyteller-open_up-diplomat-inner',
    name: 'Feel the Grief Under It',
    essence: 'Let yourself feel the loss beneath the story before you tell anyone.',
    steps: [
      'Drop under the storyline to the feeling.',
      'Let the grief or tenderness be in your body without fixing it.',
      'Stay until it has something to say.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['storyteller'],
    capabilities: ['connection'],
    primaryQuestion: 'What am I grieving that the story is covering?',
    campaignQuestion: "What loss underneath this haven't I let myself feel?",
    optimizesFor: 'Telling from real feeling, not performed emotion.',
    forbiddenMoves: ['Skipping to the moral', "Performing grief you don't feel", "Turning your pain into others' obligation"],
    failureModes: ['A polished story with no pulse', 'Spectacle over truth'],
    remediation: 'Put words to the feeling for yourself first, privately.',
    tell: { working: 'The feeling moves and clarifies.', performed: 'You rehearse how the grief will look.' },
    contraindications: ["When you're not safe enough to open yet"],
    example: 'Before sharing why this matters, you sit with the actual loss for three breaths.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-storyteller-OPEN-DIPLOMAT-OUTER': {
    id: 'sp-storyteller-OPEN-DIPLOMAT-OUTER',
    slug: 'storyteller-open_up-diplomat-outer',
    name: 'Hold What It Means to Them',
    essence: 'Receive what this means to the people in it before shaping a story.',
    steps: [
      'Ask what it means to them and actually listen.',
      'Feel their meaning land in your body.',
      'Reflect it back in their words, not yours.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['storyteller'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I making space for their meaning or mine?',
    campaignQuestion: 'What does this mean to the people most affected?',
    optimizesFor: 'A story rooted in their truth and consent, not your spin.',
    forbiddenMoves: ['Speaking for people', 'Using their pain as content', 'Implying they owe you their story'],
    failureModes: ['Extractive storytelling', 'Spectacle over truth'],
    remediation: "Ask 'did I get that right?' and let them rewrite it.",
    tell: { working: 'They feel accurately seen.', performed: 'You collect a better anecdote.' },
    contraindications: ["When they haven't consented to share"],
    example: 'You ask someone what the moment meant to them, then echo their exact words back.',
    tier: 'canonical',
    status: 'published',
  },

  // ── clean_up × sage — weave loss into meaning ──
  'sp-storyteller-CLEAN-SAGE-INNER': {
    id: 'sp-storyteller-CLEAN-SAGE-INNER',
    slug: 'storyteller-clean_up-sage-inner',
    name: 'Find Your True Meaning First',
    essence: 'Distill what this actually means to you before you offer meaning to anyone.',
    steps: [
      'Sift the event for the one true thing it taught you.',
      'Feel whether it rings true in the body.',
      'Write it as one honest sentence.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['sage'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['storyteller'],
    capabilities: ['exploration'],
    primaryQuestion: "What's the real meaning here, under the meaning I'd perform?",
    campaignQuestion: 'What durable truth am I taking from this?',
    optimizesFor: "Meaning that's earned, not manufactured.",
    forbiddenMoves: ['Forcing a tidy lesson', 'Performing wisdom', 'Pressuring an arc onto raw experience'],
    failureModes: ["A moral that isn't true yet", 'Spectacle over truth'],
    remediation: 'If the sentence feels like a slogan, sit longer.',
    tell: { working: 'The sentence lands quietly true.', performed: 'You reach for the quotable version.' },
    contraindications: ["When it's too soon to know the meaning"],
    example: "Instead of 'everything happens for a reason,' you write the smaller true thing you learned.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-storyteller-CLEAN-SAGE-OUTER': {
    id: 'sp-storyteller-CLEAN-SAGE-OUTER',
    slug: 'storyteller-clean_up-sage-outer',
    name: 'Weave Loss into Belonging',
    essence: 'Find the thread that turns a shared loss into shared meaning and belonging.',
    steps: [
      'Name what was lost, honestly.',
      'Find what it reveals that still matters to everyone.',
      'Offer the thread that lets people hold both, and feel whether it lands.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['sage'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['storyteller'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I bypassing the grief to get to the uplift?',
    campaignQuestion: 'What meaning lets this community carry the loss together?',
    optimizesFor: 'Collective meaning that honors the loss instead of erasing it.',
    forbiddenMoves: ['Premature silver-linings', 'Spinning loss into a brand', 'Guilt-tripping people into hope'],
    failureModes: ['Toxic positivity', 'Spectacle over truth'],
    remediation: 'Let the grief be witnessed before offering the meaning.',
    tell: { working: 'People feel both held and moved.', performed: 'You skip to the inspirational close.' },
    contraindications: ['When the wound is too fresh for meaning-making'],
    example: 'At a hard moment you name the loss fully, then the bond it revealed — not a tidy lesson.',
    tier: 'canonical',
    status: 'published',
  },

  // ── grow_up × regent — deepen / steward the voice ──
  'sp-storyteller-GROW-REGENT-INNER': {
    id: 'sp-storyteller-GROW-REGENT-INNER',
    slug: 'storyteller-grow_up-regent-inner',
    name: 'Deepen Your Honest Voice',
    essence: 'Practice telling it true over time, so honesty outgrows performance.',
    steps: [
      'Notice where you reach for effect instead of truth.',
      'Tell one story this week stripped of polish.',
      'Feel the difference in your body afterward.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['storyteller'],
    capabilities: ['participation'],
    primaryQuestion: 'Where am I performing instead of telling it true?',
    campaignQuestion: 'What practice grows my honest voice?',
    optimizesFor: "A voice people trust because it's true, not slick.",
    forbiddenMoves: ['Practicing the performance', 'Chasing applause', 'Pressuring yourself to be profound'],
    failureModes: ['Polished but hollow', 'Spectacle over truth'],
    remediation: 'Cut the most impressive line; keep the truest one.',
    tell: { working: 'It costs a little and feels more real.', performed: 'You workshop the applause line.' },
    contraindications: ['When rawness would harm, not serve'],
    example: 'You tell a story without the punchline you usually lean on, and it lands deeper.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-storyteller-GROW-REGENT-OUTER': {
    id: 'sp-storyteller-GROW-REGENT-OUTER',
    slug: 'storyteller-grow_up-regent-outer',
    name: 'Steward the Shared Story',
    essence: "Tend the group's story over time so it stays true as things change.",
    steps: [
      'Notice where the shared story has gone stale or false.',
      'Update it with the people, not for them — feel where it still rings true.',
      'Keep the thread that still holds; let the rest evolve.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['storyteller'],
    capabilities: ['participation'],
    primaryQuestion: 'Am I clinging to a story that no longer serves us?',
    campaignQuestion: 'How do we keep our story honest as we grow?',
    optimizesFor: 'A living narrative the group still recognizes as theirs.',
    forbiddenMoves: ['Freezing the founding myth', 'Rewriting history alone', 'Guilt-tripping people with the old story'],
    failureModes: ['A stale legend nobody believes', 'Spectacle over truth'],
    remediation: 'Invite the group to retell it in their own words.',
    tell: { working: 'People feel ownership of the story.', performed: 'You defend your version of the legend.' },
    contraindications: ["When the old story is load-bearing and shouldn't change yet"],
    example: 'You gather the crew to retell why you started — and let the story update.',
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × diplomat — tell the shared story ──
  'sp-storyteller-SHOW-DIPLOMAT-INNER': {
    id: 'sp-storyteller-SHOW-DIPLOMAT-INNER',
    slug: 'storyteller-show_up-diplomat-inner',
    name: 'Tell It Without Centering Yourself',
    essence: 'Tell the story in a way that serves the room, not your image.',
    steps: [
      'Check your motive: am I sharing to serve or to be seen?',
      'Feel the nerves without letting them drive performance.',
      'Tell it plainly, then get out of the way.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['storyteller'],
    capabilities: ['connection'],
    primaryQuestion: 'Am I telling this for them or for me?',
    campaignQuestion: 'How do I tell this so the focus stays where it belongs?',
    optimizesFor: 'A telling that points at the cause, not the teller.',
    forbiddenMoves: ['Making yourself the hero', 'Fishing for sympathy', 'Pressuring the room to react'],
    failureModes: ['The self-centered share', 'Spectacle over truth'],
    remediation: "Cut every line that's about how you look.",
    tell: { working: 'Afterward the room talks about the cause, not you.', performed: 'You scan for who was impressed.' },
    contraindications: ['When your own story IS the point and consent is clear'],
    example: "You share your part briefly, then turn the room toward the people it's about.",
    tier: 'canonical',
    status: 'published',
  },
  'sp-storyteller-SHOW-DIPLOMAT-OUTER': {
    id: 'sp-storyteller-SHOW-DIPLOMAT-OUTER',
    slug: 'storyteller-show_up-diplomat-outer',
    name: 'Name What This Means, for the Room',
    essence: 'Give the room a story it can hold and act from — true, shared, and inviting.',
    steps: [
      'Name the meaning in one clear line everyone can feel and carry.',
      'Make room for others to add their thread.',
      'End with an opening to act, not a mic-drop.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['diplomat'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['storyteller'],
    capabilities: ['connection', 'participation'],
    primaryQuestion: 'Is this a story that includes them, or a performance at them?',
    campaignQuestion: 'What story gives this group something true to rally around?',
    optimizesFor: 'A shared story that invites participation, with consent.',
    forbiddenMoves: ['Monologuing', "Using anyone's story without consent", 'Guilt-tripping the room into action'],
    failureModes: ["The speech that impresses but doesn't move", 'Spectacle over truth'],
    remediation: "Ask 'what would you add?' and mean it.",
    tell: { working: 'People pick up the story and run with it.', performed: 'You land the applause line and stop.' },
    contraindications: ['When the room needs quiet, not a story'],
    example: "You name the one thing it's really about — then invite others to add why it matters to them.",
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × sage — leave a lasting meaning ──
  'sp-storyteller-SHOW-SAGE-INNER': {
    id: 'sp-storyteller-SHOW-SAGE-INNER',
    slug: 'storyteller-show_up-sage-inner',
    name: "Tell the Story You'll Stand Behind",
    essence: "Tell it so you can stand behind it tomorrow — true past the moment's heat.",
    steps: [
      "Ask if you'll believe this telling next week.",
      "Feel whether it's true or just effective.",
      'Tell the version that ages well.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['water'],
    aspect: 'inner',
    superpowers: ['storyteller'],
    capabilities: ['exploration'],
    primaryQuestion: 'Will I stand behind this story when the moment cools?',
    campaignQuestion: "What's the telling I won't regret?",
    optimizesFor: "Durable truth over a moment's impact.",
    forbiddenMoves: ['Exaggerating for effect', 'Bending facts to land harder', 'Pressuring belief with drama'],
    failureModes: ["The viral lie you can't walk back", 'Spectacle over truth'],
    remediation: "Trim any claim you couldn't defend later.",
    tell: { working: 'It holds up on a reread.', performed: 'You optimize for the reaction, not the record.' },
    contraindications: ['When precision matters more than narrative'],
    example: 'You resist the tempting exaggeration and tell the true version that still moves people.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-storyteller-SHOW-SAGE-OUTER': {
    id: 'sp-storyteller-SHOW-SAGE-OUTER',
    slug: 'storyteller-show_up-sage-outer',
    name: 'Leave a Story That Lasts',
    essence: "Tell it so something true remains after you're gone from the room.",
    steps: [
      'Name the meaning worth remembering — the one you feel in your gut.',
      'Put it where it can outlive the moment (a record, a ritual, a retelling).',
      'Hand it to others to carry.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['water'],
    aspect: 'outer',
    superpowers: ['storyteller'],
    capabilities: ['participation'],
    primaryQuestion: 'What story do I want to outlast me here?',
    campaignQuestion: 'What meaning should remain when this campaign ends?',
    optimizesFor: 'A lasting narrative artifact, not a spent performance.',
    forbiddenMoves: ['Ephemeral spectacle', 'Hoarding the story', 'Guilt-tripping the next generation with it'],
    failureModes: ['A great night no one remembers', 'Spectacle over truth'],
    remediation: 'Write it down and give it away.',
    tell: { working: 'Others retell it without you.', performed: 'You perform a finale and leave nothing.' },
    contraindications: ['When the moment should stay ephemeral'],
    example: "You turn the effort's story into a short written piece others can share.",
    tier: 'canonical',
    status: 'published',
  },
}
