/**
 * Hand-authored hero cells — Strategist (inner + outer). Authored to L4.
 * Spec: .specify/specs/superpower-deck-quality/spec.md § FR8
 *
 * CAMPAIGN-AGNOSTIC. Strategist = clarity in complexity: the cartographer who
 * finds pattern, bottleneck, and sequence — and then MOVES. Inner = clearing your
 * own overwhelm; outer = mapping the shared problem. Shadows woven through: the
 * Detached Planner (mapping instead of acting) and the perfectionist who won't act
 * without a flawless plan. Six coords × both aspects = 12 cells; published.
 */

import type { Technique } from '../../types'

const GM = { origin: 'gm' as const, name: 'Authored hero cell', author: 'Wendell Britt' }

export const STRATEGIST_OVERRIDES: Record<string, Technique> = {
  // ── wake_up × shaman — see the real shape ──
  'sp-strategist-WAKE-SHAMAN-INNER': {
    id: 'sp-strategist-WAKE-SHAMAN-INNER',
    slug: 'strategist-wake_up-shaman-inner',
    name: 'See Your Own Overwhelm',
    essence: 'Notice the overwhelm honestly before you try to map your way out of it.',
    steps: [
      'Notice the moment the problem starts to feel like too much.',
      'Feel where the overwhelm sits in your body — the tight chest, the held breath.',
      'Name it plainly: "I am overwhelmed," before reaching for a plan.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['strategist'],
    capabilities: ['exploration'],
    primaryQuestion: 'What am I refusing to admit is overwhelming me right now?',
    campaignQuestion: 'Where am I planning to avoid feeling out of control?',
    optimizesFor: 'Seeing your own state clearly before it distorts every map you draw.',
    forbiddenMoves: ['Planning your way around the feeling', 'Pressuring yourself to be calm before you have looked', 'Calling overwhelm weakness'],
    failureModes: ['Maps drawn by a panicked hand', 'Frantic productivity'],
    remediation: 'Name the overwhelm out loud; take one breath before the next thought.',
    tell: { working: 'You admit the overwhelm and steady.', performed: 'You draw a confident chart to hide the panic.' },
    contraindications: ['When you genuinely need to act first and feel later'],
    example: 'The project balloons; instead of a frantic spreadsheet, you name that you are overwhelmed.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-strategist-WAKE-SHAMAN-OUTER': {
    id: 'sp-strategist-WAKE-SHAMAN-OUTER',
    slug: 'strategist-wake_up-shaman-outer',
    name: 'See the Real Shape',
    essence: 'Sense the true shape of the problem before anyone rushes to solve it.',
    steps: [
      'Slow the room down before solutions start flying.',
      'Feel for the bottleneck everyone is talking around.',
      'Name the actual shape of the problem out loud.',
    ],
    source: GM,
    moves: ['wake_up'],
    operations: ['shaman'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['strategist'],
    capabilities: ['exploration'],
    primaryQuestion: 'Am I solving the problem in front of me or the real one?',
    campaignQuestion: 'What is the true shape of this problem that no one has named?',
    optimizesFor: 'Naming the real problem so the group stops solving the wrong one.',
    forbiddenMoves: ['Jumping to the solution you already like', 'Pressuring the group toward your read', 'Mistaking the loud problem for the real one'],
    failureModes: ['Elegant answers to the wrong question', 'Analysis that flatters the planner'],
    remediation: 'Ask "what is actually in our way?" and listen before mapping.',
    tell: { working: 'The group recognizes the real problem.', performed: 'You impress them with a diagram.' },
    contraindications: ['When the problem is obvious and action is overdue'],
    example: 'The team debates features; you name that the real bottleneck is a single approval step.',
    tier: 'canonical',
    status: 'published',
  },

  // ── open_up × architect — hold the not-yet-known ──
  'sp-strategist-OPEN-ARCHITECT-INNER': {
    id: 'sp-strategist-OPEN-ARCHITECT-INNER',
    slug: 'strategist-open_up-architect-inner',
    name: 'Hold the Not-Yet-Knowing',
    essence: 'Take in the discomfort of not yet knowing, and build a frame that can hold it.',
    steps: [
      'Notice the urge to resolve uncertainty too fast.',
      'Feel the discomfort of the open question without closing it.',
      'Make a small frame — a list, a sketch — that holds the unknown without faking an answer.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['strategist'],
    capabilities: ['exploration'],
    primaryQuestion: 'What am I rushing to decide just to escape not-knowing?',
    campaignQuestion: 'Where am I forcing certainty I do not actually have?',
    optimizesFor: 'Staying in the open question long enough to see the real structure.',
    forbiddenMoves: ['Premature certainty', 'Pressuring yourself to a decision to feel safe', 'Building a structure to avoid the feeling'],
    failureModes: ['Locking in the first frame', 'False precision'],
    remediation: 'Write the question you cannot yet answer; let it stay open one more day.',
    tell: { working: 'You hold the question and keep looking.', performed: 'You decide early to stop the discomfort.' },
    contraindications: ['When a decision is genuinely due and waiting costs more'],
    example: 'You want to lock the plan tonight; instead you frame the open variables and sleep on it.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-strategist-OPEN-ARCHITECT-OUTER': {
    id: 'sp-strategist-OPEN-ARCHITECT-OUTER',
    slug: 'strategist-open_up-architect-outer',
    name: 'Take In the Messy Data',
    essence: 'Receive the messy data others avoid, and build it a structure it can live in.',
    steps: [
      'Invite the inconvenient information no one wants to look at.',
      'Feel the urge to tidy it away, and resist it.',
      'Give the mess a structure — categories, a map — without amputating what is real.',
    ],
    source: GM,
    moves: ['open_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['strategist'],
    capabilities: ['exploration'],
    primaryQuestion: 'Whose inconvenient data am I leaving out of the model?',
    campaignQuestion: 'What messy reality does our plan keep ignoring?',
    optimizesFor: 'A map that includes the data that breaks the clean story.',
    forbiddenMoves: ['Trimming reality to fit the model', 'Pressuring people to give tidy answers', 'Dismissing the outlier'],
    failureModes: ['Clean maps of a false world', 'Garbage in, confident out'],
    remediation: 'Add the one data point that ruins your tidy model; rebuild around it.',
    tell: { working: 'The model gets messier and truer.', performed: 'The model stays clean and wrong.' },
    contraindications: ['When more data is procrastination, not diligence'],
    example: 'You fold the support tickets everyone ignores into the roadmap, and it changes.',
    tier: 'canonical',
    status: 'published',
  },

  // ── clean_up × challenger — cut to leverage ──
  'sp-strategist-CLEAN-CHALLENGER-INNER': {
    id: 'sp-strategist-CLEAN-CHALLENGER-INNER',
    slug: 'strategist-clean_up-challenger-inner',
    name: 'Cut the Noise in Your Head',
    essence: 'Clear the mental noise down to the one thing that actually matters.',
    steps: [
      'Dump every competing thought onto the page.',
      'Feel which one makes your gut tighten — that is usually the real one.',
      'Cross out the noise; keep the single leverage point.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['metal'],
    aspect: 'inner',
    superpowers: ['strategist'],
    capabilities: ['exploration'],
    primaryQuestion: 'Of everything spinning in my head, what is the one thing that matters?',
    campaignQuestion: 'What am I letting clutter my judgment here?',
    optimizesFor: 'Finding your own leverage point under the mental noise.',
    forbiddenMoves: ['Mistaking busywork for the lever', 'Pressuring a fake clarity', 'Cutting the uncomfortable thing to feel tidy'],
    failureModes: ['Optimizing the trivial', 'Tidy mind, wrong priority'],
    remediation: 'Name the single thing that would make the rest easier; start there.',
    tell: { working: 'One priority stands clear.', performed: 'You reorganize the noise and call it focus.' },
    contraindications: ['When several things genuinely need to move at once'],
    example: 'Ten tabs of worry; you find the one decision that quiets the other nine.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-strategist-CLEAN-CHALLENGER-OUTER': {
    id: 'sp-strategist-CLEAN-CHALLENGER-OUTER',
    slug: 'strategist-clean_up-challenger-outer',
    name: 'Cut to the Leverage Point',
    essence: 'Reduce the tangled problem to the single point where force actually moves it.',
    steps: [
      'Lay out the whole tangle so everyone can see it.',
      'Feel for the constraint that, if it moved, would free the rest.',
      'Name the leverage point and let the busywork fall away.',
    ],
    source: GM,
    moves: ['clean_up'],
    operations: ['challenger'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['strategist'],
    capabilities: ['exploration'],
    primaryQuestion: 'Am I attacking the bottleneck or the symptoms around it?',
    campaignQuestion: 'Where is the one constraint that is holding all of this back?',
    optimizesFor: 'The whole group pushing on the point that actually moves the problem.',
    forbiddenMoves: ['Spreading effort everywhere', 'Pressuring people onto your pet lever', 'Naming a lever to look decisive'],
    failureModes: ['Effort with no movement', 'Theatre of progress'],
    remediation: 'Ask "if only one thing changed, what would unblock the rest?"',
    tell: { working: 'The bottleneck moves and the rest loosens.', performed: 'Everyone is busy and nothing shifts.' },
    contraindications: ['When the constraint is a person who needs care, not pressure'],
    example: 'You stop the team polishing the deck and point all of it at the unsigned contract.',
    tier: 'canonical',
    status: 'published',
  },

  // ── grow_up × regent — sharpen the read over time ──
  'sp-strategist-GROW-REGENT-INNER': {
    id: 'sp-strategist-GROW-REGENT-INNER',
    slug: 'strategist-grow_up-regent-inner',
    name: 'Sharpen Your Read',
    essence: 'Build, over time, a sharper read of patterns — and notice when the map drifts from the world.',
    steps: [
      'After a call goes wrong, revisit what you predicted.',
      'Feel the sting of the miss without explaining it away.',
      'Adjust one rule of thumb so your next read is truer.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['earth'],
    aspect: 'inner',
    superpowers: ['strategist'],
    capabilities: ['rest'],
    primaryQuestion: 'Where has my map quietly stopped matching the territory?',
    campaignQuestion: 'What pattern do I keep misreading the same way?',
    optimizesFor: 'A judgment that gets truer with each miss instead of more defended.',
    forbiddenMoves: ['Defending a wrong prediction', 'Pressuring yourself to be right faster', 'Updating the story instead of the model'],
    failureModes: ['Confidence outrunning calibration', 'The Detached Planner, more certain'],
    remediation: 'Write what you got wrong and the one rule you will change.',
    tell: { working: 'Your reads get quietly more accurate.', performed: 'You explain why you were basically right.' },
    contraindications: ['When over-analyzing the miss feeds avoidance'],
    example: 'Your estimate was off by double; you adjust your buffer rule instead of blaming the team.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-strategist-GROW-REGENT-OUTER': {
    id: 'sp-strategist-GROW-REGENT-OUTER',
    slug: 'strategist-grow_up-regent-outer',
    name: 'Tend the Shared Map',
    essence: 'Steward the group’s shared map so it stays alive, owned, and matched to reality.',
    steps: [
      'Make the plan visible where everyone can mark it up.',
      'Feel for where people have quietly stopped believing it.',
      'Update it with them, so it stays theirs and not just yours.',
    ],
    source: GM,
    moves: ['grow_up'],
    operations: ['regent'],
    domains: [],
    channels: ['wood'],
    aspect: 'outer',
    superpowers: ['strategist'],
    capabilities: ['participation'],
    primaryQuestion: 'Is this still our map, or only mine on the wall?',
    campaignQuestion: 'Where has the shared plan drifted from what people actually do?',
    optimizesFor: 'A living plan the group owns and keeps honest together.',
    forbiddenMoves: ['Guarding the plan as yours', 'Pressuring compliance with a stale map', 'Updating it in private'],
    failureModes: ['A beautiful plan nobody follows', 'Map ownership hoarded'],
    remediation: 'Hand the marker to someone else and let them revise a piece.',
    tell: { working: 'People edit the plan unprompted.', performed: 'People nod at a plan they have abandoned.' },
    contraindications: ['When constant re-planning is avoiding execution'],
    example: 'You turn your private roadmap into a board the team reorders each week.',
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × architect — lay the path ──
  'sp-strategist-SHOW-ARCHITECT-INNER': {
    id: 'sp-strategist-SHOW-ARCHITECT-INNER',
    slug: 'strategist-show_up-architect-inner',
    name: 'Name Your Next Right Step',
    essence: 'Collapse the whole plan into the one concrete step you can take today.',
    steps: [
      'Look at the plan and find the first physical action.',
      'Feel the resistance that wants one more pass of planning.',
      'Do the step today, before the map is perfect.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['strategist'],
    capabilities: ['agency'],
    primaryQuestion: 'What is the one step I could take today instead of planning more?',
    campaignQuestion: 'What am I planning in order to avoid starting?',
    optimizesFor: 'Turning your map into motion before perfection stalls it.',
    forbiddenMoves: ['One more planning pass', 'Pressuring yourself to a leap with no footing', 'Waiting for the perfect plan'],
    failureModes: ['The Detached Planner — endless mapping', 'Ready, ready, ready, never set'],
    remediation: 'Pick the smallest real action on the plan and do it now.',
    tell: { working: 'You take a concrete first step.', performed: 'You refine the plan a fourth time.' },
    contraindications: ['When a step now would be reckless without a key fact'],
    example: 'Instead of re-sequencing the roadmap again, you send the one email that starts it.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-strategist-SHOW-ARCHITECT-OUTER': {
    id: 'sp-strategist-SHOW-ARCHITECT-OUTER',
    slug: 'strategist-show_up-architect-outer',
    name: 'Lay the Path Others Can Walk',
    essence: 'Sequence the plan into steps other people can actually pick up and walk.',
    steps: [
      'Break the goal into steps sized for the people who will carry them.',
      'Feel for where a handoff is vague enough to stall.',
      'Name who does what next, concretely, and start the first one.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['architect'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['strategist'],
    capabilities: ['exploration'],
    primaryQuestion: 'Could someone else actually walk the path I just drew?',
    campaignQuestion: 'Where is our plan too abstract for anyone to act on?',
    optimizesFor: 'A sequence people can execute without you in the room.',
    forbiddenMoves: ['Handing over a vision with no steps', 'Pressuring people through an unclear handoff', 'Keeping the sequence in your head'],
    failureModes: ['Inspiring plans no one can start', 'Everything waits on the planner'],
    remediation: 'Write the next three concrete actions with names attached.',
    tell: { working: 'People start without asking you what to do.', performed: 'People wait for you to clarify again.' },
    contraindications: ['When over-specifying robs people of their own judgment'],
    example: 'You turn "improve onboarding" into three named, dated steps and the team moves.',
    tier: 'canonical',
    status: 'published',
  },

  // ── show_up × sage — act before perfect / move the whole ──
  'sp-strategist-SHOW-SAGE-INNER': {
    id: 'sp-strategist-SHOW-SAGE-INNER',
    slug: 'strategist-show_up-sage-inner',
    name: 'Act Before the Plan Is Perfect',
    essence: 'Integrate map and motion: act on the good-enough plan and let reality finish it.',
    steps: [
      'Accept the plan is 80% and that the last 20% only comes from moving.',
      'Feel the fear that acting will expose a flaw — and go anyway.',
      'Take the real action and treat what you learn as the next data.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['fire'],
    aspect: 'inner',
    superpowers: ['strategist'],
    capabilities: ['agency'],
    primaryQuestion: 'What would I do now if the plan only had to be good enough?',
    campaignQuestion: 'What am I perfecting to postpone the risk of acting?',
    optimizesFor: 'Strategy that moves — map and action as one loop, not two phases.',
    forbiddenMoves: ['Perfecting to avoid exposure', 'Pressuring a leap to prove decisiveness', 'Treating the plan as the achievement'],
    failureModes: ['The perfect plan that never ships', 'Paralysis dressed as rigor'],
    remediation: 'Ship the good-enough version; schedule the review for after, not before.',
    tell: { working: 'You move and learn in the same step.', performed: 'You polish the plan to stay safe.' },
    contraindications: ['When the cost of a wrong move is irreversible and high'],
    example: 'You launch the imperfect pilot instead of planning a flawless one for another month.',
    tier: 'canonical',
    status: 'published',
  },
  'sp-strategist-SHOW-SAGE-OUTER': {
    id: 'sp-strategist-SHOW-SAGE-OUTER',
    slug: 'strategist-show_up-sage-outer',
    name: 'Move the Whole System',
    essence: 'Make the one move that shifts the whole system, then read how the field responds.',
    steps: [
      'Find the move whose effects ripple past its own step.',
      'Feel for the second-order consequences before you pull it.',
      'Make the move, then watch the whole field, not just the spot you touched.',
    ],
    source: GM,
    moves: ['show_up'],
    operations: ['sage'],
    domains: [],
    channels: ['metal'],
    aspect: 'outer',
    superpowers: ['strategist'],
    capabilities: ['exploration'],
    primaryQuestion: 'Am I moving a piece or moving the system?',
    campaignQuestion: 'What single move would change the whole field for everyone?',
    optimizesFor: 'Leverage that shifts the system, watched for what it sets in motion.',
    forbiddenMoves: ['Optimizing one box while the system rots', 'Pressuring a system change past people’s consent', 'Ignoring the ripple you start'],
    failureModes: ['Local wins, systemic loss', 'Clever moves with ugly side effects'],
    remediation: 'Name one likely side effect of the move and plan for it before acting.',
    tell: { working: 'The whole field shifts and you adjust.', performed: 'You win your square and lose the board.' },
    contraindications: ['When a humble local fix is what the moment actually needs'],
    example: 'Instead of patching one team’s process, you change the incentive that shaped all of them.',
    tier: 'canonical',
    status: 'published',
  },
}
